// Package localization generated by SHOPLINE since v20251201
package localization

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

type GetStoreLanguagesAPIReq struct {
	client.BaseAPIRequest
}

func (req *GetStoreLanguagesAPIReq) GetEndpoint() string {

	return "store/languages.json"

}

func (req *GetStoreLanguagesAPIReq) GetMethod() string {
	return "GET"
}

// Verify the api request parameters
func (req *GetStoreLanguagesAPIReq) Verify() error {

	return nil
}

func (req *GetStoreLanguagesAPIReq) NewAPIResp() *GetStoreLanguagesAPIResp {
	return &GetStoreLanguagesAPIResp{}
}

type GetStoreLanguagesAPIResp struct {
	client.BaseAPIResponse
	/*
	   Response body.
	   Example: map[default_language:en supported_languages:[vi]]
	*/
	Data GetStoreLanguagesAPIRespData `json:"data,omitempty" url:"-"`
}

type GetStoreLanguagesAPIRespData struct {
	/*
	   List of languages in use.
	   Example: [vi]
	*/
	SupportedLanguages []string `json:"supported_languages,omitempty" url:"-"`

	/*
	   The store's default language.
	   Example: en
	*/
	DefaultLanguage string `json:"default_language,omitempty" url:"-"`
}
