// Package localization generated by SHOPLINE since v20251201
package localization

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

type QueryStoreSAvailableLanguagesAPIReq struct {
	client.BaseAPIRequest
}

func (req *QueryStoreSAvailableLanguagesAPIReq) GetEndpoint() string {

	return "store/available_locales.json"

}

func (req *QueryStoreSAvailableLanguagesAPIReq) GetMethod() string {
	return "GET"
}

// Verify the api request parameters
func (req *QueryStoreSAvailableLanguagesAPIReq) Verify() error {

	return nil
}

func (req *QueryStoreSAvailableLanguagesAPIReq) NewAPIResp() *QueryStoreSAvailableLanguagesAPIResp {
	return &QueryStoreSAvailableLanguagesAPIResp{}
}

type QueryStoreSAvailableLanguagesAPIResp struct {
	client.BaseAPIResponse
	/*
	   Response
	   Example: map[available_locales:[map[iso_code:en name:English]]]
	*/
	Data QueryStoreSAvailableLanguagesAPIRespData `json:"data,omitempty" url:"-"`
}

type QueryStoreSAvailableLanguagesAPIRespData struct {
	/*
	   List of the store's available languages.
	   Example: [map[iso_code:en name:English]]
	*/
	AvailableLocales []AvailableLocale `json:"available_locales,omitempty" url:"-"`
}

type AvailableLocale struct {
	/*
	   Language code that follows the [IETF BCP 47](https://en.wikipedia.org/wiki/IETF_language_tag) standard.
	   Example: `en`
	   Example: en
	*/
	IsoCode string `json:"iso_code,omitempty" url:"-"`

	/*
	   Language name. Example: `English`
	   Example: English
	*/
	Name string `json:"name,omitempty" url:"-"`
}
