// Package order generated by SHOPLINE since v20251201
package order

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *BillingAttemptsToSucceedEvent) GetSupportedTopic() string {
	return "subscribe/success"
}

type BillingAttemptsToSucceedEvent struct {
	client.WebhookEvent
	/*
	   Billing attempts to succeed or not
	   Example: false
	*/
	Ready bool `json:"ready,omitempty"`

	/*
	   store ID
	   Example:
	*/
	StoreId string `json:"store_id,omitempty"`

	/*
	   Associated subscription contract number
	   Example:
	*/
	SubscriptionContractId string `json:"subscription_contract_id,omitempty"`

	/*
	   Billing try to fail error message
	   Example:
	*/
	ErrorMessage string `json:"error_message,omitempty"`

	/*
	   Billing try single
	   Example:
	*/
	Id string `json:"id,omitempty"`

	/*
	   Billing try with target order number
	   Example:
	*/
	OrderId string `json:"order_id,omitempty"`
}
