// Package order generated by SHOPLINE since v20251201
package order

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *SubscriptionContractCreationEvent) GetSupportedTopic() string {
	return "subscribe/create"
}

type BillingPolicy struct {
	/*
	   Interval value
	   Example: 0
	*/
	IntervalCount int `json:"interval_count,omitempty"`

	/*
	   Maximum cycle
	   Example: 0
	*/
	MaxCycles int `json:"max_cycles,omitempty"`

	/*
	   Minimum cycle
	   Example: 0
	*/
	MinCycles int `json:"minCycles,omitempty"`

	/*
	   Interval units ( day , MONTH , weed , year )
	   Example:
	*/
	Interval string `json:"interval,omitempty"`
}

type DeliveryPolicy struct {
	/*
	   Shipping plan name
	   Example:
	*/
	DeliveryName string `json:"delivery_name,omitempty"`

	/*
	   Shipping plan single
	   Example:
	*/
	DeliverySeq string `json:"delivery_seq,omitempty"`
}

type SubscriptionContractCreationEventLineItem struct {
	/*
	   The quantity of the product.
	   Example:
	*/
	Quantity string `json:"quantity,omitempty"`

	/*
	   The item number of the product.
	   Example:
	*/
	Sku string `json:"sku,omitempty"`

	/*
	   The title of the product.
	   Example:
	*/
	Title string `json:"title,omitempty"`

	/*
	   The SKU of the line item.
	   Example:
	*/
	VariantId string `json:"variant_id,omitempty"`

	/*
	   The product's amount in multi-currency.
	   Example: map[presentment_money:map[amount: currency_code:] shop_money:map[amount: currency_code:]]
	*/
	AmountSet AmountSet `json:"amount_set,omitempty"`

	/*
	   The attributes of the products.
	   Example: []
	*/
	Attributes []Attribute `json:"attributes,omitempty"`

	/*
	   The group ID of the line item.
	   Example:
	*/
	GroupId string `json:"group_id,omitempty"`

	/*
	   The unique ID of the contract line item.
	   Example:
	*/
	Id string `json:"id,omitempty"`

	/*
	   The amount of the product with a precision of  2 decimal places, eg, '88.10'.
	   Example:
	*/
	Amount string `json:"amount,omitempty"`

	/*
	   The image URL of the product.
	   Example:
	*/
	ImageUrl string `json:"image_url,omitempty"`

	/*
	   The discount information for the selling plan.
	   Example: []
	*/
	PricingPolicy []PricingPolicy `json:"pricing_policy,omitempty"`

	/*
	   The source of the product:
	   `main_site`: for main site products
	   `customize`: for customized products
	   Example:
	*/
	ProductSource string `json:"product_source,omitempty"`
}

type Attribute struct {
	/*
	   The attribute key or name of the product.
	   Example:
	*/
	Key string `json:"key,omitempty"`

	/*
	   The attribute value of the product.
	   Example:
	*/
	Value string `json:"value,omitempty"`
}

type PricingPolicy struct {
	/*
	   The adjustment of the subscription cycles.
	   Example: []
	*/
	CycleDiscounts []CycleDiscount `json:"cycle_discounts,omitempty"`
}

type CycleDiscount struct {
	/*
	   The type of discounts:
	   `FIXED_AMOUNT`: a fixed amount discount
	   `PERCENTAGE`: a percentage discount.
	   Example:
	*/
	AdjustmentType string `json:"adjustment_type,omitempty"`

	/*
	   The discount value in amount or a percentage.
	   Example: 0
	*/
	AdjustmentValue int64 `json:"adjustment_value,omitempty"`
}

type SubscriptionContractCreationEvent struct {
	client.WebhookEvent
	/*
	   store ID
	   Example:
	*/
	StoreId string `json:"store_id,omitempty"`

	/*
	   Billing strategy information
	   Example: map[interval: interval_count:0 max_cycles:0 minCycles:0]
	*/
	BillingPolicy BillingPolicy `json:"billing_policy,omitempty"`

	/*
	   Shipping plan
	   Example: map[delivery_name: delivery_seq:]
	*/
	DeliveryPolicy DeliveryPolicy `json:"delivery_policy,omitempty"`

	/*
	   Event type
	   Example:
	*/
	EventType string `json:"event_type,omitempty"`

	/*
	   Subscription contract single number
	   Example:
	*/
	Id string `json:"id,omitempty"`

	/*
	   The information for contract lines.
	   Example: []
	*/
	LineItems []SubscriptionContractCreationEventLineItem `json:"line_items,omitempty"`

	/*
	   Contract status , ACTIVE、PAUSED、EXPIRED、CANCELLED、FAILED
	   Example:
	*/
	Status string `json:"status,omitempty"`
}
