// Package order generated by SHOPLINE since v20260301
package order

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *DeliveryOfFulfillmentRecoveryEvent) GetSupportedTopic() string {
	return "fulfillment_order/released"
}

type DeliveryOfFulfillmentRecoveryEvent struct {
	client.WebhookEvent
	/*
	   Performance details
	   Example: map[id:"83234231_8234234" status:"open"]
	*/
	FulfillmentOrder DeliveryOfFulfillmentRecoveryEventFulfillmentOrder `json:"fulfillment_order,omitempty" url:"-"`
}

type DeliveryOfFulfillmentRecoveryEventFulfillmentOrder struct {
	/*
	   Identifies id
	   Example: "83234231_8234234"
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   Performance-date status
	   Example: "open"
	*/
	Status string `json:"status,omitempty" url:"-"`
}
