// Package order generated by SHOPLINE since v20260301
package order

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *DraftOrderDeletedEvent) GetSupportedTopic() string {
	return "draft_orders/delete"
}

type DraftOrderDeletedEvent struct {
	client.WebhookEvent
	/*
	   Draft order information.
	   Example: map[id:]
	*/
	DraftOrder DraftOrderDeletedEventDraftOrder `json:"draft_order,omitempty" url:"-"`

	/*
	   The unique identifier of the store.
	   Example:
	*/
	StoreId string `json:"store_id,omitempty" url:"-"`
}

type DraftOrderDeletedEventDraftOrder struct {
	/*
	   The unique identifier of the draft order.
	   Example:
	*/
	Id string `json:"id,omitempty" url:"-"`
}
