// Package order generated by SHOPLINE since v20260301
package order

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *FulfillmentSuspensionEvent) GetSupportedTopic() string {
	return "fulfillment_order/on_hold"
}

type FulfillmentHold struct {
	/*
	   Pause cause
	   Example: "out of stock"
	*/
	Reason string `json:"reason,omitempty" url:"-"`

	/*
	   Pause notes
	   Example: "customer require"
	*/
	ReasonNotes string `json:"reason_notes,omitempty" url:"-"`
}

type FulfillmentSuspensionEvent struct {
	client.WebhookEvent
	/*
	   Performance details
	   Example: map[fulfillment_holds:[] id:"83234231_8234234" status:"open"]
	*/
	FulfillmentOrder FulfillmentSuspensionEventFulfillmentOrder `json:"fulfillment_order,omitempty" url:"-"`
}

type FulfillmentSuspensionEventFulfillmentOrder struct {
	/*
	   Pause information
	   Example: []
	*/
	FulfillmentHolds []FulfillmentHold `json:"fulfillment_holds,omitempty" url:"-"`

	/*
	   Identifies id
	   Example: "83234231_8234234"
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   Performance-date status
	   Example: "open"
	*/
	Status string `json:"status,omitempty" url:"-"`
}
