// Package order generated by SHOPLINE since v20260301
package order

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *OrderPaymentCreatedEvent) GetSupportedTopic() string {
	return "order_transactions/create"
}

type OrderPaymentCreatedEvent struct {
	client.WebhookEvent
	/*
	   The date and time when the order payment was created. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).
	   Example: 2024-08-31T02:20:26+08:00
	*/
	CreateTime string `json:"create_time,omitempty" url:"-"`

	/*
	   Payment amount in the store currency. The value is rounded to two decimal places.
	   Example: 0
	*/
	PayAmount float64 `json:"pay_amount,omitempty" url:"-"`

	/*
	   Payment serial number generated by the payment channel.
	   Example:
	*/
	PayChannelDealId string `json:"pay_channel_deal_id,omitempty" url:"-"`

	/*
	   Payment order number, a unique ID for order payment defined internally by SHOPLINE.
	   Example:
	*/
	PaySeq string `json:"pay_seq,omitempty" url:"-"`

	/*
	   Payment status. Valid values are:
	   - `unpaid`: unpaid
	   - `pending`: payment in process
	   - `risking`: under risk control
	   - `paid`：paid
	   - `paid_overtime`: payment timeout
	   - `paid_failed`: payment failed
	   Example:
	*/
	PayStatus string `json:"pay_status,omitempty" url:"-"`

	/*
	   Payment channel standard status code.
	   Example:
	*/
	StatusCode string `json:"status_code,omitempty" url:"-"`

	/*
	   The description of `status_code`.
	   Example:
	*/
	StatusMsg string `json:"status_msg,omitempty" url:"-"`
}
