// Package order generated by SHOPLINE since v20260301
package order

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *OrderCancelledEvent) GetSupportedTopic() string {
	return "orders/cancelled"
}

type OrderCancelledEventTaxLine struct {
	/*
	   The tax amount, displayed in both the buyer's currency and the store's currency.
	   Example: map[presentment_money:map[amount:8.88 currency_code:USD] shop_money:map[amount:8.88 currency_code:USD]]
	*/
	PriceSet PriceSet `json:"price_set,omitempty" url:"-"`

	/*
	   Tax rate.
	   Example: 0
	*/
	Rate float64 `json:"rate,omitempty" url:"-"`

	/*
	   Tax rate (percentage value, i.e. rate * 100).
	   Example: 0
	*/
	RatePercentage float64 `json:"rate_percentage,omitempty" url:"-"`

	/*
	   Tax name.
	   Example:
	*/
	Title string `json:"title,omitempty" url:"-"`
}

type OrderCancelledEventFulfillment struct {
	/*
	   Fulfillment ID.
	   Example: 22046737798141702810214336
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   A list of product line.
	   Example: []
	*/
	LineItems []OrderCancelledEventLineItem `json:"line_items,omitempty" url:"-"`

	/*
	   The order ID.
	   Example: 21056577640603870897253153
	*/
	OrderId string `json:"order_id,omitempty" url:"-"`

	/*
	   Logistics delivery status. Valid values are:
	   - `success`: shipment successful
	   - `cancelled`: shipment has been canceled
	   Example: fulfilled
	*/
	ShipmentStatus string `json:"shipment_status,omitempty" url:"-"`

	/*
	   Logistics company name.
	   Example: Sf international
	*/
	TrackingCompany string `json:"tracking_company,omitempty" url:"-"`

	/*
	   Third-party logistics tracking number.
	   Example: yun0991
	*/
	TrackingNumber string `json:"tracking_number,omitempty" url:"-"`

	/*
	   Logistics company URL.
	   Example: https://www.sf-international.com/
	*/
	TrackingUrl string `json:"tracking_url,omitempty" url:"-"`

	/*
	   The date and time when the fulfillment was updated. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).

	   Example: `2024-08-31T02:20:26+08:00`
	   Example: 2022-11-04T10:18:46+00:00
	*/
	UpdatedAt string `json:"updated_at,omitempty" url:"-"`

	/*
	   The date and time when the fulfillment was created. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).

	   Example: `2024-08-31T02:20:26+08:00`
	   Example: 2022-11-04T10:18:46+00:00
	*/
	CreatedAt string `json:"created_at,omitempty" url:"-"`

	/*
	   Logistics delivery status. Valid values are:
	   - `success`: shipped
	   - `cancelled`: cancelled
	   Example: success
	*/
	Status string `json:"status,omitempty" url:"-"`

	/*
	   If this parameter is specified, the individual parameters `tracking_url`, `tracking_number`, and `tracking_company` will be ignored.Maximum of 10 tracking infos allowed.
	   Example: []
	*/
	TrackingInfoList []TrackingInfoList `json:"tracking_info_list,omitempty" url:"-"`
}

type OrderCancelledEvent struct {
	client.WebhookEvent
	/*
	   Merchant's reason for order cancellation.
	   Example: 157.119.232.35
	*/
	BrowserIp string `json:"browser_ip,omitempty" url:"-"`

	/*
	   The order amount deducted using membership points, displayed in the store's currency.
	   Example: 8.00
	*/
	DeductMemberPointAmount string `json:"deduct_member_point_amount,omitempty" url:"-"`

	/*
	   Discount information.
	   Example: []
	*/
	DiscountApplications []DiscountApplication `json:"discount_applications,omitempty" url:"-"`

	/*
	   Merchant note content.
	   Example: []
	*/
	NoteAttributes []NoteAttribute `json:"note_attributes,omitempty" url:"-"`

	/*
	   The date and time when the order was completed. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).

	   Example: `2024-08-31T02:20:26+08:00`
	   Example: 2023-04-12T22:59:52+08:00
	*/
	ProcessedAt string `json:"processed_at,omitempty" url:"-"`

	/*
	   The total tax amount, displayed in both the buyer's currency and the store's currency.
	   Example: map[presentment_money:map[amount:8.00 currency_code:USD] shop_money:map[amount:8.00 currency_code:USD]]
	*/
	TotalTaxSet TotalTaxSet `json:"total_tax_set,omitempty" url:"-"`

	/*
	   The amount discrepancy due to rounding adjustments in POS transactions, expressed in the store currency.
	   Example: 8.00
	*/
	AdjustPrice string `json:"adjust_price,omitempty" url:"-"`

	/*
	   The order source channel.
	   Example: pos
	*/
	OrderSource string `json:"order_source,omitempty" url:"-"`

	/*
	   Merchant's reason for order cancellation.
	   Example: I don't want to buy it.
	*/
	CancelReason string `json:"cancel_reason,omitempty" url:"-"`

	/*
	   The buyer's company information.
	   Example: map[id:1005619945158043247856 location_id:3005619945158043247856 tax_registration_id:213213]
	*/
	Company Company `json:"company,omitempty" url:"-"`

	/*
	   Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).
	   Example: 2021-08-16T08:27:57+00:00
	*/
	CreatedAt string `json:"created_at,omitempty" url:"-"`

	/*
	   The total discount amount, rounded to two decimal places, is the sum of marketing discounts and custom discounts, displayed in the store's currency.
	   Example: 8.00
	*/
	CurrentTotalDiscounts string `json:"current_total_discounts,omitempty" url:"-"`

	/*
	   The draft order ID.
	   Example:
	*/
	DraftOrderSeq string `json:"draft_order_seq,omitempty" url:"-"`

	/*
	   Shipping address.
	   Example: map[address1:Address 1 address2:Address 2 city:New York company:new company country:USA country_code:USD first_name:Tom last_name:Washington latitude:23.35773 longitude:116.4151 name:Tom Washington phone:13100000000 province:Guangdong province_code:4200006 standard_province_code: zip:521000]
	*/
	ShippingAddress OrderCancelledEventShippingAddress `json:"shipping_address,omitempty" url:"-"`

	/*
	   TIN. Tax identification number.
	   Example: 1111111
	*/
	TaxNumber string `json:"tax_number,omitempty" url:"-"`

	/*
	   The unique identifier for abandoned order data.
	   Example: c2c4a58186b9d96395d7e6b5c2969577
	*/
	CheckoutToken string `json:"checkout_token,omitempty" url:"-"`

	/*
	   The total amount of the products, calculated as the product of the unit price and quantity, displayed in the store's currency.
	   Example: 8.00
	*/
	CurrentSubtotalPrice string `json:"current_subtotal_price,omitempty" url:"-"`

	/*
	   Order label.
	   Example: watch
	*/
	Tags string `json:"tags,omitempty" url:"-"`

	/*
	   The total unpaid amount, rounded to two decimal places, is displayed in the store's currency.
	   Example: 8.00
	*/
	TotalOutstanding string `json:"total_outstanding,omitempty" url:"-"`

	/*
	   The tip amount, rounded to two decimal places, is displayed in the store's currency.
	   Example: 8.00
	*/
	TotalTipReceived string `json:"total_tip_received,omitempty" url:"-"`

	/*
	   A list of product line.
	   Example: []
	*/
	LineItems []OrderCancelledEventLineItem `json:"line_items,omitempty" url:"-"`

	/*
	   A list of refund.
	   Example: []
	*/
	Refunds []OrderCancelledEventRefund `json:"refunds,omitempty" url:"-"`

	/*
	   The total tax amount, displayed in the store's currency.
	   Example: 8.00
	*/
	CurrentTotalTax string `json:"current_total_tax,omitempty" url:"-"`

	/*
	   Position in discount details.
	   Example: 8.00
	*/
	SubtotalPrice string `json:"subtotal_price,omitempty" url:"-"`

	/*
	   The tip amount, displayed in both the store's currency and the buyer's currency.
	   Example: map[presentment_money:map[amount:8.88 currency_code:USD] shop_money:map[amount:8.88 currency_code:USD]]
	*/
	TotalTipReceivedSet TotalTipReceivedSet `json:"total_tip_received_set,omitempty" url:"-"`

	/*
	   The total customs duties for the products, displayed in both the buyer's currency and the store's currency.
	   Example: map[presentment_money:map[amount:8.88 currency_code:USD] shop_money:map[amount:8.88 currency_code:USD]]
	*/
	CurrentTotalDutiesSet CurrentTotalDutiesSet `json:"current_total_duties_set,omitempty" url:"-"`

	/*
	   The total tax amount, displayed in both the buyer's currency and the store's currency.
	   Example: map[presentment_money:map[amount:8.00 currency_code:USD] shop_money:map[amount:8.00 currency_code:USD]]
	*/
	CurrentTotalTaxSet CurrentTotalTaxSet `json:"current_total_tax_set,omitempty" url:"-"`

	/*
	   The total discount amount, rounded to two decimal places, is the sum of marketing discounts and custom discounts, displayed in the store's currency.
	   Example: 8.00
	*/
	TotalDiscounts string `json:"total_discounts,omitempty" url:"-"`

	/*
	   The date and time when the order was updated. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).

	   Example: `2024-08-31T02:20:26+08:00`
	   Example: 2021-08-16T08:27:57+00:00
	*/
	UpdatedAt string `json:"updated_at,omitempty" url:"-"`

	/*
	   Abandoned checkout ID.
	   Example: 2404785166526352972864
	*/
	CheckoutId string `json:"checkout_id,omitempty" url:"-"`

	/*
	   The total amount of the products, calculated as the product of the unit price and quantity, displayed in both the buyer's currency and the store's currency.
	   Example: map[presentment_money:map[amount:8.00 currency_code:USD] shop_money:map[amount:8.00 currency_code:USD]]
	*/
	CurrentSubtotalPriceSet CurrentSubtotalPriceSet `json:"current_subtotal_price_set,omitempty" url:"-"`

	/*
	   Buyer side currency.
	   Example: 8.00
	*/
	PresentmentCurrency string `json:"presentment_currency,omitempty" url:"-"`

	/*
	   Logistics information.
	   Example: []
	*/
	ShippingLines []ShippingLine `json:"shipping_lines,omitempty" url:"-"`

	/*
	   The total price after product discounts is calculated as the total product price minus discounts and custom discounts, displayed in the store's currency.
	   Example: map[presentment_money:map[amount:8.00 currency_code:USD] shop_money:map[amount:8.00 currency_code:USD]]
	*/
	SubtotalPriceSet SubtotalPriceSet `json:"subtotal_price_set,omitempty" url:"-"`

	/*
	   The order tax information.
	   Example: []
	*/
	TaxLines []TaxLine `json:"tax_lines,omitempty" url:"-"`

	/*
	   The total original price of the products, rounded to two decimal places, is displayed in the store's currency.
	   Example: 8.00
	*/
	TotalLineItemsPrice string `json:"total_line_items_price,omitempty" url:"-"`

	/*
	   The total original price of the products, displayed in both the buyer's currency and the store's currency.
	   Example: map[presentment_money:map[amount:8.00 currency_code:USD] shop_money:map[amount:8.00 currency_code:USD]]
	*/
	TotalLineItemsPriceSet TotalLineItemsPriceSet `json:"total_line_items_price_set,omitempty" url:"-"`

	/*
	   Settlement currency of the order. A three-letter currency code that follows the  [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html) standard. For example, `USD`.
	   Example: USD
	*/
	Currency string `json:"currency,omitempty" url:"-"`

	/*
	   Promo code information.
	   Example: []
	*/
	DiscountCodes []DiscountCode `json:"discount_codes,omitempty" url:"-"`

	/*
	   System order number.
	   Example: 21056577640603870897253153
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   Whether the total amount includes the tax amount.
	   - `true`：including
	   - `false`：not including
	   Example: true
	*/
	TaxesIncluded bool `json:"taxes_included,omitempty" url:"-"`

	/*
	   The total shipping fee for the order, displayed in both the buyer's currency and the store's currency.
	   Example: map[presentment_money:map[amount:8.00 currency_code:USD] shop_money:map[amount:8.00 currency_code:USD]]
	*/
	TotalShippingPriceSet TotalShippingPriceSet `json:"total_shipping_price_set,omitempty" url:"-"`

	/*
	   Total product weight, unit: g.
	   Example: 100
	*/
	TotalWeight float64 `json:"total_weight,omitempty" url:"-"`

	/*
	   Buyer ID.
	   Example: 4201057495
	*/
	UserId string `json:"user_id,omitempty" url:"-"`

	/*
	   Buyer's country, language code + country name abbreviation.

	   Example: `enCA`
	   Example: enCN
	*/
	CustomerLocale string `json:"customer_locale,omitempty" url:"-"`

	/*
	   Merchant remark content, multiple separated by commas.
	   Example: Notes
	*/
	Note string `json:"note,omitempty" url:"-"`

	/*
	   A list of payment order.
	   Example: []
	*/
	PaymentDetails []OrderCancelledEventPaymentDetail `json:"payment_details,omitempty" url:"-"`

	/*
	   Store ID.
	   Example: 1644828244663
	*/
	StoreId string `json:"store_id,omitempty" url:"-"`

	/*
	   Types of tax ID.
	   Example: Type
	*/
	TaxType string `json:"tax_type,omitempty" url:"-"`

	/*
	   The total tax amount, rounded to two decimal places, is displayed in the store's currency.
	   Example: 8.00
	*/
	TotalTax string `json:"total_tax,omitempty" url:"-"`

	/*
	   The unique identifier for shopping cart data.
	   Example: c2c4a58186b9d96395d7e6b5c2969577
	*/
	CartToken string `json:"cart_token,omitempty" url:"-"`

	/*
	   The total discount amount, displayed in both the buyer's currency and the store's currency.
	   Example: map[presentment_money:map[amount:8.00 currency_code:USD] shop_money:map[amount:8.00 currency_code:USD]]
	*/
	CurrentTotalDiscountsSet CurrentTotalDiscountsSet `json:"current_total_discounts_set,omitempty" url:"-"`

	/*
	   Buyer's mobile phone number.
	   Example: 18978789878
	*/
	Phone string `json:"phone,omitempty" url:"-"`

	/*
	   The address for sending billing invoices.
	   Example: map[address1:Address 1 address2:Address 2 city:New York company:new company country:USA country_code:US first_name:Tom last_name:Washington name:Tom Washington phone:13100000000 province:California province_code:4200006 standard_province_code: zip:5100000]
	*/
	BillingAddress BillingAddress `json:"billing_address,omitempty" url:"-"`

	/*
	   The total order amount, displayed in both the buyer's currency and the store's currency.
	   Example: 8.00
	*/
	CurrentTotalPrice string `json:"current_total_price,omitempty" url:"-"`

	/*
	   Buyer's email.
	   Example: test1000@Gmail.com
	*/
	Email string `json:"email,omitempty" url:"-"`

	/*
	   Order number. Different from the order ID, this number can have a custom prefix set in the SHOPLINE Admin.
	   Example: test001
	*/
	Name string `json:"name,omitempty" url:"-"`

	/*
	   The amount discrepancy due to rounding adjustments in POS transactions, displayed in both the buyer's order currency and the store currency.
	   Example: map[presentment_money:map[amount:8.00 currency_code:USD] shop_money:map[amount:8.00 currency_code:USD]]
	*/
	AdjustPriceSet AdjustPriceSet `json:"adjust_price_set,omitempty" url:"-"`

	/*
	   Buyer information.
	   Example: map[addresses:map[address1:Address 1 address2:Address 2 city:New York country:USA country_code:US first_name:Tom last_name:Washington name:Tom Washington phone:18978789878 province:California province_code:4200006 zip:510000] area_code:+86 created_at:2021-08-16T08:27:57+00:00 currency:USD email:test1000@Gmail.com first_name:Tom id:4201057495 last_name:Washington phone:18978789878]
	*/
	Customer Customer `json:"customer,omitempty" url:"-"`

	/*
	   Shipping status. Valid values are:
	   - `fulfilled`: order shipped
	   - `partial`: order partially shipped
	   - `null`: order not shipped

	   Note: the returned enum value is different from the query enumeration value of the input parameter.
	   Example: fulfilled
	*/
	FulfillmentStatus string `json:"fulfillment_status,omitempty" url:"-"`

	/*
	   Order status page URL.
	   Example: https://shoptest.myshopline.com/trade/thank_you?mainOrderMark=xxx&mainOrderSeq=200565776406008509
	*/
	OrderStatusUrl string `json:"order_status_url,omitempty" url:"-"`

	/*
	   Order creator.
	   Example: 4201057495
	*/
	ProcessedUserId string `json:"processed_user_id,omitempty" url:"-"`

	/*
	   The order amount deducted using membership points, displayed in both the buyer's currency and the store's currency.
	   Example: map[presentment_money:map[amount:8.88 currency_code:USD] shop_money:map[amount:8.88 currency_code:USD]]
	*/
	DeductMemberPointAmountSet DeductMemberPointAmountSet `json:"deduct_member_point_amount_set,omitempty" url:"-"`

	/*
	   Order payment status. Valid values are:

	   Example: unpaid
	*/
	FinancialStatus string `json:"financial_status,omitempty" url:"-"`

	/*
	   A list of fulfillment.
	   Example: []
	*/
	Fulfillments []OrderCancelledEventFulfillment `json:"fulfillments,omitempty" url:"-"`

	/*
	   The total discount amount, rounded to two decimal places, is the sum of marketing discounts and custom discounts, displayed in both the buyer's currency and the store's currency.
	   Example: map[presentment_money:map[amount:8.00 currency_code:USD] shop_money:map[amount:8.00 currency_code:USD]]
	*/
	TotalDiscountsSet TotalDiscountsSet `json:"total_discounts_set,omitempty" url:"-"`

	/*
	   Payment method list, payment method list used for this order:
	   - `SLpayments`
	   - `Paypal`
	   - `Oceanpay`
	   - `TwoCheckout`
	   - `AsiaBill`
	   - `Stripe`
	   - `Pacypay`
	   - `WorldPay`
	   - `COD`
	   - `CUSTOM`
	   - `adjustPay`
	   - `Xendit`
	   - `XenditOther`
	   Example: [Paypal]
	*/
	PaymentGatewayNames []string `json:"payment_gateway_names,omitempty" url:"-"`

	/*
	   The date and time when the order is canceled.
	   Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).

	   Example: `2024-08-31T02:20:26+08:00`
	   Example: 2012-05-01T14:22:25-04:00
	*/
	CancelledAt string `json:"cancelled_at,omitempty" url:"-"`

	/*
	   Client details.
	   Example: map[browser_ip:157.119.232.35 session_hash:c2c4a58186b9d96395d7e6b5c2969577 user_agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Sa uuid:4201057495]
	*/
	ClientDetails ClientDetails `json:"client_details,omitempty" url:"-"`

	/*
	   The total order amount, displayed in both the buyer's currency and the store's currency.
	   Example: map[presentment_money:map[amount:8.00 currency_code:USD] shop_money:map[amount:8.00 currency_code:USD]]
	*/
	CurrentTotalPriceSet CurrentTotalPriceSet `json:"current_total_price_set,omitempty" url:"-"`

	/*
	   The total unpaid amount, displayed in both the buyer's currency and the store's currency.
	   Example: map[presentment_money:map[amount:8.88 currency_code:USD] shop_money:map[amount:8.88 currency_code:USD]]
	*/
	TotalOutstandingSet TotalOutstandingSet `json:"total_outstanding_set,omitempty" url:"-"`
}

type OrderCancelledEventShippingAddress struct {
	/*
	   The city in the shipping address.
	   Example: New York
	*/
	City string `json:"city,omitempty" url:"-"`

	/*
	   Latitude of shipping address.
	   Example: 23.35773
	*/
	Latitude string `json:"latitude,omitempty" url:"-"`

	/*
	   Longitude of shipping address.
	   Example: 116.4151
	*/
	Longitude string `json:"longitude,omitempty" url:"-"`

	/*
	   The buyer's name.
	   Example: Tom Washington
	*/
	Name string `json:"name,omitempty" url:"-"`

	/*
	   The company name of the recipient.
	   Example: new company
	*/
	Company string `json:"company,omitempty" url:"-"`

	/*
	   The buyer's phone number.
	   Example: 13100000000
	*/
	Phone string `json:"phone,omitempty" url:"-"`

	/*
	   The postal code for the shipping address.
	   Example: 521000
	*/
	Zip string `json:"zip,omitempty" url:"-"`

	/*
	   The first line of the address. This typically includes information such as the street address or a post office box number.
	   Example: Address 1
	*/
	Address1 string `json:"address1,omitempty" url:"-"`

	/*
	   The second line of the address. This typically includes information such as apartment, suite, or unit number.
	   Example: Address 2
	*/
	Address2 string `json:"address2,omitempty" url:"-"`

	/*
	   The country or region in the shipping address.
	   Example: USA
	*/
	Country string `json:"country,omitempty" url:"-"`

	/*
	   The province in the shipping address.
	   Example: Guangdong
	*/
	Province string `json:"province,omitempty" url:"-"`

	/*
	   A two-letter country or region code that follows the [ISO 3166-1](https://www.iso.org/iso-3166-country-codes.html) standard, used to identify a specific country or region in the address. For example, `US`.
	   Example: USD
	*/
	CountryCode string `json:"country_code,omitempty" url:"-"`

	/*
	   The buyer's first name.
	   Example: Tom
	*/
	FirstName string `json:"first_name,omitempty" url:"-"`

	/*
	   The buyer's last name.
	   Example: Washington
	*/
	LastName string `json:"last_name,omitempty" url:"-"`

	/*
	   The code for the province in the shipping address, which can be a custom code or a two-digit [ISO 3166-2](https://www.iso.org/iso-3166-country-codes.html#2012_iso3166-2) international code.
	   Example: 4200006
	*/
	ProvinceCode string `json:"province_code,omitempty" url:"-"`

	/*
	   The code for the province in the shipping address, which is a two-digit [ISO 3166-2](https://www.iso.org/iso-3166-country-codes.html#2012_iso3166-2) international code.This differs from `province_code` - the `province_code` response field uses a custom code.
	   Example:
	*/
	StandardProvinceCode string `json:"standard_province_code,omitempty" url:"-"`
}

type OrderCancelledEventRefund struct {
	/*
	   Refund notes.
	   Example: Notes
	*/
	Note string `json:"note,omitempty" url:"-"`

	/*
	   Order ID.
	   Example: 21056577640603870897253153
	*/
	OrderId string `json:"order_id,omitempty" url:"-"`

	/*
	   The date and time when the refund was updated. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).

	   Example: `2024-08-31T02:20:26+08:00`
	   Example: 2022-11-04T10:18:46+00:00
	*/
	ProcessedAt string `json:"processed_at,omitempty" url:"-"`

	/*
	   User ID.
	   Example: 4201057495
	*/
	UserId string `json:"user_id,omitempty" url:"-"`

	/*
	   The date and time when the refund was created. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).

	   Example: `2024-08-31T02:20:26+08:00`
	   Example: 2022-11-04T10:18:46+00:00
	*/
	CreatedAt string `json:"created_at,omitempty" url:"-"`

	/*
	   Refund ID.
	   Example: 2605659027312156877634
	*/
	Id string `json:"id,omitempty" url:"-"`
}

type OrderCancelledEventPaymentDetail struct {
	/*
	   Payment order status code description.
	   Example: PENDING_REVIEW
	*/
	StatusMsg string `json:"status_msg,omitempty" url:"-"`

	/*
	   Buyer's message.
	   Example: Notes
	*/
	BuyerNote string `json:"buyer_note,omitempty" url:"-"`

	/*
	   Indicate whether it is an archived order. Valid values are:
	   - `true`: archived order
	   - `false`: unarchived order
	   Example: true
	*/
	HiddenOrder bool `json:"hidden_order,omitempty" url:"-"`

	/*
	   Payment serial number: the payment number generated by the payment channel.
	   Example: pi_3MI897Hezv8FxjBO1uGxMPhX
	*/
	PayChannelDealId string `json:"pay_channel_deal_id,omitempty" url:"-"`

	/*
	   Payment network payment order number, the unique number request number of the payment order defined internally in SL.
	   Example: 23057287797738260472676128
	*/
	PaySeq string `json:"pay_seq,omitempty" url:"-"`

	/*
	   Payment order status. Valid values are:
	   - `unpaid`: payment order unpaid
	   - `pending`: payment order in process
	   - `risking`: payment order under risk control
	   - `paid`：payment order paid
	   - `paid_overtime`: payment order payment timeout
	   - `paid_failed`: payment order failed
	   Example: unpaid
	*/
	PayStatus string `json:"pay_status,omitempty" url:"-"`

	/*
	   The date and time when the payment order was completed. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).

	   Example: `2024-08-31T02:20:26+08:00`
	   Example: 2023-04-12T22:59:52+08:00
	*/
	ProcessedAt string `json:"processed_at,omitempty" url:"-"`

	/*
	   The date and time when the payment order was created. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).

	   Example: `2024-08-31T02:20:26+08:00`
	   Example: 2021-08-16T08:27:57+00:00
	*/
	CreateTime string `json:"create_time,omitempty" url:"-"`

	/*
	   Payment amount.
	   Example: 8
	*/
	PayAmount float64 `json:"pay_amount,omitempty" url:"-"`

	/*
	   Order status. Valid values are:
	   - `open`: processing
	   - `cancelled`: cancelled
	   Example: open
	*/
	Status string `json:"status,omitempty" url:"-"`

	/*
	   Payment status code.
	   Example: RISK_PENDING
	*/
	StatusCode string `json:"status_code,omitempty" url:"-"`
}

type OrderCancelledEventLineItem struct {
	/*
	   Commodity attribute value, multiple divided by " / ".

	   Example: `155 / red / large`
	   Example: big
	*/
	VariantTitle string `json:"variant_title,omitempty" url:"-"`

	/*
	   Indicates whether the product is a gift card item.
	   - `true`：gift card item
	   - `false`：not a gift card item
	   Example: true
	*/
	GiftCard bool `json:"gift_card,omitempty" url:"-"`

	/*
	   The ID of the product snapshot table, generated by the system, uniquely confirms a product with the order number.
	   Example: 401
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   Product picture.
	   Example: https://d2n979dmt31clo.cloudfront.net/image/store/4211449909/1667384795847/63928f08a7174ab2958c6a969
	*/
	ImageUrl string `json:"image_url,omitempty" url:"-"`

	/*
	   Customize additional fields for products.
	   Example: []
	*/
	Properties []Property `json:"properties,omitempty" url:"-"`

	/*
	   Product SKU serial number.
	   Example: 18056761559987524812644011
	*/
	VariantId string `json:"variant_id,omitempty" url:"-"`

	/*
	   Location ID.
	   Example: 5327026538935748524
	*/
	LocationId string `json:"location_id,omitempty" url:"-"`

	/*
	   Product selling price. The value is rounded to two decimal places.
	   Example: 8.00
	*/
	Price string `json:"price,omitempty" url:"-"`

	/*
	   The product price, displayed in both the store's currency and the buyer's currency.
	   Example: map[presentment_money:map[amount:8.00 currency_code:USD] shop_money:map[amount:8.00 currency_code:USD]]
	*/
	PriceSet PriceSet `json:"price_set,omitempty" url:"-"`

	/*
	   SPU serial number.
	   Example: 16056761559984840457934011
	*/
	ProductId string `json:"product_id,omitempty" url:"-"`

	/*
	   Supplier.
	   Example: Supplier
	*/
	Vendor string `json:"vendor,omitempty" url:"-"`

	/*
	   Product attributes: name - attribute value. Multiple separated by comma ",".

	   Example: `color - red, size - X`
	   Example: red
	*/
	Attribute string `json:"attribute,omitempty" url:"-"`

	/*
	   Discount details.
	   Example: []
	*/
	DiscountAllocations []DiscountAllocation `json:"discount_allocations,omitempty" url:"-"`

	/*
	   Tariff information.
	   Example: []
	*/
	Duties []Duty `json:"duties,omitempty" url:"-"`

	/*
	   Logistics business name, if there are multiple different delivery providers in product, then use separated by ','.
	   Example: Sf international
	*/
	FulfillmentService string `json:"fulfillment_service,omitempty" url:"-"`

	/*
	   The shipping status of the product. Valid values are:
	   - `fulfilled`: products shipped
	   - `partial`: products partially shipped
	   - `null`: products not shipped
	   Example: fulfilled
	*/
	FulfillmentStatus string `json:"fulfillment_status,omitempty" url:"-"`

	/*
	   SKU title.
	   Example: test-002
	*/
	Name string `json:"name,omitempty" url:"-"`

	/*
	   Indicates whether the product is subject to shipping.
	   - `true`：Shipping is required.
	   - `false`：Shipping is not.
	   Example: true
	*/
	RequiresShipping bool `json:"requires_shipping,omitempty" url:"-"`

	/*
	   SKU number.
	   Example: 18056761559987524812644011
	*/
	Sku string `json:"sku,omitempty" url:"-"`

	/*
	   The remaining quantity of products that can be fulfilled at the product line dimension.
	   Example: 2
	*/
	FulfillableQuantity int `json:"fulfillable_quantity,omitempty" url:"-"`

	/*
	   Product weight, unit: g.
	   Example: 100
	*/
	Grams float64 `json:"grams,omitempty" url:"-"`

	/*
	   Quantity of products in the order.
	   Example: 2
	*/
	Quantity int `json:"quantity,omitempty" url:"-"`

	/*
	   Product tags, multiple commas separated.
	   Example: watch
	*/
	Tags string `json:"tags,omitempty" url:"-"`

	/*
	   List of tax.
	   Example: []
	*/
	TaxLines []OrderCancelledEventTaxLine `json:"tax_lines,omitempty" url:"-"`

	/*
	   Indicates whether the product is taxable.
	   - `true`: taxable
	   - `false`: not taxable
	   Example: true
	*/
	Taxable bool `json:"taxable,omitempty" url:"-"`

	/*
	   Product title.
	   Example: Beautiful skirt
	*/
	Title string `json:"title,omitempty" url:"-"`
}

type Property struct {
	/*
	   Product attributes: name - attribute value. Multiple separated by comma ",".

	   Example: `color - red, size - X`
	   Example: Attach
	*/
	Additional string `json:"additional,omitempty" url:"-"`

	/*
	   Product customization information name.
	   Example: Custom properties
	*/
	Name string `json:"name,omitempty" url:"-"`

	/*
	   Types of customized product information. Valid values are:
	   - `text`：text type
	   - `picture`：picture type
	   - `link`：link type
	   Example: text
	*/
	Type string `json:"type,omitempty" url:"-"`

	/*
	   Product customization information link.
	   Example: [https://www.urls.com]
	*/
	Urls []string `json:"urls,omitempty" url:"-"`

	/*
	   Product customization information content.
	   Example: Custom attribute values
	*/
	Value string `json:"value,omitempty" url:"-"`
}

type Duty struct {
	/*
	   Tariff number.
	   Example:
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   Tariff, displayed in both the buyer's currency and the store's currency.
	   Example: map[presentment_money:map[amount:8.88 currency_code:USD] shop_money:map[amount:8.88 currency_code:USD]]
	*/
	Price Price `json:"price,omitempty" url:"-"`

	/*
	   List of tax.
	   Example: []
	*/
	TaxLines []OrderCancelledEventTaxLine `json:"tax_lines,omitempty" url:"-"`

	/*
	   Country code of origin or shipping point.
	   Example:
	*/
	CountryCodeOfOrigin string `json:"country_code_of_origin,omitempty" url:"-"`

	/*
	   Customs code.
	   Example:
	*/
	HarmonizedSystemCode string `json:"harmonized_system_code,omitempty" url:"-"`
}

type Price struct {
	/*
	   Buyer's currency.
	   Example: map[amount:8.88 currency_code:USD]
	*/
	PresentmentMoney PresentmentMoney `json:"presentment_money,omitempty" url:"-"`

	/*
	   Store's currency.
	   Example: map[amount:8.88 currency_code:USD]
	*/
	ShopMoney ShopMoney `json:"shop_money,omitempty" url:"-"`
}
