// Package order generated by SHOPLINE since v20260301
package order

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *RefundCreatedEvent) GetSupportedTopic() string {
	return "refunds/create"
}

type TaxAmountSet struct {
	/*
	   Display amount
	   Example: map[amount:100 currency_code:USD]
	*/
	PresentmentMoney RefundCreatedEventPresentmentMoney `json:"presentment_money,omitempty" url:"-"`

	/*
	   Shop amount
	   Example: map[amount:100 currency_code:USD]
	*/
	ShopMoney RefundCreatedEventShopMoney `json:"shop_money,omitempty" url:"-"`
}

type RefundCreatedEventPresentmentMoney struct {
	/*
	   Amount
	   Example: 100
	*/
	Amount float64 `json:"amount,omitempty" url:"-"`

	/*
	   Currency
	   Example: USD
	*/
	CurrencyCode string `json:"currency_code,omitempty" url:"-"`
}

type RefundCreatedEventShopMoney struct {
	/*
	   Amount
	   Example: 100
	*/
	Amount float64 `json:"amount,omitempty" url:"-"`

	/*
	   Currency
	   Example: USD
	*/
	CurrencyCode string `json:"currency_code,omitempty" url:"-"`
}

type RefundCreatedEventLineItem struct {
	/*
	   Tax information
	   Example: []
	*/
	TaxLines []RefundCreatedEventTaxLine `json:"tax_lines,omitempty" url:"-"`

	/*
	   Product attributes: name - attribute value. Multiple separated by comma ", ". For example: color - red, size - X
	   Example: Size-x
	*/
	Attribute string `json:"attribute,omitempty" url:"-"`

	/*
	   Logistics company name
	   Example: Go square
	*/
	FulfillmentService string `json:"fulfillment_service,omitempty" url:"-"`

	/*
	   Multi-currency selling price
	   Example: map[presentment_money:map[amount: currency_code:] shop_money:map[amount: currency_code:]]
	*/
	PriceSet PriceSet `json:"price_set,omitempty" url:"-"`

	/*
	   SPU serial number
	   Example: 18054488231146952151833534
	*/
	ProductId string `json:"product_id,omitempty" url:"-"`

	/*
	   Product SKU serial number
	   Example: 18054488231146952151833534
	*/
	VariantId string `json:"variant_id,omitempty" url:"-"`

	/*
	   Supplier
	   Example: Supplier
	*/
	Vendor string `json:"vendor,omitempty" url:"-"`

	/*
	   The shipping status of the product, shipping status, fulfilled-shipped; partial-partially shipped; null-unshipped;
	   Example: partial
	*/
	FulfillmentStatus string `json:"fulfillment_status,omitempty" url:"-"`

	/*
	   Product code, barCode
	   Example: SKU1234
	*/
	Sku string `json:"sku,omitempty" url:"-"`

	/*
	   Product title
	   Example: T-short
	*/
	Title string `json:"title,omitempty" url:"-"`

	/*
	   Commodity attribute value, multiple divided by " / ", such as: "155 / red / large"
	   Example: 155 / red / large
	*/
	VariantTitle string `json:"variant_title,omitempty" url:"-"`

	/*
	   Available quantity
	   Example: 1
	*/
	FulfillableQuantity int `json:"fulfillable_quantity,omitempty" url:"-"`

	/*
	   The ID of the product snapshot table, generated by the system, uniquely confirms a product with the order number
	   Example: 2655436734527560
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   Product quantity
	   Example: 1
	*/
	Quantity int `json:"quantity,omitempty" url:"-"`

	/*
	   Shipping or not
	   Example: true
	*/
	RequiresShipping bool `json:"requires_shipping,omitempty" url:"-"`

	/*
	   Tax or not？
	   Example: true
	*/
	Taxable bool `json:"taxable,omitempty" url:"-"`

	/*
	   The quantity of products that are actually shipped.
	   Example: 1
	*/
	FulfillmentQuantity int `json:"fulfillment_quantity,omitempty" url:"-"`

	/*
	   Weight ( grams )
	   Example: 1.2
	*/
	Grams float64 `json:"grams,omitempty" url:"-"`

	/*
	   Commodity price, precision 2
	   Example: 100
	*/
	Price string `json:"price,omitempty" url:"-"`
}

type RefundCreatedEventTaxLine struct {
	/*
	   Multi-currency information of tax
	   Example: map[presentment_money:map[amount:100 currency_code:USD] shop_money:map[amount:100 currency_code:USD]]
	*/
	PriceSet PriceSet `json:"price_set,omitempty" url:"-"`

	/*
	   Tax rate
	   Example: 1.2
	*/
	Rate float64 `json:"rate,omitempty" url:"-"`

	/*
	   Headline
	   Example: Headline
	*/
	Title string `json:"title,omitempty" url:"-"`

	/*
	   Tax type , product_tax : product tax ; shipping_tax : shipping tax
	   Example: product_tax
	*/
	Type string `json:"type,omitempty" url:"-"`

	/*
	   Tax, precision 2
	   Example: 100
	*/
	Price string `json:"price,omitempty" url:"-"`
}

type PaymentDetails struct {
	/*
	   Card details for credit card payments.
	   Example: map[credit_card_bin:471110 credit_card_brand:visa credit_card_expire_month:12 credit_card_expire_year:30 credit_card_number:471110******0000]
	*/
	CreditCard CreditCard `json:"credit_card,omitempty" url:"-"`

	/*
	   Payment serial number from the external channel.
	   Example: pi_3MI897Hezv8FxjBO1uGxMPhX
	*/
	PayChannelDealId string `json:"pay_channel_deal_id,omitempty" url:"-"`

	/*
	   Transaction receipt returned by the payment gateway. Note that receipt formats may vary across different payment providers. Currently, only gift card payment method information is supported in the returned data.
	   Example: \"gift_card_id\":30170521219516412793210045
	*/
	ReceiptJson string `json:"receipt_json,omitempty" url:"-"`
}

type CreditCard struct {
	/*
	   Masked credit card number.
	   Example: 471110******0000
	*/
	CreditCardNumber string `json:"credit_card_number,omitempty" url:"-"`

	/*
	   Credit card bin.
	   Example: 471110
	*/
	CreditCardBin string `json:"credit_card_bin,omitempty" url:"-"`

	/*
	   Credit card brand.
	   Example: visa
	*/
	CreditCardBrand string `json:"credit_card_brand,omitempty" url:"-"`

	/*
	   Credit card expiration month.
	   Example: 12
	*/
	CreditCardExpireMonth string `json:"credit_card_expire_month,omitempty" url:"-"`

	/*
	   Credit card expiration year.
	   Example: 30
	*/
	CreditCardExpireYear string `json:"credit_card_expire_year,omitempty" url:"-"`
}

type RefundCreatedEvent struct {
	client.WebhookEvent
	/*
	   Adjust the order information
	   Example: []
	*/
	OrderAdjustments []OrderAdjustment `json:"order_adjustments,omitempty" url:"-"`

	/*
	   Order number
	   Example: 21057168152571061289431726
	*/
	OrderId string `json:"order_id,omitempty" url:"-"`

	/*
	   Refund items Details.
	   Example: []
	*/
	RefundLineItems []RefundCreatedEventRefundLineItem `json:"refund_line_items,omitempty" url:"-"`

	/*
	   Refund transaction information
	   Example: []
	*/
	Transactions []Transaction `json:"transactions,omitempty" url:"-"`

	/*
	   User ID
	   Example: 16576456
	*/
	UserId string `json:"user_id,omitempty" url:"-"`

	/*
	   Refund form creation time (see IOS8601 for the format)
	   Example: 2022-10-03T12:44:45-04:00
	*/
	CreatedAt string `json:"created_at,omitempty" url:"-"`

	/*
	   Refund ID
	   Example: SL201AS4571669738589065294
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   Update time (see IOS8601 for the format)
	   Example: 2022-10-03T12:44:45-04:00
	*/
	ProcessedAt string `json:"processed_at,omitempty" url:"-"`

	/*
	   A list of refund transactions.
	   Example: []
	*/
	TransactionsV2 []TransactionsV2 `json:"transactions_v2,omitempty" url:"-"`

	/*
	   Refund Notes
	   Example: Notes
	*/
	Note string `json:"note,omitempty" url:"-"`
}

type OrderAdjustment struct {
	/*
	   Adjust the single amount
	   Example: map[presentment_money:map[amount:100 currency_code:USD] shop_money:map[amount:100 currency_code:USD]]
	*/
	AmountSet AmountSet `json:"amount_set,omitempty" url:"-"`

	/*
	   Refund adjustment single id
	   Example: 2309123221222208434
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   Adjust single type
	   Example: shipping_refund
	*/
	Kind string `json:"kind,omitempty" url:"-"`

	/*
	   Adjust the reason
	   Example: reason msg
	*/
	Reason string `json:"reason,omitempty" url:"-"`

	/*
	   Adjust the single amount
	   Example: 100
	*/
	Amount string `json:"amount,omitempty" url:"-"`

	/*
	   Order number
	   Example: 21057168152571061289431726
	*/
	OrderId string `json:"order_id,omitempty" url:"-"`

	/*
	   Refund single id
	   Example: 27057168152571061289431726
	*/
	RefundId string `json:"refund_id,omitempty" url:"-"`

	/*
	   Adjust the single tax amount
	   Example: 100
	*/
	TaxAmount string `json:"tax_amount,omitempty" url:"-"`

	/*
	   Adjust the single tax amount
	   Example: map[presentment_money:map[amount:100 currency_code:USD] shop_money:map[amount:100 currency_code:USD]]
	*/
	TaxAmountSet TaxAmountSet `json:"tax_amount_set,omitempty" url:"-"`
}

type RefundCreatedEventRefundLineItem struct {
	/*
	   Product rows
	   Example: map[attribute:Size-x fulfillable_quantity:1 fulfillment_quantity:1 fulfillment_service:Go square fulfillment_status:partial grams:1.2 id:2655436734527560 price:100 price_set:map[presentment_money:map[amount: currency_code:] shop_money:map[amount: currency_code:]] product_id:18054488231146952151833534 quantity:1 requires_shipping:true sku:SKU1234 tax_lines:[] taxable:true title:T-short variant_id:18054488231146952151833534 variant_title:155 / red / large vendor:Supplier]
	*/
	LineItem RefundCreatedEventLineItem `json:"line_item,omitempty" url:"-"`

	/*
	   The ID of the product snapshot table, generated by the system, uniquely confirms a product with the order number
	   Example: 23312553324324
	*/
	LineItemId string `json:"line_item_id,omitempty" url:"-"`

	/*
	   Quantity, quantity of goods
	   Example: 1
	*/
	Quantity int `json:"quantity,omitempty" url:"-"`

	/*
	   Inventory return type, no_restock-not returned, cancel-cancelled, return-returned only not returned
	   Example: no_restock
	*/
	RestockType string `json:"restock_type,omitempty" url:"-"`

	/*
	   Total refund amount, precision 2
	   Example: 100
	*/
	Subtotal float64 `json:"subtotal,omitempty" url:"-"`

	/*
	   Tax amount of refunded goods, precision 2
	   Example: 100
	*/
	TotalTax float64 `json:"total_tax,omitempty" url:"-"`

	/*
	   Total tax amount, multi-currency information
	   Example: map[presentment_money:map[amount:100 currency_code:USD] shop_money:map[amount:100 currency_code:USD]]
	*/
	TotalTaxSet TotalTaxSet `json:"total_tax_set,omitempty" url:"-"`

	/*
	   Refund order number
	   Example: 27057168152571061289431726
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   Total refund amount, multi-currency information, same on seller and buyer side
	   Example: map[presentment_money:map[amount:100 currency_code:USD] shop_money:map[amount:100 currency_code:USD]]
	*/
	SubtotalSet SubtotalSet `json:"subtotal_set,omitempty" url:"-"`
}

type Transaction struct {
	/*
	   Order number
	   Example: 21056836827909126061559008
	*/
	OrderId string `json:"order_id,omitempty" url:"-"`

	/*
	   Transaction type (authorization, capture, sale, void, refund)
	   Example: refund
	*/
	Kind string `json:"kind,omitempty" url:"-"`

	/*
	   Creation time
	   Example: 2022-10-03T12:44:45-04:00
	*/
	ProcessedAt string `json:"processed_at,omitempty" url:"-"`

	/*
	   Handling status, pending, failure, success, and error
	   Example: success
	*/
	Status string `json:"status,omitempty" url:"-"`

	/*
	   Buyer ID
	   Example: 4323434
	*/
	UserId string `json:"user_id,omitempty" url:"-"`

	/*
	   Refund amount , accuracy 2
	   Example: 100
	*/
	Amount string `json:"amount,omitempty" url:"-"`

	/*
	   Creation time
	   Example: 2022-10-03T12:44:45-04:00
	*/
	CreatedAt string `json:"created_at,omitempty" url:"-"`

	/*
	   Currency
	   Example: USD
	*/
	Currency string `json:"currency,omitempty" url:"-"`

	/*
	   Refund ID
	   Example: 10100112220607455014540963840
	*/
	Id string `json:"id,omitempty" url:"-"`
}

type TransactionsV2 struct {
	/*
	   Payment failure message returned by the channel.
	   Example: PENDING_REVIEW
	*/
	ErrorMsg string `json:"error_msg,omitempty" url:"-"`

	/*
	   Transaction ID.
	   Example: 3201270375342377769857557605
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   Payment method.
	   Example: Mypay
	*/
	PaymentMethod string `json:"payment_method,omitempty" url:"-"`

	/*
	   The date and time when the transaction was canceled. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).
	   Example: 2021-08-16T08:27:57+00:00
	*/
	CreateAt string `json:"create_at,omitempty" url:"-"`

	/*
	   Payment failure reason code returned by the channel.
	   Example: RISK_PENDING
	*/
	ErrorCode string `json:"error_code,omitempty" url:"-"`

	/*
	   Payment channel.
	   Example: Mypay
	*/
	Gateway string `json:"gateway,omitempty" url:"-"`

	/*
	   Transaction kind：

	   - `sale`: Automatically captured transaction
	   - `authorization`: Authorized transaction
	   - `capture`: Manually captured transaction
	   - `void`: Voided transaction
	   - `refund`: Refunded transaction
	   Example:
	*/
	Kind string `json:"kind,omitempty" url:"-"`

	/*
	   Payment details.
	   Example: map[credit_card:map[credit_card_bin:471110 credit_card_brand:visa credit_card_expire_month:12 credit_card_expire_year:30 credit_card_number:471110******0000] pay_channel_deal_id:pi_3MI897Hezv8FxjBO1uGxMPhX receipt_json:\"gift_card_id\":30170521219516412793210045]
	*/
	PaymentDetails PaymentDetails `json:"payment_details,omitempty" url:"-"`

	/*
	   Transaction status：

	   - `created`：Transaction has been created
	   - `pending`：Processing by the gateway.
	   - `success`：Transaction succeeded
	   - `fail`：Transaction failed
	   Example:
	*/
	Status string `json:"status,omitempty" url:"-"`

	/*
	   Transaction amount.The value is rounded to two decimal places.
	   Example: 8.00
	*/
	Amount string `json:"amount,omitempty" url:"-"`

	/*
	   Transaction currency. A three-letter currency code that follows the [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html) standard.
	   Example: USD
	*/
	Currency string `json:"currency,omitempty" url:"-"`
}
