// Package customer generated by SHOPLINE since v20251201
package customer

import (
	"errors"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type DeleteSpecifyCustomerTagAPIReq struct {
	client.BaseAPIRequest
	/*
	   Tag id collection
	   Example: [[SL201UT5491137867706559244,SL201UT5491137867790445325]]
	*/
	TagIds []string `json:"tag_ids,omitempty" url:"-"`

	/*
	   Customer id
	   Example: 2277270272
	*/
	UserId string `json:"user_id,omitempty" url:"-"`
}

func (req *DeleteSpecifyCustomerTagAPIReq) GetEndpoint() string {

	return "customer_tags_remove.json"

}

func (req *DeleteSpecifyCustomerTagAPIReq) GetMethod() string {
	return "POST"
}

func (req *DeleteSpecifyCustomerTagAPIReq) GetData() interface{} {
	return req
}

// Verify the api request parameters
func (req *DeleteSpecifyCustomerTagAPIReq) Verify() error {

	if req.UserId == "" {
		return errors.New("UserId is required")
	}

	return nil
}

func (req *DeleteSpecifyCustomerTagAPIReq) GetRequestOptions() *client.RequestOptions {
	opts := &client.RequestOptions{
		NotDecodeBody: true,
	}
	return opts
}

func (req *DeleteSpecifyCustomerTagAPIReq) NewAPIResp() *DeleteSpecifyCustomerTagAPIResp {
	return &DeleteSpecifyCustomerTagAPIResp{}
}

type DeleteSpecifyCustomerTagAPIResp struct {
	client.BaseAPIResponse
}
