// Package customer generated by SHOPLINE since v20251201
package customer

import (
	"errors"
	"fmt"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type QueryCustomerAddressDetails20APIReq struct {
	client.BaseAPIRequest
	/*
	   Address ID
	   Example:
	*/
	AddressId string `url:"-" json:"-"` // Required
	/*
	   Customer id
	   Example:
	*/
	Id string `url:"-" json:"-"` // Required
}

func (req *QueryCustomerAddressDetails20APIReq) GetEndpoint() string {

	return fmt.Sprintf("customers/%s/addresses/%s.json", req.AddressId, req.Id)

}

func (req *QueryCustomerAddressDetails20APIReq) GetMethod() string {
	return "GET"
}

// Verify the api request parameters
func (req *QueryCustomerAddressDetails20APIReq) Verify() error {

	if req.AddressId == "" {
		return errors.New("AddressId is required")
	}

	if req.Id == "" {
		return errors.New("Id is required")
	}

	return nil
}

func (req *QueryCustomerAddressDetails20APIReq) NewAPIResp() *QueryCustomerAddressDetails20APIResp {
	return &QueryCustomerAddressDetails20APIResp{}
}

type QueryCustomerAddressDetails20APIResp struct {
	client.BaseAPIResponse
	/*
	   Customer address information
	   Example: map[address1: address2: address_type:0 city: city_code: company: country: country_code: customer_id: def:false district: district_code: first_name: id: last_name: phone: province: province_code: province_code_v2: town: zip:]
	*/
	CustomerAddress QueryCustomerAddressDetails20APIRespCustomerAddress `json:"customer_address,omitempty" url:"-"`
}

type QueryCustomerAddressDetails20APIRespCustomerAddress struct {
	/*
	   City
	   Example:
	*/
	City string `json:"city,omitempty" url:"-"`

	/*
	   Zone / county code
	   Example:
	*/
	DistrictCode string `json:"district_code,omitempty" url:"-"`

	/*
	   Company
	   Example:
	*/
	Company string `json:"company,omitempty" url:"-"`

	/*
	   Detail address 1
	   Example:
	*/
	Address1 string `json:"address1,omitempty" url:"-"`

	/*
	   Country
	   Example:
	*/
	Country string `json:"country,omitempty" url:"-"`

	/*
	   District/County
	   Example:
	*/
	District string `json:"district,omitempty" url:"-"`

	/*
	   Default address
	   Example: false
	*/
	Def bool `json:"def,omitempty" url:"-"`

	/*
	   Customer id
	   Example:
	*/
	CustomerId string `json:"customer_id,omitempty" url:"-"`

	/*
	   Province code
	   Example:
	*/
	ProvinceCode string `json:"province_code,omitempty" url:"-"`

	/*
	   The province code（ISO-3166-2 format) of the address.
	   Example:
	*/
	ProvinceCodeV2 string `json:"province_code_v2,omitempty" url:"-"`

	/*
	   Detail address 2
	   Example:
	*/
	Address2 string `json:"address2,omitempty" url:"-"`

	/*
	   National code
	   Example:
	*/
	CountryCode string `json:"country_code,omitempty" url:"-"`

	/*
	   Urban code
	   Example:
	*/
	CityCode string `json:"city_code,omitempty" url:"-"`

	/*
	   Province
	   Example:
	*/
	Province string `json:"province,omitempty" url:"-"`

	/*
	   Postal code
	   Example:
	*/
	Zip string `json:"zip,omitempty" url:"-"`

	/*
	   Address type
	   Example: 0
	*/
	AddressType int `json:"address_type,omitempty" url:"-"`

	/*
	   Last name
	   Example:
	*/
	LastName string `json:"last_name,omitempty" url:"-"`

	/*
	   First name
	   Example:
	*/
	FirstName string `json:"first_name,omitempty" url:"-"`

	/*
	   Street town
	   Example:
	*/
	Town string `json:"town,omitempty" url:"-"`

	/*
	   Address ID
	   Example:
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   Phone number
	   Example:
	*/
	Phone string `json:"phone,omitempty" url:"-"`
}
