// Package store generated by SHOPLINE since v20251201
package store

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *StorePlanStatusChangedEvent) GetSupportedTopic() string {
	return "subscription/status_changed"
}

type StorePlanStatusChangedEvent struct {
	client.WebhookEvent
	/*
	   The type of the plan subscription.
	   - `trial`: Trial (current period). A trial-type plan.
	   - `paid`: Paid (current period). A paid-type plan that has entered its billing cycle.
	   - `preorder`: Paid (next period). A paid-type plan that has not yet entered its billing cycle.
	   Example: preorder
	*/
	SubType string `json:"sub_type,omitempty"`

	/*
	   The plan subscription ID, which can be used as a unique key.
	   Example: SUB6025977562148654208
	*/
	SubscriptionId string `json:"subscription_id,omitempty"`

	/*
	   The start time of the updated plan subscription, formatted as a 13-digit millisecond timestamp.
	   Example: 1.689504361e+12
	*/
	StartTime int64 `json:"start_time,omitempty"`

	/*
	   Store ID.
	   Example: 1.666942294702e+12
	*/
	StoreId int64 `json:"store_id,omitempty"`

	/*
	   The previous status of the plan subscription.
	   - `pending` Unpaid. The plan subscription payment is incomplete.
	   - `active` Active. The plan subscription is currently in effect.
	   - `expired` Expired. The plan subscription has reached its end time but is still within the grace period.
	   Example: active
	*/
	BeforeStatus string `json:"before_status,omitempty"`

	/*
	   The creation time of the updated plan subscription, formatted as a 13-digit millisecond timestamp.
	   Example: 1.689504361e+12
	*/
	CreateTime int64 `json:"create_time,omitempty"`

	/*
	   The end time of the updated plan subscription, formatted as a 13-digit millisecond timestamp.
	   Example: 1.692179184e+12
	*/
	EndTime int64 `json:"end_time,omitempty"`

	/*
	   The unique identifier for the merchant's registered account.
	   Example: 2.011061373e+09
	*/
	MerchantId int64 `json:"merchant_id,omitempty"`

	/*
	   The updated status of the plan subscription.
	   - `active`: Active. The plan subscription is currently in effect.
	   - `expired`: Expired. The plan subscription has reached its end time but is still within the grace period.
	   - `locked`: The plan subscription has reached its end time and exceeded the grace period.
	   - `cancelled`: Cancelled. The plan subscription has been cancelled.
	   Example: active
	*/
	Status string `json:"status,omitempty"`
}
