// Package order generated by SHOPLINE since v20251201
package order

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *DraftOrderDeletedEvent) GetSupportedTopic() string {
	return "draft_orders/delete"
}

type DraftOrderDeletedEvent struct {
	client.WebhookEvent
	/*
	   Draft order object
	   Example: map[id:]
	*/
	DraftOrder DraftOrderDeletedEventDraftOrder `json:"draft_order,omitempty"`

	/*
	   store ID
	   Example:
	*/
	StoreId string `json:"store_id,omitempty"`
}

type DraftOrderDeletedEventDraftOrder struct {
	/*
	   Draft order id
	   Example:
	*/
	Id string `json:"id,omitempty"`
}
