// Package order generated by SHOPLINE since v20251201
package order

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *FulfillmentOrderCancellationRequestAcceptedEvent) GetSupportedTopic() string {
	return "fulfillment_order/cancellation_request_accepted"
}

type FulfillmentOrderCancellationRequestAcceptedEvent struct {
	client.WebhookEvent
	/*
	   Information on the order
	   Example: map[id:"21057401932826316666967110_4005740193290131085320" status:"open"]
	*/
	FulfillmentOrder FulfillmentOrderCancellationRequestAcceptedEventFulfillmentOrder `json:"fulfillment_order,omitempty"`

	/*
	   Notes
	   Example: "cancel order"
	*/
	Message string `json:"message,omitempty"`
}

type FulfillmentOrderCancellationRequestAcceptedEventFulfillmentOrder struct {
	/*
	   Tracking order status
	   Example: "open"
	*/
	Status string `json:"status,omitempty"`

	/*
	   Identifies id
	   Example: "21057401932826316666967110_4005740193290131085320"
	*/
	Id string `json:"id,omitempty"`
}
