// Package order generated by SHOPLINE since v20251201
package order

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *OrdersDeletionEvent) GetSupportedTopic() string {
	return "orders/delete"
}

type OrdersDeletionEventFulfillment struct {
	/*
	   Creation time (see IOS8601 for the format)
	   Example: 2022-11-04T10:18:46+00:00
	*/
	CreatedAt string `json:"created_at,omitempty"`

	/*
	   Package number
	   Example: 22046737798141702810214336
	*/
	Id string `json:"id,omitempty"`

	/*
	   Product list
	   Example: []
	*/
	LineItems []OrdersDeletionEventLineItem `json:"line_items,omitempty"`

	/*
	   Invoice Short Number
	   Example: 1032-F2
	*/
	Name string `json:"name,omitempty"`

	/*
	   Order number
	   Example: 21056577640603870897253153
	*/
	OrderId string `json:"order_id,omitempty"`

	/*
	   Package tracking
	   Example: fulfilled
	*/
	ShipmentStatus string `json:"shipment_status,omitempty"`

	/*
	   Logistics company name
	   Example: SF Express International
	*/
	TrackingCompany string `json:"tracking_company,omitempty"`

	/*
	   Third party tracking number
	   Example: yun0001
	*/
	TrackingNumber string `json:"tracking_number,omitempty"`

	/*
	   Logistics delivery status, success-shipped; cancelled-cancelled;
	   Example: success
	*/
	Status string `json:"status,omitempty"`

	/*
	   Logistics company URL
	   Example: https://www.sf-international.com/
	*/
	TrackingUrl string `json:"tracking_url,omitempty"`

	/*
	   Update time (see IOS8601 for the format)
	   Example: 2022-11-04T10:18:46+00:00
	*/
	UpdatedAt string `json:"updated_at,omitempty"`
}

type OrdersDeletionEventBillingAddress struct {
	/*
	   Last name
	   Example: Washington
	*/
	LastName string `json:"last_name,omitempty"`

	/*
	   Name
	   Example: Tom Washington
	*/
	Name string `json:"name,omitempty"`

	/*
	   Phone
	   Example: 18723465843
	*/
	Phone string `json:"phone,omitempty"`

	/*
	   City
	   Example: New York
	*/
	City string `json:"city,omitempty"`

	/*
	   country / region
	   Example: USA
	*/
	Country string `json:"country,omitempty"`

	/*
	   Provincial/Secondary Address
	   Example: California
	*/
	Province string `json:"province,omitempty"`

	/*
	   Province/Secondary Address Code
	   Example: 4200006
	*/
	ProvinceCode string `json:"province_code,omitempty"`

	/*
	   Postal code
	   Example: 54213
	*/
	Zip string `json:"zip,omitempty"`

	/*
	   Detailed address 1
	   Example: Address 1
	*/
	Address1 string `json:"address1,omitempty"`

	/*
	   Detailed address 2, optional
	   Example: Address 2
	*/
	Address2 string `json:"address2,omitempty"`

	/*
	   Company Name
	   Example: New company name
	*/
	Company string `json:"company,omitempty"`

	/*
	   Country Code
	   Example: US
	*/
	CountryCode string `json:"country_code,omitempty"`

	/*
	   First name
	   Example: Tom
	*/
	FirstName string `json:"first_name,omitempty"`
}

type OrdersDeletionEvent struct {
	client.WebhookEvent
	/*
	   Total product weight ( g )
	   Example: 0
	*/
	TotalWeight float64 `json:"total_weight,omitempty"`

	/*
	   Client Information
	   Example: map[browser_ip:157.119.232.35 session_hash:c2c4a58186b9d96395d7e6b5c2969577 user_agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Sa uuid:432354345]
	*/
	ClientDetails ClientDetails `json:"client_details,omitempty"`

	/*
	   Discount sum and multi-currency information. There is no multi-currency, so the buyer and seller currencies and amounts are the same.
	   Example: map[presentment_money:map[amount:8.00 currency_code:USD] shop_money:map[amount:8.00 currency_code:USD]]
	*/
	CurrentTotalDiscountsSet CurrentTotalDiscountsSet `json:"current_total_discounts_set,omitempty"`

	/*
	   Payment status: unpaid - unpaid; authorized - authorized; pending - payment; partially_paid - partially paid; paid - paid; partially_refunded - partially refunded; refunded - refunded;
	   Example: unpaid
	*/
	FinancialStatus string `json:"financial_status,omitempty"`

	/*
	   Order product snapshot information
	   Example: []
	*/
	LineItems []OrdersDeletionEventLineItem `json:"line_items,omitempty"`

	/*
	   Order time
	   Example: 2021-08-16T08:27:57+00:00
	*/
	OrderAt string `json:"order_at,omitempty"`

	/*
	   Payment method list, the payment method list used for this order
	   Example: [Paypal]
	*/
	PaymentGatewayNames []string `json:"payment_gateway_names,omitempty"`

	/*
	   Refund list
	   Example: []
	*/
	Refunds []Refund `json:"refunds,omitempty"`

	/*
	   The current order member points deduction amount
	   Example: 8.00
	*/
	DeductMemberPointAmount string `json:"deduct_member_point_amount,omitempty"`

	/*
	   The order source channel. Currently, only the POS channel has this field. Other channels have this field value.
	   Example: POS
	*/
	OrderSource string `json:"order_source,omitempty"`

	/*
	   Buyer contact information
	   Example: 13100000000
	*/
	Phone string `json:"phone,omitempty"`

	/*
	   Shipping address
	   Example: map[address1:Address 1 address2:Address 2 city:New York company:New Company country:USA country_code:US delivery_store_code:1001 delivery_store_name:Store district:Panyu District district_code:5213300 first_name:Tom last_name:Washington latitude:23.35773 longitude:116.4151 name:Tom Washington phone:13100000000 province:California province_code:4200006 zip:521000]
	*/
	ShippingAddress OrdersDeletionEventShippingAddress `json:"shipping_address,omitempty"`

	/*
	   Logistics information
	   Example: []
	*/
	ShippingLines []ShippingLine `json:"shipping_lines,omitempty"`

	/*
	   Total outstanding amount, multi-currency information
	   Example: map[presentment_money:map[amount:8.88 currency_code:USD] shop_money:map[amount:8.88 currency_code:USD]]
	*/
	TotalOutstandingSet TotalOutstandingSet `json:"total_outstanding_set,omitempty"`

	/*
	   Is it an archived order? true = archived order, false = not archived order
	   Example: true
	*/
	HiddenOrder bool `json:"hidden_order,omitempty"`

	/*
	   Custom order number (subject to change)
	   Example: test001
	*/
	Name string `json:"name,omitempty"`

	/*
	   Merchant note log, date content
	   Example: []
	*/
	NoteAttributes []NoteAttribute `json:"note_attributes,omitempty"`

	/*
	   Payment slip information
	   Example: []
	*/
	PaymentDetails []PaymentDetail `json:"payment_details,omitempty"`

	/*
	   Order creator
	   Example: 4201057495
	*/
	ProcessedUserId string `json:"processed_user_id,omitempty"`

	/*
	   Store ID
	   Example: 1644828244663
	*/
	StoreId string `json:"store_id,omitempty"`

	/*
	   Shopping cart token
	   Example: c2c4a58186b9d96395d7e6b5c2969577
	*/
	CartToken string `json:"cart_token,omitempty"`

	/*
	   Total taxes, product tax + shipping tax

	   Example: 8.00
	*/
	CurrentTotalTax string `json:"current_total_tax,omitempty"`

	/*
	   Merchant remarks, multiple remarks separated by commas
	   Example: Remark
	*/
	Note string `json:"note,omitempty"`

	/*
	   Multi-currency information of total product price after discount
	   Example: map[presentment_money:map[amount:8.00 currency_code:USD] shop_money:map[amount:8.00 currency_code:USD]]
	*/
	SubtotalPriceSet SubtotalPriceSet `json:"subtotal_price_set,omitempty"`

	/*
	   Types of tax ID
	   Example: type
	*/
	TaxType string `json:"tax_type,omitempty"`

	/*
	   Total original price of goods, multi-currency information
	   Example: map[presentment_money:map[amount:8.00 currency_code:USD] shop_money:map[amount:8.00 currency_code:USD]]
	*/
	TotalLineItemsPriceSet TotalLineItemsPriceSet `json:"total_line_items_price_set,omitempty"`

	/*
	   Order shipping sum, multi-currency information
	   Example: map[presentment_money:map[amount:8.00 currency_code:USD] shop_money:map[amount:8.00 currency_code:USD]]
	*/
	TotalShippingPriceSet TotalShippingPriceSet `json:"total_shipping_price_set,omitempty"`

	/*
	   Multi-currency information of the current order total, the buyer's and seller‘s currency and the amount are the same
	   Example: map[presentment_money:map[amount:8.00 currency_code:USD] shop_money:map[amount:8.00 currency_code:USD]]
	*/
	CurrentTotalPriceSet CurrentTotalPriceSet `json:"current_total_price_set,omitempty"`

	/*
	   Location Information
	   Example: []
	*/
	Locations []Location `json:"locations,omitempty"`

	/*
	   Sum of original prices of goods, precision 2
	   Example: 8.00
	*/
	TotalLineItemsPrice string `json:"total_line_items_price,omitempty"`

	/*
	   Cancellation time
	   Example: 2012-05-01T14:22:25-04:00
	*/
	CancelledAt string `json:"cancelled_at,omitempty"`

	/*
	   Current total of goods, total price*quantity

	   Example: 8.00
	*/
	CurrentSubtotalPrice string `json:"current_subtotal_price,omitempty"`

	/*
	   Multi-currency information of the sum of taxes, the currency and amount of buyers and sellers are the same
	   Example: map[presentment_money:map[amount:8.00 currency_code:USD] shop_money:map[amount:8.00 currency_code:USD]]
	*/
	CurrentTotalTaxSet CurrentTotalTaxSet `json:"current_total_tax_set,omitempty"`

	/*
	   Buyer's Email
	   Example: test001@Gmail.com
	*/
	Email string `json:"email,omitempty"`

	/*
	   Sum of unpaid amount, precision 2
	   Example: 8.00
	*/
	TotalOutstanding string `json:"total_outstanding,omitempty"`

	/*
	   Total taxes and fees, multi-currency information
	   Example: map[presentment_money:map[amount:8.00 currency_code:USD] shop_money:map[amount:8.00 currency_code:USD]]
	*/
	TotalTaxSet TotalTaxSet `json:"total_tax_set,omitempty"`

	/*
	   Browser IP
	   Example: 157.119.232.35
	*/
	BrowserIp string `json:"browser_ip,omitempty"`

	/*
	   All discounts applied to this order
	   Example: []
	*/
	DiscountApplications []DiscountApplication `json:"discount_applications,omitempty"`

	/*
	   Shipping status, fulfilled-shipped; partial-partially shipped; null-unshipped; Note: the returned enum value is different from the query enumeration value of the input parameter
	   Example: fulfilled
	*/
	FulfillmentStatus string `json:"fulfillment_status,omitempty"`

	/*
	   Reason for cancellation
	   Example: I don't want to buy it.
	*/
	CancelReason string `json:"cancel_reason,omitempty"`

	/*
	   company information
	   Example: map[id:1026538935748524 location_id:326538935748524 tax_registration_id:503002]
	*/
	Company Company `json:"company,omitempty"`

	/*
	   Buyer's country Language code + country abbreviation
	   Example: CN
	*/
	CustomerLocale string `json:"customer_locale,omitempty"`

	/*
	   System order number
	   Example: 21056577640603870897253153
	*/
	Id string `json:"id,omitempty"`

	/*
	   Tip, precision 2
	   Example: 8.00
	*/
	TotalTipReceived string `json:"total_tip_received,omitempty"`

	/*
	   Buyer ID
	   Example: 4201057495
	*/
	UserId string `json:"user_id,omitempty"`

	/*
	   Buyer's Notes
	   Example: Remark
	*/
	BuyerNote string `json:"buyer_note,omitempty"`

	/*
	   Settlement currency
	   Example: USD
	*/
	Currency string `json:"currency,omitempty"`

	/*
	   Total discount, marketing discount + artificial discount
	   Example: 8.00
	*/
	TotalDiscounts string `json:"total_discounts,omitempty"`

	/*
	   Adjust the amount, the balance amount caused by rounding in the POS scenario
	   Example: 8.00
	*/
	AdjustPrice string `json:"adjust_price,omitempty"`

	/*
	   Adjustment amount in store currency and transaction currency
	   Example: map[presentment_money:map[amount:8.00 currency_code:USD] shop_money:map[amount:8.00 currency_code:USD]]
	*/
	AdjustPriceSet AdjustPriceSet `json:"adjust_price_set,omitempty"`

	/*
	   The current order total, value logic: total amount of goods - total discount + shipping fee + tax

	   Example: 8.00
	*/
	CurrentTotalPrice string `json:"current_total_price,omitempty"`

	/*
	   Order status page URL
	   Example: https://shoptest.myshopline.com/trade/thank_you?mainOrderMark=xxx&mainOrderSeq=200565776406008509
	*/
	OrderStatusUrl string `json:"order_status_url,omitempty"`

	/*
	   Buy side currency
	   Example: USD
	*/
	PresentmentCurrency string `json:"presentment_currency,omitempty"`

	/*
	   Sum of taxes, precision 2, commodity tax + shipping tax
	   Example: 8.00
	*/
	TotalTax string `json:"total_tax,omitempty"`

	/*
	   Tipping, multi-currency information
	   Example: map[presentment_money:map[amount:8.88 currency_code:USD] shop_money:map[amount:8.88 currency_code:USD]]
	*/
	TotalTipReceivedSet TotalTipReceivedSet `json:"total_tip_received_set,omitempty"`

	/*
	   Order creation time
	   Example: 2021-08-16T08:27:57+00:00
	*/
	CreatedAt string `json:"created_at,omitempty"`

	/*
	   Order Tags
	   Example: watch
	*/
	Tags string `json:"tags,omitempty"`

	/*
	   Order update time, (see IOS8601 for the format)
	   Example: 2021-08-16T08:27:57+00:00
	*/
	UpdatedAt string `json:"updated_at,omitempty"`

	/*
	   Package information
	   Example: []
	*/
	Fulfillments []OrdersDeletionEventFulfillment `json:"fulfillments,omitempty"`

	/*
	   POS transaction location
	   Example: 5227248679317408779
	*/
	PosLocationId string `json:"pos_location_id,omitempty"`

	/*
	   Total product price after discount, total product price - marketing discount - artificial discount
	   Example: 8.00
	*/
	SubtotalPrice string `json:"subtotal_price,omitempty"`

	/*
	   Multi-currency information of discount total
	   Example: map[presentment_money:map[amount:8.00 currency_code:USD] shop_money:map[amount:8.00 currency_code:USD]]
	*/
	TotalDiscountsSet TotalDiscountsSet `json:"total_discounts_set,omitempty"`

	/*
	   Sum of discounts, precision 2, marketing offers + artificial discounts
	   Example: 8.00
	*/
	CurrentTotalDiscounts string `json:"current_total_discounts,omitempty"`

	/*
	   TIN
	   Example: 11111
	*/
	TaxNumber string `json:"tax_number,omitempty"`

	/*
	   The abandoned order id associated with the current order
	   Example: 2404785166526352972864
	*/
	CheckoutId string `json:"checkout_id,omitempty"`

	/*
	   Order time, format: 2023-04-12T22:59:52+08:00 2023-04-12T22:59:52+08:00
	   Example: 2023-04-12T22:59:52+08:00
	*/
	ProcessedAt string `json:"processed_at,omitempty"`

	/*
	   Order status, open - in process, cancelled - canceled
	   Example: open
	*/
	Status string `json:"status,omitempty"`

	/*
	   billing address
	   Example: map[address1:Address 1 address2:Address 2 city:New York company:New company name country:USA country_code:US first_name:Tom last_name:Washington name:Tom Washington phone:18723465843 province:California province_code:4200006 zip:54213]
	*/
	BillingAddress OrdersDeletionEventBillingAddress `json:"billing_address,omitempty"`

	/*
	   Settlement page token
	   Example: c2c4a58186b9d96395d7e6b5c2969577
	*/
	CheckoutToken string `json:"checkout_token,omitempty"`

	/*
	   Current total tariffs on goods
	   Example: map[presentment_money:map[amount:8.88 currency_code:USD] shop_money:map[amount:8.88 currency_code:USD]]
	*/
	CurrentTotalDutiesSet CurrentTotalDutiesSet `json:"current_total_duties_set,omitempty"`

	/*
	   The current order member points deduction amount, multi-currency information
	   Example: map[presentment_money:map[amount:8.88 currency_code:USD] shop_money:map[amount:8.88 currency_code:USD]]
	*/
	DeductMemberPointAmountSet DeductMemberPointAmountSet `json:"deduct_member_point_amount_set,omitempty"`

	/*
	   Promo code information
	   Example: []
	*/
	DiscountCodes []DiscountCode `json:"discount_codes,omitempty"`

	/*
	   Does the total include tax?
	   Example: true
	*/
	TaxesIncluded bool `json:"taxes_included,omitempty"`

	/*
	   Multi-currency information of the current commodity sum, the buyer's and seller's currency and the amount are the same
	   Example: map[presentment_money:map[amount:8.00 currency_code:USD] shop_money:map[amount:8.00 currency_code:USD]]
	*/
	CurrentSubtotalPriceSet CurrentSubtotalPriceSet `json:"current_subtotal_price_set,omitempty"`

	/*
	   Buyer information
	   Example: map[addresses:map[address1:Address 1 address2:Address 2 city:New York country:USA country_code:US first_name:Tom last_name:Washington name:Tom Washington phone:13100000000 province:California province_code:4200006 zip:98734] area_code:+86 created_at:2022-11-04T10:18:46+00:00 currency:USD email:test1001@Gmail.com first_name:Tom id:4201057495 last_name:Washington phone:13100000000]
	*/
	Customer Customer `json:"customer,omitempty"`

	/*
	   Tax information
	   Example: []
	*/
	TaxLines []TaxLine `json:"tax_lines,omitempty"`
}

type OrdersDeletionEventLineItem struct {
	/*
	   Quantity of items in the order
	   Example: 1
	*/
	Quantity int `json:"quantity,omitempty"`

	/*
	   Tariff Information
	   Example: []
	*/
	Duties []Duty `json:"duties,omitempty"`

	/*
	   Location ID
	   Example: 5327026538935748524
	*/
	LocationId string `json:"location_id,omitempty"`

	/*
	   sku title
	   Example: Product title
	*/
	Name string `json:"name,omitempty"`

	/*
	   SPU serial number
	   Example: 16056761559984840457934011
	*/
	ProductId string `json:"product_id,omitempty"`

	/*
	   Shipping or not
	   Example: true
	*/
	RequiresShipping bool `json:"requires_shipping,omitempty"`

	/*
	   Tax information
	   Example: []
	*/
	TaxLines []OrdersDeletionEventTaxLine `json:"tax_lines,omitempty"`

	/*
	   Product title
	   Example: Nice skirt
	*/
	Title string `json:"title,omitempty"`

	/*
	   Product SKU serial number
	   Example: 18056761559987524812644011
	*/
	VariantId string `json:"variant_id,omitempty"`

	/*
	   Commodity price, precision 2
	   Example: 8.00
	*/
	Price string `json:"price,omitempty"`

	/*
	   The name of the logistics provider. If a product has multiple different delivery service providers, separate them with commas.
	   Example: SF Express International
	*/
	FulfillmentService string `json:"fulfillment_service,omitempty"`

	/*
	   The shipping status of the product, shipping status, fulfilled-shipped; partial-partially shipped; null-unshipped;
	   Example: yun0001
	*/
	FulfillmentStatus string `json:"fulfillment_status,omitempty"`

	/*
	   product picture
	   Example: https://d2n979dmt31clo.cloudfront.net/image/store/4211449909/1667384795847/63928f08a7174ab2958c6a969
	*/
	ImageUrl string `json:"image_url,omitempty"`

	/*
	   Product customization information
	   Example: []
	*/
	Properties []Property `json:"properties,omitempty"`

	/*
	   Commodity attribute value, multiple divided by " / ", such as: "155 / red / large"
	   Example: big
	*/
	VariantTitle string `json:"variant_title,omitempty"`

	/*
	   Supplier
	   Example: Supplier
	*/
	Vendor string `json:"vendor,omitempty"`

	/*
	   Discount details amount in multiple currencies
	   Example: []
	*/
	DiscountAllocations []DiscountAllocation `json:"discount_allocations,omitempty"`

	/*
	   Product price, amount information in multiple currencies
	   Example: map[presentment_money:map[amount:8.00 currency_code:USD] shop_money:map[amount:8.00 currency_code:USD]]
	*/
	PriceSet PriceSet `json:"price_set,omitempty"`

	/*
	   Product Code
	   Example: 18056761559987524812644011
	*/
	Sku string `json:"sku,omitempty"`

	/*
	   Product tags (separate multiple tags with commas)
	   Example: watch
	*/
	Tags string `json:"tags,omitempty"`

	/*
	   Tax or not？
	   Example: true
	*/
	Taxable bool `json:"taxable,omitempty"`

	/*
	   Product attributes: Name - Attribute value Multiple attributes are separated by commas, such as: Color - Red, Size - X
	   Example: red
	*/
	Attribute string `json:"attribute,omitempty"`

	/*
	   Available quantity
	   Example: 1
	*/
	FulfillableQuantity int `json:"fulfillable_quantity,omitempty"`

	/*
	   Is it a gift card product?
	   Example: false
	*/
	GiftCard bool `json:"gift_card,omitempty"`

	/*
	   Weight ( grams )
	   Example: 100
	*/
	Grams float64 `json:"grams,omitempty"`

	/*
	   The ID of the product snapshot table, generated by the system, uniquely confirms a product with the order number
	   Example: 413
	*/
	Id string `json:"id,omitempty"`
}

type OrdersDeletionEventTaxLine struct {
	/*
	   Tax type, used to distinguish between product tax and shipping tax. The enumeration values ​​are as follows: product_tax: product tax shipping_tax: shipping tax
	   Example: shipping_tax
	*/
	Type string `json:"type,omitempty"`

	/*
	   Price
	   Example: 8.00
	*/
	Price string `json:"price,omitempty"`

	/*
	   Multi-currency information of tax
	   Example: map[presentment_money:map[amount:8.00 currency_code:USD] shop_money:map[amount:8.00 currency_code:USD]]
	*/
	PriceSet PriceSet `json:"price_set,omitempty"`

	/*
	   Tax rate
	   Example: 1
	*/
	Rate float64 `json:"rate,omitempty"`

	/*
	   Tax name
	   Example: Taxes
	*/
	Title string `json:"title,omitempty"`
}

type OrdersDeletionEventShippingAddress struct {
	/*
	   Detailed address 1
	   Example: Address 1
	*/
	Address1 string `json:"address1,omitempty"`

	/*
	   Detailed address 2, optional
	   Example: Address 2
	*/
	Address2 string `json:"address2,omitempty"`

	/*
	   Phone
	   Example: 13100000000
	*/
	Phone string `json:"phone,omitempty"`

	/*
	   Province
	   Example: California
	*/
	Province string `json:"province,omitempty"`

	/*
	   City
	   Example: New York
	*/
	City string `json:"city,omitempty"`

	/*
	   Country
	   Example: USA
	*/
	Country string `json:"country,omitempty"`

	/*
	   Country code
	   Example: US
	*/
	CountryCode string `json:"country_code,omitempty"`

	/*
	   District code
	   Example: 5213300
	*/
	DistrictCode string `json:"district_code,omitempty"`

	/*
	   Company Name
	   Example: New Company
	*/
	Company string `json:"company,omitempty"`

	/*
	   Store ID
	   Example: 1001
	*/
	DeliveryStoreCode string `json:"delivery_store_code,omitempty"`

	/*
	   Store name
	   Example: Store
	*/
	DeliveryStoreName string `json:"delivery_store_name,omitempty"`

	/*
	   District
	   Example: Panyu District
	*/
	District string `json:"district,omitempty"`

	/*
	   First name
	   Example: Tom
	*/
	FirstName string `json:"first_name,omitempty"`

	/*
	   Province code
	   Example: 4200006
	*/
	ProvinceCode string `json:"province_code,omitempty"`

	/*
	   Last name
	   Example: Washington
	*/
	LastName string `json:"last_name,omitempty"`

	/*
	   Address Latitude
	   Example: 23.35773
	*/
	Latitude string `json:"latitude,omitempty"`

	/*
	   Address Longitude
	   Example: 116.4151
	*/
	Longitude string `json:"longitude,omitempty"`

	/*
	   Full name
	   Example: Tom Washington
	*/
	Name string `json:"name,omitempty"`

	/*
	   Postal code
	   Example: 521000
	*/
	Zip string `json:"zip,omitempty"`
}
