// Package saleschannels generated by SHOPLINE since v20260301
package saleschannels

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *AddProductToSalesChannelsEvent) GetSupportedTopic() string {
	return "product_listings/add"
}

type AddProductToSalesChannelsEvent struct {
	client.WebhookEvent
	/*
	   Product information
	   Example: map[body_html:This is a description created_at:2023-03-02T18:18:42.883+0800 handle:proudct-handle id:16058287356753559620272670 images:[] options:[] product_behavior:RISK,HIDDEN product_category:Electronic product_type:Electronic published_at:2023-03-02T18:18:42.883+0800 published_scope:web spu:S000000001 status:active subtitle:This is a subtitle tags:tag1,tag2 template_path:templates/products/detail.json title:This is a title updated_at:2023-03-02T18:18:42.883+0800 variants:[] vendor:Shopline]
	*/
	ProductListing ProductListing `json:"product_listing,omitempty" url:"-"`
}

type ProductListing struct {
	/*
	   Launch range , " web " means online stores
	   Example: web
	*/
	PublishedScope string `json:"published_scope,omitempty" url:"-"`

	/*
	   Product create time
	   Example: 2023-03-02T18:18:42.883+0800
	*/
	CreatedAt string `json:"created_at,omitempty" url:"-"`

	/*
	   Global unique Product handle
	   Example: proudct-handle
	*/
	Handle string `json:"handle,omitempty" url:"-"`

	/*
	   Product ID
	   Example: 16058287356753559620272670
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   Option list
	   Example: []
	*/
	Options []Option `json:"options,omitempty" url:"-"`

	/*
	   Product behavior
	   Example: RISK,HIDDEN
	*/
	ProductBehavior string `json:"product_behavior,omitempty" url:"-"`

	/*
	   Tag , multiple separated by ','
	   Example: tag1,tag2
	*/
	Tags string `json:"tags,omitempty" url:"-"`

	/*
	   Product update time
	   Example: 2023-03-02T18:18:42.883+0800
	*/
	UpdatedAt string `json:"updated_at,omitempty" url:"-"`

	/*
	   Product description
	   Example: This is a description
	*/
	BodyHtml string `json:"body_html,omitempty" url:"-"`

	/*
	   Product title
	   Example: This is a title
	*/
	Title string `json:"title,omitempty" url:"-"`

	/*
	   Time to post to online stores
	   Example: 2023-03-02T18:18:42.883+0800
	*/
	PublishedAt string `json:"published_at,omitempty" url:"-"`

	/*
	   Size s pu
	   Example: S000000001
	*/
	Spu string `json:"spu,omitempty" url:"-"`

	/*
	   Product status : active- on shelf , draft- off shelf , archived- filing
	   Example: active
	*/
	Status string `json:"status,omitempty" url:"-"`

	/*
	   Product main image listing
	   Example: []
	*/
	Images []Image `json:"images,omitempty" url:"-"`

	/*
	   Product polymer type
	   Example: Electronic
	*/
	ProductCategory string `json:"product_category,omitempty" url:"-"`

	/*
	   Product type
	   Example: Electronic
	*/
	ProductType string `json:"product_type,omitempty" url:"-"`

	/*
	   Theme template
	   Example: templates/products/detail.json
	*/
	TemplatePath string `json:"template_path,omitempty" url:"-"`

	/*
	   Product summary
	   Example: This is a subtitle
	*/
	Subtitle string `json:"subtitle,omitempty" url:"-"`

	/*
	   Style list
	   Example: []
	*/
	Variants []Variant `json:"variants,omitempty" url:"-"`

	/*
	   Product manufacturer
	   Example: Shopline
	*/
	Vendor string `json:"vendor,omitempty" url:"-"`
}

type Option struct {
	/*
	   Duiying id corresponding
	   Example: 16058287356753569620272670
	*/
	ProductId string `json:"product_id,omitempty" url:"-"`

	/*
	   List of options value
	   Example: [["Red", "Green", "White"]]
	*/
	Values []string `json:"values,omitempty" url:"-"`

	/*
	   Option value chart
	   Example: map[]
	*/
	ValuesImages map[string]string `json:"values_images,omitempty" url:"-"`

	/*
	   Option id
	   Example: 16158288104774469113452670
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   Option name
	   Example: Color
	*/
	Name string `json:"name,omitempty" url:"-"`

	/*
	   List of option values.
	   Example: []
	*/
	OptionValues []OptionValue `json:"option_values,omitempty" url:"-"`
}

type OptionValue struct {
	/*
	   The ID of option value.
	   Example: 16247051995358890915900034
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   The option value.
	   Example: Red
	*/
	Value string `json:"value,omitempty" url:"-"`
}

type Image struct {
	/*
	   Picture alt
	   Example: This is a image alt
	*/
	Alt string `json:"alt,omitempty" url:"-"`

	/*
	   Image URL
	   Example: https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png
	*/
	Src string `json:"src,omitempty" url:"-"`
}

type Variant struct {
	/*
	   Original price
	   Example: 1
	*/
	CompareAtPrice string `json:"compare_at_price,omitempty" url:"-"`

	/*
	   Track inventory or not
	   Example: true
	*/
	InventoryTracker bool `json:"inventory_tracker,omitempty" url:"-"`

	/*
	   Value for the first option that this style corresponds to
	   Example: Red
	*/
	Option1 string `json:"option1,omitempty" url:"-"`

	/*
	   Value for the third option that this style corresponds to
	   Example:
	*/
	Option3 string `json:"option3,omitempty" url:"-"`

	/*
	   Selling price
	   Example: 1
	*/
	Price string `json:"price,omitempty" url:"-"`

	/*
	   Duiying id corresponding
	   Example: 16058287356753569620272670
	*/
	ProductId string `json:"product_id,omitempty" url:"-"`

	/*
	   Sku
	   Example: B0000001
	*/
	Sku string `json:"sku,omitempty" url:"-"`

	/*
	   Weight
	   Example: 1
	*/
	Weight string `json:"weight,omitempty" url:"-"`

	/*
	   Bar code
	   Example: B0000000001
	*/
	Barcode string `json:"barcode,omitempty" url:"-"`

	/*
	   Style id
	   Example: 18058288104774469113432670
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   Allows oversold , continue or not : allowed , deny : not allowed
	   Example: continue
	*/
	InventoryPolicy string `json:"inventory_policy,omitempty" url:"-"`

	/*
	   Style chart
	   Example: map[alt:This is a image alt src:https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png]
	*/
	Image Image `json:"image,omitempty" url:"-"`

	/*
	   Suoyou summary of all locations
	   Example: 1
	*/
	InventoryQuantity int `json:"inventory_quantity,omitempty" url:"-"`

	/*
	   Value for the fifth option that this style corresponds to
	   Example:
	*/
	Option5 string `json:"option5,omitempty" url:"-"`

	/*
	   Tax or not？
	   Example: false
	*/
	Taxable bool `json:"taxable,omitempty" url:"-"`

	/*
	   Style title
	   Example: Red/L
	*/
	Title string `json:"title,omitempty" url:"-"`

	/*
	   Value for the second option that this style corresponds to
	   Example: L
	*/
	Option2 string `json:"option2,omitempty" url:"-"`

	/*
	   Value of the fourth option that this style corresponds to
	   Example:
	*/
	Option4 string `json:"option4,omitempty" url:"-"`

	/*
	   Shipping or not
	   Example: false
	*/
	RequiredShipping bool `json:"required_shipping,omitempty" url:"-"`

	/*
	   Weight unit , g : g , kg : kg , lb : lb , oz : oz
	   Example: g
	*/
	WeightUnit string `json:"weight_unit,omitempty" url:"-"`
}
