// Package product generated by SHOPLINE since v20251201
package product

import (
	"errors"
	"fmt"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type CreateAProductImageAPIReq struct {
	client.BaseAPIRequest
	/*
	   The unique identifier for a product.<br/>
	   Maximum length：64
	   Example: 16057039432335099907370282
	*/
	ProductId string `url:"-" json:"-"` // Required
	/*
	   Image information.
	   Example: map[alt:This is an image alt. sku_id:18057548296490304172320473 src:https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png]
	*/
	Image CreateAProductImageAPIReqImage `json:"image,omitempty" url:"-"`
}

type CreateAProductImageAPIReqImage struct {
	/*
	   The link to a product image, represented as a URL.<br/>
	   Maximum length: 255
	   Example: https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png
	*/
	Src string `json:"src,omitempty" url:"-"`

	/*
	   The alternative textual description of a product image, usually a word or phrase with the characteristics or content of the image.<br/>
	   Maximum length: 255
	   Example: This is an image alt.
	*/
	Alt string `json:"alt,omitempty" url:"-"`

	/*
	   The unique identifier for a variant.<br/>
	   Maximum length：64
	   Example: 18057548296490304172320473
	*/
	SkuId string `json:"sku_id,omitempty" url:"-"`
}

func (req *CreateAProductImageAPIReq) GetEndpoint() string {

	return fmt.Sprintf("products/%s/images.json", req.ProductId)

}

func (req *CreateAProductImageAPIReq) GetMethod() string {
	return "POST"
}

func (req *CreateAProductImageAPIReq) GetData() interface{} {
	return req
}

// Verify the api request parameters
func (req *CreateAProductImageAPIReq) Verify() error {

	if req.ProductId == "" {
		return errors.New("ProductId is required")
	}

	return nil
}

func (req *CreateAProductImageAPIReq) NewAPIResp() *CreateAProductImageAPIResp {
	return &CreateAProductImageAPIResp{}
}

type CreateAProductImageAPIResp struct {
	client.BaseAPIResponse
	/*
	   Image information.
	   Example: map[alt:This is an image alt. create_time:2023-01-31T13:22:37+08:00 height:1280 id:5785060242207917075 position:1 product_id:16059626017307301045451133 sku_id:18057850264851626133510282 src:https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png update_time:2023-01-31T13:22:37+08:00 width:1280]
	*/
	Image CreateAProductImageAPIRespImage `json:"image,omitempty" url:"-"`
}

type CreateAProductImageAPIRespImage struct {
	/*
	   The date and time when the product image was created. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).
	   Example: 2023-01-31T13:22:37+08:00
	*/
	CreateTime string `json:"create_time,omitempty" url:"-"`

	/*
	   Image height, in pixels.
	   Example: 1280
	*/
	Height int `json:"height,omitempty" url:"-"`

	/*
	   The unique identifier for a product image.
	   Example: 5785060242207917075
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   The unique identifier for a variant.
	   Example: 18057850264851626133510282
	*/
	SkuId string `json:"sku_id,omitempty" url:"-"`

	/*
	   The link to a product image, represented as a URL.
	   Example: https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png
	*/
	Src string `json:"src,omitempty" url:"-"`

	/*
	   The date and time when the product image was last updated. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).
	   Example: 2023-01-31T13:22:37+08:00
	*/
	UpdateTime string `json:"update_time,omitempty" url:"-"`

	/*
	   Image width, in pixels.
	   Example: 1280
	*/
	Width string `json:"width,omitempty" url:"-"`

	/*
	   The alternative textual description of a product image, usually a word or phrase with the characteristics or content of the image.
	   Example: This is an image alt.
	*/
	Alt string `json:"alt,omitempty" url:"-"`

	/*
	   Image position.
	   Example: 1
	*/
	Position int `json:"position,omitempty" url:"-"`

	/*
	   The unique identifier for a product.
	   Example: 16059626017307301045451133
	*/
	ProductId string `json:"product_id,omitempty" url:"-"`
}
