// Package product generated by SHOPLINE since v20251201
package product

import (
	"errors"
	"fmt"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type DeleteASalesPlanGroupAPIReq struct {
	client.BaseAPIRequest
	/*
	   The unique identifier for the sales plan group.
	   Example: 14056200245844372441100009
	*/
	SellingPlanGroupId string `url:"-" json:"-"` // Required
}

func (req *DeleteASalesPlanGroupAPIReq) GetEndpoint() string {

	return fmt.Sprintf("selling_plan_group/%s.json", req.SellingPlanGroupId)

}

func (req *DeleteASalesPlanGroupAPIReq) GetMethod() string {
	return "DELETE"
}

// Verify the api request parameters
func (req *DeleteASalesPlanGroupAPIReq) Verify() error {

	if req.SellingPlanGroupId == "" {
		return errors.New("SellingPlanGroupId is required")
	}

	return nil
}

func (req *DeleteASalesPlanGroupAPIReq) GetRequestOptions() *client.RequestOptions {
	opts := &client.RequestOptions{
		NotDecodeBody: true,
	}
	return opts
}

func (req *DeleteASalesPlanGroupAPIReq) NewAPIResp() *DeleteASalesPlanGroupAPIResp {
	return &DeleteASalesPlanGroupAPIResp{}
}

type DeleteASalesPlanGroupAPIResp struct {
	client.BaseAPIResponse
}
