// Package product generated by SHOPLINE since v20251201
package product

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

type GetProductsAPIReq struct {
	client.BaseAPIRequest
	/*
	   The unique identifier for the product collection.<br/>
	   Maximum length：64
	   Example: 12248721639068681442230282
	*/
	CollectionId string `url:"collection_id,omitempty" json:"-"`
	/*
	   Specify the latest creation time for the product to be queried. Products created on or before this time will be returned. Format: [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601).
	   Example: 2021-09-02T14:11:54+00:00
	*/
	CreatedAtMax string `url:"created_at_max,omitempty" json:"-"`
	/*
	   Specify the earliest creation time for the product to be queried. Products created on or after this time will be returned. Format: [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601).
	   Example: 2021-09-03T14:11:54+00:00
	*/
	CreatedAtMin string `url:"created_at_min,omitempty" json:"-"`
	/*
	   Specify the fields to be returned, with multiple fields separated by commas. For available fields, refer to the top-level child parameters under the `product` object in the response.
	   Example: title,id,created_at
	*/
	Fields string `url:"fields,omitempty" json:"-"`
	/*
	   The semantically unique identifier for the product,
	   which is generated based on `title` by default.<br/>
	   Maximum length: 255
	   Example: product-handle
	*/
	Handle string `url:"handle,omitempty" json:"-"`
	/*
	   The unique identifiers for products to query, with multiple IDs separated by commas.
	   Example: 16057850264845250791280282,16057850264845250333280282
	*/
	Ids string `url:"ids,omitempty" json:"-"`
	/*
	   The quantity limit of products to be queried.<br/>Value range: 1-250<br/>Default Value: `50`
	   Example: 0
	*/
	Limit int `url:"limit,omitempty" json:"-"`
	/*
	   The sorting rule based on product creation time. Valid values are:
	   - `created_at_asc`: Sort products from the earliest to the latest creation time.
	   - `created_at_desc`: Sort products from the earliest to the latest creation time.
	   Example: created_at_desc
	*/
	OrderBy string `url:"order_by,omitempty" json:"-"`
	/*
	   The unique identifier for pagination queries, used to locate a specific page.

	   This parameter value is obtained from the `link` value in the response header of this API after you have queried the pagination information.

	   For example, if the `link` value you obtained is `<https://{handle}.myshopline.com/admin/openapi/{version}/products/products.json?limit=1&page_info=eyJzaW5jZUlkIjoiMTYwNTc1OTAxNTM4OTA4Mjk1MjExMTI3ODgiLCJkaXJlY3Rpb24iOiJuZXh0IiwibGltaXQiOjF9>; rel="next"` , the value of `page_info` is `eyJzaW5jZUlkIjoiMTYwNTc1OTAxNTM4OTA4Mjk1MjExMTI3ODgiLCJkaXJlY3Rpb24iOiJuZXh0IiwibGltaXQiOjF9` .
	   For more information on how to use pagination, refer to [Paging Mechanism](/docs/apps/api-instructions-for-use/paging-mechanism).
	   Example:
	*/
	PageInfo string `url:"page_info,omitempty" json:"-"`
	/*
	   The product category customized by the merchant.<br/>
	   Maximum length: 255
	   Example: Electronics
	*/
	ProductCategory string `url:"product_category,omitempty" json:"-"`
	/*
	   The ID of a specific product. Start querying products from this specified ID.
	   Example: 16057850264845250791280282
	*/
	SinceId string `url:"since_id,omitempty" json:"-"`
	/*
	   The status of the product. Valid values are:
	   - `active`: products on shelves
	   - `draft`: products off shelves
	   - `archived`: products archiving
	   Example:
	*/
	Status string `url:"status,omitempty" json:"-"`
	/*
	   The title of the product.<br/>
	   Maximum length: 255
	   Example: This is a title.
	*/
	Title string `url:"title,omitempty" json:"-"`
	/*
	   Specify the latest update time for the product to be queried. Products updated on or before this time will be returned. Format: [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601).
	   Example: 2021-09-02T14:11:54+00:00
	*/
	UpdatedAtMax string `url:"updated_at_max,omitempty" json:"-"`
	/*
	   Specify the earliest update time for the product to be queried. Products updated on or after this time will be returned. Format: [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601).
	   Example: 2021-09-03T14:11:54+00:00
	*/
	UpdatedAtMin string `url:"updated_at_min,omitempty" json:"-"`
	/*
	   The brand or vendor of the product.<br/>
	   Maximum length: 255
	   Example: SHOPLINE
	*/
	Vendor string `url:"vendor,omitempty" json:"-"`
}

func (req *GetProductsAPIReq) GetEndpoint() string {

	return "products/products.json"

}

func (req *GetProductsAPIReq) GetMethod() string {
	return "GET"
}

func (req *GetProductsAPIReq) GetQuery() interface{} {
	return req
}

// Verify the api request parameters
func (req *GetProductsAPIReq) Verify() error {

	return nil
}

func (req *GetProductsAPIReq) NewAPIResp() *GetProductsAPIResp {
	return &GetProductsAPIResp{}
}

type GetProductsAPIResp struct {
	client.BaseAPIResponse
	/*
	   A list of products.
	   Example: [map[body_html: created_at:2025-03-06T02:20:26+08:00 handle:product-handle id:16057850264845250791280282 image:map[alt:This is an image alt. id:5785060242207917075 src:https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png] images:[map[alt:This is an image alt. id:5785060242207917075 src:https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png]] options:[map[id:16158068291703878544960282 name:Color option_values:[map[id:16050375155238626683133099 value:red]] product_id:16057850264845250791280282 values:[["red", "green", "white"]] values_images:map[]]] path:/products/clothes product_behavior:RISK, HIDDEN product_category:Electronics product_type: published_at:2025-03-06T02:20:26+08:00 published_scope: spu:S00000001 status: subtitle:This is a subtitle tags:tag1, tag2 template_path:templates/product.product_template_name.json title:This is a Product title updated_at:2025-03-06T02:20:26+08:00 variants:[map[barcode:T0000001 compare_at_price:129.99 id:18057850264851626133510282 image:map[alt:This is an image alt. id:5785060242207917075 src:https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png] inventory_item_id:5785060242375689228 inventory_policy: inventory_quantity:99 inventory_tracker:false option1:red option2:xl option3:cotton option4:short option5:casual position:1 price:90.22 product_id:16057850264845250791280282 required_shipping:false sku:S000000001 taxable:false title:red · xl weight:0.23 weight_unit:]] vendor:SHOPLINE]]
	*/
	Products []Product `json:"products,omitempty" url:"-"`
}

type Variant struct {
	/*
	   The ordering position of the variant within the variant list.
	   Example: 1
	*/
	Position int `json:"position,omitempty" url:"-"`

	/*
	   The image of the variant.
	   Example: map[alt:This is an image alt. id:5785060242207917075 src:https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png]
	*/
	Image Image `json:"image,omitempty" url:"-"`

	/*
	   Information of the fifth option of the variant.
	   Example: casual
	*/
	Option5 string `json:"option5,omitempty" url:"-"`

	/*
	   The unique identifier for the variant.
	   Example: 18057850264851626133510282
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   Indicates whether the inventory tracking is enabled.
	   - ` true`: Inventory tracking is enabled.
	   - ` false`: Inventory tracking is not enabled.
	   Example: false
	*/
	InventoryTracker bool `json:"inventory_tracker,omitempty" url:"-"`

	/*
	   Information of the third option of the variant.
	   Example: cotton
	*/
	Option3 string `json:"option3,omitempty" url:"-"`

	/*
	   The title of the variant, assembled from the option value of the variant.
	   Example: red · xl
	*/
	Title string `json:"title,omitempty" url:"-"`

	/*
	   The product SKU. It is distinct from `variant.id` returned by SHOPLINE.
	   Example: S000000001
	*/
	Sku string `json:"sku,omitempty" url:"-"`

	/*
	   The unique identifier for the product corresponding to the variant.
	   Example: 16057850264845250791280282
	*/
	ProductId string `json:"product_id,omitempty" url:"-"`

	/*
	   Indicates whether the variant is required to be shipped.
	   - `true`: Shipping is required.
	   - `false`: Shipping is not required.
	   Example: false
	*/
	RequiredShipping bool `json:"required_shipping,omitempty" url:"-"`

	/*
	   The total inventory quantity at all storage locations.
	   Example: 99
	*/
	InventoryQuantity int `json:"inventory_quantity,omitempty" url:"-"`

	/*
	   Information of the first option of the variant.
	   Example: red
	*/
	Option1 string `json:"option1,omitempty" url:"-"`

	/*
	   Indicates whether the variant is subject to tax.
	   - `true`: Tax is required.
	   - `false`: Tax is not required.
	   Example: false
	*/
	Taxable bool `json:"taxable,omitempty" url:"-"`

	/*
	   Information of the fourth option of the variant.
	   Example: short
	*/
	Option4 string `json:"option4,omitempty" url:"-"`

	/*
	   The unique identifier for the inventory item.
	   Example: 5785060242375689228
	*/
	InventoryItemId string `json:"inventory_item_id,omitempty" url:"-"`

	/*
	   The original price of the variant. The value is rounded to two decimal places.
	   Example: 129.99
	*/
	CompareAtPrice string `json:"compare_at_price,omitempty" url:"-"`

	/*
	   The weight of the variant. The value is rounded up if it exceeds two decimal places.
	   Example: 0.23
	*/
	Weight string `json:"weight,omitempty" url:"-"`

	/*
	   The selling price of the variant. The value is rounded to two decimal places.
	   Example: 90.22
	*/
	Price string `json:"price,omitempty" url:"-"`

	/*
	   Information of the second option of the variant.
	   Example: xl
	*/
	Option2 string `json:"option2,omitempty" url:"-"`

	/*
	   The unit of weight for the variant. Valid values are:
	   - `g`: gram
	   - `kg`: kilogram
	   - `lb`: pound
	   - `oz`: ounce
	   - `zh_kg`: kilogram
	   Example:
	*/
	WeightUnit string `json:"weight_unit,omitempty" url:"-"`

	/*
	   The barcode of the variant.
	   Example: T0000001
	*/
	Barcode string `json:"barcode,omitempty" url:"-"`

	/*
	   Indicates whether the variant is allowed to be oversold.
	   - `deny`: Does not allow overselling.
	   - `continue`: Allow overselling.
	   Example:
	*/
	InventoryPolicy string `json:"inventory_policy,omitempty" url:"-"`
}

type Image struct {
	/*
	   The link to the variant image, represented as a URL.
	   Example: https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png
	*/
	Src string `json:"src,omitempty" url:"-"`

	/*
	   The alternative textual description of the variant image, usually a word or phrase with the characteristics or content of the image.
	   Example: This is an image alt.
	*/
	Alt string `json:"alt,omitempty" url:"-"`

	/*
	   The unique identifier for the variant image.
	   Example: 5785060242207917075
	*/
	Id string `json:"id,omitempty" url:"-"`
}

type Product struct {
	/*
	   A list of product options.
	   Example: [map[id:16158068291703878544960282 name:Color option_values:[map[id:16050375155238626683133099 value:red]] product_id:16057850264845250791280282 values:[["red", "green", "white"]] values_images:map[]]]
	*/
	Options []Option `json:"options,omitempty" url:"-"`

	/*
	   Used to identify the special behavior of the product. This field returns a value only under certain conditions.

	   For example, if the product has potential risks, the field returns a value.
	   Example: RISK, HIDDEN
	*/
	ProductBehavior string `json:"product_behavior,omitempty" url:"-"`

	/*
	   The date and time when the product was created. Format: [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601).
	   Example: 2025-03-06T02:20:26+08:00
	*/
	CreatedAt string `json:"created_at,omitempty" url:"-"`

	/*
	   The product category customized by the merchant.
	   Example: Electronics
	*/
	ProductCategory string `json:"product_category,omitempty" url:"-"`

	/*
	   The relative path of the product page.
	   Example: /products/clothes
	*/
	Path string `json:"path,omitempty" url:"-"`

	/*
	   The unique identifier for the product.
	   Example: 16057850264845250791280282
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   The status of the product. Valid values are:
	   - `active`: products on shelves
	   - `draft`: products off shelves
	   - `archived`: products archiving
	   Example:
	*/
	Status string `json:"status,omitempty" url:"-"`

	/*
	   The semantically unique identifier for the product,
	   which is generated based on `title` by default.
	   Example: product-handle
	*/
	Handle string `json:"handle,omitempty" url:"-"`

	/*
	   The subtitle of the product.
	   Example: This is a subtitle
	*/
	Subtitle string `json:"subtitle,omitempty" url:"-"`

	/*
	   A list of tags of the product.
	   Example: tag1, tag2
	*/
	Tags string `json:"tags,omitempty" url:"-"`

	/*
	   The product description.
	   Example:
	*/
	BodyHtml string `json:"body_html,omitempty" url:"-"`

	/*
	   The identifier customized for the product by the merchant. It is distinct from `product.id` returned by SHOPLINE.
	   Example: S00000001
	*/
	Spu string `json:"spu,omitempty" url:"-"`

	/*
	   A list of product variants.
	   Example: [map[barcode:T0000001 compare_at_price:129.99 id:18057850264851626133510282 image:map[alt:This is an image alt. id:5785060242207917075 src:https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png] inventory_item_id:5785060242375689228 inventory_policy: inventory_quantity:99 inventory_tracker:false option1:red option2:xl option3:cotton option4:short option5:casual position:1 price:90.22 product_id:16057850264845250791280282 required_shipping:false sku:S000000001 taxable:false title:red · xl weight:0.23 weight_unit:]]
	*/
	Variants []Variant `json:"variants,omitempty" url:"-"`

	/*
	   A list of product images.
	   Example: [map[alt:This is an image alt. id:5785060242207917075 src:https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png]]
	*/
	Images []Image `json:"images,omitempty" url:"-"`

	/*
	   The theme template of the product.
	   Example: templates/product.product_template_name.json
	*/
	TemplatePath string `json:"template_path,omitempty" url:"-"`

	/*
	   The title of the product.
	   Example: This is a Product title
	*/
	Title string `json:"title,omitempty" url:"-"`

	/*
	   The brand or vendor of the product.
	   Example: SHOPLINE
	*/
	Vendor string `json:"vendor,omitempty" url:"-"`

	/*
	   The date and time when the product was published to the online store. Format:[ISO 8601](https://en.wikipedia.org/wiki/ISO_8601).
	   Example: 2025-03-06T02:20:26+08:00
	*/
	PublishedAt string `json:"published_at,omitempty" url:"-"`

	/*
	   The date and time when the product was last updated. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).
	   Example: 2025-03-06T02:20:26+08:00
	*/
	UpdatedAt string `json:"updated_at,omitempty" url:"-"`

	/*
	   The source of the product. Valid values are:
	   - `NORMAL` : products maintained in the SHOPLINE Admin
	   - `POD_TEMPORARY` : temporary products on the Product Option Customizer&ProductBundler app
	   - `TEMPORARY` : other temporary products
	   Example:
	*/
	ProductType string `json:"product_type,omitempty" url:"-"`

	/*
	   The published scope of product sales channels. The value of this field is fixed to `web`, indicating an online store.
	   Example:
	*/
	PublishedScope string `json:"published_scope,omitempty" url:"-"`

	/*
	   The cover image of the product.
	   Example: map[alt:This is an image alt. id:5785060242207917075 src:https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png]
	*/
	Image Image `json:"image,omitempty" url:"-"`
}

type Option struct {
	/*
	   The unique identifier for the option.
	   Example: 16158068291703878544960282
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   The name of the option.
	   Example: Color
	*/
	Name string `json:"name,omitempty" url:"-"`

	/*
	   A list of product option values.
	   Example: [map[id:16050375155238626683133099 value:red]]
	*/
	OptionValues []OptionValue `json:"option_values,omitempty" url:"-"`

	/*
	   The unique identifier for the product corresponding to the option.
	   Example: 16057850264845250791280282
	*/
	ProductId string `json:"product_id,omitempty" url:"-"`

	/*
	   A list of option values.
	   Example: [["red", "green", "white"]]
	*/
	Values []string `json:"values,omitempty" url:"-"`

	/*
	   The mapping relationship between the option value and the corresponding image URL.
	   Example: map[]
	*/
	ValuesImages map[string]string `json:"values_images,omitempty" url:"-"`
}

type OptionValue struct {
	/*
	   The unique identifier for the option value.
	   Example: 16050375155238626683133099
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   The option value.
	   Example: red
	*/
	Value string `json:"value,omitempty" url:"-"`
}
