// Package product generated by SHOPLINE since v20251201
package product

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

type GetManualCollectionsAPIReq struct {
	client.BaseAPIRequest
	/*
	   The quantity limit of collections to be queried.  <br/>
	   Value range: 1-250  <br/>
	   Default value: 50
	*/
	Limit string `url:"limit,omitempty" json:"-"`
	/*
	   The unique identifier for pagination queries, used to locate a specific page.

	   This parameter value is obtained from the `link` value in the response header of this API after you have queried the pagination information.

	   For example, if the `link` value you obtained is `<https://{handle}.myshopline.com/admin/openapi/{version}/products/custom_collections.json?limit=1&page_info=eyJzaW5jZUlkIjoiMTYwNTc1OTAxNTM4OTA4Mjk1MjExMTI3ODgiLCJkaXJlY3Rpb24iOiJuZXh0IiwibGltaXQiOjF9>; rel="next"` , the value of `page_info` is `eyJzaW5jZUlkIjoiMTYwNTc1OTAxNTM4OTA4Mjk1MjExMTI3ODgiLCJkaXJlY3Rpb24iOiJuZXh0IiwibGltaXQiOjF9` .

	   For more information on how to use pagination, refer to [Paging Mechanism](/docs/apps/api-instructions-for-use/paging-mechanism).
	*/
	PageInfo string `url:"page_info,omitempty" json:"-"`
	/*
	   The title of the collection.<br/>
	   Maximum length: 255
	   Example: This is a title
	*/
	Title string `url:"title,omitempty" json:"-"`
	/*
	   Specify the latest update time for the collection to be queried. Collections updated before this time will be returned. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).
	   Example: 2021-09-03T14:11:54+00:00
	*/
	UpdatedAtMax string `url:"updated_at_max,omitempty" json:"-"`
	/*
	   Specify the fields to be returned, with multiple fields separated by commas. For available fields, refer to the top-level child parameters under the `custom_collections` object in the response.
	   Example: title,handle
	*/
	Fields string `url:"fields,omitempty" json:"-"`
	/*
	   The unique identifiers for collections to query, with multiple IDs separated by commas.
	   Example: 12257170618007271602093384,12257170618007271602083384
	*/
	Ids string `url:"ids,omitempty" json:"-"`
	/*
	   The ID of a specific collection. Start querying collections from this specified ID.
	   Example: 12257170618007271602093384
	*/
	SinceId string `url:"since_id,omitempty" json:"-"`
	/*
	   Specify the earliest update time for the collection to be queried. Collections updated on and after this time will be returned. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).
	   Example: 2021-09-03T14:11:54+00:00
	*/
	UpdatedAtMin string `url:"updated_at_min,omitempty" json:"-"`
	/*
	   The semantically unique identifier for the collection, which is generated based on `title` by default.  <br/>
	   Maximum length: 255
	   Example: collection-handle
	*/
	Handle string `url:"handle,omitempty" json:"-"`
}

func (req *GetManualCollectionsAPIReq) GetEndpoint() string {

	return "products/custom_collections.json"

}

func (req *GetManualCollectionsAPIReq) GetMethod() string {
	return "GET"
}

func (req *GetManualCollectionsAPIReq) GetQuery() interface{} {
	return req
}

// Verify the api request parameters
func (req *GetManualCollectionsAPIReq) Verify() error {

	return nil
}

func (req *GetManualCollectionsAPIReq) NewAPIResp() *GetManualCollectionsAPIResp {
	return &GetManualCollectionsAPIResp{}
}

type GetManualCollectionsAPIResp struct {
	client.BaseAPIResponse
	/*
	   Collection information.
	   Example: [map[banner:map[alt:This is an image alt src:https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png] body_html:This is a description created_at:2021-09-03T14:11:54+00:00 handle:collection-handle id:12257170618007271602093384 image:map[alt:This is an image alt src:https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png] path:/collections/spring published_at:2021-09-03T14:11:54+00:00 published_scope:<nil> sort_order:<nil> template_path:templates/sortation/detail.json title:This is a title updated_at:2021-09-04T14:11:54+00:00]]
	*/
	CustomCollections []CustomCollection `json:"custom_collections,omitempty" url:"-"`
}
