// Package product generated by SHOPLINE since v20251201
package product

import (
	"errors"
	"fmt"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type GetAProductAPIReq struct {
	client.BaseAPIRequest
	/*
	   The unique identifier for the product. <br/>
	   Maximum length：64
	   Example: 16049619743346320200470282
	*/
	ProductId string `url:"-" json:"-"` // Required
	/*
	   Specify the fields to be returned, with multiple fields separated by commas. For available fields, refer to the top-level child parameters under the `product` object in the response.
	   Example: title,id
	*/
	Fields string `url:"fields,omitempty" json:"-"`
}

func (req *GetAProductAPIReq) GetEndpoint() string {

	return fmt.Sprintf("products/%s.json", req.ProductId)

}

func (req *GetAProductAPIReq) GetMethod() string {
	return "GET"
}

func (req *GetAProductAPIReq) GetQuery() interface{} {
	return req
}

// Verify the api request parameters
func (req *GetAProductAPIReq) Verify() error {

	if req.ProductId == "" {
		return errors.New("ProductId is required")
	}

	return nil
}

func (req *GetAProductAPIReq) NewAPIResp() *GetAProductAPIResp {
	return &GetAProductAPIResp{}
}

type GetAProductAPIResp struct {
	client.BaseAPIResponse
	/*
	   Product information.
	   Example: map[body_html:<nil> created_at:2025-03-06T02:20:26+08:00 handle:product-handle id:16057850264845250791280282 image:map[alt:This is an image alt. id:5785060242207917075 src:https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png] images:[map[alt:This is an image alt. id:5785060242207917075 src:https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png]] options:[map[id:16158068291703878544960282 name:Color option_values:[map[id:16050375155238626683133099 value:red]] product_id:16057850264845250791280282 values:[["red", "green", "white"]] values_images:map[red:https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png]]] path:/products/clothes product_behavior:RISK,HIDDEN product_category:Electronic product_type:<nil> published_at:2025-03-06T02:20:26+08:00 published_scope:<nil> spu:S00000001 status:<nil> subtitle:This is a subtitle tags:tag1, tag2 template_path:templates/product.product_template_name.json title:This is a Product title updated_at:2025-03-06T02:20:26+08:00 variants:[map[barcode:T00000001 compare_at_price:129.99 id:18057039439794751459380282 image:map[alt:This is an image alt. id:5785060242207917075 src:https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png] inventory_item_id:59854602422372317075 inventory_policy:<nil> inventory_quantity:99 inventory_tracker:<nil> option1:red option2:xl option3:cotton option4:short option5:casual price:90.22 product_id:16057039432335097907370282 require_shipping:<nil> sku:S00000001 taxable:<nil> title:red · xl weight:0.23 weight_unit:<nil>]] vendor:SHOPLINE]
	*/
	Product Product `json:"product,omitempty" url:"-"`
}
