// Package product generated by SHOPLINE since v20251201
package product

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

type GetProductCollectionRelationshipsAPIReq struct {
	client.BaseAPIRequest
	/*
	   The quantity limit of relationships to be queried.  <br/>
	   Value range: 1-250  <br/>
	   Default Value: 50
	*/
	Limit string `url:"limit,omitempty" json:"-"`
	/*
	   The unique identifier for pagination queries, used to locate a specific page.

	   This parameter value is obtained from the `link` value in the response header of this API after you have queried the pagination information.

	   For example, if the `link` value you obtained is `<https://{handle}.myshopline.com/admin/openapi/{version}/products/collects.json?limit=1&page_info=eyJzaW5jZUlkIjoiMTYwNTc1OTAxNTM4OTA4Mjk1MjExMTI3ODgiLCJkaXJlY3Rpb24iOiJuZXh0IiwibGltaXQiOjF9>; rel="next"` , the value of `page_info` is `eyJzaW5jZUlkIjoiMTYwNTc1OTAxNTM4OTA4Mjk1MjExMTI3ODgiLCJkaXJlY3Rpb24iOiJuZXh0IiwibGltaXQiOjF9` .

	   For more information on how to use pagination, refer to [Paging Mechanism](/docs/apps/api-instructions-for-use/paging-mechanism).
	*/
	PageInfo string `url:"page_info,omitempty" json:"-"`
	/*
	   The unique identifier for the product. <br/>
	   Maximum length：64
	   Example: 16057039432335097907370282
	*/
	ProductId string `url:"product_id,omitempty" json:"-"`
	/*
	   The ID of a specific product collection relationship. Start querying product collection relationships from this specified ID.
	   Example: 6063851731392959569,6239973670640427881
	*/
	SinceId string `url:"since_id,omitempty" json:"-"`
	/*
	   The unique identifier for the collection.
	   <br/>Maximum length: 64
	   Example: 12249026592161154694000282
	*/
	CollectionId string `url:"collection_id,omitempty" json:"-"`
	/*
	   Specify the fields to be returned, with multiple fields separated by commas. For available fields, refer to the top-level child parameters under the `collects` object in the response.
	   Example: created_at,id
	*/
	Fields string `url:"fields,omitempty" json:"-"`
}

func (req *GetProductCollectionRelationshipsAPIReq) GetEndpoint() string {

	return "products/collects.json"

}

func (req *GetProductCollectionRelationshipsAPIReq) GetMethod() string {
	return "GET"
}

func (req *GetProductCollectionRelationshipsAPIReq) GetQuery() interface{} {
	return req
}

// Verify the api request parameters
func (req *GetProductCollectionRelationshipsAPIReq) Verify() error {

	return nil
}

func (req *GetProductCollectionRelationshipsAPIReq) NewAPIResp() *GetProductCollectionRelationshipsAPIResp {
	return &GetProductCollectionRelationshipsAPIResp{}
}

type GetProductCollectionRelationshipsAPIResp struct {
	client.BaseAPIResponse
	/*
	   A list of relationships.
	   Example: [map[collection_id:12249026592161154694000282 created_at:2025-03-06T02:20:26+08:00 id:5.392284410644534e+18 product_id:16057039432335097907370282 product_priority:1e+13 sort_value:00000010000000000000 updated_at:2025-03-06T02:20:26+08:00]]
	*/
	Collects []GetProductCollectionRelationshipsAPIRespCollect `json:"collects,omitempty" url:"-"`
}

type GetProductCollectionRelationshipsAPIRespCollect struct {
	/*
	   The unique identifier for the collection.
	   Example: 12249026592161154694000282
	*/
	CollectionId string `json:"collection_id,omitempty" url:"-"`

	/*
	   The date and time when the product collection relationship was created. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).
	   Example: 2025-03-06T02:20:26+08:00
	*/
	CreatedAt string `json:"created_at,omitempty" url:"-"`

	/*
	   The unique identifier for the product collection relationship.
	   Example: 5.392284410644534e+18
	*/
	Id int64 `json:"id,omitempty" url:"-"`

	/*
	   The unique identifier for the product.
	   Example: 16057039432335097907370282
	*/
	ProductId string `json:"product_id,omitempty" url:"-"`

	/*
	   The priority of a product within a collection. A smaller value indicates a higher priority. The priority values are non-continuous and are not arranged in sequential integers.
	   Example: 1e+13
	*/
	ProductPriority int64 `json:"product_priority,omitempty" url:"-"`

	/*
	   Product sorting value within a collection. Constructed by left-padding the `product_priority` value with zeros to reach a total length of 20 characters.
	   Example: 00000010000000000000
	*/
	SortValue string `json:"sort_value,omitempty" url:"-"`

	/*
	   The date and time when the product collection relationship was last updated. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).
	   Example: 2025-03-06T02:20:26+08:00
	*/
	UpdatedAt string `json:"updated_at,omitempty" url:"-"`
}
