// Package product generated by SHOPLINE since v20251201
package product

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

type InitiateAFileStagedUploadAPIReq struct {
	client.BaseAPIRequest
	/*
	   A list of information about the files.
	   Example: [map[file_name:file_name file_size:300 mime_type:string]]
	*/
	FileInfo []InitiateAFileStagedUploadAPIReqFileInfo `json:"file_info,omitempty" url:"-"`
}

type InitiateAFileStagedUploadAPIReqFileInfo struct {
	/*
	   The name of the file. <br/>
	   Maximum length: 255
	   Example: file_name
	*/
	FileName string `json:"file_name,omitempty" url:"-"`

	/*
	   The size of the file, in bytes. Required when the file type is a video.
	   Example: 300
	*/
	FileSize int64 `json:"file_size,omitempty" url:"-"`

	/*
	   The MIME type of the file. Valid values are:
	   - `image/jpeg`
	   - `image/png`
	   - `image/bmp`
	   - `image/webp`
	   - `image/svg+xml`
	   - `image/x-icon`
	   - `video/mp4`
	   - `video/webm`
	   - `video/quicktime`
	   - `application/pdf`
	   - `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet`
	   - `text/csv`
	   - `application/vnd.openxmlformats-officedocument.wordprocessingml.document`
	   - `font/ttf`
	   - `font/woff`
	   - `font/otf`
	   - `font/sfnt`
	   - `application/font-sfnt`
	   - `audio/mpeg`
	   - `text/html`
	   - `text/javascript`
	   - `application/javascript`
	   - `text/css`
	   - `application/json`
	   - `application/xml`
	   - `text/xml`
	   - `text/plain`
	   - `application/octet-stream`
	   - `application/x-rar-compressed`
	   - `application/zip`
	   Example: string
	*/
	MimeType string `json:"mime_type,omitempty" url:"-"`
}

func (req *InitiateAFileStagedUploadAPIReq) GetEndpoint() string {

	return "files/upload.json"

}

func (req *InitiateAFileStagedUploadAPIReq) GetMethod() string {
	return "POST"
}

func (req *InitiateAFileStagedUploadAPIReq) GetData() interface{} {
	return req
}

// Verify the api request parameters
func (req *InitiateAFileStagedUploadAPIReq) Verify() error {

	return nil
}

func (req *InitiateAFileStagedUploadAPIReq) NewAPIResp() *InitiateAFileStagedUploadAPIResp {
	return &InitiateAFileStagedUploadAPIResp{}
}

type InitiateAFileStagedUploadAPIResp struct {
	client.BaseAPIResponse
	/*
	   A list of signature information for the files.
	   Example: [map[access_id:LTAI5tRrVqCocJKdSpEovixm call_back:eyJjYWxsYmFja0JvZHkiOiJidWNrZXQ9JHtidWNrZXR9Jm9iamVjdD0ke29iamVjdH0mc2l6ZT0ke3NpemV9JmNvbnRlbnRUeXBlVHlwZT0ke2NvbnRlbnRUeXBlVHlwZX0mZm9ybWF0PSR7aW1hZ2VJbmZvLmZvcm1hdH0mYml6dHlwZT1cIm9wZW5hcGlTdGFzaENoYW5nZUxpbmtcIiIsImNhbGxiYWNrQm9keVR5cGUiOiJhcHBsaWNhdGl host:https://sl-resource-tmp-sg.s3.xxx.com key:temp/file/store/1626235806828/6991265004189666341/image.jpg policy:eyJleHBpcmF0aW9uIjoiMjAyNi0wNS0xMlQwODo1Mjo1NloiLCJjb25kaXRpb25zIjpbWyJjb250ZW50LWxlbmd0aC1yYW5nZSIsMCwyMDk3MTUyMF0sWyJlcSIsIiRrZXkiLCJ0ZW1wL2ZpbGUvc3RvcmUvMTYyNjIzNTgwNjgyOC82OTkxMjY1MDA0MTg5NjY2MzQxLzAwMDQ5ZWEzNDQ4ZTQzMWM4YTRiYzVh signature:6+YHcWnLhu0YofPIzAQUaZ9kKZI= url:https://sl-resource-tmp-sg.s3-ap-southeast-1.xxx.com/temp%2Ffile%2Fstore%2F1672369729606%2F6995259736342668404%2Fimage.png?Expires=1747882880&OSSAccessKeyId=LTAI5tNjm7fr4EUCoEps4UPE&Signature=kLIWPCVwWTQMZcHUWyszjoH4DPM%3D]]
	*/
	Signs []Sign `json:"signs,omitempty" url:"-"`
}

type Sign struct {
	/*
	   Signature for the upload request.
	   Example: 6+YHcWnLhu0YofPIzAQUaZ9kKZI=
	*/
	Signature string `json:"signature,omitempty" url:"-"`

	/*
	   A staged upload URL.
	   Example: https://sl-resource-tmp-sg.s3-ap-southeast-1.xxx.com/temp%2Ffile%2Fstore%2F1672369729606%2F6995259736342668404%2Fimage.png?Expires=1747882880&OSSAccessKeyId=LTAI5tNjm7fr4EUCoEps4UPE&Signature=kLIWPCVwWTQMZcHUWyszjoH4DPM%3D
	*/
	Url string `json:"url,omitempty" url:"-"`

	/*
	   Access key for the upload signature.
	   Example: LTAI5tRrVqCocJKdSpEovixm
	*/
	AccessId string `json:"access_id,omitempty" url:"-"`

	/*
	   Callback parameters for the file load.
	   Example: eyJjYWxsYmFja0JvZHkiOiJidWNrZXQ9JHtidWNrZXR9Jm9iamVjdD0ke29iamVjdH0mc2l6ZT0ke3NpemV9JmNvbnRlbnRUeXBlVHlwZT0ke2NvbnRlbnRUeXBlVHlwZX0mZm9ybWF0PSR7aW1hZ2VJbmZvLmZvcm1hdH0mYml6dHlwZT1cIm9wZW5hcGlTdGFzaENoYW5nZUxpbmtcIiIsImNhbGxiYWNrQm9keVR5cGUiOiJhcHBsaWNhdGl
	*/
	CallBack string `json:"call_back,omitempty" url:"-"`

	/*
	   The base URL endpoint where the file will be uploaded.
	   Example: https://sl-resource-tmp-sg.s3.xxx.com
	*/
	Host string `json:"host,omitempty" url:"-"`

	/*
	   Relative path for storing the file, including the filename.
	   Example: temp/file/store/1626235806828/6991265004189666341/image.jpg
	*/
	Key string `json:"key,omitempty" url:"-"`

	/*
	   Signature policy information for the file upload.
	   Example: eyJleHBpcmF0aW9uIjoiMjAyNi0wNS0xMlQwODo1Mjo1NloiLCJjb25kaXRpb25zIjpbWyJjb250ZW50LWxlbmd0aC1yYW5nZSIsMCwyMDk3MTUyMF0sWyJlcSIsIiRrZXkiLCJ0ZW1wL2ZpbGUvc3RvcmUvMTYyNjIzNTgwNjgyOC82OTkxMjY1MDA0MTg5NjY2MzQxLzAwMDQ5ZWEzNDQ4ZTQzMWM4YTRiYzVh
	*/
	Policy string `json:"policy,omitempty" url:"-"`
}
