// Package product generated by SHOPLINE since v20251201
package product

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

type QueryMultipleSellingProgramsAPIReq struct {
	client.BaseAPIRequest
	/*
	   Create time before xxx ( format see IOS8601 )
	   Example: 2022-01-07T14:38:25.734+08:00
	*/
	CreateAtMax string `url:"create_at_max,omitempty" json:"-"`
	/*
	   Creation time starts from XXX (see IOS8601 for the format)
	   Example: 2022-01-07T14:38:25.734+08:00
	*/
	CreateAtMin string `url:"create_at_min,omitempty" json:"-"`
	/*
	   Limit of query , default 50 , can not exceed 250
	   Example: 50
	*/
	Limit int `url:"limit,omitempty" json:"-"`
	/*
	   Sales plan group name , fuzzy query
	   Example: Discount
	*/
	Name string `url:"name,omitempty" json:"-"`
	/*
	   The unique identifier for pagination queries, used to locate a specific page.

	   This parameter value is obtained from the `link` value in the response header of this API after you have queried the pagination information.

	   For example, if the `link` value you obtained is `<https://{handle}.myshopline.com/admin/openapi/{version}/selling_plan_group/selling_plan_group.json?limit=1&page_info=eyJzaW5jZUlkIjoiMTYwNTc1OTAxNTM4OTA4Mjk1MjExMTI3ODgiLCJkaXJlY3Rpb24iOiJuZXh0IiwibGltaXQiOjF9>; rel="next"` , the value of `page_info` is `eyJzaW5jZUlkIjoiMTYwNTc1OTAxNTM4OTA4Mjk1MjExMTI3ODgiLCJkaXJlY3Rpb24iOiJuZXh0IiwibGltaXQiOjF9` .
	   For more information on how to use pagination, refer to [Paging Mechanism](/docs/apps/api-instructions-for-use/paging-mechanism).
	   Example: eyJzaW5jZUlkIjoiMTQwNTYyMDAyNDU4NDQzNzI0NDExMDAwMDkiLCJkaXJlY3Rpb24iOiJuZXh0In0=
	*/
	PageInfo string `url:"page_info,omitempty" json:"-"`
	/*
	   Start with specify selling plan group id query
	   Example: 14056200245844372441100010
	*/
	SinceId string `url:"since_id,omitempty" json:"-"`
}

func (req *QueryMultipleSellingProgramsAPIReq) GetEndpoint() string {

	return "selling_plan_group/selling_plan_group.json"

}

func (req *QueryMultipleSellingProgramsAPIReq) GetMethod() string {
	return "GET"
}

func (req *QueryMultipleSellingProgramsAPIReq) GetQuery() interface{} {
	return req
}

// Verify the api request parameters
func (req *QueryMultipleSellingProgramsAPIReq) Verify() error {

	return nil
}

func (req *QueryMultipleSellingProgramsAPIReq) NewAPIResp() *QueryMultipleSellingProgramsAPIResp {
	return &QueryMultipleSellingProgramsAPIResp{}
}

type QueryMultipleSellingProgramsAPIResp struct {
	client.BaseAPIResponse
	/*
	   List of sales plan groups
	   Example: [map[app_id:c41ac9e6736785502d2333d1b1153aca795075c4 description:This is a description id:14056200245844372441100009 merchant_code:Subscription plan group default name name:Subscription plan group default name options:[["delivery every 1 months", "delivery every 2 months", "delivery every 3 months"]] position:1 product_count:10]]
	*/
	SellingPlanGroupList []SellingPlanGroupList `json:"selling_plan_group_list,omitempty" url:"-"`
}

type SellingPlanGroupList struct {
	/*
	   Show the name to the seller
	   Example: Subscription plan group default name
	*/
	MerchantCode string `json:"merchant_code,omitempty" url:"-"`

	/*
	   Sales plan group name
	   Example: Subscription plan group default name
	*/
	Name string `json:"name,omitempty" url:"-"`

	/*
	   List of sales plan group options
	   Example: [["delivery every 1 months", "delivery every 2 months", "delivery every 3 months"]]
	*/
	Options []string `json:"options,omitempty" url:"-"`

	/*
	   Display location
	   Example: 1
	*/
	Position int `json:"position,omitempty" url:"-"`

	/*
	   Associated Product count
	   Example: 10
	*/
	ProductCount int `json:"product_count,omitempty" url:"-"`

	/*
	   Sales channel id
	   Example: c41ac9e6736785502d2333d1b1153aca795075c4
	*/
	AppId string `json:"app_id,omitempty" url:"-"`

	/*
	   Description
	   Example: This is a description
	*/
	Description string `json:"description,omitempty" url:"-"`

	/*
	   Sales plan group id
	   Example: 14056200245844372441100009
	*/
	Id string `json:"id,omitempty" url:"-"`
}
