// Package product generated by SHOPLINE since v20251201
package product

import (
	"errors"
	"fmt"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type QuerySingleGiftCardAPIReq struct {
	client.BaseAPIRequest
	/*
	   Gift card id
	   Example: 30157043359245339231360282
	*/
	GiftCardId string `url:"-" json:"-"` // Required
}

func (req *QuerySingleGiftCardAPIReq) GetEndpoint() string {

	return fmt.Sprintf("gift_cards/%s.json", req.GiftCardId)

}

func (req *QuerySingleGiftCardAPIReq) GetMethod() string {
	return "GET"
}

// Verify the api request parameters
func (req *QuerySingleGiftCardAPIReq) Verify() error {

	if req.GiftCardId == "" {
		return errors.New("GiftCardId is required")
	}

	return nil
}

func (req *QuerySingleGiftCardAPIReq) NewAPIResp() *QuerySingleGiftCardAPIResp {
	return &QuerySingleGiftCardAPIResp{}
}

type QuerySingleGiftCardAPIResp struct {
	client.BaseAPIResponse
	/*
	   Gift card information
	   Example: map[api_client_id:36d2bc4e97af056677b61c529d9e3a3f7396040d balance:200 created_at:2023-08-16T23:59:59+08:00 currency:CNY customer_id:4200113946 disabled_at:2023-08-16T23:59:59+08:00 expires_on:2023-08-16T23:59:59+08:00 id:30157043359245339231360282 initial_value:200 last_characters:d246 line_item_id:18060183094426803997483534 note:This is a note order_id:24060486231247568944830202 updated_at:2023-08-16T23:59:59+08:00 user_id:4214250478]
	*/
	GiftCard QuerySingleGiftCardAPIRespGiftCard `json:"gift_card,omitempty" url:"-"`
}

type QuerySingleGiftCardAPIRespGiftCard struct {
	/*
	   Expiration date for present gift card, “null” means never expired
	   Example: 2023-08-16T23:59:59+08:00
	*/
	ExpiresOn string `json:"expires_on,omitempty" url:"-"`

	/*
	   Gift card id
	   Example: 30157043359245339231360282
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   Note information for present gift card
	   Example: This is a note
	*/
	Note string `json:"note,omitempty" url:"-"`

	/*
	   Gift card disable time
	   Example: 2023-08-16T23:59:59+08:00
	*/
	DisabledAt string `json:"disabled_at,omitempty" url:"-"`

	/*
	   Gift card balance
	   Example: 200
	*/
	Balance string `json:"balance,omitempty" url:"-"`

	/*
	   Gift card par currency
	   Example: CNY
	*/
	Currency string `json:"currency,omitempty" url:"-"`

	/*
	   Associated order id
	   Example: 24060486231247568944830202
	*/
	OrderId string `json:"order_id,omitempty" url:"-"`

	/*
	   Gift card creation time
	   Example: 2023-08-16T23:59:59+08:00
	*/
	CreatedAt string `json:"created_at,omitempty" url:"-"`

	/*
	   Administrator account id on the admin interface for users to create gift cards
	   Example: 4214250478
	*/
	UserId string `json:"user_id,omitempty" url:"-"`

	/*
	   The last four characters from code
	   Example: d246
	*/
	LastCharacters string `json:"last_characters,omitempty" url:"-"`

	/*
	   Client id for customers assigned to present gift card
	   Example: 4200113946
	*/
	CustomerId string `json:"customer_id,omitempty" url:"-"`

	/*
	   Associated order items
	   Example: 18060183094426803997483534
	*/
	LineItemId string `json:"line_item_id,omitempty" url:"-"`

	/*
	   Gift card update time
	   Example: 2023-08-16T23:59:59+08:00
	*/
	UpdatedAt string `json:"updated_at,omitempty" url:"-"`

	/*
	   Call party id
	   Example: 36d2bc4e97af056677b61c529d9e3a3f7396040d
	*/
	ApiClientId string `json:"api_client_id,omitempty" url:"-"`

	/*
	   Initial face value of gift card
	   Example: 200
	*/
	InitialValue string `json:"initial_value,omitempty" url:"-"`
}
