// Package product generated by SHOPLINE since v20251201
package product

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

type QueryTaxonomyOfTheStoreAPIReq struct {
	client.BaseAPIRequest
}

func (req *QueryTaxonomyOfTheStoreAPIReq) GetEndpoint() string {

	return "taxonomies.json"

}

func (req *QueryTaxonomyOfTheStoreAPIReq) GetMethod() string {
	return "GET"
}

// Verify the api request parameters
func (req *QueryTaxonomyOfTheStoreAPIReq) Verify() error {

	return nil
}

func (req *QueryTaxonomyOfTheStoreAPIReq) NewAPIResp() *QueryTaxonomyOfTheStoreAPIResp {
	return &QueryTaxonomyOfTheStoreAPIResp{}
}

type QueryTaxonomyOfTheStoreAPIResp struct {
	client.BaseAPIResponse
	/*
	   A list of taxonomy collection node.
	   Example: [map[children:[map[]] collection_id:12257170618007271602093384 id:7004220176356349981 parent_id:7004220176355548881]]
	*/
	Taxonomies []QueryTaxonomyOfTheStoreAPIRespTaxonomy `json:"taxonomies,omitempty" url:"-"`
}

type Children struct {
}

type QueryTaxonomyOfTheStoreAPIRespTaxonomy struct {
	/*
	   The unique identifier for the taxonomy collection node.
	   Example: 7004220176356349981
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   The unique identifier for the parent node.
	   Example: 7004220176355548881
	*/
	ParentId string `json:"parent_id,omitempty" url:"-"`

	/*
	   Child nodes (next-level nodes).
	   Example: [map[]]
	*/
	Children []Children `json:"children,omitempty" url:"-"`

	/*
	   The unique identifier for the collection.
	   Example: 12257170618007271602093384
	*/
	CollectionId string `json:"collection_id,omitempty" url:"-"`
}
