// Package app generated by SHOPLINE since v20251201
package app

import (
	"errors"
	"fmt"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type QueryImagesOfVariantAPIReq struct {
	client.BaseAPIRequest
	/*
	   The ID of the product.
	   Example: 16049619743346320200470282
	*/
	ProductId string `url:"-" json:"-"` // Required
}

func (req *QueryImagesOfVariantAPIReq) GetEndpoint() string {

	return fmt.Sprintf("variant_images/%s.json", req.ProductId)

}

func (req *QueryImagesOfVariantAPIReq) GetMethod() string {
	return "GET"
}

// Verify the api request parameters
func (req *QueryImagesOfVariantAPIReq) Verify() error {

	if req.ProductId == "" {
		return errors.New("ProductId is required")
	}

	return nil
}

func (req *QueryImagesOfVariantAPIReq) NewAPIResp() *QueryImagesOfVariantAPIResp {
	return &QueryImagesOfVariantAPIResp{}
}

type QueryImagesOfVariantAPIResp struct {
	client.BaseAPIResponse
	/*
	   Return data.
	   Example: map[product_id:16049619743346320200470282 variant_images:[map[urls:[https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png] variant_id:18050375907221969070393099]]]
	*/
	Data QueryImagesOfVariantAPIRespData `json:"data,omitempty" url:"-"`
}

type QueryImagesOfVariantAPIRespData struct {
	/*
	   The ID of the product.
	   Example: 16049619743346320200470282
	*/
	ProductId string `json:"product_id,omitempty" url:"-"`

	/*
	   variant images created by 'Variants Multiple Images'.
	   Example: [map[urls:[https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png] variant_id:18050375907221969070393099]]
	*/
	VariantImages []VariantImage `json:"variant_images,omitempty" url:"-"`
}

type VariantImage struct {
	/*
	   The URL address of the image.
	   Example: [https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png]
	*/
	Urls []string `json:"urls,omitempty" url:"-"`

	/*
	   A unique ID of the variant.
	   Example: 18050375907221969070393099
	*/
	VariantId string `json:"variant_id,omitempty" url:"-"`
}
