// Package onlinestore generated by SHOPLINE since v20251201
package onlinestore

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

type QueryListOfAllArticlesAuthorsAPIReq struct {
	client.BaseAPIRequest
}

func (req *QueryListOfAllArticlesAuthorsAPIReq) GetEndpoint() string {

	return "store/blogs/authors.json"

}

func (req *QueryListOfAllArticlesAuthorsAPIReq) GetMethod() string {
	return "GET"
}

// Verify the api request parameters
func (req *QueryListOfAllArticlesAuthorsAPIReq) Verify() error {

	return nil
}

func (req *QueryListOfAllArticlesAuthorsAPIReq) NewAPIResp() *QueryListOfAllArticlesAuthorsAPIResp {
	return &QueryListOfAllArticlesAuthorsAPIResp{}
}

type QueryListOfAllArticlesAuthorsAPIResp struct {
	client.BaseAPIResponse
	/*
	   Author list
	   Example: [["wilson"]]
	*/
	Authors []string `json:"authors,omitempty" url:"-"`
}
