// Package onlinestore generated by SHOPLINE since v20251201
package onlinestore

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

type StatisticalRedirectQuantityAPIReq struct {
	client.BaseAPIRequest
	/*
	   The source path to be redirected.
	   Example: /products/A
	*/
	Path string `url:"path,omitempty" json:"-"`
	/*
	   The target path where the user will be redirected.
	   Example: /products/B
	*/
	Target string `url:"target,omitempty" json:"-"`
}

func (req *StatisticalRedirectQuantityAPIReq) GetEndpoint() string {

	return "redirects/count.json"

}

func (req *StatisticalRedirectQuantityAPIReq) GetMethod() string {
	return "GET"
}

func (req *StatisticalRedirectQuantityAPIReq) GetQuery() interface{} {
	return req
}

// Verify the api request parameters
func (req *StatisticalRedirectQuantityAPIReq) Verify() error {

	return nil
}

func (req *StatisticalRedirectQuantityAPIReq) NewAPIResp() *StatisticalRedirectQuantityAPIResp {
	return &StatisticalRedirectQuantityAPIResp{}
}

type StatisticalRedirectQuantityAPIResp struct {
	client.BaseAPIResponse
	/*
	   Compliance with filter conditions for redirect quantity
	   Example: 100
	*/
	Count int64 `json:"count,omitempty" url:"-"`
}
