// Package onlinestore generated by SHOPLINE since v20251201
package onlinestore

import (
	"errors"
	"fmt"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type ByReviewingIdQueryCommentsAPIReq struct {
	client.BaseAPIRequest
	/*
	   Comment id
	   Example: 638040c6a0a9ba4487960880
	*/
	CommentId string `url:"-" json:"-"` // Required
	/*
	   Limited return object fields , multiple separated by ',' are used
	   Example: author,body
	*/
	Fields string `url:"fields,omitempty" json:"-"`
}

func (req *ByReviewingIdQueryCommentsAPIReq) GetEndpoint() string {

	return fmt.Sprintf("store/comments/%s.json", req.CommentId)

}

func (req *ByReviewingIdQueryCommentsAPIReq) GetMethod() string {
	return "GET"
}

func (req *ByReviewingIdQueryCommentsAPIReq) GetQuery() interface{} {
	return req
}

// Verify the api request parameters
func (req *ByReviewingIdQueryCommentsAPIReq) Verify() error {

	if req.CommentId == "" {
		return errors.New("CommentId is required")
	}

	return nil
}

func (req *ByReviewingIdQueryCommentsAPIReq) NewAPIResp() *ByReviewingIdQueryCommentsAPIResp {
	return &ByReviewingIdQueryCommentsAPIResp{}
}

type ByReviewingIdQueryCommentsAPIResp struct {
	client.BaseAPIResponse
	/*
	   Review information
	   Example: map[author:demo-author blog_collection_id:639bfda0ee877c4a9bd600b6 blog_id:63a2afa527797d5cedcecb52 body:demo-content body_html:<p>demo-content</p> create_at:2022-08-03T10:45:00+08:00

	   	email:demo@qq.com id:638040c6a0a9ba4487960880 ip:172.28.173.136 published_at:2022-08-03T10:45:00+08:00
	   	status:unapproved updated_at:2022-08-03T10:45:00+08:00
	   	user_agent:]
	*/
	Comment Comment `json:"comment,omitempty" url:"-"`
}
