// Package onlinestore generated by SHOPLINE since v20251201
package onlinestore

import (
	"errors"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type CreateACommentAPIReq struct {
	client.BaseAPIRequest
	/*
	   Comment content
	   Example: demo-content
	*/
	Body string `json:"body,omitempty" url:"-"`

	/*
	   Body content with html markings
	   Example: <p>demo-content</p>
	*/
	BodyHtml string `json:"body_html,omitempty" url:"-"`

	/*
	   Comment on the e-mail address of the author
	   Example: demo@qq.com
	*/
	Email string `json:"email,omitempty" url:"-"`

	/*
	   Ip to post a review
	   Example: 172.28.173.136
	*/
	Ip string `json:"ip,omitempty" url:"-"`

	/*
	   Author of the review
	   Example: demo-author
	*/
	Author string `json:"author,omitempty" url:"-"`

	/*
	   Comment on blog id
	   Example: 63a2afa527797d5cedcecb52
	*/
	BlogId string `json:"blog_id,omitempty" url:"-"`
}

func (req *CreateACommentAPIReq) GetEndpoint() string {

	return "store/comments.json"

}

func (req *CreateACommentAPIReq) GetMethod() string {
	return "POST"
}

func (req *CreateACommentAPIReq) GetData() interface{} {
	return req
}

// Verify the api request parameters
func (req *CreateACommentAPIReq) Verify() error {

	if req.Author == "" {
		return errors.New("Author is required")
	}

	if req.BlogId == "" {
		return errors.New("BlogId is required")
	}

	if req.Body == "" {
		return errors.New("Body is required")
	}

	if req.Email == "" {
		return errors.New("Email is required")
	}

	if req.Ip == "" {
		return errors.New("Ip is required")
	}

	return nil
}

func (req *CreateACommentAPIReq) NewAPIResp() *CreateACommentAPIResp {
	return &CreateACommentAPIResp{}
}

type CreateACommentAPIResp struct {
	client.BaseAPIResponse
	/*
	   Review information
	   Example: map[author:demo-author blog_collection_id:639bfda0ee877c4a9bd600b6 blog_id:63a2afa527797d5cedcecb52 body:demo-content body_html:<p>demo-content</p> create_at:2022-08-03T10:45:00+08:00

	   	email:demo@qq.com id:63aaa20f6b7b014b289c0765 ip:172.28.173.136 published_at:2022-08-03T10:45:00+08:00
	   	status:unapproved updated_at:2022-08-03T10:45:00+08:00
	   	user_agent:]
	*/
	Comment Comment `json:"comment,omitempty" url:"-"`
}

type Comment struct {
	/*
	   Update time ISO 8601
	   Example: 2022-08-03T10:45:00+08:00
	*/
	UpdatedAt string `json:"updated_at,omitempty" url:"-"`

	/*
	   Comment on blog id
	   Example: 63a2afa527797d5cedcecb52
	*/
	BlogId string `json:"blog_id,omitempty" url:"-"`

	/*
	   User agent
	   Example:
	*/
	UserAgent string `json:"user_agent,omitempty" url:"-"`

	/*
	   Comment on the blog collection id for articles belonging to
	   Example: 639bfda0ee877c4a9bd600b6
	*/
	BlogCollectionId string `json:"blog_collection_id,omitempty" url:"-"`

	/*
	   Comment status , post value : unapproved ( default state , comment waiting to be approved , c end does not show this state comment ) ; published : ( posted state , and visible to users on the end of c ) ; spam : ( garbage review , c end )Removed : ( review is marked as deleted status , not visible for users on the end of the c )
	   Example: unapproved
	*/
	Status string `json:"status,omitempty" url:"-"`

	/*
	   Comment content
	   Example: demo-content
	*/
	Body string `json:"body,omitempty" url:"-"`

	/*
	   Comment id
	   Example: 63aaa20f6b7b014b289c0765
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   Time to post a review ISO 8601
	   Example: 2022-08-03T10:45:00+08:00
	*/
	PublishedAt string `json:"published_at,omitempty" url:"-"`

	/*
	   Comment on the e-mail address of the author
	   Example: demo@qq.com
	*/
	Email string `json:"email,omitempty" url:"-"`

	/*
	   Author of the review
	   Example: demo-author
	*/
	Author string `json:"author,omitempty" url:"-"`

	/*
	   Ip to post a review
	   Example: 172.28.173.136
	*/
	Ip string `json:"ip,omitempty" url:"-"`

	/*
	   Body content with html markings
	   Example: <p>demo-content</p>
	*/
	BodyHtml string `json:"body_html,omitempty" url:"-"`

	/*
	   Created time for reviews ISO 8601
	   Example: 2022-08-03T10:45:00+08:00
	*/
	CreateAt string `json:"create_at,omitempty" url:"-"`
}
