// Package onlinestore generated by SHOPLINE since v20251201
package onlinestore

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

type NumberOfGetTheCommentsAPIReq struct {
	client.BaseAPIRequest
	/*
	   Comment on the blog collection id for articles belonging to
	   Example: 639bfda0ee877c4a9bd600b6
	*/
	BlogCollectionId string `url:"blog_collection_id,omitempty" json:"-"`
	/*
	   Comment on blog id
	   Example: 63a2afa527797d5cedcecb52
	*/
	BlogId string `url:"blog_id,omitempty" json:"-"`
	/*
	   Review max creation time ISO 8601
	   Example: 2022-08-03T10:45:00+08:00
	*/
	CreatedAtMax string `url:"created_at_max,omitempty" json:"-"`
	/*
	   Review minimum time to create ISO 8601
	   Example: 2022-08-03T10:45:00+08:00
	*/
	CreatedAtMin string `url:"created_at_min,omitempty" json:"-"`
	/*
	   Post review max time ISO 8601
	   Example: 2022-08-03T10:45:00+08:00
	*/
	PublishedAtMax string `url:"published_at_max,omitempty" json:"-"`
	/*
	   Post review min time ISO 8601
	   Example: 2022-08-03T10:45:00+08:00
	*/
	PublishedAtMin string `url:"published_at_min,omitempty" json:"-"`
	/*
	   Launch status , value : published ( posted status ) ; unpublished : ( not released status ) ; any : ( all status ) ;
	   Example: published
	*/
	PublishedStatus string `url:"published_status,omitempty" json:"-"`
	/*
	   Status : value : unapproved ( review waiting to approve ) ; published ( posted status ) ;
	   Example: unapproved
	*/
	Status string `url:"status,omitempty" json:"-"`
	/*
	   Update max time ISO 8601
	   Example: 2022-08-03T10:45:00+08:00
	*/
	UpdatedAtMax string `url:"updated_at_max,omitempty" json:"-"`
	/*
	   Update min time ISO 8601
	   Example: 2022-08-03T10:45:00+08:00
	*/
	UpdatedAtMin string `url:"updated_at_min,omitempty" json:"-"`
}

func (req *NumberOfGetTheCommentsAPIReq) GetEndpoint() string {

	return "store/comments/count.json"

}

func (req *NumberOfGetTheCommentsAPIReq) GetMethod() string {
	return "GET"
}

func (req *NumberOfGetTheCommentsAPIReq) GetQuery() interface{} {
	return req
}

// Verify the api request parameters
func (req *NumberOfGetTheCommentsAPIReq) Verify() error {

	return nil
}

func (req *NumberOfGetTheCommentsAPIReq) NewAPIResp() *NumberOfGetTheCommentsAPIResp {
	return &NumberOfGetTheCommentsAPIResp{}
}

type NumberOfGetTheCommentsAPIResp struct {
	client.BaseAPIResponse
	/*
	   Number of reviews for filter conditions
	   Example: 100
	*/
	Count int64 `json:"count,omitempty" url:"-"`
}
