// Package onlinestore generated by SHOPLINE since v20251201
package onlinestore

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

type QueryBlogCollectionListAPIReq struct {
	client.BaseAPIRequest
	/*
	   The handle of blog collection
	   Example: demo-blogs
	*/
	Handle string `url:"handle,omitempty" json:"-"`
	/*
	   Query of query quantity , default 50 , can not exceed 1000
	   Example: 50
	*/
	Limit int `url:"limit,omitempty" json:"-"`
	/*
	   Show blog collection after this id
	   Example: 63a50a79cec17b0b728a3b69
	*/
	SinceId string `url:"since_id,omitempty" json:"-"`
}

func (req *QueryBlogCollectionListAPIReq) GetEndpoint() string {

	return "store/blogs.json"

}

func (req *QueryBlogCollectionListAPIReq) GetMethod() string {
	return "GET"
}

func (req *QueryBlogCollectionListAPIReq) GetQuery() interface{} {
	return req
}

// Verify the api request parameters
func (req *QueryBlogCollectionListAPIReq) Verify() error {

	return nil
}

func (req *QueryBlogCollectionListAPIReq) NewAPIResp() *QueryBlogCollectionListAPIResp {
	return &QueryBlogCollectionListAPIResp{}
}

type QueryBlogCollectionListAPIResp struct {
	client.BaseAPIResponse
	/*
	   Blog collection list
	   Example: [map[commentable:moderate created_at:2022-08-03T10:45:00+08:00

	   	handle:demo-blogs id:63a9a344609552261f00f23e template_suffix:templates/blogs/list.json title:demo blogs updated_at:2022-08-03T10:45:00+08:00

	   ]]
	*/
	Blogs []QueryBlogCollectionListAPIRespBlog `json:"blogs,omitempty" url:"-"`
}

type QueryBlogCollectionListAPIRespBlog struct {
	/*
	   The handle of the blog collection
	   Example: demo-blogs
	*/
	Handle string `json:"handle,omitempty" url:"-"`

	/*
	   blog collection id
	   Example: 63a9a344609552261f00f23e
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   The template name of the blog collection
	   Example: templates/blogs/list.json
	*/
	TemplateSuffix string `json:"template_suffix,omitempty" url:"-"`

	/*
	   Title of blog collection
	   Example: demo blogs
	*/
	Title string `json:"title,omitempty" url:"-"`

	/*
	   Update time ISO 8601
	   Example: 2022-08-03T10:45:00+08:00
	*/
	UpdatedAt string `json:"updated_at,omitempty" url:"-"`

	/*
	   Comment configuration , post value : no ( can not post reviews ) ; moderate ( default , can post reviews , but need to review ) ; yes ( can post reviews and do not need to review automatic posting success )
	   Example: moderate
	*/
	Commentable string `json:"commentable,omitempty" url:"-"`

	/*
	   Create time ISO 8601
	   Example: 2022-08-03T10:45:00+08:00
	*/
	CreatedAt string `json:"created_at,omitempty" url:"-"`
}
