// Package onlinestore generated by SHOPLINE since v20251201
package onlinestore

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

type QueryTheNumberOfScriptTagsAPIReq struct {
	client.BaseAPIRequest
}

func (req *QueryTheNumberOfScriptTagsAPIReq) GetEndpoint() string {

	return "store/script_tags/count.json"

}

func (req *QueryTheNumberOfScriptTagsAPIReq) GetMethod() string {
	return "GET"
}

// Verify the api request parameters
func (req *QueryTheNumberOfScriptTagsAPIReq) Verify() error {

	return nil
}

func (req *QueryTheNumberOfScriptTagsAPIReq) NewAPIResp() *QueryTheNumberOfScriptTagsAPIResp {
	return &QueryTheNumberOfScriptTagsAPIResp{}
}

type QueryTheNumberOfScriptTagsAPIResp struct {
	client.BaseAPIResponse
	/*
	   Script tag quantity
	   Example: 100
	*/
	Count int64 `json:"count,omitempty" url:"-"`
}
