// Package metafield generated by SHOPLINE since v20260301
package metafield

import (
	"errors"
	"fmt"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type AddASecondaryMetafieldToBeDeprecatedAPIReq struct {
	client.BaseAPIRequest
	/*
	   Secondary resource id
	   Example: 1802351351232521351351
	*/
	OwnerId string `url:"-" json:"-"` // Required
	/*
	   First class resource id
	   Example: 16024213413413412341234
	*/
	POwnerId string `url:"-" json:"-"` // Required
	/*
	   First class resources , like products
	   Example: products
	*/
	PResource string `url:"-" json:"-"` // Required
	/*
	   Secondary resources such as variants
	   Example: variants
	*/
	Resource string `url:"-" json:"-"` // Required
	/*
	   metafield
	   Example: map[description:My description key:key_123 namespace:namespace_123 type:single_line_text_field value:<nil>]
	*/
	Metafield AddASecondaryMetafieldToBeDeprecatedAPIReqMetafield `json:"metafield,omitempty" url:"-"`
}

type AddASecondaryMetafieldToBeDeprecatedAPIReqMetafield struct {
	/*
	   Description
	   Example: My description
	*/
	Description string `json:"description,omitempty" url:"-"`

	/*
	   A unique identifier for a metafield within its `namespace`.
	   Example: key_123
	*/
	Key string `json:"key,omitempty" url:"-"`

	/*
	   Namespace , 2-50 characters
	   Example: namespace_123
	*/
	Namespace string `json:"namespace,omitempty" url:"-"`

	/*
	   The type of value, such as single_line_text_field, multi_line_text_field, boolean, url, variant_reference, product_reference, page_reference, rating, number_decimal, number_integer, dimension, volume, weight, json, file_reference, date_time, date, color
	   Example: single_line_text_field
	*/
	Type string `json:"type,omitempty" url:"-"`

	/*
	   The data stored in the metafield.
	*/
	Value Value `json:"value,omitempty" url:"-"`
}

func (req *AddASecondaryMetafieldToBeDeprecatedAPIReq) GetEndpoint() string {

	return fmt.Sprintf("%s/%s/%s/%s/metafields.json", req.OwnerId, req.POwnerId, req.PResource, req.Resource)

}

func (req *AddASecondaryMetafieldToBeDeprecatedAPIReq) GetMethod() string {
	return "POST"
}

func (req *AddASecondaryMetafieldToBeDeprecatedAPIReq) GetData() interface{} {
	return req
}

// Verify the api request parameters
func (req *AddASecondaryMetafieldToBeDeprecatedAPIReq) Verify() error {

	if req.OwnerId == "" {
		return errors.New("OwnerId is required")
	}

	if req.POwnerId == "" {
		return errors.New("POwnerId is required")
	}

	if req.PResource == "" {
		return errors.New("PResource is required")
	}

	if req.Resource == "" {
		return errors.New("Resource is required")
	}

	return nil
}

func (req *AddASecondaryMetafieldToBeDeprecatedAPIReq) NewAPIResp() *AddASecondaryMetafieldToBeDeprecatedAPIResp {
	return &AddASecondaryMetafieldToBeDeprecatedAPIResp{}
}

type AddASecondaryMetafieldToBeDeprecatedAPIResp struct {
	client.BaseAPIResponse
	/*
	   metafield
	   Example: map[created_at:2022-12-28T09:39:35+00:00 description:My description id:1.2421341342134213e+17 key:key_123 namespace:namespace_123 owner_id:18024213413413412341234 owner_resource:variants type:single_line_text_field updated_at:2022-12-28T09:39:35+00:00 value:<nil>]
	*/
	Metafield Metafield `json:"metafield,omitempty" url:"-"`
}
