// Package metafield generated by SHOPLINE since v20260301
package metafield

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

type CreateAMetafieldDefinitionAPIReq struct {
	client.BaseAPIRequest
	/*
	   Metafield definition.
	   Example: map[access:map[admin:<nil>] description:This is the description for the Product Care Guide key:key_001 name:Product Care Guide namespace:my_fields owner_resource:products type:single_line_text_field]
	*/
	Definition CreateAMetafieldDefinitionAPIReqDefinition `json:"definition,omitempty" url:"-"`
}

type CreateAMetafieldDefinitionAPIReqDefinition struct {
	/*
	   The data type for the metafield definition. Valid values are:
	   - `single_line_text_field`: A single-line text field
	   - `list.single_line_text_field`: Multiple single-line text fields
	   - `multi_line_text_field`: Multi-line text field
	   - `color`: A single color
	   - `list.color`: Multiple colors
	   - `date`: A single date
	   - `list.date`: Multiple dates
	   - `date_time`: A single date and time. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).
	   - `list.date_time`: Multiple dates and times. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).
	   - `url`: A single URL
	   - `list.url`: Multiple URLs
	   - `file_reference`: A single file. Support a PDF or image file within 10 MB. Supported image formats: JPG, JPEG, PNG, and GIF.
	   - `list.file_reference`: Multiple files. Support PDF or image files and each file must be within 10 MB. Supported image formats: JPG, JPEG, PNG, and GIF.
	   - `json`: JSON
	   - `weight`: A single weight with a unit
	   - `list.weight`: Multiple weights with units
	   - `volume`: A single volume with a unit
	   - `list.volume`: Multiple volumes with units
	   - `dimension`: A single size with a unit
	   - `list.dimension`: Multiple sizes with units
	   - `number_integer`: A single integer
	   - `list.number_integer`: Multiple integers
	   - `number_decimal`: A single decimal
	   - `list.number_decimal`: Multiple decimals
	   - `rating`: A single rating
	   - `list.rating`: Multiple ratings
	   - `page_reference`: A single page
	   - `list.page_reference`: Multiple pages
	   - `product_reference`: A single product
	   - `list.product_reference`: Multiple products
	   - `variant_reference`: A single product variant
	   - `list.variant_reference`: Multiple product variants
	   - `collection_reference`: A single product collection
	   - `list.collection_reference`: Multiple product collections
	   - `customer_reference`: A single customer
	   - `list.customer_reference`: Multiple customers
	   - `order_reference`: A single order
	   - `list.order_reference`: Multiple orders
	   - `boolean`: Boolean type. Valid values are `true` and `false`.
	   - `money`: Amount with a currency

	   For more information about metafields, refer to  [Guide to Using Metafields Feature](https://help.shopline.com/hc/en-001/articles/7095355017113).
	   Example: single_line_text_field
	*/
	Type string `json:"type,omitempty" url:"-"`

	/*
	   Permission information for the metafield definition.
	   Example: map[admin:<nil>]
	*/
	Access Access `json:"access,omitempty" url:"-"`

	/*
	   The description of the metafield definition.
	   Example: This is the description for the Product Care Guide
	*/
	Description string `json:"description,omitempty" url:"-"`

	/*
	   A unique identifier for a metafield definition within its `namespace`.
	   Only letters, numbers, hyphens, and underscores are supported.
	   Minimum length: 3
	   Maximum length: 30
	   Example: key_001
	*/
	Key string `json:"key,omitempty" url:"-"`

	/*
	   The name of the metafield definition.

	   Maximum length: 255

	   Example: Product Care Guide
	*/
	Name string `json:"name,omitempty" url:"-"`

	/*
	   The namespace of the metafield definition. A metafield definition can be uniquely identified by its `key` and `namespace`.
	   Only letters, numbers, hyphens, and underscores are supported.
	   Minimum length: 2
	   Maximum length: 50

	   :::tip
	   **TIP**: When `access.admin` is provided, the `namespace` parameter must use the `$app:{namespace}` format.
	   :::

	   Example: my_fields
	*/
	Namespace string `json:"namespace,omitempty" url:"-"`

	/*
	   The type of the resource to which the metafield definition belongs. Valid values are:
	   - `products`: products
	   - `variants`: product variants
	   - `collections`: product collections
	   - `customers`: customers
	   - `orders`: orders
	   - `pages`: pages
	   - `blogs`: blogs collections
	   - `articles`: blogs
	   - `shop`: store
	   Example: products
	*/
	OwnerResource string `json:"owner_resource,omitempty" url:"-"`
}

type Access struct {
	/*
	   The access permission for the metafield definition. Valid values are:
	   - `MERCHANT_READ_WRITE`: Merchants can read and write.
	   - `MERCHANT_READ`: Merchants have read-only access.
	   - `PUBLIC_READ`: The public has read-only access.
	   - `PRIVATE`: Accessible only to the current app.
	   - `NONE`: No explicit permission set.

	   :::tip
	   **TIP**: When `namespace` uses the `$app:{namespace}` format, this value is valid and the default value is `PRIVATE`.
	   :::
	*/
	Admin string `json:"admin,omitempty" url:"-"`
}

func (req *CreateAMetafieldDefinitionAPIReq) GetEndpoint() string {

	return "metafield_definition.json"

}

func (req *CreateAMetafieldDefinitionAPIReq) GetMethod() string {
	return "POST"
}

func (req *CreateAMetafieldDefinitionAPIReq) GetData() interface{} {
	return req
}

// Verify the api request parameters
func (req *CreateAMetafieldDefinitionAPIReq) Verify() error {

	return nil
}

func (req *CreateAMetafieldDefinitionAPIReq) NewAPIResp() *CreateAMetafieldDefinitionAPIResp {
	return &CreateAMetafieldDefinitionAPIResp{}
}

type CreateAMetafieldDefinitionAPIResp struct {
	client.BaseAPIResponse
	/*
	   Metafield definition.
	   Example: map[access:map[admin:<nil>] created_at:<nil> description:<nil> id:<nil> key:<nil> name:<nil> namespace:<nil> owner_resource:<nil> type:<nil> updated_at:<nil>]
	*/
	Definition Definition `json:"definition,omitempty" url:"-"`
}

type Definition struct {
	/*
	   The name of the metafield definition.
	*/
	Name string `json:"name,omitempty" url:"-"`

	/*
	   The date and time when the metafield definition was updated. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).
	*/
	UpdatedAt string `json:"updated_at,omitempty" url:"-"`

	/*
	   The date and time when the metafield definition was created. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).
	*/
	CreatedAt string `json:"created_at,omitempty" url:"-"`

	/*
	   The ID of the metafield definition.
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   The namespace of the metafield definition.
	*/
	Namespace string `json:"namespace,omitempty" url:"-"`

	/*
	   The type of the resource to which the metafield definition belongs. Valid values are:
	   - `products`: products
	   - `variants`: product variants
	   - `collections`: product collections
	   - `customers`: customers
	   - `orders`: orders
	   - `pages`: pages
	   - `blogs`: blogs collections
	   - `articles`: blogs
	   - `shop`: store
	*/
	OwnerResource string `json:"owner_resource,omitempty" url:"-"`

	/*
	   The data type for the metafield definition. Valid values are:
	   - `single_line_text_field`: A single-line text field
	   - `list.single_line_text_field`: Multiple single-line text fields
	   - `multi_line_text_field`: Multi-line text field
	   - `color`: A single color
	   - `list.color`: Multiple colors
	   - `date`: A single date
	   - `list.date`: Multiple dates
	   - `date_time`: A single date and time. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).
	   - `list.date_time`: Multiple dates and times. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).
	   - `url`: A single URL
	   - `list.url`: Multiple URLs
	   - `file_reference`: A single file. Support a PDF or image file within 10 MB. Supported image formats: JPG, JPEG, PNG, and GIF.
	   - `list.file_reference`: Multiple files. Support PDF or image files and each file must be within 10 MB. Supported image formats: JPG, JPEG, PNG, and GIF.
	   - `json`: JSON
	   - `weight`: A single weight with a unit
	   - `list.weight`: Multiple weights with units
	   - `volume`: A single volume with a unit
	   - `list.volume`: Multiple volumes with units
	   - `dimension`: A single size with a unit
	   - `list.dimension`: Multiple sizes with units
	   - `number_integer`: A single integer
	   - `list.number_integer`: Multiple integers
	   - `number_decimal`: A single decimal
	   - `list.number_decimal`: Multiple decimals
	   - `rating`: A single rating
	   - `list.rating`: Multiple ratings
	   - `page_reference`: A single page
	   - `list.page_reference`: Multiple pages
	   - `product_reference`: A single product
	   - `list.product_reference`: Multiple products
	   - `variant_reference`: A single product variant
	   - `list.variant_reference`: Multiple product variants
	   - `collection_reference`: A single product collection
	   - `list.collection_reference`: Multiple product collections
	   - `customer_reference`: A single customer
	   - `list.customer_reference`: Multiple customers
	   - `order_reference`: A single order
	   - `list.order_reference`: Multiple orders
	   - `boolean`: Boolean type. Valid values are `true` and `false`.
	   - `money`: Amount with a currency

	   For more information about metafields, refer to  [Guide to Using Metafields Feature](https://help.shopline.com/hc/en-001/articles/7095355017113).
	*/
	Type string `json:"type,omitempty" url:"-"`

	/*
	   Permission information for the metafield definition.
	   Example: map[admin:<nil>]
	*/
	Access Access `json:"access,omitempty" url:"-"`

	/*
	   The description of the metafield definition.
	*/
	Description string `json:"description,omitempty" url:"-"`

	/*
	   A unique identifier for a metafield definition within its `namespace`.
	*/
	Key string `json:"key,omitempty" url:"-"`
}
