// Package metafield generated by SHOPLINE since v20260301
package metafield

import (
	"errors"
	"fmt"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type GetAMetafieldToBeDeprecatedAPIReq struct {
	client.BaseAPIRequest
	/*
	   Metafield's id
	   Example: 398100698691
	*/
	Id string `url:"-" json:"-"` // Required
	/*
	   Secondary resource id
	   Example: 1802351351232521351351
	*/
	OwnerId string `url:"-" json:"-"` // Required
	/*
	   First class resource id
	   Example: 16024213413413412341234
	*/
	POwnerId string `url:"-" json:"-"` // Required
	/*
	   First class resources , like products
	   Example: products
	*/
	PResource string `url:"-" json:"-"` // Required
	/*
	   Secondary resources such as variants
	   Example: variants
	*/
	Resource string `url:"-" json:"-"` // Required
}

func (req *GetAMetafieldToBeDeprecatedAPIReq) GetEndpoint() string {

	return fmt.Sprintf("%s/%s/%s/%s/metafields/%s.json", req.Id, req.OwnerId, req.POwnerId, req.PResource, req.Resource)

}

func (req *GetAMetafieldToBeDeprecatedAPIReq) GetMethod() string {
	return "GET"
}

// Verify the api request parameters
func (req *GetAMetafieldToBeDeprecatedAPIReq) Verify() error {

	if req.Id == "" {
		return errors.New("Id is required")
	}

	if req.OwnerId == "" {
		return errors.New("OwnerId is required")
	}

	if req.POwnerId == "" {
		return errors.New("POwnerId is required")
	}

	if req.PResource == "" {
		return errors.New("PResource is required")
	}

	if req.Resource == "" {
		return errors.New("Resource is required")
	}

	return nil
}

func (req *GetAMetafieldToBeDeprecatedAPIReq) NewAPIResp() *GetAMetafieldToBeDeprecatedAPIResp {
	return &GetAMetafieldToBeDeprecatedAPIResp{}
}

type GetAMetafieldToBeDeprecatedAPIResp struct {
	client.BaseAPIResponse
	/*
	   metafield
	   Example: map[created_at:2022-12-28T09:48:09+00:00 description:desc id:3.98100698691e+11 key:key_123 namespace:namespace_123 owner_id:1802351351232521351351 owner_resource:variants type:single_line_text_field updated_at:2022-12-28T09:48:09+00:00 value:<nil>]
	*/
	Metafield Metafield `json:"metafield,omitempty" url:"-"`
}
