// Package metafield generated by SHOPLINE since v20260301
package metafield

import (
	"errors"
	"fmt"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type UpdateASecondaryMetafieldToBeDeprecatedAPIReq struct {
	client.BaseAPIRequest
	/*
	   Secondary resource id
	   Example: 1802351351232521351351
	*/
	OwnerId string `url:"-" json:"-"` // Required
	/*
	   First class resource id
	   Example: 16024213413413412341234
	*/
	POwnerId string `url:"-" json:"-"` // Required
	/*
	   First class resources , like products
	   Example: products
	*/
	PResource string `url:"-" json:"-"` // Required
	/*
	   Secondary resources such as variants
	   Example: variants
	*/
	Resource string `url:"-" json:"-"` // Required
	/*
	   Metafield's id
	   Example: 398100698691
	*/
	Id string `url:"-" json:"-"` // Required
	/*
	   metafield
	   Example: map[description:test id:3.98100698691e+11 type:single_line_text_field value:map[]]
	*/
	Metafield UpdateASecondaryMetafieldToBeDeprecatedAPIReqMetafield `json:"metafield,omitempty" url:"-"`
}

type UpdateASecondaryMetafieldToBeDeprecatedAPIReqMetafield struct {
	/*
	   Value , type relies on type , default each application dispenses 100 m storage space，the maximum input length for a single metafield is 500,000 characters.
	   Example: map[]
	*/
	Value Value `json:"value,omitempty" url:"-"`

	/*
	   Description
	   Example: test
	*/
	Description string `json:"description,omitempty" url:"-"`

	/*
	   Metafield's id
	   Example: 3.98100698691e+11
	*/
	Id int64 `json:"id,omitempty" url:"-"`

	/*
	   Value type , like single_line_text_field
	   Example: single_line_text_field
	*/
	Type string `json:"type,omitempty" url:"-"`
}

func (req *UpdateASecondaryMetafieldToBeDeprecatedAPIReq) GetEndpoint() string {

	return fmt.Sprintf("%s/%s/%s/%s/metafields/%s.json", req.OwnerId, req.POwnerId, req.PResource, req.Resource, req.Id)

}

func (req *UpdateASecondaryMetafieldToBeDeprecatedAPIReq) GetMethod() string {
	return "PUT"
}

func (req *UpdateASecondaryMetafieldToBeDeprecatedAPIReq) GetData() interface{} {
	return req
}

// Verify the api request parameters
func (req *UpdateASecondaryMetafieldToBeDeprecatedAPIReq) Verify() error {

	if req.OwnerId == "" {
		return errors.New("OwnerId is required")
	}

	if req.POwnerId == "" {
		return errors.New("POwnerId is required")
	}

	if req.PResource == "" {
		return errors.New("PResource is required")
	}

	if req.Resource == "" {
		return errors.New("Resource is required")
	}

	if req.Id == "" {
		return errors.New("Id is required")
	}

	return nil
}

func (req *UpdateASecondaryMetafieldToBeDeprecatedAPIReq) NewAPIResp() *UpdateASecondaryMetafieldToBeDeprecatedAPIResp {
	return &UpdateASecondaryMetafieldToBeDeprecatedAPIResp{}
}

type UpdateASecondaryMetafieldToBeDeprecatedAPIResp struct {
	client.BaseAPIResponse
	/*
	   metafield
	   Example: map[created_at:2022-12-28T09:48:09+00:00 description:update id:3.98100698691e+11 key:key_123 namespace:namespace_123 owner_id:1802351351232521351351 owner_resource:products type:single_line_text_field updated_at:2022-12-28T09:48:09+00:00 value:<nil>]
	*/
	Metafield Metafield `json:"metafield,omitempty" url:"-"`
}
