// Package product generated by SHOPLINE since v20251201
package product

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

type CreateManualCollectionAPIReq struct {
	client.BaseAPIRequest
	/*
	   Collection information
	   Example: map[banner:map[alt:This is a image alt. src:https://img.myshopline.com/image/official/e46e6189ed5641a3b179444cacdcdd2a.png] body_html:This is a description. collects:[map[product_id:16057850264845250791280282]] handle:spring-clothing image:map[alt:This is a image alt. src:https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png] path:/collections/spring published_scope:web sort_order:updated-desc title:spring clothing]
	*/
	CustomCollection CreateManualCollectionAPIReqCustomCollection `json:"custom_collection,omitempty" url:"-"`
}

type CreateManualCollectionAPIReqCustomCollection struct {
	/*
	   The title of collection.
	   Example: spring clothing
	*/
	Title string `json:"title,omitempty" url:"-"`

	/*
	   List of product relationships within the collection
	   Example: [map[product_id:16057850264845250791280282]]
	*/
	Collects []Collect `json:"collects,omitempty" url:"-"`

	/*
	   The handle of collection.
	   Example: spring-clothing
	*/
	Handle string `json:"handle,omitempty" url:"-"`

	/*
	   The relative path of the collection URL in the online store, max 512 characters.
	   Example: /collections/spring
	*/
	Path string `json:"path,omitempty" url:"-"`

	/*
	   The description of the collection.
	   Example: This is a description.
	*/
	BodyHtml string `json:"body_html,omitempty" url:"-"`

	/*
	   The banner image of the collection.
	   Example: map[alt:This is a image alt. src:https://img.myshopline.com/image/official/e46e6189ed5641a3b179444cacdcdd2a.png]
	*/
	Banner Banner `json:"banner,omitempty" url:"-"`

	/*
	   The image of collection.
	   Example: map[alt:This is a image alt. src:https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png]
	*/
	Image CreateManualCollectionAPIReqImage `json:"image,omitempty" url:"-"`

	/*
	   Set the sales channel , when the value is " web " , it means online stores
	   Example: web
	*/
	PublishedScope string `json:"published_scope,omitempty" url:"-"`

	/*
	   Specify the sorting order of products within the collection.

	   | value | description |
	   | --- | --- |
	   | best-selling | Sorted by best-selling products. |
	   | alpha-asc | Sorted in ascending alphabetical order (A - Z).  |
	   | alpha-desc | Sorted in descending alphabetical order (Z - A).  |
	   | updated-desc | Sorted by update date in descending order (newest to oldest). |
	   | updated-asc | Sorted by update date in ascending order (oldest to newest). |
	   | manual | Sorted by the order manually set by the merchant.  |
	   Example: updated-desc
	*/
	SortOrder string `json:"sort_order,omitempty" url:"-"`
}

type Collect struct {
	/*
	   The ID of product.
	   Example: 16057850264845250791280282
	*/
	ProductId string `json:"product_id,omitempty" url:"-"`
}

type CreateManualCollectionAPIReqImage struct {
	/*
	   Words or phrases that share the characteristics or content of images.
	   Example: This is a image alt.
	*/
	Alt string `json:"alt,omitempty" url:"-"`

	/*
	   The image's location represented as a URL.
	   Example: https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png
	*/
	Src string `json:"src,omitempty" url:"-"`
}

func (req *CreateManualCollectionAPIReq) GetEndpoint() string {

	return "products/custom_collections.json"

}

func (req *CreateManualCollectionAPIReq) GetMethod() string {
	return "POST"
}

func (req *CreateManualCollectionAPIReq) GetData() interface{} {
	return req
}

// Verify the api request parameters
func (req *CreateManualCollectionAPIReq) Verify() error {

	return nil
}

func (req *CreateManualCollectionAPIReq) NewAPIResp() *CreateManualCollectionAPIResp {
	return &CreateManualCollectionAPIResp{}
}

type CreateManualCollectionAPIResp struct {
	client.BaseAPIResponse
	/*
	   Manually collection information
	   Example: map[banner:map[alt:This is a image alt src:https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png] body_html:This is a description created_at:2021-09-03T14:11:54+00:00 handle:spring-clothing id:12257170618007271602093384 image:map[alt:This is a image alt src:https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png] published_at:2021-09-03T14:11:54+00:00 published_scope:web sort_order:updated-desc template_path:templates/sortation/detail.json title:spring clothing updated_at:2021-09-03T14:11:54+00:00]
	*/
	CustomCollection CreateManualCollectionAPIRespCustomCollection `json:"custom_collection,omitempty" url:"-"`
}

type CreateManualCollectionAPIRespCustomCollection struct {
	/*
	   The title of collection.
	   Example: spring clothing
	*/
	Title string `json:"title,omitempty" url:"-"`

	/*
	   The description of the collection.
	   Example: This is a description
	*/
	BodyHtml string `json:"body_html,omitempty" url:"-"`

	/*
	   The image of collection.
	   Example: map[alt:This is a image alt src:https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png]
	*/
	Image CreateManualCollectionAPIRespImage `json:"image,omitempty" url:"-"`

	/*
	   Specify the sorting order of products within the collection.

	   | value | description |
	   | --- | --- |
	   | best-selling | Sorted by best-selling products. |
	   | alpha-asc | Sorted in ascending alphabetical order (A - Z).  |
	   | alpha-desc | Sorted in descending alphabetical order (Z - A).  |
	   | updated-desc | Sorted by update date in descending order (newest to oldest). |
	   | updated-asc | Sorted by update date in ascending order (oldest to newest). |
	   | manual | Sorted by the order manually set by the merchant.  |
	   Example: updated-desc
	*/
	SortOrder string `json:"sort_order,omitempty" url:"-"`

	/*
	   The template of theme.
	   Example: templates/sortation/detail.json
	*/
	TemplatePath string `json:"template_path,omitempty" url:"-"`

	/*
	   The handle of collection.
	   Example: spring-clothing
	*/
	Handle string `json:"handle,omitempty" url:"-"`

	/*
	   The ID of collection.
	   Example: 12257170618007271602093384
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   The banner image of the collection.
	   Example: map[alt:This is a image alt src:https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png]
	*/
	Banner Banner `json:"banner,omitempty" url:"-"`

	/*
	   The creation date and time of the collection.
	   Example: 2021-09-03T14:11:54+00:00
	*/
	CreatedAt string `json:"created_at,omitempty" url:"-"`

	/*
	   Time to post to online stores
	   Example: 2021-09-03T14:11:54+00:00
	*/
	PublishedAt string `json:"published_at,omitempty" url:"-"`

	/*
	   Set the sales channel , when the value is " web " , it means online stores
	   Example: web
	*/
	PublishedScope string `json:"published_scope,omitempty" url:"-"`

	/*
	   The last modified date and time of the collection.
	   Example: 2021-09-03T14:11:54+00:00
	*/
	UpdatedAt string `json:"updated_at,omitempty" url:"-"`
}

type CreateManualCollectionAPIRespImage struct {
	/*
	   Words or phrases that share the characteristics or content of images.
	   Example: This is a image alt
	*/
	Alt string `json:"alt,omitempty" url:"-"`

	/*
	   The image's location represented as a URL.
	   Example: https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png
	*/
	Src string `json:"src,omitempty" url:"-"`
}
