// Package product generated by SHOPLINE since v20251201
package product

import (
	"errors"
	"fmt"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type DeleteAProductImageAPIReq struct {
	client.BaseAPIRequest
	/*
	   The unique identifier for the product image.<br/>
	   Maximum length：64
	   Example: 5785060242207917075
	*/
	ImageId string `url:"-" json:"-"` // Required
	/*
	   The unique identifier for the product. <br/>
	   Maximum length：64
	   Example: 18057850264851626133510282
	*/
	ProductId string `url:"-" json:"-"` // Required
}

func (req *DeleteAProductImageAPIReq) GetEndpoint() string {

	return fmt.Sprintf("products/%s/images/%s.json", req.ImageId, req.ProductId)

}

func (req *DeleteAProductImageAPIReq) GetMethod() string {
	return "DELETE"
}

// Verify the api request parameters
func (req *DeleteAProductImageAPIReq) Verify() error {

	if req.ImageId == "" {
		return errors.New("ImageId is required")
	}

	if req.ProductId == "" {
		return errors.New("ProductId is required")
	}

	return nil
}

func (req *DeleteAProductImageAPIReq) GetRequestOptions() *client.RequestOptions {
	opts := &client.RequestOptions{
		NotDecodeBody: true,
	}
	return opts
}

func (req *DeleteAProductImageAPIReq) NewAPIResp() *DeleteAProductImageAPIResp {
	return &DeleteAProductImageAPIResp{}
}

type DeleteAProductImageAPIResp struct {
	client.BaseAPIResponse
}
