// Package product generated by SHOPLINE since v20251201
package product

import (
	"errors"
	"fmt"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type GetAnInventoryItemAPIReq struct {
	client.BaseAPIRequest
	/*
	   The unique identifier for the inventory item.<br/>
	   Maximum length：64
	   Example: 5703943240925324252
	*/
	InventoryItemId string `url:"-" json:"-"` // Required
}

func (req *GetAnInventoryItemAPIReq) GetEndpoint() string {

	return fmt.Sprintf("inventory_items/%s.json", req.InventoryItemId)

}

func (req *GetAnInventoryItemAPIReq) GetMethod() string {
	return "GET"
}

// Verify the api request parameters
func (req *GetAnInventoryItemAPIReq) Verify() error {

	if req.InventoryItemId == "" {
		return errors.New("InventoryItemId is required")
	}

	return nil
}

func (req *GetAnInventoryItemAPIReq) NewAPIResp() *GetAnInventoryItemAPIResp {
	return &GetAnInventoryItemAPIResp{}
}

type GetAnInventoryItemAPIResp struct {
	client.BaseAPIResponse
	/*
	   Inventory item information.
	   Example: map[cost:10.91 created_at:2022-12-06T20:23:06+08:00 id:5703943240925324252 required_shipping:<nil> sku:K00000000001 tracked:<nil> updated_at:2022-12-06T20:23:06+08:00 variant_id:18057039432358082693350282]
	*/
	InventoryItem GetAnInventoryItemAPIRespInventoryItem `json:"inventory_item,omitempty" url:"-"`
}

type GetAnInventoryItemAPIRespInventoryItem struct {
	/*
	   The unique identifier for the inventory item.
	   Example: 5703943240925324252
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   Indicates whether the variant is required to be shipped.
	   - `true`: Shipping is required.
	   - `false`: Shipping is not required.
	*/
	RequiredShipping bool `json:"required_shipping,omitempty" url:"-"`

	/*
	   The product SKU. It is distinct from `variant_id` returned by SHOPLINE.
	   Example: K00000000001
	*/
	Sku string `json:"sku,omitempty" url:"-"`

	/*
	   Indicates whether the inventory tracking is enabled.
	   - ` true`: Inventory tracking is enabled.
	   - ` false`: Inventory tracking is not enabled.
	*/
	Tracked bool `json:"tracked,omitempty" url:"-"`

	/*
	   The date and time when the inventory item was last updated. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).
	   Example: 2022-12-06T20:23:06+08:00
	*/
	UpdatedAt string `json:"updated_at,omitempty" url:"-"`

	/*
	   The unique identifier for the variant.
	   Example: 18057039432358082693350282
	*/
	VariantId string `json:"variant_id,omitempty" url:"-"`

	/*
	   The cost price of the variant. The value is rounded to two decimal places.
	   Example: 10.91
	*/
	Cost string `json:"cost,omitempty" url:"-"`

	/*
	   The date and time when the inventory item was created. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).
	   Example: 2022-12-06T20:23:06+08:00
	*/
	CreatedAt string `json:"created_at,omitempty" url:"-"`
}
