// Package product generated by SHOPLINE since v20251201
package product

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

type GetTheCountOfIntelligentCollectionsAPIReq struct {
	client.BaseAPIRequest
	/*
	   The unique identifier for the product. <br/>
	   Maximum length：64
	   Example: 16057850264845250791280282
	*/
	ProductId string `url:"product_id,omitempty" json:"-"`
	/*
	   The title of the collection.<br/>
	   Maximum length: 255
	   Example: This is a title
	*/
	Title string `url:"title,omitempty" json:"-"`
	/*
	   Specify the latest update time for the collection to be queried. Collections updated before this time will be returned. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).
	   Example: 2021-09-03T14:11:54+00:00
	*/
	UpdatedAtMax string `url:"updated_at_max,omitempty" json:"-"`
	/*
	   Specify the earliest update time for the collection to be queried. Collections updated on and after this time will be returned. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).
	   Example: 2021-09-02T14:11:54+00:00
	*/
	UpdatedAtMin string `url:"updated_at_min,omitempty" json:"-"`
}

func (req *GetTheCountOfIntelligentCollectionsAPIReq) GetEndpoint() string {

	return "products/smart_collections/count.json"

}

func (req *GetTheCountOfIntelligentCollectionsAPIReq) GetMethod() string {
	return "GET"
}

func (req *GetTheCountOfIntelligentCollectionsAPIReq) GetQuery() interface{} {
	return req
}

// Verify the api request parameters
func (req *GetTheCountOfIntelligentCollectionsAPIReq) Verify() error {

	return nil
}

func (req *GetTheCountOfIntelligentCollectionsAPIReq) NewAPIResp() *GetTheCountOfIntelligentCollectionsAPIResp {
	return &GetTheCountOfIntelligentCollectionsAPIResp{}
}

type GetTheCountOfIntelligentCollectionsAPIResp struct {
	client.BaseAPIResponse
	/*
	   The count of intelligent collections.
	   Example: 100
	*/
	Count int `json:"count,omitempty" url:"-"`
}
