// Package product generated by SHOPLINE since v20251201
package product

import (
	"errors"
	"fmt"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type GetProductsInACollectionAPIReq struct {
	client.BaseAPIRequest
	/*
	   Specify the fields to be returned, with multiple fields separated by commas. For available fields, refer to the top-level child parameters under the `products` object in the response.
	   Example: title,id
	*/
	Fields string `url:"fields,omitempty" json:"-"`
	/*
	   The quantity limit of products to be queried.
	   <br/>Value range: 1-250
	   <br/>Default Value: 50
	*/
	Limit string `url:"limit,omitempty" json:"-"`
	/*
	   The unique identifier for pagination queries, used to locate a specific page.

	   This parameter value is obtained from the `link` value in the response header of this API after you have queried the pagination information.

	   For example, if the `link` value you obtained is `<https://{handle}.myshopline.com/admin/openapi/{version}/products/collections/:collection_id/products.json?limit=1&page_info=eyJzaW5jZUlkIjoiMTYwNTc1OTAxNTM4OTA4Mjk1MjExMTI3ODgiLCJkaXJlY3Rpb24iOiJuZXh0IiwibGltaXQiOjF9>; rel="next"` , the value of `page_info` is `eyJzaW5jZUlkIjoiMTYwNTc1OTAxNTM4OTA4Mjk1MjExMTI3ODgiLCJkaXJlY3Rpb24iOiJuZXh0IiwibGltaXQiOjF9` .

	   For more information on how to use pagination, refer to [Paging Mechanism](/docs/apps/api-instructions-for-use/paging-mechanism).
	*/
	PageInfo string `url:"page_info,omitempty" json:"-"`
	/*
	   The unique identifier for the collection.
	   <br/>Maximum length: 64
	   Example: 16050375155238626683133099
	*/
	CollectionId string `url:"-" json:"-"` // Required
}

func (req *GetProductsInACollectionAPIReq) GetEndpoint() string {

	return fmt.Sprintf("products/collections/%s/products.json", req.CollectionId)

}

func (req *GetProductsInACollectionAPIReq) GetMethod() string {
	return "GET"
}

func (req *GetProductsInACollectionAPIReq) GetQuery() interface{} {
	return req
}

// Verify the api request parameters
func (req *GetProductsInACollectionAPIReq) Verify() error {

	if req.CollectionId == "" {
		return errors.New("CollectionId is required")
	}

	return nil
}

func (req *GetProductsInACollectionAPIReq) NewAPIResp() *GetProductsInACollectionAPIResp {
	return &GetProductsInACollectionAPIResp{}
}

type GetProductsInACollectionAPIResp struct {
	client.BaseAPIResponse
	/*
	   A list of products.
	   Example: [map[body_html:<nil> created_at:2025-03-06T02:20:26+08:00 handle:product-handle id:16057850264845250791280282 image:map[alt:This is an image alt. src:https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png] images:[map[alt:This is an image alt. src:https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png]] options:[map[id:16158068291703878544960282 name:Color product_id:16057850264845250791280282 values:[["red", "green", "white"]] values_images:map[red:https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png]]] path:/products/clothes product_behavior:RISK,HIDDEN product_type:<nil> published_at:2025-03-06T02:20:26+08:00 published_scope:<nil> spu:S0000001 status:<nil> subtitle:This is a subtitle tags:tag1, tag2 template_path:templates/product.product_template_name.json title:This is a Product title updated_at:2025-03-06T02:20:26+08:00 variants:[map[barcode:T0000001 compare_at_price:129.99 id:18057850264851626133510282 image:map[alt:This is an image alt. src:https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png] inventory_item_id:5785060242375689228 inventory_policy:<nil> inventory_quantity:99 inventory_tracker:<nil> option1:red option2:xl option3:cotton option4:short option5:casual position:1 price:90.22 product_id:16057850264845250791280282 required_shipping:<nil> sku:S000000001 taxable:<nil> title:red · xl weight:0.23 weight_unit:<nil>]] vendor:SHOPLINE]]
	*/
	Products []GetProductsInACollectionAPIRespProduct `json:"products,omitempty" url:"-"`
}

type GetProductsInACollectionAPIRespOption struct {
	/*
	   The unique identifier for the product corresponding to the option.
	   Example: 16057850264845250791280282
	*/
	ProductId string `json:"product_id,omitempty" url:"-"`

	/*
	   A list of option values.
	   Example: [["red", "green", "white"]]
	*/
	Values []string `json:"values,omitempty" url:"-"`

	/*
	   The mapping relationship between the option value and the corresponding image URL.
	   Example: map[red:https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png]
	*/
	ValuesImages map[string]string `json:"values_images,omitempty" url:"-"`

	/*
	   The unique identifier for the option.
	   Example: 16158068291703878544960282
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   The name of the option.
	   Example: Color
	*/
	Name string `json:"name,omitempty" url:"-"`
}

type GetProductsInACollectionAPIRespProduct struct {
	/*
	   The theme template of the product.
	   Example: templates/product.product_template_name.json
	*/
	TemplatePath string `json:"template_path,omitempty" url:"-"`

	/*
	   A list of product images.
	   Example: [map[alt:This is an image alt. src:https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png]]
	*/
	Images []GetProductsInACollectionAPIRespImage `json:"images,omitempty" url:"-"`

	/*
	   A list of product options.
	   Example: [map[id:16158068291703878544960282 name:Color product_id:16057850264845250791280282 values:[["red", "green", "white"]] values_images:map[red:https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png]]]
	*/
	Options []GetProductsInACollectionAPIRespOption `json:"options,omitempty" url:"-"`

	/*
	   The relative path of the product page.
	   Example: /products/clothes
	*/
	Path string `json:"path,omitempty" url:"-"`

	/*
	   Used to identify the special behavior of the product. This field returns a value only under certain conditions.

	   For example, if the product has potential risks, the field returns a value.
	   Example: RISK,HIDDEN
	*/
	ProductBehavior string `json:"product_behavior,omitempty" url:"-"`

	/*
	   The title of the product.
	   Example: This is a Product title
	*/
	Title string `json:"title,omitempty" url:"-"`

	/*
	   The date and time when the product was last updated. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).
	   Example: 2025-03-06T02:20:26+08:00
	*/
	UpdatedAt string `json:"updated_at,omitempty" url:"-"`

	/*
	   A list of product variants.
	   Example: [map[barcode:T0000001 compare_at_price:129.99 id:18057850264851626133510282 image:map[alt:This is an image alt. src:https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png] inventory_item_id:5785060242375689228 inventory_policy:<nil> inventory_quantity:99 inventory_tracker:<nil> option1:red option2:xl option3:cotton option4:short option5:casual position:1 price:90.22 product_id:16057850264845250791280282 required_shipping:<nil> sku:S000000001 taxable:<nil> title:red · xl weight:0.23 weight_unit:<nil>]]
	*/
	Variants []Variant `json:"variants,omitempty" url:"-"`

	/*
	   The product description.
	*/
	BodyHtml string `json:"body_html,omitempty" url:"-"`

	/*
	   The date and time when the product was created. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).
	   Example: 2025-03-06T02:20:26+08:00
	*/
	CreatedAt string `json:"created_at,omitempty" url:"-"`

	/*
	   The source of the product. Valid values are:
	   - `NORMAL` : products maintained in the SHOPLINE Admin
	   - `POD_TEMPORARY` : temporary products in the Product Option Customizer&ProductBundler app
	   - `TEMPORARY` : other temporary products
	*/
	ProductType string `json:"product_type,omitempty" url:"-"`

	/*
	   The date and time when the product was published to the online store. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).
	   Example: 2025-03-06T02:20:26+08:00
	*/
	PublishedAt string `json:"published_at,omitempty" url:"-"`

	/*
	   The published scope of product sales channels. The value of this field is fixed to `web`, indicating an online store.
	*/
	PublishedScope string `json:"published_scope,omitempty" url:"-"`

	/*
	   The status of the product. Valid values are:
	   - `active`: products on shelves
	   - `draft`: products off shelves
	   - `archived`: products archiving
	*/
	Status string `json:"status,omitempty" url:"-"`

	/*
	   A list of tags of the product.
	   Example: tag1, tag2
	*/
	Tags string `json:"tags,omitempty" url:"-"`

	/*
	   The brand or vendor of the product.
	   Example: SHOPLINE
	*/
	Vendor string `json:"vendor,omitempty" url:"-"`

	/*
	   The semantically unique identifier for the product,
	   which is generated based on `title` by default.
	   Example: product-handle
	*/
	Handle string `json:"handle,omitempty" url:"-"`

	/*
	   The unique identifier for the product.
	   Example: 16057850264845250791280282
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   The cover image of the product.
	   Example: map[alt:This is an image alt. src:https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png]
	*/
	Image GetProductsInACollectionAPIRespImage `json:"image,omitempty" url:"-"`

	/*
	   The identifier customized for the product by the merchant. It is distinct from `products.id` returned by SHOPLINE.
	   Example: S0000001
	*/
	Spu string `json:"spu,omitempty" url:"-"`

	/*
	   The subtitle of the product.
	   Example: This is a subtitle
	*/
	Subtitle string `json:"subtitle,omitempty" url:"-"`
}

type GetProductsInACollectionAPIRespImage struct {
	/*
	   The alternative textual description of the product image, usually a word or phrase with the characteristics or content of the image.
	   Example: This is an image alt.
	*/
	Alt string `json:"alt,omitempty" url:"-"`

	/*
	   The link to the product image, represented as a URL.
	   Example: https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png
	*/
	Src string `json:"src,omitempty" url:"-"`
}
