// Package product generated by SHOPLINE since v20251201
package product

import (
	"errors"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type GetInventoryQuantitiesAPIReq struct {
	client.BaseAPIRequest
	/*
	   The unique identifiers for inventory items to query, with multiple IDs separated by commas.
	   Example: 5703943240925324252,5703943989105270965
	*/
	InventoryItemIds string `url:"inventory_item_ids,omitempty" json:"-"` // Required
	/*
	   The unique identifiers for locations to query, with multiple IDs separated by commas.
	   Example: 7177011084762551696,5886279556961182184
	*/
	LocationIds string `url:"location_ids,omitempty" json:"-"`
}

func (req *GetInventoryQuantitiesAPIReq) GetEndpoint() string {

	return "inventory_levels.json"

}

func (req *GetInventoryQuantitiesAPIReq) GetMethod() string {
	return "GET"
}

func (req *GetInventoryQuantitiesAPIReq) GetQuery() interface{} {
	return req
}

// Verify the api request parameters
func (req *GetInventoryQuantitiesAPIReq) Verify() error {

	if req.InventoryItemIds == "" {
		return errors.New("InventoryItemIds is required")
	}

	return nil
}

func (req *GetInventoryQuantitiesAPIReq) NewAPIResp() *GetInventoryQuantitiesAPIResp {
	return &GetInventoryQuantitiesAPIResp{}
}

type GetInventoryQuantitiesAPIResp struct {
	client.BaseAPIResponse
	/*
	   A list of inventory information.
	   Example: [map[available:10 inventory_item_id:7177011084762551696 location_id:5421704248135526901 updated_at:2022-12-06T20:23:06+08:00 variant_id:18057039432358082693350282]]
	*/
	InventoryLevels []InventoryLevel `json:"inventory_levels,omitempty" url:"-"`
}
