// Package product generated by SHOPLINE since v20251201
package product

import (
	"errors"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type GetTaxonomyCollectionNodesAPIReq struct {
	client.BaseAPIRequest
	/*
	   The unique identifiers for products, with multiple IDs separated by commas.<br/>
	   Maximum size: 10
	   Example: 16057850264845250791280282,16057850264845250333280282
	*/
	ProductIds string `url:"product_ids,omitempty" json:"-"` // Required
}

func (req *GetTaxonomyCollectionNodesAPIReq) GetEndpoint() string {

	return "taxonomies/taxonomy_collections.json"

}

func (req *GetTaxonomyCollectionNodesAPIReq) GetMethod() string {
	return "GET"
}

func (req *GetTaxonomyCollectionNodesAPIReq) GetQuery() interface{} {
	return req
}

// Verify the api request parameters
func (req *GetTaxonomyCollectionNodesAPIReq) Verify() error {

	if req.ProductIds == "" {
		return errors.New("ProductIds is required")
	}

	return nil
}

func (req *GetTaxonomyCollectionNodesAPIReq) NewAPIResp() *GetTaxonomyCollectionNodesAPIResp {
	return &GetTaxonomyCollectionNodesAPIResp{}
}

type GetTaxonomyCollectionNodesAPIResp struct {
	client.BaseAPIResponse
	/*
	   A list of information about taxonomy collections.
	   Example: [map[product_id:16057850264845250791280282 taxonomy:map[collection_id:16050375155238626683133099 id:7004220176356349981 parent:map[collection_id:16050375155238626683133099 id:7004220176356349981 parent:map[collection_id:16050375155238626683133099 id:7004220176356349981 parent:map[collection_id:16050375155238626683133099 id:7004220176356349981 parent:map[collection_id:16050375155238626683133099 id:7004220176356349981 parent:map[collection_id:16050375155238626683133099 id:7004220176356349981 title:This is a collection title] title:This is a collection title] title:This is a collection title] title:This is a collection title] title:This is a collection title] title:This is a collection title]]]
	*/
	ProductsTaxonomies []ProductsTaxonomy `json:"products_taxonomies,omitempty" url:"-"`
}

type ProductsTaxonomy struct {
	/*
	   The unique identifier for the product.
	   Example: 16057850264845250791280282
	*/
	ProductId string `json:"product_id,omitempty" url:"-"`

	/*
	   Taxonomy collection node information.
	   Example: map[collection_id:16050375155238626683133099 id:7004220176356349981 parent:map[collection_id:16050375155238626683133099 id:7004220176356349981 parent:map[collection_id:16050375155238626683133099 id:7004220176356349981 parent:map[collection_id:16050375155238626683133099 id:7004220176356349981 parent:map[collection_id:16050375155238626683133099 id:7004220176356349981 parent:map[collection_id:16050375155238626683133099 id:7004220176356349981 title:This is a collection title] title:This is a collection title] title:This is a collection title] title:This is a collection title] title:This is a collection title] title:This is a collection title]
	*/
	Taxonomy GetTaxonomyCollectionNodesAPIRespTaxonomy `json:"taxonomy,omitempty" url:"-"`
}

type GetTaxonomyCollectionNodesAPIRespTaxonomy struct {
	/*
	   The unique identifier for the collection.
	   Example: 16050375155238626683133099
	*/
	CollectionId string `json:"collection_id,omitempty" url:"-"`

	/*
	   The unique identifier for the taxonomy collection node.
	   Example: 7004220176356349981
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   The parent node information.
	   Example: map[collection_id:16050375155238626683133099 id:7004220176356349981 parent:map[collection_id:16050375155238626683133099 id:7004220176356349981 parent:map[collection_id:16050375155238626683133099 id:7004220176356349981 parent:map[collection_id:16050375155238626683133099 id:7004220176356349981 parent:map[collection_id:16050375155238626683133099 id:7004220176356349981 title:This is a collection title] title:This is a collection title] title:This is a collection title] title:This is a collection title] title:This is a collection title]
	*/
	Parent *Parent `json:"parent,omitempty" url:"-"`

	/*
	   The title of the node, automatically inherited from the title of its associated collection.
	   Example: This is a collection title
	*/
	Title string `json:"title,omitempty" url:"-"`
}

type Parent struct {
	/*
	   The unique identifier for the collection.
	   Example: 16050375155238626683133099
	*/
	CollectionId string `json:"collection_id,omitempty" url:"-"`

	/*
	   The unique identifier for the taxonomy collection node.
	   Example: 7004220176356349981
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   The parent node information.
	   Example: map[collection_id:16050375155238626683133099 id:7004220176356349981 parent:map[collection_id:16050375155238626683133099 id:7004220176356349981 parent:map[collection_id:16050375155238626683133099 id:7004220176356349981 parent:map[collection_id:16050375155238626683133099 id:7004220176356349981 title:This is a collection title] title:This is a collection title] title:This is a collection title] title:This is a collection title]
	*/
	Parent *Parent `json:"parent,omitempty" url:"-"`

	/*
	   The title of the node, automatically inherited from the title of its associated collection.
	   Example: This is a collection title
	*/
	Title string `json:"title,omitempty" url:"-"`
}
