// Package product generated by SHOPLINE since v20251201
package product

import (
	"errors"
	"fmt"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type QueryManualCollectionAttributesByIdAPIReq struct {
	client.BaseAPIRequest
	/*
	   Manual collection ID
	   Example: 12257170618007271602093384
	*/
	CustomCollectionId string `url:"-" json:"-"` // Required
	/*
	   Return field , separated by ','
	   Example: title,handle
	*/
	Fields string `url:"fields,omitempty" json:"-"`
}

func (req *QueryManualCollectionAttributesByIdAPIReq) GetEndpoint() string {

	return fmt.Sprintf("products/custom_collections/%s.json", req.CustomCollectionId)

}

func (req *QueryManualCollectionAttributesByIdAPIReq) GetMethod() string {
	return "GET"
}

func (req *QueryManualCollectionAttributesByIdAPIReq) GetQuery() interface{} {
	return req
}

// Verify the api request parameters
func (req *QueryManualCollectionAttributesByIdAPIReq) Verify() error {

	if req.CustomCollectionId == "" {
		return errors.New("CustomCollectionId is required")
	}

	return nil
}

func (req *QueryManualCollectionAttributesByIdAPIReq) NewAPIResp() *QueryManualCollectionAttributesByIdAPIResp {
	return &QueryManualCollectionAttributesByIdAPIResp{}
}

type QueryManualCollectionAttributesByIdAPIResp struct {
	client.BaseAPIResponse
	/*
	   Manually collection information
	   Example: map[banner:map[alt:This is a image alt src:https://img.myshopline.com/image/official/e46e6189dd4641a3b179444cacdcdd2a.png] body_html:This is a description created_at:2021-09-03T14:11:54+00:00 handle:collection-handle id:12257170618007271602093384 image:map[alt:This is a image alt src:https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png] path:/collections/spring published_at:2021-09-03T14:11:54+00:00 published_scope:web sort_order:updated-asc template_path:templates/sortation/detail.json title:This is a title updated_at:2021-09-03T14:11:54+00:00]
	*/
	CustomCollection CustomCollection `json:"custom_collection,omitempty" url:"-"`
}

type CustomCollection struct {
	/*
	   Theme template
	   Example: templates/sortation/detail.json
	*/
	TemplatePath string `json:"template_path,omitempty" url:"-"`

	/*
	   Collection banner
	   Example: map[alt:This is a image alt src:https://img.myshopline.com/image/official/e46e6189dd4641a3b179444cacdcdd2a.png]
	*/
	Banner Banner `json:"banner,omitempty" url:"-"`

	/*
	   Collection images
	   Example: map[alt:This is a image alt src:https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png]
	*/
	Image QueryManualCollectionAttributesByIdAPIRespImage `json:"image,omitempty" url:"-"`

	/*
	   Set the sales channel , when the value is " web " , it means online stores
	   Example: web
	*/
	PublishedScope string `json:"published_scope,omitempty" url:"-"`

	/*
	   Collection description
	   Example: This is a description
	*/
	BodyHtml string `json:"body_html,omitempty" url:"-"`

	/*
	   The relative path of the product URL in the online store, max 512 characters.
	   Example: /collections/spring
	*/
	Path string `json:"path,omitempty" url:"-"`

	/*
	   Collection name
	   Example: This is a title
	*/
	Title string `json:"title,omitempty" url:"-"`

	/*
	   Update time
	   Example: 2021-09-03T14:11:54+00:00
	*/
	UpdatedAt string `json:"updated_at,omitempty" url:"-"`

	/*
	   Time to post to online stores
	   Example: 2021-09-03T14:11:54+00:00
	*/
	PublishedAt string `json:"published_at,omitempty" url:"-"`

	/*
	   Creation time
	   Example: 2021-09-03T14:11:54+00:00
	*/
	CreatedAt string `json:"created_at,omitempty" url:"-"`

	/*
	   Collection handle
	   Example: collection-handle
	*/
	Handle string `json:"handle,omitempty" url:"-"`

	/*
	   Collection id
	   Example: 12257170618007271602093384
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   Sort by , hot sale : best-selling , product name from a-z : alpha-asc , product name from z-a : alpha-desc , new update time → old : updated-desc ,Update time old → new : updated-asc , custom : manual
	   Example: updated-asc
	*/
	SortOrder string `json:"sort_order,omitempty" url:"-"`
}

type QueryManualCollectionAttributesByIdAPIRespImage struct {
	/*
	   Image src
	   Example: https://img.myshopline.com/image/official/e46e6189dd5641a3b179444cacdcdd2a.png
	*/
	Src string `json:"src,omitempty" url:"-"`

	/*
	   Image alt
	   Example: This is a image alt
	*/
	Alt string `json:"alt,omitempty" url:"-"`
}
