// Package product generated by SHOPLINE since v20251201
package product

import (
	"errors"
	"fmt"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type SpecifyVariantForPricingRulesAPIReq struct {
	client.BaseAPIRequest
	/*
	   The ID of company location catalog.
	   Example: 6598087148213149672
	*/
	CatalogId string `url:"-" json:"-"` // Required
	/*
	   The ID of the variant in the catalog.
	   Example: 18064649853096752677070520
	*/
	VariantId string `url:"-" json:"-"` // Required
}

func (req *SpecifyVariantForPricingRulesAPIReq) GetEndpoint() string {

	return fmt.Sprintf("company_location_catalog/%s/%s.json", req.CatalogId, req.VariantId)

}

func (req *SpecifyVariantForPricingRulesAPIReq) GetMethod() string {
	return "GET"
}

// Verify the api request parameters
func (req *SpecifyVariantForPricingRulesAPIReq) Verify() error {

	if req.CatalogId == "" {
		return errors.New("CatalogId is required")
	}

	if req.VariantId == "" {
		return errors.New("VariantId is required")
	}

	return nil
}

func (req *SpecifyVariantForPricingRulesAPIReq) NewAPIResp() *SpecifyVariantForPricingRulesAPIResp {
	return &SpecifyVariantForPricingRulesAPIResp{}
}

type SpecifyVariantForPricingRulesAPIResp struct {
	client.BaseAPIResponse
	/*
	   The adjustment value based on `percent_type`, formatted as a percentage.
	   - When decreasing the price, the value is limited to 0-100.
	   - When increasing the price, the value is limited to 0-10,000.
	   Example: 50
	*/
	Percent int `json:"percent,omitempty" url:"-"`

	/*
	   The type of percentage adjustment, with a value of `1` for decreasing the price and a value of `2` for increasing the price.
	   Example: 1
	*/
	PercentType int `json:"percent_type,omitempty" url:"-"`

	/*
	   Fixed price
	   Example: 100
	*/
	Price string `json:"price,omitempty" url:"-"`

	/*
	   The type of price adjustment, with a value of `1` for percentage and a value of `2` for fixed price (default).
	   Example: 1
	*/
	PriceAdjustmentMethod int `json:"price_adjustment_method,omitempty" url:"-"`

	/*
	   Gradient pricing list.
	   Example: [map[minimum_qty:2 percent:50 percent_type:1 price:100]]
	*/
	QuantityPriceBreaks []QuantityPriceBreak `json:"quantity_price_breaks,omitempty" url:"-"`

	/*
	   Rules for purchase quantity
	   Example: map[increment:2 maximum:8 minimum:2]
	*/
	QuantityRules QuantityRules `json:"quantity_rules,omitempty" url:"-"`

	/*
	   The ID of the variant in the catalog.
	   Example: 18064649853096752677070520
	*/
	VariantId string `json:"variant_id,omitempty" url:"-"`
}

type QuantityPriceBreak struct {
	/*
	   The adjustment value based on `percent_type`, formatted as a percentage.
	   - When decreasing the price, the value is limited to 0-100.
	   - When increasing the price, the value is limited to 0-10,000.
	   Example: 50
	*/
	Percent int `json:"percent,omitempty" url:"-"`

	/*
	   The type of percentage adjustment, with a value of `1` for decreasing the price and a value of `2` for increasing the price.
	   Example: 1
	*/
	PercentType int `json:"percent_type,omitempty" url:"-"`

	/*
	   Fixed price, valid only when `price_adjustment_method=2`.
	   Example: 100
	*/
	Price string `json:"price,omitempty" url:"-"`

	/*
	   Gradient-based minimum purchase quantity.
	   Example: 2
	*/
	MinimumQty int `json:"minimum_qty,omitempty" url:"-"`
}

type QuantityRules struct {
	/*
	   Maximum purchase quantity.
	   Example: 8
	*/
	Maximum int `json:"maximum,omitempty" url:"-"`

	/*
	   Minimum purchase quantity.
	   Example: 2
	*/
	Minimum int `json:"minimum,omitempty" url:"-"`

	/*
	   Purchase quantity increment where each increase must be a multiple of the increment.
	   Example: 2
	*/
	Increment int `json:"increment,omitempty" url:"-"`
}
