// Package order generated by SHOPLINE since v20260301
package order

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

type GetAnOrderCountAPIReq struct {
	client.BaseAPIRequest
	/*
	   Specify the start creation date and time for orders to query. Orders updated on and after this date are counted. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).
	   Example: 2024-08-31T02:20:26+08:00
	*/
	UpdatedAtMin string `url:"updated_at_min,omitempty" json:"-"`
	/*
	   Specify the cutoff creation date and time for orders to query. Orders created on and before this date are counted. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).
	   Example: 2024-08-31T02:20:26+08:00
	*/
	CreatedAtMax string `url:"created_at_max,omitempty" json:"-"`
	/*
	   Specify the start creation date and time for orders to query. Orders created on and after this date are counted. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).
	   Example: 2024-08-31T02:20:26+08:00
	*/
	CreatedAtMin string `url:"created_at_min,omitempty" json:"-"`
	/*
	   The payment status of the order. Valid values are:
	   - `unpaid`: Order not paid
	   - `authorized`: Order payment has been authorized
	   - `pending`: Order payment in progress
	   - `partially_paid`: Order partially paid
	   - `paid`: Order paid
	   - `partially_refunded`: Order partially refunded
	   - `refunded`: Order refunded
	   - `any`: Contains all statuses

	   Default value: `any`
	*/
	FinancialStatus string `url:"financial_status,omitempty" json:"-"`
	/*
	   The fulfillment status of the order. Valid values are:
	   - `unshipped`: Not shipped
	   - `partial`: Partially shipped
	   - `shipped`: Shipped
	   - `any`: All fulfillment statuses

	   Default value: `any`
	*/
	FulfillmentStatus string `url:"fulfillment_status,omitempty" json:"-"`
	/*
	   Location ID.
	*/
	LocationId string `url:"location_id,omitempty" json:"-"`
	/*
	   Sales channel. Valid values are:
	   - `oneshop`: One-page store
	   - `web`: Online store
	   - `mc`: Message center
	   - `live`: Live shopping
	   - `post`: Post shopping
	   - `shopee`: Shopee
	   - `lazada`: Lazada
	   - `buy_button`: Buy button app
	   - `pos`: POS
	   - `any`: Contains all sales channels

	   Default value: `any`
	*/
	OrderSource string `url:"order_source,omitempty" json:"-"`
	/*
	   Order status. Valid values are:
	   - `open`: Order in process
	   - `cancelled`: Order canceled
	   - `hidden`: Order archived
	   - `any`: Contains all statuses

	   Default value: `any`
	*/
	Status string `url:"status,omitempty" json:"-"`
	/*
	   Specify the cutoff creation date and time for orders to query. Orders updated on and before this date are counted. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).
	   Example: 2024-08-31T02:20:26+08:00
	*/
	UpdatedAtMax string `url:"updated_at_max,omitempty" json:"-"`
}

func (req *GetAnOrderCountAPIReq) GetEndpoint() string {

	return "orders/count.json"

}

func (req *GetAnOrderCountAPIReq) GetMethod() string {
	return "GET"
}

func (req *GetAnOrderCountAPIReq) GetQuery() interface{} {
	return req
}

// Verify the api request parameters
func (req *GetAnOrderCountAPIReq) Verify() error {

	return nil
}

func (req *GetAnOrderCountAPIReq) NewAPIResp() *GetAnOrderCountAPIResp {
	return &GetAnOrderCountAPIResp{}
}

type GetAnOrderCountAPIResp struct {
	client.BaseAPIResponse
	/*
	   Order count based on the query parameters.
	*/
	Count int64 `json:"count,omitempty" url:"-"`
}
