// Package order generated by SHOPLINE since v20251201
package order

import (
	"errors"
	"fmt"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type CancelSubscriptionContractAPIReq struct {
	client.BaseAPIRequest
	/*
	   Subscription contract number
	   Example: 3005605174257397540869
	*/
	Id string `url:"-" json:"-"` // Required
}

func (req *CancelSubscriptionContractAPIReq) GetEndpoint() string {

	return fmt.Sprintf("subscription/%s/cancel.json", req.Id)

}

func (req *CancelSubscriptionContractAPIReq) GetMethod() string {
	return "POST"
}

// Verify the api request parameters
func (req *CancelSubscriptionContractAPIReq) Verify() error {

	if req.Id == "" {
		return errors.New("Id is required")
	}

	return nil
}

func (req *CancelSubscriptionContractAPIReq) GetRequestOptions() *client.RequestOptions {
	opts := &client.RequestOptions{
		NotDecodeBody: true,
	}
	return opts
}

func (req *CancelSubscriptionContractAPIReq) NewAPIResp() *CancelSubscriptionContractAPIResp {
	return &CancelSubscriptionContractAPIResp{}
}

type CancelSubscriptionContractAPIResp struct {
	client.BaseAPIResponse
}
