// Package order generated by SHOPLINE since v20251201
package order

import (
	"errors"
	"fmt"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type CreateYourOrderAsSoonAsYourSubscriptionContractIsCreatedAPIReq struct {
	client.BaseAPIRequest
	/*
	   Subscription contract number
	   Example: 3005605174257397540869
	*/
	Id string `url:"-" json:"-"` // Required
}

func (req *CreateYourOrderAsSoonAsYourSubscriptionContractIsCreatedAPIReq) GetEndpoint() string {

	return fmt.Sprintf("subscription/%s/create_order.json", req.Id)

}

func (req *CreateYourOrderAsSoonAsYourSubscriptionContractIsCreatedAPIReq) GetMethod() string {
	return "POST"
}

// Verify the api request parameters
func (req *CreateYourOrderAsSoonAsYourSubscriptionContractIsCreatedAPIReq) Verify() error {

	if req.Id == "" {
		return errors.New("Id is required")
	}

	return nil
}

func (req *CreateYourOrderAsSoonAsYourSubscriptionContractIsCreatedAPIReq) GetRequestOptions() *client.RequestOptions {
	opts := &client.RequestOptions{
		NotDecodeBody: true,
	}
	return opts
}

func (req *CreateYourOrderAsSoonAsYourSubscriptionContractIsCreatedAPIReq) NewAPIResp() *CreateYourOrderAsSoonAsYourSubscriptionContractIsCreatedAPIResp {
	return &CreateYourOrderAsSoonAsYourSubscriptionContractIsCreatedAPIResp{}
}

type CreateYourOrderAsSoonAsYourSubscriptionContractIsCreatedAPIResp struct {
	client.BaseAPIResponse
}
