// Package order generated by SHOPLINE since v20251201
package order

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

type CreateFulfillmentLocationAPIReq struct {
	client.BaseAPIRequest
	/*
	   Location information
	   Example: map[address1:126 York Street address2:Unit 42 city:Ottawa city_code:120100 country:Canada country_code:CA name:Ottawa Store phone:18883290139 phone_code:0010 province:Ontario province_code:2400011 zip:A1B 2C3]
	*/
	Location CreateFulfillmentLocationAPIReqLocation `json:"location,omitempty" url:"-"`
}

type CreateFulfillmentLocationAPIReqLocation struct {
	/*
	   Country
	   Example: Canada
	*/
	Country string `json:"country,omitempty" url:"-"`

	/*
	   Detailed address 1
	   Example: 126 York Street
	*/
	Address1 string `json:"address1,omitempty" url:"-"`

	/*
	   Phone number international district
	   Example: 0010
	*/
	PhoneCode string `json:"phone_code,omitempty" url:"-"`

	/*
	   Location name
	   Example: Ottawa Store
	*/
	Name string `json:"name,omitempty" url:"-"`

	/*
	   State / provincial encoding
	   Example: 2400011
	*/
	ProvinceCode string `json:"province_code,omitempty" url:"-"`

	/*
	   Detailed address 2, optional
	   Example: Unit 42
	*/
	Address2 string `json:"address2,omitempty" url:"-"`

	/*
	   City
	   Example: Ottawa
	*/
	City string `json:"city,omitempty" url:"-"`

	/*
	   Contact phone number
	   Example: 18883290139
	*/
	Phone string `json:"phone,omitempty" url:"-"`

	/*
	   City ​code
	   Example: 120100
	*/
	CityCode string `json:"city_code,omitempty" url:"-"`

	/*
	   State / province
	   Example: Ontario
	*/
	Province string `json:"province,omitempty" url:"-"`

	/*
	   Postal code
	   Example: A1B 2C3
	*/
	Zip string `json:"zip,omitempty" url:"-"`

	/*
	   Country encoding
	   Example: CA
	*/
	CountryCode string `json:"country_code,omitempty" url:"-"`
}

func (req *CreateFulfillmentLocationAPIReq) GetEndpoint() string {

	return "fulfillment_service_location/create.json"

}

func (req *CreateFulfillmentLocationAPIReq) GetMethod() string {
	return "POST"
}

func (req *CreateFulfillmentLocationAPIReq) GetData() interface{} {
	return req
}

// Verify the api request parameters
func (req *CreateFulfillmentLocationAPIReq) Verify() error {

	return nil
}

func (req *CreateFulfillmentLocationAPIReq) NewAPIResp() *CreateFulfillmentLocationAPIResp {
	return &CreateFulfillmentLocationAPIResp{}
}

type CreateFulfillmentLocationAPIResp struct {
	client.BaseAPIResponse
	/*
	   Location information
	   Example: map[active:true address1:126 York Street address2:Unit 42 city:Ottawa city_code:120100 country:Canada country_code:CA create_at:2021-08-16T08:27:57+00:00 id:5668167071852661850 is_default:true legacy:true name:Ottawa Store phone:18883290139 phone_code:0010 province:Ontario province_code:2400011 update_at:2021-08-16T08:27:57+00:00 zip:A1B 2C3]
	*/
	Location CreateFulfillmentLocationAPIRespLocation `json:"location,omitempty" url:"-"`
}

type CreateFulfillmentLocationAPIRespLocation struct {
	/*
	   Is a location for fulfillment service or not
	   Example: true
	*/
	Legacy bool `json:"legacy,omitempty" url:"-"`

	/*
	   Telephone number
	   Example: 18883290139
	*/
	Phone string `json:"phone,omitempty" url:"-"`

	/*
	   Province name
	   Example: Ontario
	*/
	Province string `json:"province,omitempty" url:"-"`

	/*
	   Detailed address 2, optional
	   Example: Unit 42
	*/
	Address2 string `json:"address2,omitempty" url:"-"`

	/*
	   Province code
	   Example: 2400011
	*/
	ProvinceCode string `json:"province_code,omitempty" url:"-"`

	/*
	   City name
	   Example: Ottawa
	*/
	City string `json:"city,omitempty" url:"-"`

	/*
	   Urban code
	   Example: 120100
	*/
	CityCode string `json:"city_code,omitempty" url:"-"`

	/*
	   Enable or not
	   Example: true
	*/
	Active bool `json:"active,omitempty" url:"-"`

	/*
	   Country Name
	   Example: Canada
	*/
	Country string `json:"country,omitempty" url:"-"`

	/*
	   National code
	   Example: CA
	*/
	CountryCode string `json:"country_code,omitempty" url:"-"`

	/*
	   Location id
	   Example: 5668167071852661850
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   Location name
	   Example: Ottawa Store
	*/
	Name string `json:"name,omitempty" url:"-"`

	/*
	   Postal code
	   Example: A1B 2C3
	*/
	Zip string `json:"zip,omitempty" url:"-"`

	/*
	   Location created time ( format see IOS8601 )
	   Example: 2021-08-16T08:27:57+00:00
	*/
	CreateAt string `json:"create_at,omitempty" url:"-"`

	/*
	   Default location or not
	   Example: true
	*/
	IsDefault bool `json:"is_default,omitempty" url:"-"`

	/*
	   Location created time ( format see IOS8601 )
	   Example: 2021-08-16T08:27:57+00:00
	*/
	UpdateAt string `json:"update_at,omitempty" url:"-"`

	/*
	   Phone number international district
	   Example: 0010
	*/
	PhoneCode string `json:"phone_code,omitempty" url:"-"`

	/*
	   Detailed address 1
	   Example: 126 York Street
	*/
	Address1 string `json:"address1,omitempty" url:"-"`
}
