// Package order generated by SHOPLINE since v20251201
package order

import (
	"errors"
	"fmt"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type QueryRiskFraudForOrderSpecifyAPIReq struct {
	client.BaseAPIRequest
	/*
	   Order id
	   Example: "21056863763067384710591058"
	*/
	OrderId string `url:"-" json:"-"` // Required
	/*
	   Risk id
	   Example: "2905687834858288060687"
	*/
	RiskId string `url:"-" json:"-"` // Required
}

func (req *QueryRiskFraudForOrderSpecifyAPIReq) GetEndpoint() string {

	return fmt.Sprintf("orders/v2/%s/risks/%s.json", req.OrderId, req.RiskId)

}

func (req *QueryRiskFraudForOrderSpecifyAPIReq) GetMethod() string {
	return "GET"
}

// Verify the api request parameters
func (req *QueryRiskFraudForOrderSpecifyAPIReq) Verify() error {

	if req.OrderId == "" {
		return errors.New("OrderId is required")
	}

	if req.RiskId == "" {
		return errors.New("RiskId is required")
	}

	return nil
}

func (req *QueryRiskFraudForOrderSpecifyAPIReq) NewAPIResp() *QueryRiskFraudForOrderSpecifyAPIResp {
	return &QueryRiskFraudForOrderSpecifyAPIResp{}
}

type QueryRiskFraudForOrderSpecifyAPIResp struct {
	client.BaseAPIResponse
	/*
	   Risk information
	   Example: map[cause_cancel:true checkout_id:"2405664692071577423882" display:true id:"2905664692071577423886" order_id:"21056646934598417162363882" recommendation:"cancel" risk_detail_msg_list:[map[message:"risk detail message" risk_detail_level:cancel]] score:"1.0" source:"External"]
	*/
	Risk Risk `json:"risk,omitempty" url:"-"`
}
