// Package order generated by SHOPLINE since v20251201
package order

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

type QueryReturnFulfillmentOrderAPIReq struct {
	client.BaseAPIRequest
	/*
	   Return id
	   Example:
	*/
	ReturnId string `url:"return_id,omitempty" json:"-"`
}

func (req *QueryReturnFulfillmentOrderAPIReq) GetEndpoint() string {

	return "return_fulfillment.json"

}

func (req *QueryReturnFulfillmentOrderAPIReq) GetMethod() string {
	return "GET"
}

func (req *QueryReturnFulfillmentOrderAPIReq) GetQuery() interface{} {
	return req
}

// Verify the api request parameters
func (req *QueryReturnFulfillmentOrderAPIReq) Verify() error {

	return nil
}

func (req *QueryReturnFulfillmentOrderAPIReq) NewAPIResp() *QueryReturnFulfillmentOrderAPIResp {
	return &QueryReturnFulfillmentOrderAPIResp{}
}

type QueryReturnFulfillmentOrderAPIResp struct {
	client.BaseAPIResponse
	/*
	   Return order
	   Example: [map[id:2605860580357012238342 order_id:21058605762597644309430942 return_id:SL201AS4571636204541382726 reverse_fulfillment_order_line_items:[map[fulfillable_quantity:1 fulfillment_line_item:map[line_item:map[attribute:Color-red , size-x fulfillable_quantity:1 fulfillment_service:Sf international fulfillment_status:fulfilled gift_card:true grams:1 id:405 image_url:https://image.shopline.com/abc.jpg name:It's good Product price:100.0 product_id:16056898121352174690861487 properties:[map[name:Text type:text urls:[https://image.shopline.com] value:Freedom]] quantity:1 requires_shipping:true sku:SKU1234 tags:sales taxable:true title:It's good Product variant_id:18056898121355865678441487 variant_title:L/Red vendor:product supplier] quantity:0] id:RDP5860580372212396041 return_reason:NOT_AS_DESCRIBED return_reason_note:Product does not match the description total_quantity:1]] status:OPEN third_party_confirmation:success]]
	*/
	OrderReturnFulfillmentList []OrderReturnFulfillmentList `json:"order_return_fulfillment_list,omitempty" url:"-"`
}

type QueryReturnFulfillmentOrderAPIRespReverseFulfillmentOrderLineItem struct {
	/*
	   Invoice Product line detail node
	   Example: map[line_item:map[attribute:Color-red , size-x fulfillable_quantity:1 fulfillment_service:Sf international fulfillment_status:fulfilled gift_card:true grams:1 id:405 image_url:https://image.shopline.com/abc.jpg name:It's good Product price:100.0 product_id:16056898121352174690861487 properties:[map[name:Text type:text urls:[https://image.shopline.com] value:Freedom]] quantity:1 requires_shipping:true sku:SKU1234 tags:sales taxable:true title:It's good Product variant_id:18056898121355865678441487 variant_title:L/Red vendor:product supplier] quantity:0]
	*/
	FulfillmentLineItem FulfillmentLineItem `json:"fulfillment_line_item,omitempty" url:"-"`

	/*
	   Return order Product line number
	   Example: RDP5860580372212396041
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   The return reasons for the product line: COLOR(Incorrect color), DEFECTIVE(Product is damaged or defective), NOT_AS_DESCRIBED(Product does not match the description), OTHER(Other reasons), SIZE_TOO_LARGE(Size is too large), SIZE_TOO_SMALL(Size is too small), STYLE(Issues with the style), UNWANTED(Customer changed their mind), WRONG_ITEM(Received the wrong item)
	   Example: NOT_AS_DESCRIBED
	*/
	ReturnReason string `json:"return_reason,omitempty" url:"-"`

	/*
	   Product line return reason detailed notes, maximum 128 characters supported
	   Example: Product does not match the description
	*/
	ReturnReasonNote string `json:"return_reason_note,omitempty" url:"-"`

	/*
	   Return item about the number of returns
	   Example: 1
	*/
	TotalQuantity int `json:"total_quantity,omitempty" url:"-"`

	/*
	   Return quantity of order
	   Example: 1
	*/
	FulfillableQuantity int `json:"fulfillable_quantity,omitempty" url:"-"`
}

type OrderReturnFulfillmentList struct {
	/*
	   Associated order number
	   Example: 21058605762597644309430942
	*/
	OrderId string `json:"order_id,omitempty" url:"-"`

	/*
	   Associated return id
	   Example: SL201AS4571636204541382726
	*/
	ReturnId string `json:"return_id,omitempty" url:"-"`

	/*
	   Return Product line information
	   Example: [map[fulfillable_quantity:1 fulfillment_line_item:map[line_item:map[attribute:Color-red , size-x fulfillable_quantity:1 fulfillment_service:Sf international fulfillment_status:fulfilled gift_card:true grams:1 id:405 image_url:https://image.shopline.com/abc.jpg name:It's good Product price:100.0 product_id:16056898121352174690861487 properties:[map[name:Text type:text urls:[https://image.shopline.com] value:Freedom]] quantity:1 requires_shipping:true sku:SKU1234 tags:sales taxable:true title:It's good Product variant_id:18056898121355865678441487 variant_title:L/Red vendor:product supplier] quantity:0] id:RDP5860580372212396041 return_reason:NOT_AS_DESCRIBED return_reason_note:Product does not match the description total_quantity:1]]
	*/
	ReverseFulfillmentOrderLineItems []QueryReturnFulfillmentOrderAPIRespReverseFulfillmentOrderLineItem `json:"reverse_fulfillment_order_line_items,omitempty" url:"-"`

	/*
	   Return item order status
	   Example: OPEN
	*/
	Status string `json:"status,omitempty" url:"-"`

	/*
	   Third party logistics carrier confirmation results
	   Example: success
	*/
	ThirdPartyConfirmation string `json:"third_party_confirmation,omitempty" url:"-"`

	/*
	   Unique business id
	   Example: 2605860580357012238342
	*/
	Id string `json:"id,omitempty" url:"-"`
}
