// Package order generated by SHOPLINE since v20251201
package order

import (
	"errors"
	"fmt"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type RemoveTheSpecifyOfTheOrderRiskFraudAPIReq struct {
	client.BaseAPIRequest
	/*
	   Order number
	   Example: "21056863763067384710591058"
	*/
	OrderId string `url:"-" json:"-"` // Required
	/*
	   Risk id
	   Example: "2905687834858288060687"
	*/
	RiskId string `url:"-" json:"-"` // Required
}

func (req *RemoveTheSpecifyOfTheOrderRiskFraudAPIReq) GetEndpoint() string {

	return fmt.Sprintf("orders/v2/%s/risks/%s.json", req.OrderId, req.RiskId)

}

func (req *RemoveTheSpecifyOfTheOrderRiskFraudAPIReq) GetMethod() string {
	return "DELETE"
}

// Verify the api request parameters
func (req *RemoveTheSpecifyOfTheOrderRiskFraudAPIReq) Verify() error {

	if req.OrderId == "" {
		return errors.New("OrderId is required")
	}

	if req.RiskId == "" {
		return errors.New("RiskId is required")
	}

	return nil
}

func (req *RemoveTheSpecifyOfTheOrderRiskFraudAPIReq) GetRequestOptions() *client.RequestOptions {
	opts := &client.RequestOptions{
		NotDecodeBody: true,
	}
	return opts
}

func (req *RemoveTheSpecifyOfTheOrderRiskFraudAPIReq) NewAPIResp() *RemoveTheSpecifyOfTheOrderRiskFraudAPIResp {
	return &RemoveTheSpecifyOfTheOrderRiskFraudAPIResp{}
}

type RemoveTheSpecifyOfTheOrderRiskFraudAPIResp struct {
	client.BaseAPIResponse
}
