// Package order generated by SHOPLINE since v20251201
package order

import (
	"errors"
	"fmt"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type UpdateOrderRiskFraudAPIReq struct {
	client.BaseAPIRequest
	/*
	   Order number
	   Example: "21056863763067384710591058"
	*/
	OrderId string `url:"-" json:"-"` // Required
	/*
	   Fraud risk id
	   Example: "2905687834858288060687"
	*/
	RiskId string `url:"-" json:"-"` // Required
	/*
	   Order risk information
	   Example: map[cause_cancel:true display:true recommendation:cancel risk_detail_msg_list:[map[message:risk detail message risk_detail_level:cancel]] score:0.9 source:External]
	*/
	Risk UpdateOrderRiskFraudAPIReqRisk `json:"risk,omitempty" url:"-"`
}

type UpdateOrderRiskFraudAPIReqRisk struct {
	/*
	   Source logo , fixed to : External- external
	   Example: External
	*/
	Source string `json:"source,omitempty" url:"-"`

	/*
	   Cancel order logo , true- cancel , false- do not cancel
	   Example: true
	*/
	CauseCancel bool `json:"cause_cancel,omitempty" url:"-"`

	/*
	   Show the logo on the detail page , true- display , false- not display or not
	   Example: true
	*/
	Display bool `json:"display,omitempty" url:"-"`

	/*
	   Fraud risk rating : cancel ( high risk ) 、investigate ( medium risk ) 、accept ( low risk )
	   Example: cancel
	*/
	Recommendation string `json:"recommendation,omitempty" url:"-"`

	/*
	   Fraud risk details node
	   Example: [map[message:risk detail message risk_detail_level:cancel]]
	*/
	RiskDetailMsgList []RiskDetailMsgList `json:"risk_detail_msg_list,omitempty" url:"-"`

	/*
	   Fraud risk score , 0.0-1.0 , 1 score the highest risk
	   Example: 0.9
	*/
	Score string `json:"score,omitempty" url:"-"`
}

func (req *UpdateOrderRiskFraudAPIReq) GetEndpoint() string {

	return fmt.Sprintf("orders/v2/%s/risks/%s.json", req.OrderId, req.RiskId)

}

func (req *UpdateOrderRiskFraudAPIReq) GetMethod() string {
	return "PUT"
}

func (req *UpdateOrderRiskFraudAPIReq) GetData() interface{} {
	return req
}

// Verify the api request parameters
func (req *UpdateOrderRiskFraudAPIReq) Verify() error {

	if req.OrderId == "" {
		return errors.New("OrderId is required")
	}

	if req.RiskId == "" {
		return errors.New("RiskId is required")
	}

	return nil
}

func (req *UpdateOrderRiskFraudAPIReq) NewAPIResp() *UpdateOrderRiskFraudAPIResp {
	return &UpdateOrderRiskFraudAPIResp{}
}

type UpdateOrderRiskFraudAPIResp struct {
	client.BaseAPIResponse
	/*
	   Risk fraud information
	   Example: map[cause_cancel:true checkout_id:"2405664692071577423882" display:true id:"2905664692071577423886" order_id:"21056646934598417162363882" recommendation:"cancel" risk_detail_msg_list:[map[message:"risk detail message" risk_detail_level:cancel]] score:"1.0" source:"External"]
	*/
	Risk Risk `json:"risk,omitempty" url:"-"`
}
