// Package customers generated by SHOPLINE since v20260301
package customers

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *CustomerDeleteEvent) GetSupportedTopic() string {
	return "customers/delete"
}

type CustomerDeleteEvent struct {
	client.WebhookEvent
	/*
	   User name
	   Example: Bob
	*/
	FirstName string `json:"first_name,omitempty" url:"-"`

	/*
	   Customer id
	   Example: 200463274
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   User last name
	   Example: James
	*/
	LastName string `json:"last_name,omitempty" url:"-"`

	/*
	   User nickname
	   Example: Bob James
	*/
	NickName string `json:"nick_name,omitempty" url:"-"`

	/*
	   Phone number
	   Example: 00174623747
	*/
	Phone string `json:"phone,omitempty" url:"-"`

	/*
	   Update time
	   Example: 2022-05-31T15:32:46+08:00
	*/
	UpdatedAt string `json:"updated_at,omitempty" url:"-"`

	/*
	   Mailbox
	   Example: gungcherny@gamil.com
	*/
	Email string `json:"email,omitempty" url:"-"`
}
