// Package saleschannels generated by SHOPLINE since v20251201
package saleschannels

import (
	"errors"
	"fmt"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type RemoveCollectionFromSalesChannelsAPIReq struct {
	client.BaseAPIRequest
	/*
	   Collection id
	   Example: 12248721639068681442230282
	*/
	CollectionListingId string `url:"-" json:"-"` // Required
}

func (req *RemoveCollectionFromSalesChannelsAPIReq) GetEndpoint() string {

	return fmt.Sprintf("collection_listings/%s.json", req.CollectionListingId)

}

func (req *RemoveCollectionFromSalesChannelsAPIReq) GetMethod() string {
	return "DELETE"
}

// Verify the api request parameters
func (req *RemoveCollectionFromSalesChannelsAPIReq) Verify() error {

	if req.CollectionListingId == "" {
		return errors.New("CollectionListingId is required")
	}

	return nil
}

func (req *RemoveCollectionFromSalesChannelsAPIReq) GetRequestOptions() *client.RequestOptions {
	opts := &client.RequestOptions{
		NotDecodeBody: true,
	}
	return opts
}

func (req *RemoveCollectionFromSalesChannelsAPIReq) NewAPIResp() *RemoveCollectionFromSalesChannelsAPIResp {
	return &RemoveCollectionFromSalesChannelsAPIResp{}
}

type RemoveCollectionFromSalesChannelsAPIResp struct {
	client.BaseAPIResponse
}
