// Package store generated by SHOPLINE since v20260301
package store

import (
	"errors"
	"fmt"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type GetAStaffMemberAPIReq struct {
	client.BaseAPIRequest
	/*
	   Staff member UID.
	*/
	Uid string `url:"-" json:"-"` // Required
}

func (req *GetAStaffMemberAPIReq) GetEndpoint() string {

	return fmt.Sprintf("store/staff/%s.json", req.Uid)

}

func (req *GetAStaffMemberAPIReq) GetMethod() string {
	return "GET"
}

// Verify the api request parameters
func (req *GetAStaffMemberAPIReq) Verify() error {

	if req.Uid == "" {
		return errors.New("Uid is required")
	}

	return nil
}

func (req *GetAStaffMemberAPIReq) NewAPIResp() *GetAStaffMemberAPIResp {
	return &GetAStaffMemberAPIResp{}
}

type GetAStaffMemberAPIResp struct {
	client.BaseAPIResponse
	/*
	   Response data.
	   Example: map[account_owner:<nil> email:<nil> name:<nil> phone:<nil> uid:<nil> user_type:<nil>]
	*/
	Data GetAStaffMemberAPIRespData `json:"data,omitempty" url:"-"`
}

type GetAStaffMemberAPIRespData struct {
	/*
	   Staff member phone number.
	*/
	Phone string `json:"phone,omitempty" url:"-"`

	/*
	   Staff member UID.
	*/
	Uid string `json:"uid,omitempty" url:"-"`

	/*
	   The staff member's permission to the SHOPLINE Admin. Valid values are:
	   - `regular`: The staff member has permission to access the SHOPLINE Admin.
	   - `noaccess`: The staff member without permission to access the SHOPLINE Admin.
	   - `unregistered`: The staff member has been invited to the SHOPLINE Admin but has not yet registered.
	   - `partner`: The staff member has been granted access to the SHOPLINE Admin after approval via the [Partner Portal](https://developer.myshopline.com/home/index).
	*/
	UserType string `json:"user_type,omitempty" url:"-"`

	/*
	   Whether the staff member is the owner of the store.
	   - `true`: The staff member is the store owner.
	   - `false`: The staff member is not the store owner.
	*/
	AccountOwner bool `json:"account_owner,omitempty" url:"-"`

	/*
	   Staff member email.
	*/
	Email string `json:"email,omitempty" url:"-"`

	/*
	   Staff member name.
	*/
	Name string `json:"name,omitempty" url:"-"`
}
