// Package store generated by SHOPLINE since v20260301
package store

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

type GetActiveStorePlansAPIReq struct {
	client.BaseAPIRequest
	/*
	   Whether the returned results should include trial-type plans. Plans have two types: trial plans and paid plans.
	   - `true`: Returns both trial and paid plans.
	   - `false`: Returns only paid plans, excluding trial plans.

	   <br></br>Default value: `false`
	   Example: true
	*/
	IncludeTrial bool `json:"include_trial,omitempty" url:"-"`
}

func (req *GetActiveStorePlansAPIReq) GetEndpoint() string {

	return "store/subscription"

}

func (req *GetActiveStorePlansAPIReq) GetMethod() string {
	return "GET"
}

func (req *GetActiveStorePlansAPIReq) GetData() interface{} {
	return req
}

// Verify the api request parameters
func (req *GetActiveStorePlansAPIReq) Verify() error {

	return nil
}

func (req *GetActiveStorePlansAPIReq) NewAPIResp() *GetActiveStorePlansAPIResp {
	return &GetActiveStorePlansAPIResp{}
}

type GetActiveStorePlansAPIResp struct {
	client.BaseAPIResponse
	/*
	   A list of store plan details.
	   Example: [map[auto_recurring:true billing_cycle:1year business_parameters:map[MCC_packageVersion:pe SLP:Premium] cancelled_at:1.689504361e+12 created_at:1.689504361e+12 enable:true end_at:1.689504361e+12 extend_peroid:6 grace_period:7 grace_period_end_at:1.692182769e+12 merchant_email:open001@shopline.com merchant_id:4.200320559e+09 next_recurring_at:1.692182769e+12 payment_method:CreditCard product_line:cn_monthly_standard product_name:map[en:Starter jp:スターター malay:Versi pertama zh-hans-cn:入门版 zh-hant-tw:入門版] remarks:<nil> start_at:1.689504369e+12 status:active store_handle:<nil> store_id:1.666942294702e+12 sub_id:SUB6025977562148654208 type:trial]]
	*/
	Data []GetActiveStorePlansAPIRespData `json:"data,omitempty" url:"-"`

	/*
	   Response information.
	   :::danger{title="DEPRECATED"}
	   This parameter will be deprecated from version v20260301.
	   :::
	   Example: success
	*/
	Message string `json:"message,omitempty" url:"-"`
}

type GetActiveStorePlansAPIRespData struct {
	/*
	   The grace period of the plan subscription (in seconds). The grace period is the duration during which the plan remains usable after reaching the end time, before the store is suspended due to non-payment.
	   Example: 7
	*/
	GracePeriod int `json:"grace_period,omitempty" url:"-"`

	/*
	   The unique identifier for the merchant's registered account.
	   Example: 4.200320559e+09
	*/
	MerchantId int64 `json:"merchant_id,omitempty" url:"-"`

	/*
	   Remarks provided when the plan was activated.<br></br>
	   :::danger{title="DEPRECATED"}
	   This parameter will be deprecated from version v20260301.
	   :::
	*/
	Remarks string `json:"remarks,omitempty" url:"-"`

	/*
	   The billing cycle of the plan subscription.
	   - `1year`: Annual payment, the billing cycle is one year.
	   - `monthly`: Monthly payment, the billing cycle is one month.

	   Example: 1year
	*/
	BillingCycle string `json:"billing_cycle,omitempty" url:"-"`

	/*
	   The cancellation time of the plan subscription, formatted as a 13-digit millisecond timestamp.
	   :::danger{title="DEPRECATED"}
	   This parameter will be deprecated from version v20260301.
	   :::
	   Example: 1.689504361e+12
	*/
	CancelledAt int64 `json:"cancelled_at,omitempty" url:"-"`

	/*
	   The end time of the grace period, formatted as a 13-digit millisecond timestamp.
	   Example: 1.692182769e+12
	*/
	GracePeriodEndAt int64 `json:"grace_period_end_at,omitempty" url:"-"`

	/*
	   The payment method for the plan subscription.
	   - `CreditCard`: Credit card payment
	   - `UnionPayCard`: China UnionPay payment
	   - `PayPal`: PayPal payment
	   - `WeChat`: WeChat Pay
	   :::danger{title="Deprecated"}
	   This parameter will be deprecated from version v20260301.
	   :::
	   Example: CreditCard
	*/
	PaymentMethod string `json:"payment_method,omitempty" url:"-"`

	/*
	   The unique identifier for the store plan. Available plans may vary by region. Plans prefixed with global_ (e.g., `global_standard`) are applicable to merchants in Singapore, Malaysia, and Thailand, while plans prefixed with cn_ (e.g., `cn_standard`) are applicable to merchants in all other regions outside the aforementioned areas.
	   - `enterprise`: Enterprise.
	   - `global_lite`: Lite.
	   - `global_starter`: Starter.
	   - `global_essential`: Essential.
	   - `global_standard`: Standard.
	   - `global_premium`: Premium.
	   - `cn_lite`: Lite.
	   - `cn_monthly_standard`: Starter.
	   - `cn_basic`: Essential.
	   - `cn_standard`: Standard.
	   - `cn_plus`: Premium.
	   - `retail`: Retail.
	   - `devstore`: Development Store Plan.
	   - `sandbox_enterprise`: Sandbox Enterprise.
	   Example: cn_monthly_standard
	*/
	ProductLine string `json:"product_line,omitempty" url:"-"`

	/*
	   The start time of the plan subscription, formatted as a 13-digit millisecond timestamp.
	   Example: 1.689504369e+12
	*/
	StartAt int64 `json:"start_at,omitempty" url:"-"`

	/*
	   The store's unique identifier, which is the prefix of the store's domain name. For example, if a store's domain name is `open001.myshopline.com`, the store `handle` is `open001`.
	*/
	StoreHandle string `json:"store_handle,omitempty" url:"-"`

	/*
	   Whether the plan subscription has auto-renewal enabled.
	   - `true`: Auto-renewal is enabled for this plan subscription. The subscription will automatically renew upon expiration.
	   - `false`: Auto-renewal is not enabled for this plan subscription.
	   Example: true
	*/
	AutoRecurring bool `json:"auto_recurring,omitempty" url:"-"`

	/*
	   The creation time of the plan subscription, formatted as a 13-digit millisecond timestamp.
	   Example: 1.689504361e+12
	*/
	CreatedAt int64 `json:"created_at,omitempty" url:"-"`

	/*
	   Whether the plan subscription has been activated.

	   - `true`: Activated, meaning the store bound to the plan subscription has completed setup.
	   - `false`: Not activated, meaning the store bound to the plan subscription has not completed setup.
	   :::danger{title="Deprecated"}
	   This parameter will be deprecated from version v20260301.
	   :::

	   Example: true
	*/
	Enable bool `json:"enable,omitempty" url:"-"`

	/*
	   The next renewal time of the plan subscription, formatted as a 13-digit millisecond timestamp.
	   :::danger{title="Deprecated"}
	   This parameter will be deprecated from version v20260301.
	   :::
	   Example: 1.692182769e+12
	*/
	NextRecurringAt int64 `json:"next_recurring_at,omitempty" url:"-"`

	/*
	   The type of the plan subscription.
	   - `trial`: Trial (current period). A trial-type plan.
	   - `paid`: Paid (current period). A paid-type plan that has entered its billing cycle.
	   - `preorder`: Paid (next period). A paid-type plan that has not yet entered its billing cycle.

	   Example: trial
	*/
	Type string `json:"type,omitempty" url:"-"`

	/*
	   Additional information about the plan.
	   Example: map[MCC_packageVersion:pe SLP:Premium]
	*/
	BusinessParameters map[string]string `json:"business_parameters,omitempty" url:"-"`

	/*
	   The complimentary duration of the plan subscription (in seconds).
	   Example: 6
	*/
	ExtendPeroid int `json:"extend_peroid,omitempty" url:"-"`

	/*
	   The merchant's email address.
	   Example: open001@shopline.com
	*/
	MerchantEmail string `json:"merchant_email,omitempty" url:"-"`

	/*
	   The name of the plan. Includes Simplified Chinese, English, Traditional Chinese, Malay, and Japanese.
	   Example: map[en:Starter jp:スターター malay:Versi pertama zh-hans-cn:入门版 zh-hant-tw:入門版]
	*/
	ProductName map[string]string `json:"product_name,omitempty" url:"-"`

	/*
	   The status of the plan subscription.
	   - `active`: Active. The plan subscription is currently in effect.
	   - `expired`: Expired. The plan subscription has reached its end time but is still within the grace period.
	   Example: active
	*/
	Status string `json:"status,omitempty" url:"-"`

	/*
	   Store ID.
	   Example: 1.666942294702e+12
	*/
	StoreId int64 `json:"store_id,omitempty" url:"-"`

	/*
	   The plan subscription ID, which can be used as a unique key.
	   Example: SUB6025977562148654208
	*/
	SubId string `json:"sub_id,omitempty" url:"-"`

	/*
	   The end time of the plan subscription, formatted as a 13-digit millisecond timestamp. This includes any complimentary duration but excludes the grace period.
	   Example: 1.689504361e+12
	*/
	EndAt int64 `json:"end_at,omitempty" url:"-"`
}
