// Package store generated by SHOPLINE since v20260301
package store

import (
	"errors"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type GetStoreOperationLogsAPIReq struct {
	client.BaseAPIRequest
	/*
	   Maximum number of operation logs to be returned in the query.
	   <br></br>Value range: 1-200
	   <br></br>Default value：`50`
	*/
	Limit string `url:"limit,omitempty" json:"-"`
	/*
	   The ID of a specific operation log. Start querying operation logs from this specified ID.
	*/
	SinceId string `url:"since_id,omitempty" json:"-"`
	/*
	   Resource type. For Example, If the operation relates to product management, corresponding `subject_type` will be `products`.
	*/
	SubjectType string `url:"subject_type,omitempty" json:"-"`
	/*
	   Event type. For example, If the operation relates to product creation, `subject_type` will be `products`, and `verb` will be `add_new_product`.
	*/
	Verb string `url:"verb,omitempty" json:"-"`
	/*
	   Specify the cutoff creation date and time for operation logs to query. Operation logs created on or before this date are returned. Format: [`ISO 8601`](https://en.wikipedia.org/wiki/ISO_8601).
	   <br></br>Example: `2023-04-12T22:59:52+08:00`.
	*/
	CreatedAtMax string `url:"created_at_max,omitempty" json:"-"` // Required
	/*
	   Specify the initial creation date and time for operation logs to query. Operation logs created on or after this date are returned. Format: [`ISO 8601`](https://en.wikipedia.org/wiki/ISO_8601).
	   <br></br>Example: `2023-04-12T22:59:52+08:00`.
	*/
	CreatedAtMin string `url:"created_at_min,omitempty" json:"-"` // Required
}

func (req *GetStoreOperationLogsAPIReq) GetEndpoint() string {

	return "store/operation_logs.json"

}

func (req *GetStoreOperationLogsAPIReq) GetMethod() string {
	return "GET"
}

func (req *GetStoreOperationLogsAPIReq) GetQuery() interface{} {
	return req
}

// Verify the api request parameters
func (req *GetStoreOperationLogsAPIReq) Verify() error {

	if req.CreatedAtMax == "" {
		return errors.New("CreatedAtMax is required")
	}

	if req.CreatedAtMin == "" {
		return errors.New("CreatedAtMin is required")
	}

	return nil
}

func (req *GetStoreOperationLogsAPIReq) NewAPIResp() *GetStoreOperationLogsAPIResp {
	return &GetStoreOperationLogsAPIResp{}
}

type GetStoreOperationLogsAPIResp struct {
	client.BaseAPIResponse
	/*
	   Response body.
	   Example: [map[author:<nil> created_at:<nil> detail:<nil> id:<nil> subject_id:<nil> subject_type:<nil> verb:<nil>]]
	*/
	Data []GetStoreOperationLogsAPIRespData `json:"data,omitempty" url:"-"`
}

type GetStoreOperationLogsAPIRespData struct {
	/*
	   The description of the operation.
	*/
	Detail string `json:"detail,omitempty" url:"-"`

	/*
	   The operation log ID.
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   Resource ID. For example, If `subject_type` returns `products`, the resource ID is the product's ID.
	*/
	SubjectId string `json:"subject_id,omitempty" url:"-"`

	/*
	   Resource type. For Example, If the operation relates to product management, corresponding `subject_type` will be `products`.
	*/
	SubjectType string `json:"subject_type,omitempty" url:"-"`

	/*
	   Event type. For example, If the operation relates to product creation, `subject_type` will be `products`, and `verb` will be `add_new_product`.
	*/
	Verb string `json:"verb,omitempty" url:"-"`

	/*
	   Operator.
	*/
	Author string `json:"author,omitempty" url:"-"`

	/*
	   The date and time when the operation occurred. Format: [`ISO 8601`](https://en.wikipedia.org/wiki/ISO_8601).
	   <br></br>Example: `2023-04-12T22:59:52+08:00`
	*/
	CreatedAt string `json:"created_at,omitempty" url:"-"`
}
