// Package payment generated by SHOPLINE since v20251201
package payment

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

type BalanceAPIReq struct {
	client.BaseAPIRequest
}

func (req *BalanceAPIReq) GetEndpoint() string {

	return "payments/store/balance.json"

}

func (req *BalanceAPIReq) GetMethod() string {
	return "GET"
}

// Verify the api request parameters
func (req *BalanceAPIReq) Verify() error {

	return nil
}

func (req *BalanceAPIReq) NewAPIResp() *BalanceAPIResp {
	return &BalanceAPIResp{}
}

type BalanceAPIResp struct {
	client.BaseAPIResponse
	/*
	   Account balance object
	   Example: [map[amount:12.34 currency:USD]]
	*/
	Balance []Balance `json:"balance,omitempty" url:"-"`
}

type Balance struct {
	/*
	   Current account balance, amount reserved for two decimal points
	   Example: 12.34
	*/
	Amount string `json:"amount,omitempty" url:"-"`

	/*
	   Account currency, follow ISO4217 specifications
	   Example: USD
	*/
	Currency string `json:"currency,omitempty" url:"-"`
}
