// Package bulkoperation generated by SHOPLINE since v20251201
package bulkoperation

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

type CreateAChangeTypeBulkTaskToBeDeprecatedAPIReq struct {
	client.BaseAPIRequest
	/*
	   The publicly accessible URL used to specify the file address for the mutation task. File format: [JSON Lines](https://jsonlines.org/).
	*/
	FileUrl string `json:"file_url,omitempty" url:"-"`

	/*
	   HTTP method.
	*/
	Method string `json:"method,omitempty" url:"-"`

	/*
	   Full URL for SHOPLINE Admin API bulk mutation.
	*/
	MutationPath string `json:"mutation_path,omitempty" url:"-"`
}

func (req *CreateAChangeTypeBulkTaskToBeDeprecatedAPIReq) GetEndpoint() string {

	return "bulk_operation_run_mutation.json"

}

func (req *CreateAChangeTypeBulkTaskToBeDeprecatedAPIReq) GetMethod() string {
	return "POST"
}

func (req *CreateAChangeTypeBulkTaskToBeDeprecatedAPIReq) GetData() interface{} {
	return req
}

// Verify the api request parameters
func (req *CreateAChangeTypeBulkTaskToBeDeprecatedAPIReq) Verify() error {

	return nil
}

func (req *CreateAChangeTypeBulkTaskToBeDeprecatedAPIReq) NewAPIResp() *CreateAChangeTypeBulkTaskToBeDeprecatedAPIResp {
	return &CreateAChangeTypeBulkTaskToBeDeprecatedAPIResp{}
}

type CreateAChangeTypeBulkTaskToBeDeprecatedAPIResp struct {
	client.BaseAPIResponse
	/*
	   The reason for the bulk task execution exception.
	*/
	Reason string `json:"reason,omitempty" url:"-"`

	/*
	   The status of the bulk task. Valid values are:

	   - `CANCELED`：Canceled
	   - `CANCELING`：Canceling
	   - `COMPLETED`：Completed
	   - `CREATED`：Created
	   - `EXPIRED`：Expired
	   - `FAILED`：Failed
	   - `RUNNING`：Running
	*/
	Status string `json:"status,omitempty" url:"-"`

	/*
	   The type of the bulk task. Valid values are:
	   - `QUERY`: Query operation
	   - `MUTATION`: Mutation operation, which refers to mutation operations executed through the [Bulk operation mutation (to be Deprecated)](https://developer.shopline.com/docs/admin-rest-api/bulk-operations/create-a-change-type-bulk-task-to-be-deprecated) API.
	   - `MUTATION_GENERAL`: Mutation operation
	*/
	Type string `json:"type,omitempty" url:"-"`

	/*
	   The date and time when the bulk task was completed. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).
	*/
	CompletedAt string `json:"completedAt,omitempty" url:"-"`

	/*
	   The count of the completed bulk operations.
	*/
	CompletedCount int `json:"completedCount,omitempty" url:"-"`

	/*
	   The error code of the bulk task. Valid values are:

	   - `ACCESS_DENIED`: No access permission
	   - `TIMEOUT`: Process timeout
	   - `NO_DATA`: No data found
	*/
	ErrorCode string `json:"errorCode,omitempty" url:"-"`

	/*
	   The expiration date and time of the bulk task. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).
	*/
	ExpiredAt string `json:"expiredAt,omitempty" url:"-"`

	/*
	   The ID of the bulk task.
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   The ID of the store.
	*/
	StoreId string `json:"storeId,omitempty" url:"-"`

	/*
	   A URL to a file containing all task processing results with an expiration time. Format: [JSON Lines](https://jsonlines.org).
	   Example: https://sl-private-oss.oss-accelerate.aliyuncs.com/task-jsonline/prod/1/9b0c0f04-53cb-4ae3-94db-79af6ec193bd.jsonl?Expires=1754059510
	*/
	Url string `json:"url,omitempty" url:"-"`

	/*
	   The date and time when the bulk task was created. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).
	   Example: 2023-04-06T10:48:29+08:00
	*/
	CreatedAt string `json:"createdAt,omitempty" url:"-"`

	/*
	   A URL to a file containing task processing results with an expiration time. Format: [JSON Lines](https://jsonlines.org).
	   When `status` is `COMPLETED`, this value is identical to the `url` value. For other statuses, it may contain partial processing results.

	   Example: https://sl-private-oss.oss-accelerate.aliyuncs.com/task-jsonline/prod/1/9b0c0f04-53cb-4ae3-94db-79af6ec193bd.jsonl?Expires=1754059510
	*/
	PartialDataUrl string `json:"partialDataUrl,omitempty" url:"-"`
}
