// Package saleschannels generated by SHOPLINE since v20251201
package saleschannels

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *ProductCollectionSoldChannelsRemovedEvent) GetSupportedTopic() string {
	return "collection_listings/remove"
}

type ProductCollectionSoldChannelsRemovedEvent struct {
	client.WebhookEvent
	/*
	   Category information
	   Example: map[collectoin_id:12248721639068681442230282]
	*/
	CollectionListing ProductCollectionSoldChannelsRemovedEventCollectionListing `json:"collection_listing,omitempty"`
}

type ProductCollectionSoldChannelsRemovedEventCollectionListing struct {
	/*
	   Classified id removed from listing
	   Example: 12248721639068681442230282
	*/
	CollectoinId string `json:"collectoin_id,omitempty"`
}
