// Package membersystem generated by SHOPLINE since v20251201
package membersystem

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *PaidMembershipUpdatesEvent) GetSupportedTopic() string {
	return "app_memberSystem_paidMembership/challenged"
}

type PaidMembershipUpdatesEvent struct {
	client.WebhookEvent
	/*
	   Update source

	   MANUALLY_UPDATE: manual adjustment by the merchant

	   CANCELLED: membership cancellation

	   EXPIRY: membership expiry

	   PAID: member paid to become a member

	   SWITCH: membership mechanism switch
	   Example: SWITCH
	*/
	UpdatedSource string `json:"updated_source,omitempty"`

	/*
	   Update type

	   INITIATION: Become a customer of your store

	   DOWNGRADE: Member downgrade

	   UPGRADE: Member upgrade

	   UPDATE: Level update

	   Example: UPDATE
	*/
	UpdatedType string `json:"updated_type,omitempty"`

	/*
	   Customer id
	   Example: 2404721679
	*/
	BuyerId string `json:"buyer_id,omitempty"`

	/*
	   The code of current paid membership of the customer.
	   Example: MLC6568224957444662294
	*/
	LevelCode string `json:"level_code,omitempty"`

	/*
	   The code of paid membership of the customer before update. If the customer was a non-member, the field will be null.
	   Example: MLC6568224957444662292
	*/
	LevelCodeBefore string `json:"level_code_before,omitempty"`

	/*
	   Remarks
	   Example: remark
	*/
	Remark string `json:"remark,omitempty"`

	/*
	   The expiry time of current paid membership of the customer.
	   Example: 1.769270399e+12
	*/
	LevelExpiryTime int64 `json:"level_expiry_time,omitempty"`

	/*
	   The name of current paid membership of the customer. Up to 25 characters.
	   Example: LEVEL_2
	*/
	LevelName string `json:"level_name,omitempty"`

	/*
	   The name of paid membership of the customer before update. Up to 25 characters. If the customer was a non-member, the field will be null.
	   Example: LEVEL_1
	*/
	LevelNameBefore string `json:"level_name_before,omitempty"`

	/*
	   The start time of current paid membership of the customer.
	   Example: 1.721750465e+12
	*/
	LevelUpdatedTime int64 `json:"level_updated_time,omitempty"`

	/*
	   store ID
	   Example: 1718263946864
	*/
	StoreId string `json:"store_id,omitempty"`
}
