// Package membersystem generated by SHOPLINE since v20251201
package membersystem

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *PointsUpdatedEvent) GetSupportedTopic() string {
	return "app_memberSystem_points/challenged"
}

type PointsUpdatedEvent struct {
	client.WebhookEvent
	/*
	   Time when the points updated this time expires. Relevant only when update_type = increase. This field is empty when the reward does not expire.
	   Example: 1.721829526566e+12
	*/
	PointsExpiryTime int64 `json:"points_expiry_time,omitempty"`

	/*
	   store ID
	   Example: 1718263946864
	*/
	StoreId string `json:"store_id,omitempty"`

	/*
	   Point update type.

	   DECREASE: Points decrease

	   INCREASE: Points increase
	   Example: DECREASE
	*/
	UpdateType string `json:"update_type,omitempty"`

	/*
	   Update time
	   Example: 1.721829526566e+12
	*/
	UpdatedAt int64 `json:"updated_at,omitempty"`

	/*
	   Points update scenario types.

	   SUCCESSFUL_REGISTRATION: Customers get points after registration.

	   LOGIN_SUCCESS: Customers get points after successful login.

	   CUSTOMERS_BIRTHDAY: Customers get points on their birthdays.

	   SUCCESSFUL_ORDERS: Customers get points after successfully placing orders.

	   EMAIL_SUBSCRIPTION: Customers get points by subscribing to their email addresses.

	   ENTER_PHONE: Customers get points by filling in their phone numbers.

	   ENTER_BIRTHDAY: Customers get points by filling in their birthdays.

	   SHARE_FB: Customers get points by sharing on Facebook.

	   FOLLOW_FB: Customers get points by following Facebook.

	   FOLLOW_INS: Customers get points by following Instagram.

	   DAILY_ATTENDANCE: Customers get points by signing in daily.

	   PRODUCT_REVIEWS: Customers get points by reviewing products.

	   TOP_REVIEWS: Customers get points by reviewing products selected as high-quality reviews.

	   LEVEL_MEM_BENEFITS: Level membership benefits get points.

	   PAID_MEM_BENEFITS: Paid membership benefits get points.

	   SUCCESSFUL_REFERRAL: Customers get points by successfully completing referrals.

	   MANUALLY_INCREASE: The merchant manually adds points to the customer.

	   CUSTOMER_IMPORT_INCREASE: The merchant manually imports customers to issue points to them.

	   CASHBACK: The customer uses points to get cashback and points are deducted.

	   REDEEM_COUPON_CODE: The customer uses points to redeem coupon codes and points are deducted.

	   REDEEM_COUPON: The customer uses points to redeem coupons and points are deducted.

	   REDEEM_FREE_SHIPPING: The customer uses points to redeem free shipping coupons and points are deducted.

	   REDEEM_PRODUCTS: The customer uses points to redeem products and points are deducted.

	   MANUALLY_DECREASE: The merchant manually deducts points for the customer.

	   CUSTOMER_IMPORT_DECREASE: The merchant manually imports customers to deduct points for them.

	   POS_DECREASE: POS deducts points.
	   Example: SUCCESSFUL_REGISTRATION
	*/
	UpdatedScene string `json:"updated_scene,omitempty"`

	/*
	   Number of points for this update
	   Example: 20
	*/
	UpdatedValue int64 `json:"updated_value,omitempty"`

	/*
	   Customer id
	   Example: 2404721679
	*/
	BuyerId string `json:"buyer_id,omitempty"`

	/*
	   Remaining available points
	   Example: 20
	*/
	PointsBalance int64 `json:"points_balance,omitempty"`
}
