// Package localization generated by SHOPLINE since v20251201
package localization

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

type QueryStoreTranslationDataInBulkAPIReq struct {
	client.BaseAPIRequest
	/*
	   Language used in the [market](https://help.shopline.com/hc/en-001/articles/12436136316313-Market-Management). <br></br>For example: `en`.
	   Example: en
	*/
	Locale string `json:"locale,omitempty" url:"-"`

	/*
	   A specific market for the store.
	   Example: 2805652120189036673434
	*/
	Market string `json:"market,omitempty" url:"-"`

	/*
	   Query outdated or up-to-date translation data. If the original content has been updated but the translation hasn't, the translation is marked as `outdated`.
	   - `true`: Query outdated translation data.
	   - `false`: Query up-to-date translation data.
	   Example: true
	*/
	Outdated bool `json:"outdated,omitempty" url:"-"`

	/*
	   List of store resource information.
	   Example: [map[resource_id:1636453548928 resource_type:PRODUCT]]
	*/
	ResourceList []QueryStoreTranslationDataInBulkAPIReqResourceList `json:"resource_list,omitempty" url:"-"`
}

type QueryStoreTranslationDataInBulkAPIReqResourceList struct {
	/*
	   The unique identifier for the resource. <br></br>For example, when `resource_type` is `PRODUCT`, this parameter value is the product ID.
	   Example: 1636453548928
	*/
	ResourceId string `json:"resource_id,omitempty" url:"-"`

	/*
	   The type of the resource. <br></br>Example: `PRODUCT`.
	   Example: PRODUCT
	*/
	ResourceType string `json:"resource_type,omitempty" url:"-"`
}

func (req *QueryStoreTranslationDataInBulkAPIReq) GetEndpoint() string {

	return "ugc/resources.json"

}

func (req *QueryStoreTranslationDataInBulkAPIReq) GetMethod() string {
	return "POST"
}

func (req *QueryStoreTranslationDataInBulkAPIReq) GetData() interface{} {
	return req
}

// Verify the api request parameters
func (req *QueryStoreTranslationDataInBulkAPIReq) Verify() error {

	return nil
}

func (req *QueryStoreTranslationDataInBulkAPIReq) NewAPIResp() *QueryStoreTranslationDataInBulkAPIResp {
	return &QueryStoreTranslationDataInBulkAPIResp{}
}

type QueryStoreTranslationDataInBulkAPIResp struct {
	client.BaseAPIResponse
	/*
	   Response data.
	   Example: map[resource_list:[map[content_list:[map[locale:en market:2805652120189036673434 outdated:false resource_content: resource_content_type: resource_field:title updated_at:2023-09-07T15:50:00Z]] default_content_list:[map[resource_content:Title content resource_content_type:STRING resource_field:title]] resource_id:1636453548928 resource_type:PRODUCT]]]
	*/
	Data QueryStoreTranslationDataInBulkAPIRespData `json:"data,omitempty" url:"-"`
}

type QueryStoreTranslationDataInBulkAPIRespResourceList struct {
	/*
	   List of translation corpus corresponding to the resource.
	   Example: [map[locale:en market:2805652120189036673434 outdated:false resource_content: resource_content_type: resource_field:title updated_at:2023-09-07T15:50:00Z]]
	*/
	ContentList []ContentList `json:"content_list,omitempty" url:"-"`

	/*
	   Original untranslated corpus content list.
	   Example: [map[resource_content:Title content resource_content_type:STRING resource_field:title]]
	*/
	DefaultContentList []DefaultContentList `json:"default_content_list,omitempty" url:"-"`

	/*
	   The identifier for resource object.
	   <br></br>Example: When `resource_type` is `PRODUCT`, it represents the product ID.
	   Example: 1636453548928
	*/
	ResourceId string `json:"resource_id,omitempty" url:"-"`

	/*
	   The type of the resource. <br></br>Example: `PRODUCT`.
	   Example: PRODUCT
	*/
	ResourceType string `json:"resource_type,omitempty" url:"-"`
}

type QueryStoreTranslationDataInBulkAPIRespData struct {
	/*
	   List of store resource information.
	   Example: [map[content_list:[map[locale:en market:2805652120189036673434 outdated:false resource_content: resource_content_type: resource_field:title updated_at:2023-09-07T15:50:00Z]] default_content_list:[map[resource_content:Title content resource_content_type:STRING resource_field:title]] resource_id:1636453548928 resource_type:PRODUCT]]
	*/
	ResourceList []QueryStoreTranslationDataInBulkAPIRespResourceList `json:"resource_list,omitempty" url:"-"`
}
