// Package product generated by SHOPLINE since v20260301
package product

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *CollectionRelationshipDeleteEvent) GetSupportedTopic() string {
	return "collect/delete"
}

type CollectionRelationshipDeleteEvent struct {
	client.WebhookEvent
	/*
	   Category id
	   Example: 12248721639068681442230282
	*/
	CollectionId string `json:"collection_id,omitempty" url:"-"`

	/*
	   Product ID
	   Example: 16057039432335097907370282
	*/
	ProductId string `json:"product_id,omitempty" url:"-"`
}
