// Package product generated by SHOPLINE since v20260301
package product

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *SalesPlanGroupUpdateEvent) GetSupportedTopic() string {
	return "sellingplan/update"
}

type SalesPlanGroupUpdateEvent struct {
	client.WebhookEvent
	/*
	   Sales channel id
	   Example: c41ac9e6736785502d2333d1b1153aca795075c4
	*/
	AppId string `json:"app_id,omitempty" url:"-"`

	/*
	   Description
	   Example: This is a description
	*/
	Description string `json:"description,omitempty" url:"-"`

	/*
	   Sales program group name
	   Example: Subscription plan group default name
	*/
	Name string `json:"name,omitempty" url:"-"`

	/*
	   List of sales program group options
	   Example: [["delivery every 1 months", "delivery every 2 months", "delivery every 3 months"]]
	*/
	Options []string `json:"options,omitempty" url:"-"`

	/*
	   List of variant IDs.
	   Example: [["18065954560435138250532015"]]
	*/
	ProductVariantIds []string `json:"product_variant_ids,omitempty" url:"-"`

	/*
	   Sales plan group id
	   Example: 14056200245844372441100009
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   Show the name to the seller
	   Example: Subscription plan group default name
	*/
	MerchantCode string `json:"merchant_code,omitempty" url:"-"`

	/*
	   Display location
	   Example: 1
	*/
	Position int `json:"position,omitempty" url:"-"`

	/*
	   Bangding id list for binding
	   Example: [["16057039432335097907370282"]]
	*/
	Products []string `json:"products,omitempty" url:"-"`

	/*
	   Sales program list
	   Example: []
	*/
	SellingPlans []SellingPlan `json:"selling_plans,omitempty" url:"-"`
}
