// Package transactions generated by SHOPLINE since v20251201
package transactions

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *CheckoutCreatedEvent) GetSupportedTopic() string {
	return "checkouts/create"
}

type CheckoutCreatedEventLineItem struct {
	/*
	   Wei or not for gift cards
	   Example: false
	*/
	GiftCard bool `json:"gift_card,omitempty"`

	/*
	   Rows price
	   Example: 0
	*/
	LinePrice float64 `json:"line_price,omitempty"`

	/*
	   Request shipping or not
	   Example: false
	*/
	RequiresShipping bool `json:"requires_shipping,omitempty"`

	/*
	   Product code barCode
	   Example:
	*/
	Sku string `json:"sku,omitempty"`

	/*
	   Current Product title
	   Example:
	*/
	PresentmentTitle string `json:"presentment_title,omitempty"`

	/*
	   Headline
	   Example:
	*/
	Title string `json:"title,omitempty"`

	/*
	   Tax or not？
	   Example: false
	*/
	Taxable bool `json:"taxable,omitempty"`

	/*
	   Discount for Product line level applications ;
	   Example: []
	*/
	AppliedDiscounts []AppliedDiscount `json:"applied_discounts,omitempty"`

	/*
	   Weight
	   Example: 0
	*/
	Grams float64 `json:"grams,omitempty"`

	/*
	   Product attributes
	   Example: []
	*/
	Properties []Property `json:"properties,omitempty"`

	/*
	   Product quantity
	   Example: 0
	*/
	Quantity int `json:"quantity,omitempty"`

	/*
	   User ID
	   Example:
	*/
	UserId string `json:"user_id,omitempty"`

	/*
	   Selling price
	   Example: 0
	*/
	Price float64 `json:"price,omitempty"`

	/*
	   Product serial number
	   Example:
	*/
	ProductId string `json:"product_id,omitempty"`

	/*
	   Tax information
	   Example: []
	*/
	TaxLines []TaxLine `json:"tax_lines,omitempty"`

	/*
	   Product SKU serial number
	   Example:
	*/
	VariantId string `json:"variant_id,omitempty"`

	/*
	   Product original price
	   Example: 0
	*/
	VariantPrice float64 `json:"variant_price,omitempty"`
}

type AppliedDiscount struct {
	/*
	   Discount type : discount code , automatic discount , manual discount
	   Example:
	*/
	ApplicationType string `json:"application_type,omitempty"`

	/*
	   explicit, ENTITLED
	   Example:
	*/
	TargetSelection string `json:"target_selection,omitempty"`

	/*
	   line_item
	   Example:
	*/
	TargetType string `json:"target_type,omitempty"`

	/*
	   Event title
	   Example:
	*/
	Title string `json:"title,omitempty"`

	/*
	   Discount value
	   Example:
	*/
	Value string `json:"value,omitempty"`

	/*
	   Fixed amount , percentage
	   Example:
	*/
	ValueType string `json:"value_type,omitempty"`

	/*
	   Discount amount
	   Example:
	*/
	Amount string `json:"amount,omitempty"`
}

type CheckoutCreatedEventDiscountCode struct {
	/*
	   Discount amount
	   Example: 0
	*/
	Amount float64 `json:"amount,omitempty"`

	/*
	   Discount name
	   Example:
	*/
	Title string `json:"title,omitempty"`

	/*
	   Discount type 1 = indicate price Discount
	   Example: 0
	*/
	Type int `json:"type,omitempty"`
}

type Addresses struct {
	/*
	   First name
	   Example:
	*/
	LastName string `json:"last_name,omitempty"`

	/*
	   Full name
	   Example:
	*/
	Name string `json:"name,omitempty"`

	/*
	   Province-coding
	   Example:
	*/
	ProvinceCode string `json:"province_code,omitempty"`

	/*
	   Postal code
	   Example:
	*/
	Zip string `json:"zip,omitempty"`

	/*
	   Address 2
	   Example:
	*/
	Address2 string `json:"address2,omitempty"`

	/*
	   Country code
	   Example:
	*/
	CountryCode string `json:"country_code,omitempty"`

	/*
	   Mobile phone number
	   Example:
	*/
	Phone string `json:"phone,omitempty"`

	/*
	   Province
	   Example:
	*/
	Province string `json:"province,omitempty"`

	/*
	   Address 1
	   Example:
	*/
	Address1 string `json:"address1,omitempty"`

	/*
	   City
	   Example:
	*/
	City string `json:"city,omitempty"`

	/*
	   Country
	   Example:
	*/
	Country string `json:"country,omitempty"`

	/*
	   Last name
	   Example:
	*/
	FirstName string `json:"first_name,omitempty"`
}

type NoteAttribute struct {
	/*
	   Name
	   Example:
	*/
	Name string `json:"name,omitempty"`

	/*
	   Value
	   Example:
	*/
	Value string `json:"value,omitempty"`
}

type TaxLine struct {
	/*
	   Tax price
	   Example: 0
	*/
	Price float64 `json:"price,omitempty"`

	/*
	   Tax number
	   Example:
	*/
	TaxNo string `json:"tax_no,omitempty"`

	/*
	   Tax name
	   Example:
	*/
	Title string `json:"title,omitempty"`

	/*
	   Express_tax shipping tax , product_tax merchandise tax
	   Example:
	*/
	Type string `json:"type,omitempty"`
}

type ShippingAddress struct {
	/*
	   Address 1
	   Example:
	*/
	Address1 string `json:"address1,omitempty"`

	/*
	   Address 2
	   Example:
	*/
	Address2 string `json:"address2,omitempty"`

	/*
	   Country
	   Example:
	*/
	Country string `json:"country,omitempty"`

	/*
	   Last name
	   Example:
	*/
	FirstName string `json:"first_name,omitempty"`

	/*
	   Full name
	   Example:
	*/
	Name string `json:"name,omitempty"`

	/*
	   Mobile phone number
	   Example:
	*/
	Phone string `json:"phone,omitempty"`

	/*
	   Province-coding
	   Example:
	*/
	ProvinceCode string `json:"province_code,omitempty"`

	/*
	   Postal code
	   Example:
	*/
	Zip string `json:"zip,omitempty"`

	/*
	   City
	   Example:
	*/
	City string `json:"city,omitempty"`

	/*
	   Country code
	   Example:
	*/
	CountryCode string `json:"country_code,omitempty"`

	/*
	   First name
	   Example:
	*/
	LastName string `json:"last_name,omitempty"`

	/*
	   Province
	   Example:
	*/
	Province string `json:"province,omitempty"`
}

type Customer struct {
	/*
	   First name
	   Example:
	*/
	LastName string `json:"last_name,omitempty"`

	/*
	   Mobile phone number
	   Example:
	*/
	Phone string `json:"phone,omitempty"`

	/*
	   Address information
	   Example: map[address1: address2: city: country: country_code: first_name: last_name: name: phone: province: province_code: zip:]
	*/
	Addresses Addresses `json:"addresses,omitempty"`

	/*
	   Full name
	   Example:
	*/
	Currency string `json:"currency,omitempty"`

	/*
	   Mailbox
	   Example:
	*/
	Email string `json:"email,omitempty"`

	/*
	   Last name
	   Example:
	*/
	FirstName string `json:"first_name,omitempty"`

	/*
	   Buyer ID
	   Example:
	*/
	Id string `json:"id,omitempty"`
}

type CheckoutCreatedEvent struct {
	client.WebhookEvent
	/*
	   Total tax amount
	   Example: 0
	*/
	TotalTax float64 `json:"total_tax,omitempty"`

	/*
	   Total weight
	   Example: 0
	*/
	TotalWeight float64 `json:"total_weight,omitempty"`

	/*
	   Update time
	   Example:
	*/
	UpdateAt string `json:"update_at,omitempty"`

	/*
	   Billing address information
	   Example: map[address1: address2: city: country: country_code: first_name: last_name: name: phone: province: province_code: zip:]
	*/
	BillingAddress BillingAddress `json:"billing_address,omitempty"`

	/*
	   Finish time
	   Example:
	*/
	CompletedAt string `json:"completed_at,omitempty"`

	/*
	   Name
	   Example:
	*/
	Name string `json:"name,omitempty"`

	/*
	   Notes
	   Example:
	*/
	Note string `json:"note,omitempty"`

	/*
	   Subscribe or not
	   Example: false
	*/
	BuyerAcceptsMarketing bool `json:"buyer_accepts_marketing,omitempty"`

	/*
	   Closed time
	   Example:
	*/
	ClosedAt string `json:"closed_at,omitempty"`

	/*
	   Additional information
	   Example: []
	*/
	NoteAttributes []NoteAttribute `json:"note_attributes,omitempty"`

	/*
	   Shipping information
	   Example: []
	*/
	ShippingLines []ShippingLine `json:"shipping_lines,omitempty"`

	/*
	   Total discount amount
	   Example: 0
	*/
	TotalDiscount float64 `json:"total_discount,omitempty"`

	/*
	   Total duty
	   Example:
	*/
	TotalDuties string `json:"total_duties,omitempty"`

	/*
	   checkout token
	   Example:
	*/
	Id string `json:"id,omitempty"`

	/*
	   Product information
	   Example: []
	*/
	LineItems []CheckoutCreatedEventLineItem `json:"line_items,omitempty"`

	/*
	   Discount information
	   Example: []
	*/
	DiscountCodes []CheckoutCreatedEventDiscountCode `json:"discount_codes,omitempty"`

	/*
	   Mobile phone number
	   Example:
	*/
	Phone string `json:"phone,omitempty"`

	/*
	   Shipping address
	   Example: map[address1: address2: city: country: country_code: first_name: last_name: name: phone: province: province_code: zip:]
	*/
	ShippingAddress ShippingAddress `json:"shipping_address,omitempty"`

	/*
	   checkout token
	   Example:
	*/
	Token string `json:"token,omitempty"`

	/*
	   Shopping cart token
	   Example:
	*/
	CartToken string `json:"cart_token,omitempty"`

	/*
	   Buyer information
	   Example: map[addresses:map[address1: address2: city: country: country_code: first_name: last_name: name: phone: province: province_code: zip:] currency: email: first_name: id: last_name: phone:]
	*/
	Customer Customer `json:"customer,omitempty"`

	/*
	   Current currency
	   Example:
	*/
	PresentmentCurrency string `json:"presentment_currency,omitempty"`

	/*
	   Total price
	   Example: 0
	*/
	TotalPrice float64 `json:"total_price,omitempty"`

	/*
	   Currency
	   Example:
	*/
	Currency string `json:"currency,omitempty"`

	/*
	   Sub total
	   Example: 0
	*/
	SubTotalPrice float64 `json:"sub_total_price,omitempty"`

	/*
	   Creation time
	   Example:
	*/
	CreatedAt string `json:"created_at,omitempty"`

	/*
	   Mailbox
	   Example:
	*/
	Email string `json:"email,omitempty"`

	/*
	   Cell phone no .
	   Example: 86
	*/
	PhoneAreaCode string `json:"phone_area_code,omitempty"`

	/*
	   User ID
	   Example:
	*/
	UserId string `json:"user_id,omitempty"`

	/*
	   Discard link
	   Example:
	*/
	AbandonedCheckoutUrl string `json:"abandoned_checkout_url,omitempty"`

	/*
	   Discount on other applications on single stage
	   Example: []
	*/
	AppliedDiscounts []AppliedDiscount `json:"applied_discounts,omitempty"`

	/*
	   Incl . or not
	   Example: false
	*/
	TaxesIncluded bool `json:"taxes_included,omitempty"`
}

type BillingAddress struct {
	/*
	   Address 2
	   Example:
	*/
	Address2 string `json:"address2,omitempty"`

	/*
	   City
	   Example:
	*/
	City string `json:"city,omitempty"`

	/*
	   Country
	   Example:
	*/
	Country string `json:"country,omitempty"`

	/*
	   Last name
	   Example:
	*/
	FirstName string `json:"first_name,omitempty"`

	/*
	   First name
	   Example:
	*/
	LastName string `json:"last_name,omitempty"`

	/*
	   Province
	   Example:
	*/
	Province string `json:"province,omitempty"`

	/*
	   Province-coding
	   Example:
	*/
	ProvinceCode string `json:"province_code,omitempty"`

	/*
	   Address 1
	   Example:
	*/
	Address1 string `json:"address1,omitempty"`

	/*
	   Country code
	   Example:
	*/
	CountryCode string `json:"country_code,omitempty"`

	/*
	   Full name
	   Example:
	*/
	Name string `json:"name,omitempty"`

	/*
	   Mobile phone number
	   Example:
	*/
	Phone string `json:"phone,omitempty"`

	/*
	   Postal code
	   Example:
	*/
	Zip string `json:"zip,omitempty"`
}

type ShippingLine struct {
	/*
	   Shipping method name
	   Example:
	*/
	DeliveryName string `json:"delivery_name,omitempty"`

	/*
	   Shipping method
	   Example:
	*/
	DeliverySeq string `json:"delivery_seq,omitempty"`

	/*
	   Shipping amount
	   Example: 0
	*/
	LogisticsAmount float64 `json:"logistics_amount,omitempty"`

	/*
	   Phone
	   Example:
	*/
	Phone string `json:"phone,omitempty"`

	/*
	   Shipping method name
	   Example:
	*/
	Code string `json:"code,omitempty"`
}
