// Package transactions generated by SHOPLINE since v20251201
package transactions

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *CompanyCreditLineUpdateEvent) GetSupportedTopic() string {
	return "company_credit/update"
}

type CompanyCreditLineUpdateEvent struct {
	client.WebhookEvent
	/*
	   Store currency
	   Example: USD
	*/
	CurrencyCode string `json:"currency_code,omitempty"`

	/*
	   Status true enabled false disable
	   Example: true
	*/
	Enable bool `json:"enable,omitempty"`

	/*
	   Store id
	   Example: 23123123
	*/
	StoreId string `json:"store_id,omitempty"`

	/*
	   Remaining available amount
	   Example: 999999.99
	*/
	AvailableCreditAmount string `json:"available_credit_amount,omitempty"`

	/*
	   Company id
	   Example: 12323213123
	*/
	CompanyId string `json:"company_id,omitempty"`

	/*
	   Charged amount
	   Example: 999999.99
	*/
	ConsumedCreditAmount string `json:"consumed_credit_amount,omitempty"`

	/*
	   Credit amount
	   Example: 999999.99
	*/
	CreditLimitAmount string `json:"credit_limit_amount,omitempty"`
}
