// Package customers generated by SHOPLINE since v20251201
package customers

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *CustomerAddEvent) GetSupportedTopic() string {
	return "customers/create"
}

type SmsMarketingConsent struct {
	/*
	   Subscription status ( 0 : cancelled subscription ; 1 : on subscription ; 2 : not available
	   Example: 2
	*/
	State int `json:"state,omitempty"`

	/*
	   Subscription information source
	   Example: extInfo
	*/
	ConsentCollectedFrom string `json:"consent_collected_from,omitempty"`

	/*
	   Subscription change time
	   Example: 2022-12-16T11:06:11+08:00
	*/
	ConsentUpdatedAt string `json:"consent_updated_at,omitempty"`

	/*
	   Subscription method ( 0 : unknown ; 1 : single_opt_in ; 2 : confirmed_opt_in )
	   Example: 2
	*/
	OptInLevel int `json:"opt_in_level,omitempty"`
}

type EmailMarketingConsent struct {
	/*
	   Subscription method ( 0 : unknown ; 1 : single_opt_in ; 2 : confirmed_opt_in )
	   Example: 2
	*/
	OptInLevel int `json:"opt_in_level,omitempty"`

	/*
	   Subscription status ( 0 : cancelled subscription ; 1 : on subscription ; 2 : not on subscription ; 3 : on-subscription confirmation )
	   Example: 1
	*/
	State int `json:"state,omitempty"`

	/*
	   Subscription information source
	   Example: extInfo
	*/
	ConsentCollectedFrom string `json:"consent_collected_from,omitempty"`

	/*
	   Subscription change time
	   Example: 2022-12-16T11:06:11+08:00
	*/
	ConsentUpdatedAt string `json:"consent_updated_at,omitempty"`
}

type Addresse struct {
	/*
	   Address 2
	   Example: Apartment
	*/
	Address2 string `json:"address2,omitempty"`

	/*
	   Country
	   Example: United States
	*/
	Country string `json:"country,omitempty"`

	/*
	   Default address or not
	   Example: true
	*/
	Default bool `json:"default,omitempty"`

	/*
	   Phone number
	   Example: 008613987985473
	*/
	Phone string `json:"phone,omitempty"`

	/*
	   Address 1
	   Example: 7720 Cherokee Road
	*/
	Address1 string `json:"address1,omitempty"`

	/*
	   City
	   Example: Hagerman
	*/
	City string `json:"city,omitempty"`

	/*
	   Customer id
	   Example: 2007347234
	*/
	CustomerId string `json:"customer_id,omitempty"`

	/*
	   Name
	   Example: Bob
	*/
	FirstName string `json:"first_name,omitempty"`

	/*
	   Address ID
	   Example: SL201UA4840334721187149827
	*/
	Id string `json:"id,omitempty"`

	/*
	   Last name
	   Example: James
	*/
	LastName string `json:"last_name,omitempty"`

	/*
	   Province
	   Example: Kentucky
	*/
	Province string `json:"province,omitempty"`

	/*
	   Zip code
	   Example: 40202
	*/
	Zip string `json:"zip,omitempty"`

	/*
	   Company
	   Example: Joy
	*/
	Company string `json:"company,omitempty"`

	/*
	   Provincial encoding
	   Example: KY
	*/
	ProvinceCode string `json:"province_code,omitempty"`

	/*
	   Country code
	   Example: US
	*/
	CountryCode string `json:"country_code,omitempty"`
}

type DefaultAddress struct {
	/*
	   Address 2
	   Example: Apartment
	*/
	Address2 string `json:"address2,omitempty"`

	/*
	   Company
	   Example: Joy
	*/
	Company string `json:"company,omitempty"`

	/*
	   Address ID
	   Example: SL201UA4840334721187149827
	*/
	Id string `json:"id,omitempty"`

	/*
	   Phone number
	   Example: 008613977865436
	*/
	Phone string `json:"phone,omitempty"`

	/*
	   Province
	   Example: Kentucky
	*/
	Province string `json:"province,omitempty"`

	/*
	   Zip code
	   Example: 40202
	*/
	Zip string `json:"zip,omitempty"`

	/*
	   Country code
	   Example: US
	*/
	CountryCode string `json:"country_code,omitempty"`

	/*
	   Customer id
	   Example: 2007347234
	*/
	CustomerId string `json:"customer_id,omitempty"`

	/*
	   Name
	   Example: Bob
	*/
	FirstName string `json:"first_name,omitempty"`

	/*
	   Last name
	   Example: James
	*/
	LastName string `json:"last_name,omitempty"`

	/*
	   Provincial encoding
	   Example: KY
	*/
	ProvinceCode string `json:"province_code,omitempty"`

	/*
	   Address 1
	   Example: 7720 Cherokee Road
	*/
	Address1 string `json:"address1,omitempty"`

	/*
	   City
	   Example: Hagerman
	*/
	City string `json:"city,omitempty"`

	/*
	   Country
	   Example: United States
	*/
	Country string `json:"country,omitempty"`

	/*
	   Default address or not
	   Example: true
	*/
	Default bool `json:"default,omitempty"`
}

type CustomerAddEvent struct {
	client.WebhookEvent
	/*
	   Customer birthday Format: YYYYMMDD
	   Example: 19900623
	*/
	Birthday string `json:"birthday,omitempty"`

	/*
	   Customer id
	   Example: 2007347234
	*/
	Id string `json:"id,omitempty"`

	/*
	   Recent order number
	   Example: 200066283289389
	*/
	LastOrderId string `json:"last_order_id,omitempty"`

	/*
	   Order quantity
	   Example: 4
	*/
	OrdersCount int64 `json:"orders_count,omitempty"`

	/*
	   Subscription mail or not
	   Example: true
	*/
	AcceptsMarketing bool `json:"accepts_marketing,omitempty"`

	/*
	   Gender : male / female / others/secret
	   Example: male
	*/
	Gender string `json:"gender,omitempty"`

	/*
	   Multipass logo
	   Example: extInfo
	*/
	MultipassIdentifier string `json:"multipass_identifier,omitempty"`

	/*
	   Notes
	   Example: test
	*/
	Note string `json:"note,omitempty"`

	/*
	   Update time
	   Example: 2022-12-16T11:06:11+08:00
	*/
	UpdatedAt string `json:"updated_at,omitempty"`

	/*
	   Telephone subscription time (see IOS8601 for the format)
	   Example: 2022-12-16T11:06:11+08:00
	*/
	AcceptsMobileMarketingUpdatedAt string `json:"accepts_mobile_marketing_updated_at,omitempty"`

	/*
	   Verify if e-mail or not
	   Example: true
	*/
	VerifiedEmail bool `json:"verified_email,omitempty"`

	/*
	   Customer status [ 0 : disabled account , 1 : to enable account , 2 : invited account , 3 : valid account ]
	   Example: 2
	*/
	State string `json:"state,omitempty"`

	/*
	   Total cost amount
	   Example: 35
	*/
	TotalSpent string `json:"total_spent,omitempty"`

	/*
	   Mailbox subscription time
	   Example: 2022-12-16T11:06:11+08:00
	*/
	AcceptsMarketingUpdatedAt string `json:"accepts_marketing_updated_at,omitempty"`

	/*
	   User nickname
	   Example: Bob James
	*/
	NickName string `json:"nick_name,omitempty"`

	/*
	   Sms marketing subscription information
	   Example: map[consent_collected_from:extInfo consent_updated_at:2022-12-16T11:06:11+08:00 opt_in_level:2 state:2]
	*/
	SmsMarketingConsent SmsMarketingConsent `json:"sms_marketing_consent,omitempty"`

	/*
	   E-mail marketing subscription information
	   Example: map[consent_collected_from:extInfo consent_updated_at:2022-12-16T11:06:11+08:00 opt_in_level:2 state:1]
	*/
	EmailMarketingConsent EmailMarketingConsent `json:"email_marketing_consent,omitempty"`

	/*
	   Mailbox subscription status 0 : cancelled subscription , 1 : already available , 2 : not available
	   Example: 1
	*/
	EmailSubscribeFlag int `json:"email_subscribe_flag,omitempty"`

	/*
	   Name
	   Example: Bob
	*/
	FirstName string `json:"first_name,omitempty"`

	/*
	   Social media user ID
	   Example: 7566553464365
	*/
	SocialCustomer string `json:"social_customer,omitempty"`

	/*
	   Customer tag
	   Example: high level customer
	*/
	Tags string `json:"tags,omitempty"`

	/*
	   Address information list
	   Example: []
	*/
	Addresses []Addresse `json:"addresses,omitempty"`

	/*
	   FB login ID
	   Example: 432422124324234
	*/
	Asid string `json:"asid,omitempty"`

	/*
	   Currency
	   Example: CNY
	*/
	Currency string `json:"currency,omitempty"`

	/*
	   Default address
	   Example: map[address1:7720 Cherokee Road address2:Apartment city:Hagerman company:Joy country:United States country_code:US customer_id:2007347234 default:true first_name:Bob id:SL201UA4840334721187149827 last_name:James phone:008613977865436 province:Kentucky province_code:KY zip:40202]
	*/
	DefaultAddress DefaultAddress `json:"default_address,omitempty"`

	/*
	   Customer language
	   Example: en
	*/
	Language string `json:"language,omitempty"`

	/*
	   Last name
	   Example: James
	*/
	LastName string `json:"last_name,omitempty"`

	/*
	   Mobile phone subscription status 0 : cancelled subscription , 1 : already available , 2 : not available
	   Example: 1
	*/
	MobileSubscribeFlag int `json:"mobile_subscribe_flag,omitempty"`

	/*
	   Creation time
	   Example: 2022-12-16T11:06:11+08:00
	*/
	CreatedAt string `json:"created_at,omitempty"`

	/*
	   Mailbox
	   Example: gungcherny@gamil.com
	*/
	Email string `json:"email,omitempty"`

	/*
	   Phone number
	   Example: 008613987675435
	*/
	Phone string `json:"phone,omitempty"`

	/*
	   Accept telemarketing or not
	   Example: true
	*/
	AcceptsMobileMarketing bool `json:"accepts_mobile_marketing,omitempty"`
}
