// Package marketing generated by SHOPLINE since v20251201
package marketing

import (
	"errors"
	"fmt"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type DeleteDiscountCodeAPIReq struct {
	client.BaseAPIRequest
	/*
	   Discount code id
	   Example: 6062034195202449185
	*/
	DiscountCodeId string `url:"-" json:"-"` // Required
	/*
	   price rule id
	   Example: 6062017087609511417
	*/
	PriceRuleId string `url:"-" json:"-"` // Required
}

func (req *DeleteDiscountCodeAPIReq) GetEndpoint() string {

	return fmt.Sprintf("sales/price_rules/%s/discount_codes/%s.json", req.DiscountCodeId, req.PriceRuleId)

}

func (req *DeleteDiscountCodeAPIReq) GetMethod() string {
	return "DELETE"
}

// Verify the api request parameters
func (req *DeleteDiscountCodeAPIReq) Verify() error {

	if req.DiscountCodeId == "" {
		return errors.New("DiscountCodeId is required")
	}

	if req.PriceRuleId == "" {
		return errors.New("PriceRuleId is required")
	}

	return nil
}

func (req *DeleteDiscountCodeAPIReq) GetRequestOptions() *client.RequestOptions {
	opts := &client.RequestOptions{
		NotDecodeBody: true,
	}
	return opts
}

func (req *DeleteDiscountCodeAPIReq) NewAPIResp() *DeleteDiscountCodeAPIResp {
	return &DeleteDiscountCodeAPIResp{}
}

type DeleteDiscountCodeAPIResp struct {
	client.BaseAPIResponse
}
