// Package marketing generated by SHOPLINE since v20251201
package marketing

import (
	"errors"
	"fmt"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type QueryBulkCreatedDiscountCodeListAPIReq struct {
	client.BaseAPIRequest
	/*
	   batch id
	   Example: 6018676942227642851
	*/
	BatchId string `url:"-" json:"-"` // Required
	/*
	   price rule ID
	   Example: 6018642574989862445
	*/
	PriceRuleId string `url:"-" json:"-"` // Required
}

func (req *QueryBulkCreatedDiscountCodeListAPIReq) GetEndpoint() string {

	return fmt.Sprintf("sales/price_rules/%s/batch/%s/discount_codes.json", req.BatchId, req.PriceRuleId)

}

func (req *QueryBulkCreatedDiscountCodeListAPIReq) GetMethod() string {
	return "GET"
}

// Verify the api request parameters
func (req *QueryBulkCreatedDiscountCodeListAPIReq) Verify() error {

	if req.BatchId == "" {
		return errors.New("BatchId is required")
	}

	if req.PriceRuleId == "" {
		return errors.New("PriceRuleId is required")
	}

	return nil
}

func (req *QueryBulkCreatedDiscountCodeListAPIReq) NewAPIResp() *QueryBulkCreatedDiscountCodeListAPIResp {
	return &QueryBulkCreatedDiscountCodeListAPIResp{}
}

type QueryBulkCreatedDiscountCodeListAPIResp struct {
	client.BaseAPIResponse
	/*
	   Promo code listing
	   Example: [map[code:DISCOUNT_CODE_CONTENT errors:map[code:[]] id:6018677103624458718]]
	*/
	DiscountCodes []QueryBulkCreatedDiscountCodeListAPIRespDiscountCode `json:"discount_codes,omitempty" url:"-"`
}

type QueryBulkCreatedDiscountCodeListAPIRespDiscountCode struct {
	/*
	   Error list
	   Example: map[code:[]]
	*/
	Errors Errors `json:"errors,omitempty" url:"-"`

	/*
	   Id for discount code
	   Example: 6018677103624458718
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   discount code
	   Example: DISCOUNT_CODE_CONTENT
	*/
	Code string `json:"code,omitempty" url:"-"`
}

type Errors struct {
	/*
	   Error message
	   Example: []
	*/
	Code []string `json:"code,omitempty" url:"-"`
}
