// Package marketing generated by SHOPLINE since v20251201
package marketing

import (
	"errors"
	"fmt"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type UpdateThePriceRuleOfACodeDiscountAPIReq struct {
	client.BaseAPIRequest
	/*
	   Discount rule ID
	   Example:
	*/
	PriceRuleId string `url:"-" json:"-"` // Required
	/*
	   Discount code rules
	   Example: map[allocation_limit:2 allocation_method:across ends_at:2023-07-10T11:00:00+08:00 entitled_collection_ids:[12259764246208273857373144] entitled_country_ids:["HK","TW","SG"] entitled_product_ids:[16059766321245219059003144] entitled_variant_ids:[map[product_id:16059766321245219059003144 variant_id:18059766321249077818743144]] id:6018695669979551970 joint_discount:false joint_discount_order:true joint_discount_product:true joint_discount_shipping:true overlay_discount_code:true overlay_discount_code_order:true overlay_discount_code_product:true overlay_discount_code_shipping:true prerequisite_collection_ids:[12259764246208273857373144] prerequisite_customer_ids:[4216552768] prerequisite_product_ids:[16059766321245219059003144] prerequisite_quantity_range:map[greater_than_or_equal_to:5] prerequisite_saved_search_ids:[MLC5302535370462201296] prerequisite_shipping_price_range:map[less_than_or_equal_to:50] prerequisite_subtotal_range:map[greater_than_or_equal_to:100] prerequisite_to_entitlement_purchase:map[prerequisite_amount:100] prerequisite_to_entitlement_quantity_ratio:map[entitled_quantity:1 prerequisite_quantity:1] prerequisite_variant_ids:[map[product_id:16059766321245219059003144 variant_id:18059766321249077818743144]] sales_channels:[web] starts_at:2023-07-10T11:00:00+08:00 target_selection:all target_type:line_itme title:This is title of price rule usage_limit:2 usage_per_customer:10 value:20 value_type:percentage]
	*/
	PriceRule UpdateThePriceRuleOfACodeDiscountAPIReqPriceRule `json:"price_rule,omitempty" url:"-"`
}

type UpdateThePriceRuleOfACodeDiscountAPIReqPriceRule struct {
	/*
	   Specify product id array ● If target_selection is entitled, one of entitled_product_ids, entitled_collection_ids, and entitled_variant_ids must have a value ● The three fields entitled_product_ids, entitled_collection_ids, and entitled_variant_ids are mutually exclusive, and only one field can have a value. When you buy X and get Y, it means Y Product ID list
	   Example: [16059766321245219059003144]
	*/
	EntitledProductIds []string `json:"entitled_product_ids,omitempty" url:"-"`

	/*
	   Rule end time
	   Example: 2023-07-10T11:00:00+08:00
	*/
	EndsAt string `json:"ends_at,omitempty" url:"-"`

	/*
	   Superimposed discounts-automatic discounts-commodity discounts
	   Example: true
	*/
	JointDiscountProduct bool `json:"joint_discount_product,omitempty" url:"-"`

	/*
	   When buying X to get Y, the category Id list of X product cannot be used at the same time with prerequisite_product_ids and prerequisite_variant_ids
	   Example: [12259764246208273857373144]
	*/
	PrerequisiteCollectionIds []string `json:"prerequisite_collection_ids,omitempty" url:"-"`

	/*
	   Superimposed discounts-discount code discounts, allowing multiple discount code activities to be used in superimposed discounts. Product discount
	   Example: true
	*/
	OverlayDiscountCodeProduct bool `json:"overlay_discount_code_product,omitempty" url:"-"`

	/*
	   When buying X to get Y, the style id list of X product will not be used together with prerequisite_product_ids and prerequisite_collection_ids
	   Example: [map[product_id:16059766321245219059003144 variant_id:18059766321249077818743144]]
	*/
	PrerequisiteVariantIds []PrerequisiteVariantId `json:"prerequisite_variant_ids,omitempty" url:"-"`

	/*
	   When buying X to get Y, the amount threshold that X product needs to meet
	   Example: map[prerequisite_amount:100]
	*/
	PrerequisiteToEntitlementPurchase PrerequisiteToEntitlementPurchase `json:"prerequisite_to_entitlement_purchase,omitempty" url:"-"`

	/*
	   When buying X to get Y, when buying X to get Y, the list of X product IDs will not be used at the same time as prerequisite_collection_ids and prerequisite_variant_ids
	   Example: [16059766321245219059003144]
	*/
	PrerequisiteProductIds []string `json:"prerequisite_product_ids,omitempty" url:"-"`

	/*
	   Discount amount or percentage , it must be filled with negative numbers ● if the value_type value is percentage , indicating the Discount percentage , rounding up the reserved whole number , such as : Discount 10 % , filling 10 ; ●If the value_type value is fixed_amount , it means the Discount amount , the unit is yuan , rounded up to retain the two decimal points , such as : Discount 10.23 yuan , fill in the required field of -10.23.
	   Example: 20
	*/
	Value string `json:"value,omitempty" url:"-"`

	/*
	   Superimposed discounts - automatic discounts - order discounts
	   Example: true
	*/
	JointDiscountOrder bool `json:"joint_discount_order,omitempty" url:"-"`

	/*
	   The distribution method of the price rule, the acceptable values ​​are ● each The discount is applied to each participating product. For example, for a $15 off price rule, each eligible item will be $15 off at checkout, for a total of $15 multiplied by the number of items. ● The discount amount calculated across will be applied to the entire eligible listing. For example, for a $15 off price rule, the discount will be spread across each participating item, for a total of $15 off. When the target_type value is shipping_line, allocation_method must be each. The default is across
	   Example: across
	*/
	AllocationMethod string `json:"allocation_method,omitempty" url:"-"`

	/*
	   Superimposed discounts-discount code discounts, allowing multiple discount code activities to stack discounts
	   Example: true
	*/
	OverlayDiscountCode bool `json:"overlay_discount_code,omitempty" url:"-"`

	/*
	   Shipping must be less than or equal to the value , *non-required , default null .  * 1 ) only the content can be filled in the content in target_type=shipping_line  * 2 ) , the accuracy is consistent with the accuracy of the store currency
	   Example: map[less_than_or_equal_to:50]
	*/
	PrerequisiteShippingPriceRange PrerequisiteShippingPriceRange `json:"prerequisite_shipping_price_range,omitempty" url:"-"`

	/*
	   Limit the number of times each customer can use each code under the price rule ● If not filled, the default value is null or empty, which means unlimited usage ● Only empty and natural numbers are acceptable; ● Values ​​exceeding the upper limit are automatically processed as up limit value
	   Example: 10
	*/
	UsagePerCustomer int `json:"usage_per_customer,omitempty" url:"-"`

	/*
	   Superimposed discounts-discount code discounts, allowing multiple discount code activities to be used in superimposed discounts. shipping discount
	   Example: true
	*/
	OverlayDiscountCodeShipping bool `json:"overlay_discount_code_shipping,omitempty" url:"-"`

	/*
	   The scope of application of preferential rules, the acceptable values ​​are ● all, defined as all products; ● entitled, defined as specified range (specified product/specified category). When this field obtains the value of entitled, one of entitled_product_ids and entitled_collection_ids must be selected. Value; when target_type=shipping_line, all must be filled. The default value is all
	   Example: all
	*/
	TargetSelection string `json:"target_selection,omitempty" url:"-"`

	/*
	   Overlay Offer - Automatic Offer - Shipping Discount
	   Example: true
	*/
	JointDiscountShipping bool `json:"joint_discount_shipping,omitempty" url:"-"`

	/*
	   Whether to superimpose automatic discounts? The default value is false.
	   Example: false
	*/
	JointDiscount bool `json:"joint_discount,omitempty" url:"-"`

	/*
	   Superimposed discounts-discount code discounts, allowing multiple discount code activities to be used in superimposed discounts. order discount
	   Example: true
	*/
	OverlayDiscountCodeOrder bool `json:"overlay_discount_code_order,omitempty" url:"-"`

	/*
	   The premise : customers must belong to one of the search ( customer grouping ) requisite_saved_search_ids , which is saved by specify or one of the customers specify requisite_customer_ids .
	   Example: [MLC5302535370462201296]
	*/
	PrerequisiteSavedSearchIds []string `json:"prerequisite_saved_search_ids,omitempty" url:"-"`

	/*
	   Array of country/region ID, temporarily useless
	   Example: ["HK","TW","SG"]
	*/
	EntitledCountryIds []string `json:"entitled_country_ids,omitempty" url:"-"`

	/*
	   Price Rule start time
	   Example: 2023-07-10T11:00:00+08:00
	*/
	StartsAt string `json:"starts_at,omitempty" url:"-"`

	/*
	   The premise : customers must belong to one of the search ( customer grouping ) requisite_saved_search_ids , which is saved by specify or one of the customers specify requisite_customer_ids .
	   Example: [4216552768]
	*/
	PrerequisiteCustomerIds []string `json:"prerequisite_customer_ids,omitempty" url:"-"`

	/*
	   When you buy X and get Y, you can accumulatively allocate the limit of discounts in the shopping cart if you meet the conditions. For example: if you buy 1 X and get 1 Y discount, set allocation_limit=2, when there are 3 X products in the shopping cart, When there are 3 Y items, only 2 Y items can be obtained
	   Example: 2
	*/
	AllocationLimit int `json:"allocation_limit,omitempty" url:"-"`

	/*
	   Discount rule ID
	   Example: 6018695669979551970
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   Specify style group ●If target_selection is entitled , entitled_product_ids、entitled_collection_ids , entitled_skus three choices one must have value ●Entitled_product_ids、entitled_collection_ids , entitled_variant_ids three field mutually exclusive , only one field has value ●When buying x get y , indicate the y Product style list
	   Example: [map[product_id:16059766321245219059003144 variant_id:18059766321249077818743144]]
	*/
	EntitledVariantIds []EntitledVariantId `json:"entitled_variant_ids,omitempty" url:"-"`

	/*
	   The target type to which the price rule applies. Valid values: line_item: The price rule to apply to the shopping line item item. shipping_line: The price rule applies to the shopping order shipping line.
	   Example: line_itme
	*/
	TargetType string `json:"target_type,omitempty" url:"-"`

	/*
	   The name of the discount rules
	   Example: This is title of price rule
	*/
	Title string `json:"title,omitempty" url:"-"`

	/*
	   Promotion triggers the minimum order amount ● prerequisite_quantity_range and prerequisite_subtotal_range are mutually exclusive ● If both are empty, it is the trigger condition for no price or quantity
	   Example: map[greater_than_or_equal_to:100]
	*/
	PrerequisiteSubtotalRange UpdateThePriceRuleOfACodeDiscountAPIReqPrerequisiteSubtotalRange `json:"prerequisite_subtotal_range,omitempty" url:"-"`

	/*
	   If the sales channel is not transmitted by default, it means that all channels are available; If a specified sales channel is uploaded, it is available only in that channel
	   Example: [web]
	*/
	SalesChannels []string `json:"sales_channels,omitempty" url:"-"`

	/*
	   Offer type, acceptable values ​​are ● percentage percentage, percentage must be filled in when target_type=shipping_line, and percentage must be filled in for buy x get y type activities; ● fixed_amount fixed amount; required field
	   Example: percentage
	*/
	ValueType string `json:"value_type,omitempty" url:"-"`

	/*
	   When buying x get y , the number threshold and number of y Product required by x Product
	   Example: map[entitled_quantity:1 prerequisite_quantity:1]
	*/
	PrerequisiteToEntitlementQuantityRatio PrerequisiteToEntitlementQuantityRatio `json:"prerequisite_to_entitlement_quantity_ratio,omitempty" url:"-"`

	/*
	   Promotion triggers the minimum quantity of items ● prerequisite_quantity_range and prerequisite_subtotal_range are mutually exclusive ● If both are empty, it is the trigger condition for no price or quantity
	   Example: map[greater_than_or_equal_to:5]
	*/
	PrerequisiteQuantityRange UpdateThePriceRuleOfACodeDiscountAPIReqPrerequisiteQuantityRange `json:"prerequisite_quantity_range,omitempty" url:"-"`

	/*
	   Specify an array of category ids ● If target_selection is entitled, one of the three options entitled_product_ids, entitled_collection_ids, and entitled_variant_ids must have a value ● The three fields entitled_product_ids, entitled_collection_ids, and entitled_variant_ids are mutually exclusive, and only one field can have a value
	   Example: [12259764246208273857373144]
	*/
	EntitledCollectionIds []string `json:"entitled_collection_ids,omitempty" url:"-"`

	/*
	   Limit the total number of uses of all discount codes bound to this discount rule ● If not filled, the default value is null or empty, which means unlimited use times ● Only empty and natural numbers are acceptable; ● If the upper limit value is exceeded, it will be automatically processed as upper limit value
	   Example: 2
	*/
	UsageLimit int `json:"usage_limit,omitempty" url:"-"`
}

type UpdateThePriceRuleOfACodeDiscountAPIReqPrerequisiteSubtotalRange struct {
	/*
	   ● nullable ● rounded to two decimal places
	   Example: 100
	*/
	GreaterThanOrEqualTo string `json:"greater_than_or_equal_to,omitempty" url:"-"`
}

type UpdateThePriceRuleOfACodeDiscountAPIReqPrerequisiteQuantityRange struct {
	/*
	   ● nullable ● must be >0 ● only integers are acceptable (integer)
	   Example: 5
	*/
	GreaterThanOrEqualTo int `json:"greater_than_or_equal_to,omitempty" url:"-"`
}

func (req *UpdateThePriceRuleOfACodeDiscountAPIReq) GetEndpoint() string {

	return fmt.Sprintf("sales/price_rules/%s.json", req.PriceRuleId)

}

func (req *UpdateThePriceRuleOfACodeDiscountAPIReq) GetMethod() string {
	return "PUT"
}

func (req *UpdateThePriceRuleOfACodeDiscountAPIReq) GetData() interface{} {
	return req
}

// Verify the api request parameters
func (req *UpdateThePriceRuleOfACodeDiscountAPIReq) Verify() error {

	if req.PriceRuleId == "" {
		return errors.New("PriceRuleId is required")
	}

	return nil
}

func (req *UpdateThePriceRuleOfACodeDiscountAPIReq) NewAPIResp() *UpdateThePriceRuleOfACodeDiscountAPIResp {
	return &UpdateThePriceRuleOfACodeDiscountAPIResp{}
}

type UpdateThePriceRuleOfACodeDiscountAPIResp struct {
	client.BaseAPIResponse
	/*
	   Discount rules
	   Example: map[allocation_limit:2 allocation_method:across create_at:2023-07-10T11:00:00+08:00 ends_at:2023-08-10T11:00:00+08:00 entitled_collection_ids:[12259764246208273857373144] entitled_country_ids:["HK","TW","SG"] entitled_product_ids:[16059766321245219059003144] entitled_variant_ids:[map[product_id:16059766321245219059003144 variant_id:18059766321249077818743144]] id:6018695669979551970 joint_discount:false joint_discount_order:true joint_discount_product:true joint_discount_shipping:true overlay_discount_code:true overlay_discount_code_order:true overlay_discount_code_product:true overlay_discount_code_shipping:true prerequisite_collection_ids:[12259764246208273857373144] prerequisite_customer_ids:[4216552768] prerequisite_product_ids:[16059766321245219059003144] prerequisite_quantity_range:map[greater_than_or_equal_to:5] prerequisite_saved_search_ids:[MLC5302535370462201296] prerequisite_shipping_price_range:map[less_than_or_equal_to:50] prerequisite_subtotal_range:map[greater_than_or_equal_to:100] prerequisite_to_entitlement_purchase:map[prerequisite_amount:100] prerequisite_to_entitlement_quantity_ratio:map[entitled_quantity:1 prerequisite_quantity:1] prerequisite_variant_ids:[map[product_id:16059766321245219059003144 variant_id:18059766321249077818743144]] sales_channels:[web] starts_at:2023-07-10T11:00:00+08:00 target_selection:all target_type:line_itme target_user_feature_values:[map[target_value:4216552768 value:new user group]] title:This is title of price rule update_at:2023-07-10T11:00:00+08:00 usage_limit:2 usage_per_customer:10 value:20 value_type:percentage]
	*/
	PriceRule UpdateThePriceRuleOfACodeDiscountAPIRespPriceRule `json:"price_rule,omitempty" url:"-"`
}

type UpdateThePriceRuleOfACodeDiscountAPIRespPriceRule struct {
	/*
	   Superimposed discounts-discount code discounts, allowing multiple discount code activities to be used in superimposed discounts. Product discount
	   Example: true
	*/
	OverlayDiscountCodeProduct bool `json:"overlay_discount_code_product,omitempty" url:"-"`

	/*
	   The target type to which the price rule applies. Valid values: line_item: The price rule to apply to the shopping line item item. shipping_line: The price rule applies to the shopping order shipping line.
	   Example: line_itme
	*/
	TargetType string `json:"target_type,omitempty" url:"-"`

	/*
	   Rule end time
	   Example: 2023-08-10T11:00:00+08:00
	*/
	EndsAt string `json:"ends_at,omitempty" url:"-"`

	/*
	   Specify an array of category ids ● If target_selection is entitled, one of the three options entitled_product_ids, entitled_collection_ids, and entitled_variant_ids must have a value ● The three fields entitled_product_ids, entitled_collection_ids, and entitled_variant_ids are mutually exclusive, and only one field can have a value
	   Example: [12259764246208273857373144]
	*/
	EntitledCollectionIds []string `json:"entitled_collection_ids,omitempty" url:"-"`

	/*
	   Offer type, acceptable values ​​are ● percentage percentage, percentage must be filled in when target_type=shipping_line, and percentage must be filled in for buy x get y type activities; ● fixed_amount fixed amount; required field
	   Example: percentage
	*/
	ValueType string `json:"value_type,omitempty" url:"-"`

	/*
	   Discount rule application range , acceptable value has ● all , defined as all Product ●Entitled , defined as the specify range ( specify Product / specify classification ) when this field is obtained for entitled , the two choices of entitled_product_ids and entitled_collection_ids must be worthwhile ;● explicit , defined as a single Product , when target_type=shipping_line , you must fill in explicit. default value as all
	   Example: all
	*/
	TargetSelection string `json:"target_selection,omitempty" url:"-"`

	/*
	   Rule start time
	   Example: 2023-07-10T11:00:00+08:00
	*/
	StartsAt string `json:"starts_at,omitempty" url:"-"`

	/*
	   Promotion triggers the minimum order amount ● prerequisite_quantity_range and prerequisite_subtotal_range are mutually exclusive ● If both are empty, it is the trigger condition for no price or quantity
	   Example: map[greater_than_or_equal_to:100]
	*/
	PrerequisiteSubtotalRange UpdateThePriceRuleOfACodeDiscountAPIRespPrerequisiteSubtotalRange `json:"prerequisite_subtotal_range,omitempty" url:"-"`

	/*
	   The premise : customers must belong to one of the search ( customer grouping ) requisite_saved_search_ids , which is saved by specify or one of the customers specify requisite_customer_ids .
	   Example: [4216552768]
	*/
	PrerequisiteCustomerIds []string `json:"prerequisite_customer_ids,omitempty" url:"-"`

	/*
	   Discount rules id
	   Example: 6018695669979551970
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   The premise : customers must belong to one of the search ( customer grouping ) requisite_saved_search_ids , which is saved by specify or one of the customers specify requisite_customer_ids .
	   Example: [MLC5302535370462201296]
	*/
	PrerequisiteSavedSearchIds []string `json:"prerequisite_saved_search_ids,omitempty" url:"-"`

	/*
	   The distribution method of the price rule, the acceptable values ​​are ● each The discount is applied to each participating product. For example, for a $15 off price rule, each eligible item will be $15 off at checkout, for a total of $15 multiplied by the number of items. ● The discount amount calculated across will be applied to the entire eligible listing. For example, for a $15 off price rule, the discount will be spread across each participating item, for a total of $15 off. When the target_type value is shipping_line, allocation_method must be each. The default is across
	   Example: across
	*/
	AllocationMethod string `json:"allocation_method,omitempty" url:"-"`

	/*
	   Whether to superimpose automatic discounts? The default value is false.
	   Example: false
	*/
	JointDiscount bool `json:"joint_discount,omitempty" url:"-"`

	/*
	   When buying X to get Y, when buying X to get Y, the list of X product IDs will not be used at the same time as prerequisite_collection_ids and prerequisite_variant_ids
	   Example: [16059766321245219059003144]
	*/
	PrerequisiteProductIds []string `json:"prerequisite_product_ids,omitempty" url:"-"`

	/*
	   When buying x get y , x Product needs to meet the amount threshold
	   Example: map[prerequisite_amount:100]
	*/
	PrerequisiteToEntitlementPurchase PrerequisiteToEntitlementPurchase `json:"prerequisite_to_entitlement_purchase,omitempty" url:"-"`

	/*
	   When buying X to get Y, the category Id list of X product cannot be used at the same time with prerequisite_product_ids and prerequisite_variant_ids
	   Example: [12259764246208273857373144]
	*/
	PrerequisiteCollectionIds []string `json:"prerequisite_collection_ids,omitempty" url:"-"`

	/*
	   When buying x-d , you can distribute the limited to of the Discount in the shopping cart in the eligible situation . for example , if you are full of 1 piece x and get 1 piece of y discount , set up allocation_limit=2 , when the shopping cart has 3 pieces x Product , and 3
	   Example: 2
	*/
	AllocationLimit int `json:"allocation_limit,omitempty" url:"-"`

	/*
	   Superimposed discounts-discount code discounts, allowing multiple discount code activities to stack discounts
	   Example: true
	*/
	OverlayDiscountCode bool `json:"overlay_discount_code,omitempty" url:"-"`

	/*
	   When buying X to get Y, the style id list of X product will not be used together with prerequisite_product_ids and prerequisite_collection_ids
	   Example: [map[product_id:16059766321245219059003144 variant_id:18059766321249077818743144]]
	*/
	PrerequisiteVariantIds []PrerequisiteVariantId `json:"prerequisite_variant_ids,omitempty" url:"-"`

	/*
	   Superimposed discounts-automatic discounts-commodity discounts
	   Example: true
	*/
	JointDiscountProduct bool `json:"joint_discount_product,omitempty" url:"-"`

	/*
	   Superimposed discounts-discount code discounts, allowing multiple discount code activities to be used in superimposed discounts. shipping discount
	   Example: true
	*/
	OverlayDiscountCodeShipping bool `json:"overlay_discount_code_shipping,omitempty" url:"-"`

	/*
	   Discount amount or percentage , it must be filled with negative numbers ● if the value_type value is percentage , indicating the Discount percentage , rounding up the reserved whole number , such as : Discount 10 % , filling 10 ; ●If the value_type value is fixed_amount , it means the Discount amount , the unit is yuan , rounded up to retain the two decimal points , such as : Discount 10.23 yuan , fill in the required field of -10.23.
	   Example: 20
	*/
	Value string `json:"value,omitempty" url:"-"`

	/*
	   When buying X to get Y, the quantity threshold required for X product and the quantity of Y product obtained
	   Example: map[entitled_quantity:1 prerequisite_quantity:1]
	*/
	PrerequisiteToEntitlementQuantityRatio PrerequisiteToEntitlementQuantityRatio `json:"prerequisite_to_entitlement_quantity_ratio,omitempty" url:"-"`

	/*
	   Limit the total number of uses of all discount codes bound to this discount rule ● If not filled, the default value is null or empty, which means unlimited use times ● Only empty and natural numbers are acceptable; ● If the upper limit value is exceeded, it will be automatically processed as upper limit value
	   Example: 2
	*/
	UsageLimit int `json:"usage_limit,omitempty" url:"-"`

	/*
	   Array of country/region ID, temporarily useless
	   Example: ["HK","TW","SG"]
	*/
	EntitledCountryIds []string `json:"entitled_country_ids,omitempty" url:"-"`

	/*
	   Overlay Offer - Automatic Offer - Shipping Discount
	   Example: true
	*/
	JointDiscountShipping bool `json:"joint_discount_shipping,omitempty" url:"-"`

	/*
	   Designated style array ● If target_selection is entitled, one of entitled_product_ids, entitled_collection_ids, and entitled_variant_ids must have a value ● The three fields entitled_product_ids, entitled_collection_ids, and entitled_variant_ids are mutually exclusive, and only one field can have a value ● When you buy X and get Y, it means Y product Style list
	   Example: [map[product_id:16059766321245219059003144 variant_id:18059766321249077818743144]]
	*/
	EntitledVariantIds []EntitledVariantId `json:"entitled_variant_ids,omitempty" url:"-"`

	/*
	   Specify product id array ● If target_selection is entitled, one of entitled_product_ids, entitled_collection_ids, and entitled_variant_ids must have a value ● The three fields entitled_product_ids, entitled_collection_ids, and entitled_variant_ids are mutually exclusive, and only one field can have a value. When you buy X and get Y, it means Y Product ID list
	   Example: [16059766321245219059003144]
	*/
	EntitledProductIds []string `json:"entitled_product_ids,omitempty" url:"-"`

	/*
	   Return prerequisite_saved_search_ids or prerequisite_customer_ids character value
	   Example: [map[target_value:4216552768 value:new user group]]
	*/
	TargetUserFeatureValues []TargetUserFeatureValue `json:"target_user_feature_values,omitempty" url:"-"`

	/*
	   Discount rule id name
	   Example: This is title of price rule
	*/
	Title string `json:"title,omitempty" url:"-"`

	/*
	   Creation time
	   Example: 2023-07-10T11:00:00+08:00
	*/
	CreateAt string `json:"create_at,omitempty" url:"-"`

	/*
	   Limit the number of times a single customer can use each coupon code bound to the discount rule ● If not filled, the default value is null or empty, which means unlimited use times ● Only empty and natural numbers are acceptable; ● If the upper limit value is exceeded, it will be automatically processed as the upper limit value
	   Example: 10
	*/
	UsagePerCustomer int `json:"usage_per_customer,omitempty" url:"-"`

	/*
	   The sales channel ● default value does not transmit , it means that all channels are available ● specify channels , but the available range is : online channel
	   Example: [web]
	*/
	SalesChannels []string `json:"sales_channels,omitempty" url:"-"`

	/*
	   Superimposed discounts - automatic discounts - order discounts
	   Example: true
	*/
	JointDiscountOrder bool `json:"joint_discount_order,omitempty" url:"-"`

	/*
	   Superimposed discounts-discount code discounts, allowing multiple discount code activities to be used in superimposed discounts. order discount
	   Example: true
	*/
	OverlayDiscountCodeOrder bool `json:"overlay_discount_code_order,omitempty" url:"-"`

	/*
	   Shipping must be less than or equal to this value. * Not required, default is empty. * 1) The content can only be filled in under target_type=shipping_line * 2) The value and accuracy are consistent with the corresponding accuracy of the store currency
	   Example: map[less_than_or_equal_to:50]
	*/
	PrerequisiteShippingPriceRange PrerequisiteShippingPriceRange `json:"prerequisite_shipping_price_range,omitempty" url:"-"`

	/*
	   Update time
	   Example: 2023-07-10T11:00:00+08:00
	*/
	UpdateAt string `json:"update_at,omitempty" url:"-"`

	/*
	   Promotion triggers the minimum quantity of items ● prerequisite_quantity_range and prerequisite_subtotal_range are mutually exclusive ● If both are empty, it is the trigger condition for no price or quantity
	   Example: map[greater_than_or_equal_to:5]
	*/
	PrerequisiteQuantityRange UpdateThePriceRuleOfACodeDiscountAPIRespPrerequisiteQuantityRange `json:"prerequisite_quantity_range,omitempty" url:"-"`
}

type UpdateThePriceRuleOfACodeDiscountAPIRespPrerequisiteSubtotalRange struct {
	/*
	   ● nullable ● rounded to two decimal places
	   Example: 100
	*/
	GreaterThanOrEqualTo string `json:"greater_than_or_equal_to,omitempty" url:"-"`
}

type TargetUserFeatureValue struct {
	/*
	   When it is specify customer information and specify customer group information , this value is saved to correspond to the snapshot value of customer / customer group
	   Example: 4216552768
	*/
	TargetValue string `json:"target_value,omitempty" url:"-"`

	/*
	   User value , can be tag id , level information , specify customer information , specify customer group information , etc .
	   Example: new user group
	*/
	Value string `json:"value,omitempty" url:"-"`
}

type UpdateThePriceRuleOfACodeDiscountAPIRespPrerequisiteQuantityRange struct {
	/*
	   ● nullable ● must be >0 ● only integers are acceptable (integer)
	   Example: 5
	*/
	GreaterThanOrEqualTo int `json:"greater_than_or_equal_to,omitempty" url:"-"`
}
