// Package data generated by SHOPLINE since v20260301
package data

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *NoticeCompletedByTheCalculationOfOrderReturnEvent) GetSupportedTopic() string {
	return "order_attribution/create"
}

type NoticeCompletedByTheCalculationOfOrderReturnEvent struct {
	client.WebhookEvent
	/*
	   The time (recorded in UTC+8:00) when the user generated the last interaction within 30 days before completing an order.
	   Example: 2023-05-23T20:53:25.199
	*/
	LastInteractTime string `json:"lastInteractTime,omitempty" url:"-"`

	/*
	   Order id.
	   Example: 21059478554517401789150705
	*/
	OrderSeq string `json:"orderSeq,omitempty" url:"-"`

	/*
	   store id.
	   Example: 1637826610248
	*/
	StoreId string `json:"storeId,omitempty" url:"-"`

	/*
	   Event type, currently only supports: create
	   Example: create
	*/
	ActionType string `json:"actionType,omitempty" url:"-"`

	/*
	   The first interaction source URL within 30 days before completing an order. Users entering your store from different off-site platforms or by clicking on different ads will have an interaction.
	   Example: www.facebook.com
	*/
	FirstInteractRefererUrl string `json:"firstInteractRefererUrl,omitempty" url:"-"`

	/*
	   The first interaction source name within 30 days before completing an order.
	   Example: Direct
	*/
	FirstInteractSource string `json:"firstInteractSource,omitempty" url:"-"`

	/*
	   The time (recorded in UTC+8:00) when the user generated the first interaction within 30 days before completing an order.
	   Example: 2023-05-23T20:53:25.199
	*/
	FirstInteractTime string `json:"firstInteractTime,omitempty" url:"-"`

	/*
	   Identifies whether it is offline data.
	   Example: false
	*/
	IsOffline string `json:"isOffline,omitempty" url:"-"`

	/*
	   Message distribution key.
	   Example: 21059478554517401789150705
	*/
	Key string `json:"key,omitempty" url:"-"`

	/*
	   The user generates the last interactive landing page URL within 30 days before placing an order.
	   Example: www.facebook.com
	*/
	LastInteractUrl string `json:"lastInteractUrl,omitempty" url:"-"`

	/*
	   The user generates the first interactive landing page URL within 30 days before placing an order.
	   Example: www.facebook.com
	*/
	FirstInteractUrl string `json:"firstInteractUrl,omitempty" url:"-"`

	/*
	   The last interaction source URL within 30 days before completing an order. Users entering your store from different off-site platforms or by clicking on different ads will have an interaction.
	   Example: www.facebook.com
	*/
	LastInteractRefererUrl string `json:"lastInteractRefererUrl,omitempty" url:"-"`

	/*
	   The last interaction source name within 30 days before completing an order.
	   Example: Direct
	*/
	LastInteractSource string `json:"lastInteractSource,omitempty" url:"-"`
}
