// Package buildingstation generated by SHOPLINE since v20251201
package buildingstation

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *DeleteBlogsEvent) GetSupportedTopic() string {
	return "blogs/delete"
}

type DeleteBlogsEvent struct {
	client.WebhookEvent
	/*
	   Blog collection id
	   Example: 6183a5c83d13eb7215356705
	*/
	Id string `json:"id,omitempty"`
}
