// Package transactions generated by SHOPLINE since v20251201
package transactions

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *ReturnUpdateEvent) GetSupportedTopic() string {
	return "return/update"
}

type ReturnUpdateEvent struct {
	client.WebhookEvent
	/*
	   Return id
	   Example: 2606576826460396889110
	*/
	AfterSaleOrderSeq string `json:"after_sale_order_seq,omitempty"`

	/*
	   Order update time , ( format see IOS8601 )
	   Example: 2024-07-30T19:05:13.968+0800
	*/
	CreatedAt string `json:"created_at,omitempty"`

	/*
	   Order id
	   Example: 21064997045395244145024325
	*/
	OrderSeq string `json:"order_seq,omitempty"`

	/*
	   Return listing
	   Example: []
	*/
	ReturnLineItems []ReturnLineItem `json:"return_line_items,omitempty"`

	/*
	   Return reason
	   Example: This is a test return reason
	*/
	ReturnReason string `json:"return_reason,omitempty"`

	/*
	   Return status : REQUESTED 、CLOSED ( return is completed and refunded is completed ) 、OPEN ( in return ) 、DECLINED ( reject return ) 、CANCELED ( cancel return )
	   Example: OPEN
	*/
	Status string `json:"status,omitempty"`
}
