// Package webhook generated by SHOPLINE since v20260301
package webhook

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

type SubscribeToAWebhookAPIReq struct {
	client.BaseAPIRequest
	/*
	   Configuration information for the Webhook event subscription.
	   Example: map[address:https://www.shopline.com/webhook api_version:v20240601 topic:products/create]
	*/
	Webhook SubscribeToAWebhookAPIReqWebhook `json:"webhook,omitempty" url:"-"`
}

type SubscribeToAWebhookAPIReqWebhook struct {
	/*
	   The callback URL to which the event notification is sent when the corresponding event occurs.
	   Maximum length: 255

	   Example: https://www.shopline.com/webhook
	*/
	Address string `json:"address,omitempty" url:"-"`

	/*
	   The version of this Webhook subscription API. Only `v20240601` and later versions are supported.
	   Example: v20240601
	*/
	ApiVersion string `json:"api_version,omitempty" url:"-"`

	/*
	   The specific Webhook event to subscribe to, such as `products/create`, which represents the product creation event.
	   For valid event values, refer to the value under **Event Identification** in the table within each [Webhook document]((https://developer.shopline.com/docsv2/ec20/2ff80e9159b517704ce43f0f74e6e247/D996ADYa)).

	   Example: products/create
	*/
	Topic string `json:"topic,omitempty" url:"-"`
}

func (req *SubscribeToAWebhookAPIReq) GetEndpoint() string {

	return "webhooks.json"

}

func (req *SubscribeToAWebhookAPIReq) GetMethod() string {
	return "POST"
}

func (req *SubscribeToAWebhookAPIReq) GetData() interface{} {
	return req
}

// Verify the api request parameters
func (req *SubscribeToAWebhookAPIReq) Verify() error {

	return nil
}

func (req *SubscribeToAWebhookAPIReq) NewAPIResp() *SubscribeToAWebhookAPIResp {
	return &SubscribeToAWebhookAPIResp{}
}

type SubscribeToAWebhookAPIResp struct {
	client.BaseAPIResponse
	/*
	   The Webhook event subscription information.
	   Example: map[address:https://www.shopline.com/webhook api_version:v20240601 created_at:2024-01-31T18:21:06+08:00 id:13814 topic: updated_at:2024-01-31T18:21:06+08:00]
	*/
	Webhook Webhook `json:"webhook,omitempty" url:"-"`
}

type Webhook struct {
	/*
	   The version of this Webhook subscription API. Only `v20240601` and later versions are supported.
	   Example: v20240601
	*/
	ApiVersion string `json:"api_version,omitempty" url:"-"`

	/*
	   The date and time when the Webhook event was successfully subscribed for the first time. Format: [ISO 8601. ](https://www.iso.org/iso-8601-date-and-time-format.html)

	   Example: 2024-01-31T18:21:06+08:00
	*/
	CreatedAt string `json:"created_at,omitempty" url:"-"`

	/*
	   A unique identifier for the Webhook subscription record.
	   Example: 13814
	*/
	Id int `json:"id,omitempty" url:"-"`

	/*
	   The specific event successfully subscribed to, such as `products/create`, which represents the product creation event.
	   Example:
	*/
	Topic string `json:"topic,omitempty" url:"-"`

	/*
	   The date and time when the Webhook subscription record was last updated. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).

	   Example: 2024-01-31T18:21:06+08:00
	*/
	UpdatedAt string `json:"updated_at,omitempty" url:"-"`

	/*
	   The callback URL to which the event notification is sent when the corresponding event occurs.
	   Maximum length: 255
	   Example: https://www.shopline.com/webhook
	*/
	Address string `json:"address,omitempty" url:"-"`
}
