// Package webhook generated by SHOPLINE since v20260301
package webhook

import (
	"fmt"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type UnsubscribeFromAWebhookAPIReq struct {
	client.BaseAPIRequest
	/*
	   The unique identifier of the Webhook subscription record. You can obtain the value of this parameter from the response data in the following two APIs:
	   - [Create a Webhook](https://developer.shopline.com/docsv2/ec20/cdb180dc069f7d8d6877c0cdffe96f73/5yxG7lOk)
	   - [Get a list of Webhooks](https://developer.shopline.com/docsv2/ec20/cdb180dc069f7d8d6877c0cdffe96f73/uOOJm32H)
	   Example: 13814
	*/
	Id int `url:"-" json:"-"` // Required
}

func (req *UnsubscribeFromAWebhookAPIReq) GetEndpoint() string {

	return fmt.Sprintf("%d/webhooks.json", req.Id)

}

func (req *UnsubscribeFromAWebhookAPIReq) GetMethod() string {
	return "DELETE"
}

// Verify the api request parameters
func (req *UnsubscribeFromAWebhookAPIReq) Verify() error {

	return nil
}

func (req *UnsubscribeFromAWebhookAPIReq) GetRequestOptions() *client.RequestOptions {
	opts := &client.RequestOptions{
		NotDecodeBody: true,
	}
	return opts
}

func (req *UnsubscribeFromAWebhookAPIReq) NewAPIResp() *UnsubscribeFromAWebhookAPIResp {
	return &UnsubscribeFromAWebhookAPIResp{}
}

type UnsubscribeFromAWebhookAPIResp struct {
	client.BaseAPIResponse
}
