// Package webhook generated by SHOPLINE since v20260301
package webhook

import (
	"fmt"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type UpdateASubscribedWebhookAPIReq struct {
	client.BaseAPIRequest
	/*
	   The unique identifier of the Webhook subscription record. You can obtain the value of this parameter from the response data in the following two APIs:
	   -  [Create a Webhook](https://developer.shopline.com/docsv2/ec20/cdb180dc069f7d8d6877c0cdffe96f73/5yxG7lOk)
	   - [Get a list of Webhooks](https://developer.shopline.com/docsv2/ec20/cdb180dc069f7d8d6877c0cdffe96f73/uOOJm32H)

	   Example: 13814
	*/
	Id int `url:"-" json:"-"` // Required
	/*
	   Configuration information for the Webhook event subscription.
	   Example: map[address:https://www.shopline.com/webhook]
	*/
	Webhook UpdateASubscribedWebhookAPIReqWebhook `json:"webhook,omitempty" url:"-"`
}

type UpdateASubscribedWebhookAPIReqWebhook struct {
	/*
	   The callback URL to which the event notification is sent when the corresponding event occurs.
	   Maximum length: 255
	   Example: https://www.shopline.com/webhook
	*/
	Address string `json:"address,omitempty" url:"-"`
}

func (req *UpdateASubscribedWebhookAPIReq) GetEndpoint() string {

	return fmt.Sprintf("%d/webhooks.json", req.Id)

}

func (req *UpdateASubscribedWebhookAPIReq) GetMethod() string {
	return "PUT"
}

func (req *UpdateASubscribedWebhookAPIReq) GetData() interface{} {
	return req
}

// Verify the api request parameters
func (req *UpdateASubscribedWebhookAPIReq) Verify() error {

	return nil
}

func (req *UpdateASubscribedWebhookAPIReq) NewAPIResp() *UpdateASubscribedWebhookAPIResp {
	return &UpdateASubscribedWebhookAPIResp{}
}

type UpdateASubscribedWebhookAPIResp struct {
	client.BaseAPIResponse
	/*
	   The Webhook event subscription information.
	   Example: map[address:https://www.shopline.com/webhook api_version:v20250301 created_at:2024-01-31T18:21:06+08:00 id:0 topic:products/create updated_at:2024-01-31T18:21:06+08:00]
	*/
	Webhook Webhook `json:"webhook,omitempty" url:"-"`
}
