// Package transactions generated by SHOPLINE since v20260301
package transactions

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *LocationCreatedEvent) GetSupportedTopic() string {
	return "logistics/create"
}

type LocationCreatedEvent struct {
	client.WebhookEvent
	/*
	   Update time
	   Example:
	*/
	UpdateTime string `json:"update_time,omitempty" url:"-"`

	/*
	   Postal code
	   Example:
	*/
	ZipCode string `json:"zip_code,omitempty" url:"-"`

	/*
	   Detailed address
	   Example:
	*/
	Address string `json:"address,omitempty" url:"-"`

	/*
	   Detailed address 2
	   Example:
	*/
	AddressAdd string `json:"address_add,omitempty" url:"-"`

	/*
	   City
	   Example:
	*/
	City string `json:"city,omitempty" url:"-"`

	/*
	   Country
	   Example:
	*/
	Country string `json:"country,omitempty" url:"-"`

	/*
	   Creation time
	   Example:
	*/
	CreateTime string `json:"create_time,omitempty" url:"-"`

	/*
	   Location name
	   Example:
	*/
	Name string `json:"name,omitempty" url:"-"`

	/*
	   Telephone number
	   Example:
	*/
	Phone string `json:"phone,omitempty" url:"-"`

	/*
	   Province
	   Example:
	*/
	Province string `json:"province,omitempty" url:"-"`

	/*
	   Country code
	   Example:
	*/
	CountryCode string `json:"country_code,omitempty" url:"-"`

	/*
	   Location id
	   Example: 0
	*/
	Id int64 `json:"id,omitempty" url:"-"`

	/*
	   Province-coding
	   Example:
	*/
	ProvinceCode string `json:"province_code,omitempty" url:"-"`

	/*
	   True : false enabled : deactivation
	   Example: false
	*/
	Status bool `json:"status,omitempty" url:"-"`
}
