// Package transactions generated by SHOPLINE since v20260301
package transactions

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *ReturnCreateEvent) GetSupportedTopic() string {
	return "return/create"
}

type ReturnCreateEvent struct {
	client.WebhookEvent
	/*
	   Return id
	   Example: 2606576826460396889110
	*/
	AfterSaleOrderSeq string `json:"after_sale_order_seq,omitempty" url:"-"`

	/*
	   Order update time , ( format see IOS8601 )
	   Example: 2024-07-30T19:05:13.968+0800
	*/
	CreatedAt string `json:"created_at,omitempty" url:"-"`

	/*
	   Order id
	   Example: 21064997045395244145024325
	*/
	OrderSeq string `json:"order_seq,omitempty" url:"-"`

	/*
	   Return listing
	   Example: []
	*/
	ReturnLineItems []ReturnLineItem `json:"return_line_items,omitempty" url:"-"`

	/*
	   Return reason
	   Example: this is a test return reason
	*/
	ReturnReason string `json:"return_reason,omitempty" url:"-"`

	/*
	   Return status : REQUESTED 、CLOSED ( return is completed and refunded is completed ) 、OPEN ( in return ) 、DECLINED ( reject return ) 、CANCELED ( cancel return )
	   Example: OPEN
	*/
	Status string `json:"status,omitempty" url:"-"`
}

type FulfillmentLineItem struct {
	/*
	   Product
	   Example: map[attribute:Color - RED final_price:20 fulfillable_quantity:0 fulfillment_service:Yuan Tong Delivery fulfillment_status:fulfilled gift_card:false grams:28350 group_id:0 id:7889 image_url:https://www.asdlj22lljsf.com/gima.image location_seq:12123898712312 name:mock product title price:200.00 product_id:16065603540221212797880910 product_tax_lines:[] properties:[] quantity:3 requires_shipping:true sku:T20200925200122 tags:BWP,CUSTOM taxable:false title:mock product title variant_id:18065603540226245962750910 variant_title:RED vendor:mock product vendor version:0]
	*/
	LineItem ReturnCreateEventLineItem `json:"line_item,omitempty" url:"-"`

	/*
	   Return order return quantity
	   Example: 1
	*/
	Quantity int `json:"quantity,omitempty" url:"-"`
}

type ProductTaxLine struct {
	/*
	   Tax name
	   Example: VAT
	*/
	Title string `json:"title,omitempty" url:"-"`

	/*
	   Tax type
	   Example: product_tax
	*/
	Type string `json:"type,omitempty" url:"-"`

	/*
	   Tax name
	   Example: VAT
	*/
	Name string `json:"name,omitempty" url:"-"`

	/*
	   Tax
	   Example: 1.39
	*/
	Price string `json:"price,omitempty" url:"-"`

	/*
	   Tax amount details
	   Example: map[presentment_money:map[amount:20 currency_code:USD] shop_money:map[amount:20 currency_code:USD]]
	*/
	PriceSet PriceSet `json:"price_set,omitempty" url:"-"`

	/*
	   Tax rate
	   Example: 0.0012
	*/
	Rate float64 `json:"rate,omitempty" url:"-"`

	/*
	   Tax %
	   Example: 0
	*/
	RatePercentage float64 `json:"rate_percentage,omitempty" url:"-"`

	/*
	   Tax code
	   Example: 123343
	*/
	TaxNo string `json:"tax_no,omitempty" url:"-"`
}

type ReturnLineItem struct {
	/*
	   Return order return quantity
	   Example: 1
	*/
	Quantity int `json:"quantity,omitempty" url:"-"`

	/*
	   Return order Product line number
	   Example: RDP6576826460816319513
	*/
	RefundDetailSeq string `json:"refund_detail_seq,omitempty" url:"-"`

	/*
	   Product line return reason : COLOR issue DEFECTIVE Product damaged or defective NOT_AS_DESCRIBED Product does not match description OTHER reason SIZE_TOO_LARGE size is too large size_TOO_SMALL size is too small STYLE issue UNWANTED customer changed idea WRONG_ITEM received wrong Product
	   Example: this is a mock return reason
	*/
	ReturnReason string `json:"return_reason,omitempty" url:"-"`

	/*
	   Product line return reason details notes , maximum support 128 characters
	   Example: this is a mock return reason note
	*/
	ReturnReasonNote string `json:"return_reason_note,omitempty" url:"-"`

	/*
	   Forward invoice Product
	   Example: map[line_item:map[attribute:Color - RED final_price:20 fulfillable_quantity:0 fulfillment_service:Yuan Tong Delivery fulfillment_status:fulfilled gift_card:false grams:28350 group_id:0 id:7889 image_url:https://www.asdlj22lljsf.com/gima.image location_seq:12123898712312 name:mock product title price:200.00 product_id:16065603540221212797880910 product_tax_lines:[] properties:[] quantity:3 requires_shipping:true sku:T20200925200122 tags:BWP,CUSTOM taxable:false title:mock product title variant_id:18065603540226245962750910 variant_title:RED vendor:mock product vendor version:0] quantity:1]
	*/
	FulfillmentLineItem FulfillmentLineItem `json:"fulfillment_line_item,omitempty" url:"-"`

	/*
	   Invoice number associated with return order
	   Example: 22065768243292542110023140
	*/
	OrderPackageSeq string `json:"order_package_seq,omitempty" url:"-"`
}

type ReturnCreateEventLineItem struct {
	/*
	   Product selling price
	   Example: 200.00
	*/
	Price string `json:"price,omitempty" url:"-"`

	/*
	   Product tax information
	   Example: []
	*/
	ProductTaxLines []ProductTaxLine `json:"product_tax_lines,omitempty" url:"-"`

	/*
	   Product yards
	   Example: T20200925200122
	*/
	Sku string `json:"sku,omitempty" url:"-"`

	/*
	   Tax or not？
	   Example: false
	*/
	Taxable bool `json:"taxable,omitempty" url:"-"`

	/*
	   Supplier
	   Example: mock product vendor
	*/
	Vendor string `json:"vendor,omitempty" url:"-"`

	/*
	   Available quantity
	   Example: 0
	*/
	FulfillableQuantity int `json:"fulfillable_quantity,omitempty" url:"-"`

	/*
	   Gift card or not
	   Example: false
	*/
	GiftCard bool `json:"gift_card,omitempty" url:"-"`

	/*
	   Weight ( grams ) , involving unit conversion
	   Example: 28350
	*/
	Grams float64 `json:"grams,omitempty" url:"-"`

	/*
	   SKU title, same as title
	   Example: mock product title
	*/
	Name string `json:"name,omitempty" url:"-"`

	/*
	   SPU serial number
	   Example: 16065603540221212797880910
	*/
	ProductId string `json:"product_id,omitempty" url:"-"`

	/*
	   Product tag , separated by ','
	   Example: BWP,CUSTOM
	*/
	Tags string `json:"tags,omitempty" url:"-"`

	/*
	   Product title
	   Example: mock product title
	*/
	Title string `json:"title,omitempty" url:"-"`

	/*
	   Product attributes : name-attribute value
	   Example: Color - RED
	*/
	Attribute string `json:"attribute,omitempty" url:"-"`

	/*
	   Product transaction price
	   Example: 20
	*/
	FinalPrice string `json:"final_price,omitempty" url:"-"`

	/*
	   Picture url
	   Example: https://www.asdlj22lljsf.com/gima.image
	*/
	ImageUrl string `json:"image_url,omitempty" url:"-"`

	/*
	   Unique code of pickup location
	   Example: 12123898712312
	*/
	LocationSeq string `json:"location_seq,omitempty" url:"-"`

	/*
	   Product able custom information
	   Example: []
	*/
	Properties []ReturnCreateEventProperty `json:"properties,omitempty" url:"-"`

	/*
	   Quantity of items in the order
	   Example: 3
	*/
	Quantity int `json:"quantity,omitempty" url:"-"`

	/*
	   Shipping or not
	   Example: true
	*/
	RequiresShipping bool `json:"requires_shipping,omitempty" url:"-"`

	/*
	   Product SKU serial number
	   Example: 18065603540226245962750910
	*/
	VariantId string `json:"variant_id,omitempty" url:"-"`

	/*
	   Item group id
	   Example: 0
	*/
	GroupId string `json:"group_id,omitempty" url:"-"`

	/*
	   Product id for snapshot charts
	   Example: 7889
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   Product attribute value
	   Example: RED
	*/
	VariantTitle string `json:"variant_title,omitempty" url:"-"`

	/*
	   Product version
	   Example: 0
	*/
	Version string `json:"version,omitempty" url:"-"`

	/*
	   Logistics company name
	   Example: Yuan Tong Delivery
	*/
	FulfillmentService string `json:"fulfillment_service,omitempty" url:"-"`

	/*
	   Product shipping status
	   Example: fulfilled
	*/
	FulfillmentStatus string `json:"fulfillment_status,omitempty" url:"-"`
}

type PriceSet struct {
	/*
	   Market currency amount breakdown
	   Example: map[amount:20 currency_code:USD]
	*/
	PresentmentMoney PresentmentMoney `json:"presentment_money,omitempty" url:"-"`

	/*
	   Store currency amount breakdown
	   Example: map[amount:20 currency_code:USD]
	*/
	ShopMoney ShopMoney `json:"shop_money,omitempty" url:"-"`
}

type PresentmentMoney struct {
	/*
	   Amount
	   Example: 20
	*/
	Amount string `json:"amount,omitempty" url:"-"`

	/*
	   Currency
	   Example: USD
	*/
	CurrencyCode string `json:"currency_code,omitempty" url:"-"`
}

type ShopMoney struct {
	/*
	   Amount
	   Example: 20
	*/
	Amount string `json:"amount,omitempty" url:"-"`

	/*
	   Currency
	   Example: USD
	*/
	CurrencyCode string `json:"currency_code,omitempty" url:"-"`
}

type ReturnCreateEventProperty struct {
	/*
	   To be displayed on the front end or not
	   Example: true
	*/
	Show bool `json:"show,omitempty" url:"-"`

	/*
	   Attribute type
	   Example: Color
	*/
	Type string `json:"type,omitempty" url:"-"`

	/*
	   Url list
	   Example: [https://www.asdlj22lljsf.com/mock_title]
	*/
	Urls []string `json:"urls,omitempty" url:"-"`

	/*
	   Custom attribute values
	   Example: Red
	*/
	Value string `json:"value,omitempty" url:"-"`

	/*
	   Additional information
	   Example:
	*/
	Additional string `json:"additional,omitempty" url:"-"`

	/*
	   Expand information
	   Example:
	*/
	ExtInfo string `json:"ext_info,omitempty" url:"-"`

	/*
	   Custom attribute name
	   Example: Color
	*/
	Name string `json:"name,omitempty" url:"-"`
}
