// Package customers generated by SHOPLINE since v20251201
package customers

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *CustomerGroupCreationEvent) GetSupportedTopic() string {
	return "customer_groups/create"
}

type CustomerGroupCreationEvent struct {
	client.WebhookEvent
	/*
	   Update time
	   Example: 2022-05-31T15:32:46+08:00
	*/
	UpdatedAt string `json:"updated_at,omitempty"`

	/*
	   Creation time
	   Example: 2022-05-31T15:32:46+08:00
	*/
	CreatedAt string `json:"created_at,omitempty"`

	/*
	   Group id
	   Example: GROUP46234284793
	*/
	Id string `json:"id,omitempty"`

	/*
	   Group name
	   Example: High Level Customer
	*/
	Name string `json:"name,omitempty"`

	/*
	   Grouping conditions
	   Example: ordersCount:>2
	*/
	Query string `json:"query,omitempty"`
}
