// Package customers generated by SHOPLINE since v20251201
package customers

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *CustomerRegisteredLoginEvent) GetSupportedTopic() string {
	return "customers/action"
}

type CustomerRegisteredLoginEvent struct {
	client.WebhookEvent
	/*
	   Channels
	   Example: "EC_H5"
	*/
	Channel string `json:"channel,omitempty"`

	/*
	   Mailbox subscription status 0 : cancelled subscription , 1 : already available , 2 : not subscribe
	   Example: 1
	*/
	EmailSubscribeFlag int `json:"emailSubscribeFlag,omitempty"`

	/*
	   Login date
	   Example: 2022-12-16T11:06:11+08:00
	*/
	LoginDate string `json:"login_date,omitempty"`

	/*
	   Mobile phone subscription status 0 : cancelled subscription , 1 : already available , 2 : not subscribe
	   Example: 1
	*/
	MobileSubscribeFlag int `json:"mobileSubscribeFlag,omitempty"`

	/*
	   Registration date
	   Example: 2022-12-16T11:06:11+08:00
	*/
	RegistryDate string `json:"registry_date,omitempty"`

	/*
	   Customer id
	   Example: "4203823842"
	*/
	Uid string `json:"uid,omitempty"`

	/*
	   Behavior
	   Example: "REGISTRY","LOGIN"
	*/
	Action string `json:"action,omitempty"`
}
