// Package customers generated by SHOPLINE since v20251201
package customers

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *CustomerEditingEvent) GetSupportedTopic() string {
	return "customers/update"
}

type CustomerEditingEvent struct {
	client.WebhookEvent
	/*
	   Accept telemarketing or not
	   Example: true
	*/
	AcceptsMobileMarketing bool `json:"accepts_mobile_marketing,omitempty"`

	/*
	   Name
	   Example: Bob
	*/
	FirstName string `json:"first_name,omitempty"`

	/*
	   Customer language
	   Example: en
	*/
	Language string `json:"language,omitempty"`

	/*
	   Customer status [ 0 : disabled account , 1 : to enable account , 2 : invited account , 3 : valid account ]
	   Example: 2
	*/
	State int `json:"state,omitempty"`

	/*
	   Customer tag
	   Example: good
	*/
	Tags string `json:"tags,omitempty"`

	/*
	   Verify if e-mail or not
	   Example: true
	*/
	VerifiedEmail bool `json:"verified_email,omitempty"`

	/*
	   Customer birthday Format: YYYYMMDD
	   Example: 19900625
	*/
	Birthday string `json:"birthday,omitempty"`

	/*
	   Recent order number
	   Example: 200832869120938
	*/
	LastOrderId string `json:"last_order_id,omitempty"`

	/*
	   Telephone subscription time (see IOS8601 for the format)
	   Example: 2022-12-16T11:06:11+08:00
	*/
	AcceptsMobileMarketingUpdatedAt string `json:"accepts_mobile_marketing_updated_at,omitempty"`

	/*
	   Default address
	   Example: map[address1:7720 Cherokee Road address2:Apartment city:Hagerman company:Joy country:United States country_code:US customer_id:200838473 default:true first_name:Bob id:SL201UA5006511321220969539 last_name:James phone:008613965748321 province:Kentucky province_code:KY zip:40202]
	*/
	DefaultAddress DefaultAddress `json:"default_address,omitempty"`

	/*
	   Mailbox subscription status 0 : cancelled subscription , 1 : already available , 2 : not available
	   Example: 2
	*/
	EmailSubscribeFlag int `json:"email_subscribe_flag,omitempty"`

	/*
	   Last name
	   Example: James
	*/
	LastName string `json:"last_name,omitempty"`

	/*
	   Mobile phone subscription status 0 : cancelled subscription , 1 : already available , 2 : not available
	   Example: 2
	*/
	MobileSubscribeFlag int `json:"mobile_subscribe_flag,omitempty"`

	/*
	   Phone number
	   Example: 008613987864352
	*/
	Phone string `json:"phone,omitempty"`

	/*
	   Sms marketing subscription information
	   Example: map[consent_collected_from:Subscription information source consent_updated_at:2022-12-16T11:06:11+08:00 opt_in_level:1 state:1]
	*/
	SmsMarketingConsent SmsMarketingConsent `json:"sms_marketing_consent,omitempty"`

	/*
	   Total cost amount
	   Example: 324324
	*/
	TotalSpent string `json:"total_spent,omitempty"`

	/*
	   E-mail marketing subscription information
	   Example: map[consent_collected_from:Subscription information source consent_updated_at:2022-12-16T11:06:11+08:00 opt_in_level:2 state:2]
	*/
	EmailMarketingConsent EmailMarketingConsent `json:"email_marketing_consent,omitempty"`

	/*
	   User nickname
	   Example: Bob James
	*/
	NickName string `json:"nick_name,omitempty"`

	/*
	   Order quantity
	   Example: 4223
	*/
	OrdersCount int64 `json:"orders_count,omitempty"`

	/*
	   Creation time
	   Example: 2022-12-16T11:06:11+08:00
	*/
	CreatedAt string `json:"created_at,omitempty"`

	/*
	   Notes
	   Example: test
	*/
	Note string `json:"note,omitempty"`

	/*
	   Mailbox subscription time
	   Example: 2022-12-16T11:06:11+08:00
	*/
	AcceptsMarketingUpdatedAt string `json:"accepts_marketing_updated_at,omitempty"`

	/*
	   Address information list
	   Example: []
	*/
	Addresses []Addresse `json:"addresses,omitempty"`

	/*
	   FB login ID
	   Example: 542132312312323
	*/
	Asid string `json:"asid,omitempty"`

	/*
	   Currency
	   Example: CNY
	*/
	Currency string `json:"currency,omitempty"`

	/*
	   Gender : male / female / others/secret
	   Example: male
	*/
	Gender string `json:"gender,omitempty"`

	/*
	   Social media user ID
	   Example: 43245645353245
	*/
	SocialCustomer string `json:"social_customer,omitempty"`

	/*
	   Update time
	   Example: 2022-12-16T11:06:11+08:00
	*/
	UpdatedAt string `json:"updated_at,omitempty"`

	/*
	   Customer id
	   Example: 231321312321
	*/
	Id string `json:"id,omitempty"`

	/*
	   Multipass logo
	   Example: multipass_identifier
	*/
	MultipassIdentifier string `json:"multipass_identifier,omitempty"`

	/*
	   Subscription mail or not
	   Example: true
	*/
	AcceptsMarketing bool `json:"accepts_marketing,omitempty"`

	/*
	   Mailbox
	   Example: gungcherny@gamil.com
	*/
	Email string `json:"email,omitempty"`
}
