// Package customer generated by SHOPLINE since v20251201
package customer

import (
	"errors"
	"fmt"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type DeleteCustomerGroupingAPIReq struct {
	client.BaseAPIRequest
	/*
	   Customer grouping id
	   Example: GROUP5702593537218454508
	*/
	Id string `url:"-" json:"-"` // Required
}

func (req *DeleteCustomerGroupingAPIReq) GetEndpoint() string {

	return fmt.Sprintf("customer_saved_searches/%s.json", req.Id)

}

func (req *DeleteCustomerGroupingAPIReq) GetMethod() string {
	return "DELETE"
}

// Verify the api request parameters
func (req *DeleteCustomerGroupingAPIReq) Verify() error {

	if req.Id == "" {
		return errors.New("Id is required")
	}

	return nil
}

func (req *DeleteCustomerGroupingAPIReq) GetRequestOptions() *client.RequestOptions {
	opts := &client.RequestOptions{
		NotDecodeBody: true,
	}
	return opts
}

func (req *DeleteCustomerGroupingAPIReq) NewAPIResp() *DeleteCustomerGroupingAPIResp {
	return &DeleteCustomerGroupingAPIResp{}
}

type DeleteCustomerGroupingAPIResp struct {
	client.BaseAPIResponse
}
