// Package customer generated by SHOPLINE since v20251201
package customer

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

type RetrieveAListOfThirdPartyLoginConfigurationsOfStoreAPIReq struct {
	client.BaseAPIRequest
	/*
	   The login channel of the configuration. Possible values:
	   * apple
	   * facebook
	   * google
	   * line
	   * tiktok
	   Example: google
	*/
	LoginChannel string `url:"login_channel,omitempty" json:"-"`
	/*
	   The platform type of the login configuration. Possible values:
	   * web
	   * app
	   Example: web
	*/
	LoginPlatformType string `url:"login_platform_type,omitempty" json:"-"`
}

func (req *RetrieveAListOfThirdPartyLoginConfigurationsOfStoreAPIReq) GetEndpoint() string {

	return "customers_social_login.json"

}

func (req *RetrieveAListOfThirdPartyLoginConfigurationsOfStoreAPIReq) GetMethod() string {
	return "GET"
}

func (req *RetrieveAListOfThirdPartyLoginConfigurationsOfStoreAPIReq) GetQuery() interface{} {
	return req
}

// Verify the api request parameters
func (req *RetrieveAListOfThirdPartyLoginConfigurationsOfStoreAPIReq) Verify() error {

	return nil
}

func (req *RetrieveAListOfThirdPartyLoginConfigurationsOfStoreAPIReq) NewAPIResp() *RetrieveAListOfThirdPartyLoginConfigurationsOfStoreAPIResp {
	return &RetrieveAListOfThirdPartyLoginConfigurationsOfStoreAPIResp{}
}

type RetrieveAListOfThirdPartyLoginConfigurationsOfStoreAPIResp struct {
	client.BaseAPIResponse
	/*
	   data
	   Example: map[third_party_login_configurations:[map[login_channel:google login_platform_type:web third_app_id:demo third app id third_key:demo third key third_rsa_key:demo rsa key]]]
	*/
	Data RetrieveAListOfThirdPartyLoginConfigurationsOfStoreAPIRespData `json:"data,omitempty" url:"-"`
}

type RetrieveAListOfThirdPartyLoginConfigurationsOfStoreAPIRespData struct {
	/*
	   third party login configurations
	   Example: [map[login_channel:google login_platform_type:web third_app_id:demo third app id third_key:demo third key third_rsa_key:demo rsa key]]
	*/
	ThirdPartyLoginConfigurations []ThirdPartyLoginConfiguration `json:"third_party_login_configurations,omitempty" url:"-"`
}

type ThirdPartyLoginConfiguration struct {
	/*
	   The app secret of third-party app.
	   Example: demo third key
	*/
	ThirdKey string `json:"third_key,omitempty" url:"-"`

	/*
	   The RSA key of third-party app.
	   Example: demo rsa key
	*/
	ThirdRsaKey string `json:"third_rsa_key,omitempty" url:"-"`

	/*
	   The login channel of the configuration
	   Example: google
	*/
	LoginChannel string `json:"login_channel,omitempty" url:"-"`

	/*
	   The platform type of the login configuration.
	   Example: web
	*/
	LoginPlatformType string `json:"login_platform_type,omitempty" url:"-"`

	/*
	   The app ID of third-party app.
	   Example: demo third app id
	*/
	ThirdAppId string `json:"third_app_id,omitempty" url:"-"`
}
