// Package customer generated by SHOPLINE since v20251201
package customer

import (
	"errors"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type UpdateTheThirdPartyLoginConfigurationOfStoreAPIReq struct {
	client.BaseAPIRequest
	/*
	   The app ID of third-party app.
	   Example: demo third app id
	*/
	ThirdAppId string `json:"third_app_id,omitempty" url:"-"`

	/*
	   The app secret of third-party app.
	   Example: demo third key
	*/
	ThirdKey string `json:"third_key,omitempty" url:"-"`

	/*
	   The RSA key of third-party app.
	   Example: demo third rsa key
	*/
	ThirdRsaKey string `json:"third_rsa_key,omitempty" url:"-"`

	/*
	   The login channel of the configuration to be created or updated. Possible values:
	   * apple
	   * facebook
	   * google
	   * line
	   * tiktok
	   Example: google
	*/
	LoginChannel string `json:"login_channel,omitempty" url:"-"`

	/*
	   The platform type of the login configuration. Possible values:
	   * web
	   * app
	   Example: app
	*/
	LoginPlatformType string `json:"login_platform_type,omitempty" url:"-"`
}

func (req *UpdateTheThirdPartyLoginConfigurationOfStoreAPIReq) GetEndpoint() string {

	return "customers_social_login.json"

}

func (req *UpdateTheThirdPartyLoginConfigurationOfStoreAPIReq) GetMethod() string {
	return "POST"
}

func (req *UpdateTheThirdPartyLoginConfigurationOfStoreAPIReq) GetData() interface{} {
	return req
}

// Verify the api request parameters
func (req *UpdateTheThirdPartyLoginConfigurationOfStoreAPIReq) Verify() error {

	if req.LoginChannel == "" {
		return errors.New("LoginChannel is required")
	}

	return nil
}

func (req *UpdateTheThirdPartyLoginConfigurationOfStoreAPIReq) GetRequestOptions() *client.RequestOptions {
	opts := &client.RequestOptions{
		NotDecodeBody: true,
	}
	return opts
}

func (req *UpdateTheThirdPartyLoginConfigurationOfStoreAPIReq) NewAPIResp() *UpdateTheThirdPartyLoginConfigurationOfStoreAPIResp {
	return &UpdateTheThirdPartyLoginConfigurationOfStoreAPIResp{}
}

type UpdateTheThirdPartyLoginConfigurationOfStoreAPIResp struct {
	client.BaseAPIResponse
}
