// Package product generated by SHOPLINE since v20251201
package product

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *SalesPlanGroupCreationEvent) GetSupportedTopic() string {
	return "sellingplan/create"
}

type PricingPolicy struct {
	/*
	   Fixed price policy content
	   Example: map[adjustment_type:FIXED_AMOUNT adjustment_value:map[fixed_value:10 percentage:10]]
	*/
	Fixed Fixed `json:"fixed,omitempty"`

	/*
	   Strategy type , FIXED : fixed price strategy
	   Example: FIXED
	*/
	PolicyType string `json:"policy_type,omitempty"`
}

type Fixed struct {
	/*
	   Discount type , FIXED_AMOUNT : minus , PERCENTAGE : discount
	   Example: FIXED_AMOUNT
	*/
	AdjustmentType string `json:"adjustment_type,omitempty"`

	/*
	   Discount value
	   Example: map[fixed_value:10 percentage:10]
	*/
	AdjustmentValue AdjustmentValue `json:"adjustment_value,omitempty"`
}

type AdjustmentValue struct {
	/*
	   Deduction fixed amount
	   Example: 10
	*/
	FixedValue string `json:"fixed_value,omitempty"`

	/*
	   Subtraction percentage
	   Example: 10
	*/
	Percentage string `json:"percentage,omitempty"`
}

type BillingPolicy struct {
	/*
	   Periodic billing strategy content
	   Example: map[interval:DAY interval_count:10 max_cycles:1 min_cycles:1]
	*/
	Recurring Recurring `json:"recurring,omitempty"`

	/*
	   Strategy type , RECURRING : periodic billing strategy
	   Example: RECURRING
	*/
	PolicyType string `json:"policy_type,omitempty"`
}

type Recurring struct {
	/*
	   Billing frequency unit , DAY、MONTH、WEEK、YEAR
	   Example: DAY
	*/
	Interval string `json:"interval,omitempty"`

	/*
	   Billing interval
	   Example: 10
	*/
	IntervalCount int `json:"interval_count,omitempty"`

	/*
	   Maximum billing cycle
	   Example: 1
	*/
	MaxCycles int `json:"max_cycles,omitempty"`

	/*
	   Minimum billing cycle
	   Example: 1
	*/
	MinCycles int `json:"min_cycles,omitempty"`
}

type SalesPlanGroupCreationEvent struct {
	client.WebhookEvent
	/*
	   Sales program list
	   Example: []
	*/
	SellingPlans []SellingPlan `json:"selling_plans,omitempty"`

	/*
	   Sales plan group id
	   Example: 14056200245844372441100009
	*/
	Id string `json:"id,omitempty"`

	/*
	   Sales program group name
	   Example: Subscription plan group default name
	*/
	Name string `json:"name,omitempty"`

	/*
	   List of variant IDs.
	   Example: [["18065954560435138250532015"]]
	*/
	ProductVariantIds []string `json:"product_variant_ids,omitempty"`

	/*
	   Sales channel id
	   Example: c41ac9e6736785502d2333d1b1153aca795075c4
	*/
	AppId string `json:"app_id,omitempty"`

	/*
	   Description
	   Example: This is a description
	*/
	Description string `json:"description,omitempty"`

	/*
	   Show the name to the seller
	   Example: Subscription plan group default name
	*/
	MerchantCode string `json:"merchant_code,omitempty"`

	/*
	   List of sales program group options
	   Example: [["delivery every 1 months", "delivery every 2 months", "delivery every 3 months"]]
	*/
	Options []string `json:"options,omitempty"`

	/*
	   Display location
	   Example: 1
	*/
	Position int `json:"position,omitempty"`

	/*
	   Bangding id list for binding
	   Example: [["16057039432335097907370282"]]
	*/
	Products []string `json:"products,omitempty"`
}

type SellingPlan struct {
	/*
	   Sales program name
	   Example: delivery every 1 weeks
	*/
	Name string `json:"name,omitempty"`

	/*
	   List of sales program options
	   Example: [["Delivery every 10 days"]
	   ]
	*/
	Options []string `json:"options,omitempty"`

	/*
	   Display position , the smaller the more front
	   Example: 1
	*/
	Position int `json:"position,omitempty"`

	/*
	   Price policy
	   Example: []
	*/
	PricingPolicies []PricingPolicy `json:"pricing_policies,omitempty"`

	/*
	   Billing strategy
	   Example: map[policy_type:RECURRING recurring:map[interval:DAY interval_count:10 max_cycles:1 min_cycles:1]]
	*/
	BillingPolicy BillingPolicy `json:"billing_policy,omitempty"`

	/*
	   Sales plan description
	   Example: This is a description
	*/
	Description string `json:"description,omitempty"`

	/*
	   Sales plan id
	   Example: 14156213099368001129110062
	*/
	Id string `json:"id,omitempty"`
}
