// Package app generated by SHOPLINE since v20251201
package app

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

type BatchDeleteSizechartAPIReq struct {
	client.BaseAPIRequest
	/*
	   The IDs of `sizechart`.
	   Example: [[13266288837293171311580520, 13257619531582396231753144]]
	*/
	SizechartIds []string `json:"sizechart_ids,omitempty" url:"-"`
}

func (req *BatchDeleteSizechartAPIReq) GetEndpoint() string {

	return "sizecharts.json"

}

func (req *BatchDeleteSizechartAPIReq) GetMethod() string {
	return "DELETE"
}

func (req *BatchDeleteSizechartAPIReq) GetData() interface{} {
	return req
}

// Verify the api request parameters
func (req *BatchDeleteSizechartAPIReq) Verify() error {

	return nil
}

func (req *BatchDeleteSizechartAPIReq) GetRequestOptions() *client.RequestOptions {
	opts := &client.RequestOptions{
		NotDecodeBody: true,
	}
	return opts
}

func (req *BatchDeleteSizechartAPIReq) NewAPIResp() *BatchDeleteSizechartAPIResp {
	return &BatchDeleteSizechartAPIResp{}
}

type BatchDeleteSizechartAPIResp struct {
	client.BaseAPIResponse
}
