// Package product generated by SHOPLINE since v20251201
package product

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *DeleteProductEvent) GetSupportedTopic() string {
	return "products/delete"
}

type DeleteProductEvent struct {
	client.WebhookEvent
	/*
	   Product ID
	   Example:
	*/
	Id string `json:"id,omitempty"`
}
