// Package product generated by SHOPLINE since v20251201
package product

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *DeleteInventoryObjectEvent) GetSupportedTopic() string {
	return "inventory_items/delete"
}

type DeleteInventoryObjectEvent struct {
	client.WebhookEvent
	/*
	   Inventory id
	   Example: 5703943240925324252
	*/
	Id string `json:"id,omitempty"`
}
