// Package marketing generated by SHOPLINE since v20260301
package marketing

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *DiscountCodeDeleteIncidentEvent) GetSupportedTopic() string {
	return "discountcode/delete"
}

type DiscountCodeDeleteIncidentEvent struct {
	client.WebhookEvent
	/*
	   Serial number
	   Example: SL201SAS44906445806419601454
	*/
	ActivitySeq string `json:"activitySeq,omitempty" url:"-"`

	/*
	   Promo code
	   Example: XTDHUDE
	*/
	PromotionCode string `json:"promotionCode,omitempty" url:"-"`

	/*
	   store ID
	   Example: 1612338733229
	*/
	StoreId string `json:"storeId,omitempty" url:"-"`
}
