// Package marketing generated by SHOPLINE since v20251201
package marketing

import (
	"errors"
	"fmt"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type CreateDiscountCodeAPIReq struct {
	client.BaseAPIRequest
	/*
	   Price rule id
	   Example: 6018703930879383908
	*/
	PriceRuleId string `url:"-" json:"-"` // Required
	/*
	   discount code
	   Example: map[code:DISCOUNT_CODE_CONTENT price_rule_id:6018703930879383908
	   ]
	*/
	DiscountCode CreateDiscountCodeAPIReqDiscountCode `json:"discount_code,omitempty" url:"-"`
}

type CreateDiscountCodeAPIReqDiscountCode struct {
	/*
	   Discount code content
	   Example: DISCOUNT_CODE_CONTENT
	*/
	Code string `json:"code,omitempty" url:"-"`

	/*
	   Discount code rules id
	   Example: 6018703930879383908
	*/
	PriceRuleId string `json:"price_rule_id,omitempty" url:"-"`
}

func (req *CreateDiscountCodeAPIReq) GetEndpoint() string {

	return fmt.Sprintf("sales/price_rules/%s/discount_codes.json", req.PriceRuleId)

}

func (req *CreateDiscountCodeAPIReq) GetMethod() string {
	return "POST"
}

func (req *CreateDiscountCodeAPIReq) GetData() interface{} {
	return req
}

// Verify the api request parameters
func (req *CreateDiscountCodeAPIReq) Verify() error {

	if req.PriceRuleId == "" {
		return errors.New("PriceRuleId is required")
	}

	return nil
}

func (req *CreateDiscountCodeAPIReq) NewAPIResp() *CreateDiscountCodeAPIResp {
	return &CreateDiscountCodeAPIResp{}
}

type CreateDiscountCodeAPIResp struct {
	client.BaseAPIResponse
	/*
	   Discount code entity
	   Example: map[code:DISCOUNT_CODE_CONTENT create_at:2023-07-12T00:08:02+08:00 id:6019053959104174638 price_rule_id:6018703930879383908 update_at:2023-07-12T00:08:02+08:00 usage_count:0]
	*/
	DiscountCode CreateDiscountCodeAPIRespDiscountCode `json:"discount_code,omitempty" url:"-"`
}

type CreateDiscountCodeAPIRespDiscountCode struct {
	/*
	   Discount code content
	   Example: DISCOUNT_CODE_CONTENT
	*/
	Code string `json:"code,omitempty" url:"-"`

	/*
	   Discount code created time
	   Example: 2023-07-12T00:08:02+08:00
	*/
	CreateAt string `json:"create_at,omitempty" url:"-"`

	/*
	   Id for discount code
	   Example: 6019053959104174638
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   Id for discount price rule
	   Example: 6018703930879383908
	*/
	PriceRuleId string `json:"price_rule_id,omitempty" url:"-"`

	/*
	   Update time for discount code
	   Example: 2023-07-12T00:08:02+08:00
	*/
	UpdateAt string `json:"update_at,omitempty" url:"-"`

	/*
	   Number of times used in discount codes
	   Example: 0
	*/
	UsageCount int `json:"usage_count,omitempty" url:"-"`
}
