// Package marketing generated by SHOPLINE since v20251201
package marketing

import (
	"errors"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type ProcessStatisticsSynchronizationAPIReq struct {
	client.BaseAPIRequest
	/*
	   appKey
	   Example: ee89294e244543bd9422b446de9dece9cf0ea14e
	*/
	AppKey string `json:"app_key,omitempty" url:"-"`

	/*
	   Data list , max 100
	   Example: [map[delete_flow_node_data_list:[map[bounce_rate:10 buyer_num:5 click_rate:56.6 fail_rate:0 has_delivery_num:5 has_send_num:5 node_id:5a206848-5e7e-4e50-93de-01bb4d9c7ac5 occurred_on:1.6723656e+12 open_rate:4 order_amount:344 order_num:5 parent_node_id:5a206848-5e7e-4e50-93de-01bb4d9c7ac5 preview_image_url: unsubscribe_rate:0]] flow_id:5598349859474639045 flow_node_data_list:[map[bounce_rate:3 buyer_num:4 click_rate:80 fail_rate:80 has_delivery_num:3 has_send_num:3 node_id:5a206848-5e7e-4e50-93de-01bb4d9c7ac5 occurred_on:1.6723656e+12 open_rate:3 order_amount:220 order_num:4 parent_node_id:5a206848-5e7e-4e50-93de-01bb4d9c7ac5 preview_image_url:https://kmalgo.oss-ap-southeast-1.aliyuncs.com/material_ec2/2022-09-24/be7a1b5b947d47529c97bc78de6b unsubscribe_rate:0]] occurred_on:1.6723656e+12 order_amount:0 order_num:0 send_count:1 trigger_num:4]]
	*/
	FlowDataList []ProcessStatisticsSynchronizationAPIReqFlowDataList `json:"flow_data_list,omitempty" url:"-"`

	/*
	   Source type
	   Example: smartpush-app
	*/
	SourceType string `json:"source_type,omitempty" url:"-"`

	/*
	   Store id
	   Example: 1658921299465
	*/
	StoreId string `json:"store_id,omitempty" url:"-"`
}

type DeleteFlowNodeDataList struct {
	/*
	   Sent quantity
	   Example: 5
	*/
	HasSendNum int64 `json:"has_send_num,omitempty" url:"-"`

	/*
	   Node id
	   Example: 5a206848-5e7e-4e50-93de-01bb4d9c7ac5
	*/
	NodeId string `json:"node_id,omitempty" url:"-"`

	/*
	   Data time , millisecond time stamp
	   Example: 1.6723656e+12
	*/
	OccurredOn int64 `json:"occurred_on,omitempty" url:"-"`

	/*
	   Delivery quantity
	   Example: 5
	*/
	HasDeliveryNum int64 `json:"has_delivery_num,omitempty" url:"-"`

	/*
	   Bounce back rate
	   Example: 10
	*/
	BounceRate string `json:"bounce_rate,omitempty" url:"-"`

	/*
	   Failure rate
	   Example: 0
	*/
	FailRate string `json:"fail_rate,omitempty" url:"-"`

	/*
	   Opening rate
	   Example: 4
	*/
	OpenRate string `json:"open_rate,omitempty" url:"-"`

	/*
	   Preview picture url
	   Example:
	*/
	PreviewImageUrl string `json:"preview_image_url,omitempty" url:"-"`

	/*
	   The cancellation rate
	   Example: 0
	*/
	UnsubscribeRate string `json:"unsubscribe_rate,omitempty" url:"-"`

	/*
	   Number of orders
	   Example: 5
	*/
	OrderNum int64 `json:"order_num,omitempty" url:"-"`

	/*
	   Click-through
	   Example: 56.6
	*/
	ClickRate string `json:"click_rate,omitempty" url:"-"`

	/*
	   Sales , unit division
	   Example: 344
	*/
	OrderAmount int64 `json:"order_amount,omitempty" url:"-"`

	/*
	   Parent node id for sorting , merge show
	   Example: 5a206848-5e7e-4e50-93de-01bb4d9c7ac5
	*/
	ParentNodeId string `json:"parent_node_id,omitempty" url:"-"`

	/*
	   Number of users ordered
	   Example: 5
	*/
	BuyerNum int64 `json:"buyer_num,omitempty" url:"-"`
}

type ProcessStatisticsSynchronizationAPIReqFlowDataList struct {
	/*
	   Sales
	   Example: [map[bounce_rate:3 buyer_num:4 click_rate:80 fail_rate:80 has_delivery_num:3 has_send_num:3 node_id:5a206848-5e7e-4e50-93de-01bb4d9c7ac5 occurred_on:1.6723656e+12 open_rate:3 order_amount:220 order_num:4 parent_node_id:5a206848-5e7e-4e50-93de-01bb4d9c7ac5 preview_image_url:https://kmalgo.oss-ap-southeast-1.aliyuncs.com/material_ec2/2022-09-24/be7a1b5b947d47529c97bc78de6b unsubscribe_rate:0]]
	*/
	FlowNodeDataList []FlowNodeDataList `json:"flow_node_data_list,omitempty" url:"-"`

	/*
	   Data time , millisecond time stamp
	   Example: 1.6723656e+12
	*/
	OccurredOn int64 `json:"occurred_on,omitempty" url:"-"`

	/*
	   Sales , unit division
	   Example: 0
	*/
	OrderAmount int64 `json:"order_amount,omitempty" url:"-"`

	/*
	   Order qty
	   Example: 0
	*/
	OrderNum int64 `json:"order_num,omitempty" url:"-"`

	/*
	   Number of send
	   Example: 1
	*/
	SendCount int64 `json:"send_count,omitempty" url:"-"`

	/*
	   Trigger count
	   Example: 4
	*/
	TriggerNum int64 `json:"trigger_num,omitempty" url:"-"`

	/*
	   Process activity removed
	   Example: [map[bounce_rate:10 buyer_num:5 click_rate:56.6 fail_rate:0 has_delivery_num:5 has_send_num:5 node_id:5a206848-5e7e-4e50-93de-01bb4d9c7ac5 occurred_on:1.6723656e+12 open_rate:4 order_amount:344 order_num:5 parent_node_id:5a206848-5e7e-4e50-93de-01bb4d9c7ac5 preview_image_url: unsubscribe_rate:0]]
	*/
	DeleteFlowNodeDataList []DeleteFlowNodeDataList `json:"delete_flow_node_data_list,omitempty" url:"-"`

	/*
	   Process id
	   Example: 5598349859474639045
	*/
	FlowId string `json:"flow_id,omitempty" url:"-"`
}

type FlowNodeDataList struct {
	/*
	   Failure rate
	   Example: 80
	*/
	FailRate string `json:"fail_rate,omitempty" url:"-"`

	/*
	   Sent quantity
	   Example: 3
	*/
	HasSendNum int64 `json:"has_send_num,omitempty" url:"-"`

	/*
	   Node id
	   Example: 5a206848-5e7e-4e50-93de-01bb4d9c7ac5
	*/
	NodeId string `json:"node_id,omitempty" url:"-"`

	/*
	   Opening rate
	   Example: 3
	*/
	OpenRate string `json:"open_rate,omitempty" url:"-"`

	/*
	   Parent node id for sorting , merge show
	   Example: 5a206848-5e7e-4e50-93de-01bb4d9c7ac5
	*/
	ParentNodeId string `json:"parent_node_id,omitempty" url:"-"`

	/*
	   Delivery quantity
	   Example: 3
	*/
	HasDeliveryNum int64 `json:"has_delivery_num,omitempty" url:"-"`

	/*
	   Bounce back rate
	   Example: 3
	*/
	BounceRate string `json:"bounce_rate,omitempty" url:"-"`

	/*
	   Data time , millisecond time stamp
	   Example: 1.6723656e+12
	*/
	OccurredOn int64 `json:"occurred_on,omitempty" url:"-"`

	/*
	   Preview picture url
	   Example: https://kmalgo.oss-ap-southeast-1.aliyuncs.com/material_ec2/2022-09-24/be7a1b5b947d47529c97bc78de6b
	*/
	PreviewImageUrl string `json:"preview_image_url,omitempty" url:"-"`

	/*
	   Number of users ordered
	   Example: 4
	*/
	BuyerNum int64 `json:"buyer_num,omitempty" url:"-"`

	/*
	   Number of orders
	   Example: 4
	*/
	OrderNum int64 `json:"order_num,omitempty" url:"-"`

	/*
	   The cancellation rate
	   Example: 0
	*/
	UnsubscribeRate string `json:"unsubscribe_rate,omitempty" url:"-"`

	/*
	   Click-through
	   Example: 80
	*/
	ClickRate string `json:"click_rate,omitempty" url:"-"`

	/*
	   Sales , unit division
	   Example: 220
	*/
	OrderAmount int64 `json:"order_amount,omitempty" url:"-"`
}

func (req *ProcessStatisticsSynchronizationAPIReq) GetEndpoint() string {

	return "sales/flow/batch_sync_flow_data.json"

}

func (req *ProcessStatisticsSynchronizationAPIReq) GetMethod() string {
	return "POST"
}

func (req *ProcessStatisticsSynchronizationAPIReq) GetData() interface{} {
	return req
}

// Verify the api request parameters
func (req *ProcessStatisticsSynchronizationAPIReq) Verify() error {

	if req.AppKey == "" {
		return errors.New("AppKey is required")
	}

	if req.SourceType == "" {
		return errors.New("SourceType is required")
	}

	if req.StoreId == "" {
		return errors.New("StoreId is required")
	}

	return nil
}

func (req *ProcessStatisticsSynchronizationAPIReq) GetRequestOptions() *client.RequestOptions {
	opts := &client.RequestOptions{
		NotDecodeBody: true,
	}
	return opts
}

func (req *ProcessStatisticsSynchronizationAPIReq) NewAPIResp() *ProcessStatisticsSynchronizationAPIResp {
	return &ProcessStatisticsSynchronizationAPIResp{}
}

type ProcessStatisticsSynchronizationAPIResp struct {
	client.BaseAPIResponse
}
