// Package marketing generated by SHOPLINE since v20251201
package marketing

import (
	"errors"
	"fmt"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type QueryIndividualMarketingEventsAPIReq struct {
	client.BaseAPIRequest
	/*
	   Yingxiao id for marketing events
	   Example: MA_6062143268514178052
	*/
	MarketingEventId string `url:"-" json:"-"` // Required
}

func (req *QueryIndividualMarketingEventsAPIReq) GetEndpoint() string {

	return fmt.Sprintf("sales/marketing_events/%s.json", req.MarketingEventId)

}

func (req *QueryIndividualMarketingEventsAPIReq) GetMethod() string {
	return "GET"
}

// Verify the api request parameters
func (req *QueryIndividualMarketingEventsAPIReq) Verify() error {

	if req.MarketingEventId == "" {
		return errors.New("MarketingEventId is required")
	}

	return nil
}

func (req *QueryIndividualMarketingEventsAPIReq) NewAPIResp() *QueryIndividualMarketingEventsAPIResp {
	return &QueryIndividualMarketingEventsAPIResp{}
}

type QueryIndividualMarketingEventsAPIResp struct {
	client.BaseAPIResponse
	/*
	   Marketing events
	   Example: map[description:This is description for the marketing event ended_at:2023-12-15T09:00:00+08:00 event_type:ad id:6019937483067761963 manage_url:https://manong.myshopline.com/admin/ marketing_channel:search marketing_event_id:MA_6019942645165466925 preview_url:https://manong.myshopline.com/ referring_domain:manong.myshopline.com remote_id:6019937434467761334 started_at:2022-12-15T09:00:00+08:00 utm_campaign:google utm_content:googleAds utm_medium:email utm_source:manong.myshopline.com utm_term:This key word for search]
	*/
	MarketingEvent MarketingEvent `json:"marketing_event,omitempty" url:"-"`
}
