// Package marketing generated by SHOPLINE since v20251201
package marketing

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *PriceRuleUpdatedEvent) GetSupportedTopic() string {
	return "pricerule/update"
}

type PriceRuleUpdatedEvent struct {
	client.WebhookEvent
	/*
	   The unique identifier for the price rule.
	   Example:
	*/
	PriceRuleId string `json:"priceRuleId,omitempty"`

	/*
	   The unique identifier for the store.
	   Example:
	*/
	StoreId string `json:"storeId,omitempty"`
}
