// Package buildingstation generated by SHOPLINE since v20260301
package buildingstation

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *CustomPageUpdatedEvent) GetSupportedTopic() string {
	return "page/update"
}

type CustomPageUpdatedEvent struct {
	client.WebhookEvent
	/*
	   Title of the custom page.
	   Example: Custom page
	*/
	Title string `json:"title,omitempty" url:"-"`

	/*
	   The update time of the custom page. Format: `yyyy-MM-dd HH:mm:ss.SSS`.
	   Example: 2023-09-11 16:49:35.120
	*/
	UpdatedAt string `json:"updated_at,omitempty" url:"-"`

	/*
	   The ID or name of the author for the custom page.
	   Example: Alvin
	*/
	Author string `json:"author,omitempty" url:"-"`

	/*
	   The creation time of the custom page. Format: `yyyy-MM-dd HH:mm:ss.SSS`.
	   Example: 2023-09-11 16:49:35.120
	*/
	CreatedAt string `json:"created_at,omitempty" url:"-"`

	/*
	   A unique semantic identifier for the custom page.
	   Example: contact_us
	*/
	Handle string `json:"handle,omitempty" url:"-"`

	/*
	   The publication time of the custom page. Format: `yyyy-MM-dd HH:mm:ss.SSS`.
	   Example: 2023-09-11 16:49:35.120
	*/
	PublishedAt string `json:"published_at,omitempty" url:"-"`

	/*
	   The template type used by the custom page. Valid values are:
	   - `0`: Default theme template.
	   - `1`: Public template, available for all themes.
	   - `2`: App-defined theme template, only effective for the current theme.
	   Example:
	*/
	TemplateType string `json:"template_type,omitempty" url:"-"`

	/*
	   The body content of the custom page, formatted in HTML.
	   Example: <p>We love to hear from you.</p>
	*/
	BodyHtml string `json:"body_html,omitempty" url:"-"`

	/*
	   The unique ID of the custom page.
	   Example: 4570533223805409322
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   Whether the custom page has been published.
	   - `true`: Already published
	   - `false`: Not yet published
	   Example: false
	*/
	PublishedStatus bool `json:"published_status,omitempty" url:"-"`

	/*
	   The unique ID of the store.
	   Example: 1607433620673
	*/
	ShopId string `json:"shop_id,omitempty" url:"-"`

	/*
	   Template name used for the custom page.
	   Example: templates/page.contact.json
	*/
	TemplateName string `json:"template_name,omitempty" url:"-"`
}
