// Package order generated by SHOPLINE since v20251201
package order

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

type BatchShippingPlanV2APIReq struct {
	client.BaseAPIRequest
	/*
	   Setting area plan object
	   Example: map[delivery_location_group_list:[map[default_tag:true delivery_plans:[map[area_name:China shipping areas:[map[area_codes:[12001] country_code:CN]] shipping_plans:[map[charge_mode:1 conditional_interval:3 custom_amount:"90.88" delivery_name:Shipping from china -01 first_amount: "3.80" first_measure:3 incr_amount:"1.88" incr_measure:"1.00" intervals:[map[custom_amount:"90.88" end_interval:"3" first_amount: "3.80" first_measure:3 incr_amount:"1.88" incr_measure:"1.00" measure_unit:"kg" start_interval:"0"]] measure_unit:"kg"]]]] group_name: location_seq_list:[]]] group_type:1 product_group_info:map[product_group_name:" custom shipping 01 " product_group_seq:"PG5938934496267609846" product_ids:[["18053690657964710749100412","18055123775710848634010412"]]]]
	*/
	ShippingZones BatchShippingPlanV2APIReqShippingZones `json:"shipping_zones,omitempty" url:"-"`
}

type BatchShippingPlanV2APIReqShippingZones struct {
	/*
	   Item group information
	   Example: map[product_group_name:" custom shipping 01 " product_group_seq:"PG5938934496267609846" product_ids:[["18053690657964710749100412","18055123775710848634010412"]]]
	*/
	ProductGroupInfo ProductGroupInfo `json:"product_group_info,omitempty" url:"-"`

	/*
	   Multiple shipping schemes for multiple shipping sites object
	   Example: [map[default_tag:true delivery_plans:[map[area_name:China shipping areas:[map[area_codes:[12001] country_code:CN]] shipping_plans:[map[charge_mode:1 conditional_interval:3 custom_amount:"90.88" delivery_name:Shipping from china -01 first_amount: "3.80" first_measure:3 incr_amount:"1.88" incr_measure:"1.00" intervals:[map[custom_amount:"90.88" end_interval:"3" first_amount: "3.80" first_measure:3 incr_amount:"1.88" incr_measure:"1.00" measure_unit:"kg" start_interval:"0"]] measure_unit:"kg"]]]] group_name: location_seq_list:[]]]
	*/
	DeliveryLocationGroupList []DeliveryLocationGroupList `json:"delivery_location_group_list,omitempty" url:"-"`

	/*
	   Shipping configuration type ( 1 : general grouping , 2 : custom grouping , default 1 general grouping if not transmitted )
	   Example: 1
	*/
	GroupType int `json:"group_type,omitempty" url:"-"`
}

type DeliveryLocationGroupList struct {
	/*
	   Default shipping location group or not
	   Example: true
	*/
	DefaultTag bool `json:"default_tag,omitempty" url:"-"`

	/*
	   Multiple zone schemes object
	   Example: [map[area_name:China shipping areas:[map[area_codes:[12001] country_code:CN]] shipping_plans:[map[charge_mode:1 conditional_interval:3 custom_amount:"90.88" delivery_name:Shipping from china -01 first_amount: "3.80" first_measure:3 incr_amount:"1.88" incr_measure:"1.00" intervals:[map[custom_amount:"90.88" end_interval:"3" first_amount: "3.80" first_measure:3 incr_amount:"1.88" incr_measure:"1.00" measure_unit:"kg" start_interval:"0"]] measure_unit:"kg"]]]]
	*/
	DeliveryPlans []DeliveryPlan `json:"delivery_plans,omitempty" url:"-"`

	/*
	   The name of the shipment place is classified , if it is the default delivery place group , the name can be empty
	   Example:
	*/
	GroupName string `json:"group_name,omitempty" url:"-"`

	/*
	   Shipping location list associated with the shipping group
	   Example: []
	*/
	LocationSeqList []string `json:"location_seq_list,omitempty" url:"-"`
}

func (req *BatchShippingPlanV2APIReq) GetEndpoint() string {

	return "logistics/shipping_zones_v2.json"

}

func (req *BatchShippingPlanV2APIReq) GetMethod() string {
	return "POST"
}

func (req *BatchShippingPlanV2APIReq) GetData() interface{} {
	return req
}

// Verify the api request parameters
func (req *BatchShippingPlanV2APIReq) Verify() error {

	return nil
}

func (req *BatchShippingPlanV2APIReq) NewAPIResp() *BatchShippingPlanV2APIResp {
	return &BatchShippingPlanV2APIResp{}
}

type BatchShippingPlanV2APIResp struct {
	client.BaseAPIResponse
	/*
	   Shipping plan settings return object
	   Example: map[ext_map:map[] group_seq: is_success:false]
	*/
	ShippingZone ShippingZone `json:"shipping_zone,omitempty" url:"-"`
}
