// Package order generated by SHOPLINE since v20251201
package order

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

type GetOrderQuantityAPIReq struct {
	client.BaseAPIRequest
	/*
	   Order creation time (end) (see IOS8601 for the format)
	   Example: 2022-12-30T10:14:10+08:00
	*/
	CreatedAtMax string `url:"created_at_max,omitempty" json:"-"`
	/*
	   Order creation time (start) (see IOS8601 for the format)
	   Example: 2022-12-29T10:14:10+08:00
	*/
	CreatedAtMin string `url:"created_at_min,omitempty" json:"-"`
	/*
	   Payment status : unpaid is not paid , pending is paid , partially_paid part is paid , authorized is authorized , paid by paid , partially_refunded part is refunded ,Refunded has refunded , any payment status by any
	   Example: unpaid
	*/
	FinancialStatus string `url:"financial_status,omitempty" json:"-"`
	/*
	   Delivery status : unshipped is not shipped , partial part is shipped , shipped has been shipped , any delivery status of any
	   Example: unshipped
	*/
	FulfillmentStatus string `url:"fulfillment_status,omitempty" json:"-"`
	/*
	   Sales channels : oneshop one page store , web station online store , mc order , live anchor order , post order , shopee order , lazada order ,Buy_button order , pos openApi pos order , any sales channel
	   Example: one shop
	*/
	OrderSource string `url:"order_source,omitempty" json:"-"`
	/*
	   Order status : open processing , not filed , cancelled , not filed , hidden filed , any order status , including open+cancelled+hidden
	   Example: open
	*/
	Status string `url:"status,omitempty" json:"-"`
	/*
	   Order update time (end) (see IOS8601 for the format)
	   Example: 2022-12-30T10:14:10+08:00
	*/
	UpdatedAtMax string `url:"updated_at_max,omitempty" json:"-"`
	/*
	   Order update time (start) (see IOS8601 for the format)
	   Example: 2022-12-29T10:14:10+08:00
	*/
	UpdatedAtMin string `url:"updated_at_min,omitempty" json:"-"`
}

func (req *GetOrderQuantityAPIReq) GetEndpoint() string {

	return "orders/count.json"

}

func (req *GetOrderQuantityAPIReq) GetMethod() string {
	return "GET"
}

func (req *GetOrderQuantityAPIReq) GetQuery() interface{} {
	return req
}

// Verify the api request parameters
func (req *GetOrderQuantityAPIReq) Verify() error {

	return nil
}

func (req *GetOrderQuantityAPIReq) NewAPIResp() *GetOrderQuantityAPIResp {
	return &GetOrderQuantityAPIResp{}
}

type GetOrderQuantityAPIResp struct {
	client.BaseAPIResponse
	/*
	   Number of orders that comply with given entry conditions
	   Example: 123
	*/
	Count int64 `json:"count,omitempty" url:"-"`
}
