// Package order generated by SHOPLINE since v20251201
package order

import (
	"errors"
	"fmt"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type PerformanceAppointmentMarkerOnholdAPIReq struct {
	client.BaseAPIRequest
	/*
	   Performance order id
	   Example: "4005740193290131085320"
	*/
	FulfillmentOrderId string `url:"-" json:"-"` // Required
	/*
	   Order id
	   Example: "21057401932826316666967110"
	*/
	OrderId string `url:"-" json:"-"` // Required
	/*
	   Pause shipping reason
	   Example: map[reason:"out of stock" reason_notes:"Not enough inventory to complete this work."]
	*/
	FulfillmentHold PerformanceAppointmentMarkerOnholdAPIReqFulfillmentHold `json:"fulfillment_hold,omitempty" url:"-"`
}

type PerformanceAppointmentMarkerOnholdAPIReqFulfillmentHold struct {
	/*
	   Pause shipping reason
	   Example: "out of stock"
	*/
	Reason string `json:"reason,omitempty" url:"-"`

	/*
	   Pause shipping notes
	   Example: "Not enough inventory to complete this work."
	*/
	ReasonNotes string `json:"reason_notes,omitempty" url:"-"`
}

func (req *PerformanceAppointmentMarkerOnholdAPIReq) GetEndpoint() string {

	return fmt.Sprintf("fulfillment_orders/%s/%s/hold.json", req.FulfillmentOrderId, req.OrderId)

}

func (req *PerformanceAppointmentMarkerOnholdAPIReq) GetMethod() string {
	return "POST"
}

func (req *PerformanceAppointmentMarkerOnholdAPIReq) GetData() interface{} {
	return req
}

// Verify the api request parameters
func (req *PerformanceAppointmentMarkerOnholdAPIReq) Verify() error {

	if req.FulfillmentOrderId == "" {
		return errors.New("FulfillmentOrderId is required")
	}

	if req.OrderId == "" {
		return errors.New("OrderId is required")
	}

	return nil
}

func (req *PerformanceAppointmentMarkerOnholdAPIReq) NewAPIResp() *PerformanceAppointmentMarkerOnholdAPIResp {
	return &PerformanceAppointmentMarkerOnholdAPIResp{}
}

type PerformanceAppointmentMarkerOnholdAPIResp struct {
	client.BaseAPIResponse
	/*
	   Order details
	   Example: map[assigned_location:map[address1:"Chestnut Street 92" address2:"Chestnut Street 92" city:"Louisville" country_code:"US" location_id:"5327026538935748524" name:"Apple Api Shipwire" phone:"+1(502)-459-3417" province:"Kentucky" zip:"40202"] assigned_location_id:"5327026538935748524" delivery_method:"STORE_STREET" destination:map[address1:"Chestnut Street 92" address2:"Chestnut Street 92" city:"Louisville" company:"Apple inc" country:"United States" email:"bob.norman@mail.example.com" first_name:"Bob" last_name:"Norman" phone:"+1(502)-459-2181" province:Kentucky zip:"40202"] fulfill_at:"2023-11-19T03:43:00-05:00" fulfillment_holds:[map[reason:"inventory_out_of_stock" reason_notes:"Not enough inventory to complete this work."]] id:"4005740193290131085320" line_items:[map[fulfillable_quantity:1 fulfillment_order_id:"4005740193290131085320" id:"1039283" line_item_id:"518995019" quantity:1 shop_id:"1644828244663" variant_id:"18055128824718541486811487"]] order_id:"21057401932826316666967110" request_status:"submitted" shop_id:"1644828244663" status:"open" supported_actions:[["create_fulfillment"]]]
	*/
	FulfillmentOrder FulfillmentOrder `json:"fulfillment_order,omitempty" url:"-"`
}

type FulfillmentOrder struct {
	/*
	   Express order logistics method ,○ STORE_STREET -- super  HOME_STREET --  PO_BOX-- self- POST_HOUSE-- self- PICK_UP--Pick up by yourself-seller pick up point ( pick up at store ) ; local delivery by LOCAL_DELIVERY-- ; no shipping required by NONE--
	   Example: "STORE_STREET"
	*/
	DeliveryMethod string `json:"delivery_method,omitempty" url:"-"`

	/*
	   store ID
	   Example: "1644828244663"
	*/
	ShopId string `json:"shop_id,omitempty" url:"-"`

	/*
	   Map order status , including : open , in_progress , cmos ed , cancelled , incomplete , on_hold , scheduled
	   Example: "open"
	*/
	Status string `json:"status,omitempty" url:"-"`

	/*
	   Operation supported by the appointment order includes : create_fulfillment -- created delivery , move -- moved to a new location , hold -- suspended delivery , release_hold -- ( after pause ) started delivery
	   Example: [["create_fulfillment"]]
	*/
	SupportedActions []string `json:"supported_actions,omitempty" url:"-"`

	/*
	   Assigned location id
	   Example: "5327026538935748524"
	*/
	AssignedLocationId string `json:"assigned_location_id,omitempty" url:"-"`

	/*
	   Product line information
	   Example: [map[fulfillable_quantity:1 fulfillment_order_id:"4005740193290131085320" id:"1039283" line_item_id:"518995019" quantity:1 shop_id:"1644828244663" variant_id:"18055128824718541486811487"]]
	*/
	LineItems []PerformanceAppointmentMarkerOnholdAPIRespLineItem `json:"line_items,omitempty" url:"-"`

	/*
	   Request status, including: accepted, cancellation_accepted, cancellation_rejected, cancellation_Requested, closed, rejected, submitted, unsubmitted
	   Example: "submitted"
	*/
	RequestStatus string `json:"request_status,omitempty" url:"-"`

	/*
	   Performance order id
	   Example: "4005740193290131085320"
	*/
	Id string `json:"id,omitempty" url:"-"`

	/*
	   Shipping time ( format see IOS8601 )
	   Example: "2023-11-19T03:43:00-05:00"
	*/
	FulfillAt string `json:"fulfill_at,omitempty" url:"-"`

	/*
	   Consignee information
	   Example: map[address1:"Chestnut Street 92" address2:"Chestnut Street 92" city:"Louisville" company:"Apple inc" country:"United States" email:"bob.norman@mail.example.com" first_name:"Bob" last_name:"Norman" phone:"+1(502)-459-2181" province:Kentucky zip:"40202"]
	*/
	Destination Destination `json:"destination,omitempty" url:"-"`

	/*
	   Location details assigned
	   Example: map[address1:"Chestnut Street 92" address2:"Chestnut Street 92" city:"Louisville" country_code:"US" location_id:"5327026538935748524" name:"Apple Api Shipwire" phone:"+1(502)-459-3417" province:"Kentucky" zip:"40202"]
	*/
	AssignedLocation AssignedLocation `json:"assigned_location,omitempty" url:"-"`

	/*
	   Shipping pause information
	   Example: [map[reason:"inventory_out_of_stock" reason_notes:"Not enough inventory to complete this work."]]
	*/
	FulfillmentHolds []FulfillmentHold `json:"fulfillment_holds,omitempty" url:"-"`

	/*
	   Order id
	   Example: "21057401932826316666967110"
	*/
	OrderId string `json:"order_id,omitempty" url:"-"`
}

type PerformanceAppointmentMarkerOnholdAPIRespLineItem struct {
	/*
	   Product row id
	   Example: "518995019"
	*/
	LineItemId string `json:"line_item_id,omitempty" url:"-"`

	/*
	   Order Product line Product quantity
	   Example: 1
	*/
	Quantity int64 `json:"quantity,omitempty" url:"-"`

	/*
	   store ID
	   Example: "1644828244663"
	*/
	ShopId string `json:"shop_id,omitempty" url:"-"`

	/*
	   Product sku
	   Example: "18055128824718541486811487"
	*/
	VariantId string `json:"variant_id,omitempty" url:"-"`

	/*
	   Available in approximately Product quantities
	   Example: 1
	*/
	FulfillableQuantity int64 `json:"fulfillable_quantity,omitempty" url:"-"`

	/*
	   Performance order id
	   Example: "4005740193290131085320"
	*/
	FulfillmentOrderId string `json:"fulfillment_order_id,omitempty" url:"-"`

	/*
	   Performance order Product line id
	   Example: "1039283"
	*/
	Id string `json:"id,omitempty" url:"-"`
}

type FulfillmentHold struct {
	/*
	   Shipping pause note
	   Example: "Not enough inventory to complete this work."
	*/
	ReasonNotes string `json:"reason_notes,omitempty" url:"-"`

	/*
	   Delivery suspension reason , out of stock : out of stock , address error : address_error , high-risk fraud : high_fraudulent_risk , waiting for payment : wait_for_payment ,Other : other
	   Example: "inventory_out_of_stock"
	*/
	Reason string `json:"reason,omitempty" url:"-"`
}
