// Package order generated by SHOPLINE since v20251201
package order

import (
	"errors"
	"fmt"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type SetUpAFulfillmentOrderDeadlineAPIReq struct {
	client.BaseAPIRequest
	/*
	   Order id
	   Example: "21057401932826316666967110"
	*/
	OrderId string `url:"-" json:"-"` // Required
	/*
	   Shezhi time set
	   Example: "2021-05-26T10:00:00-04:00"
	*/
	FulfillmentDeadline string `json:"fulfillment_deadline,omitempty" url:"-"`

	/*
	   List id for performance
	   Example: [["4005740193290131085320"]]
	*/
	FulfillmentOrderIds []string `json:"fulfillment_order_ids,omitempty" url:"-"`
}

func (req *SetUpAFulfillmentOrderDeadlineAPIReq) GetEndpoint() string {

	return fmt.Sprintf("fulfillment_orders/%s/set_fulfillment_orders_deadline.json", req.OrderId)

}

func (req *SetUpAFulfillmentOrderDeadlineAPIReq) GetMethod() string {
	return "POST"
}

func (req *SetUpAFulfillmentOrderDeadlineAPIReq) GetData() interface{} {
	return req
}

// Verify the api request parameters
func (req *SetUpAFulfillmentOrderDeadlineAPIReq) Verify() error {

	if req.OrderId == "" {
		return errors.New("OrderId is required")
	}

	if req.FulfillmentDeadline == "" {
		return errors.New("FulfillmentDeadline is required")
	}

	return nil
}

func (req *SetUpAFulfillmentOrderDeadlineAPIReq) GetRequestOptions() *client.RequestOptions {
	opts := &client.RequestOptions{
		NotDecodeBody: true,
	}
	return opts
}

func (req *SetUpAFulfillmentOrderDeadlineAPIReq) NewAPIResp() *SetUpAFulfillmentOrderDeadlineAPIResp {
	return &SetUpAFulfillmentOrderDeadlineAPIResp{}
}

type SetUpAFulfillmentOrderDeadlineAPIResp struct {
	client.BaseAPIResponse
}
