// Package application generated by SHOPLINE since v20260301
package application

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *AppPlanActivatedEvent) GetSupportedTopic() string {
	return "appsubscription/create"
}

type AppPlanActivatedEvent struct {
	client.WebhookEvent
	/*
	   The store's unique identifier in SHOPLINE, corresponding to the `{handle}` part of the domain name `{handle}.myshopline.com`.
	   Example: discount
	*/
	Handle string `json:"handle,omitempty" url:"-"`

	/*
	   The secondary channel identifier for specific sales channels like offline POS stores.
	   Applicable scenarios:
	   + When plans are sold **per store location**: identifies the specific store
	   + When plans are sold **for the entire store**: this parameter is empty
	   Example: 4567223323
	*/
	SecondChannelId string `json:"secondChannelId,omitempty" url:"-"`

	/*
	   The original order number for the expired subscription.
	   Example: 6578332207010012345
	*/
	SubId string `json:"subId,omitempty" url:"-"`

	/*
	   Subscription plan details.
	   Example: map[autoRenewStatus:false endAt:1.7572392e+12 featureKeyList:["KeyName1":"demo1","KeyName2":"demo2","KeyName3":"demo3","KeyName4":"demo4"] gracePeriod:2 gracePeriodUnit: isEnterpriseGift:false period:1 periodType: serviceKeyList:[] spuKey:email startAt:1.756977716e+12 trial:false]
	*/
	SubPackage SubPackage `json:"subPackage,omitempty" url:"-"`

	/*
	   The payment success time in the format of a 13-digit milliseconds timestamp.
	   Example: 1.706810461e+12
	*/
	SubTime int64 `json:"subTime,omitempty" url:"-"`

	/*
	   The globally unique identifier for the app.
	   Example: 56978e0b3f33365396d7786a62ed0a03727e3212
	*/
	Appkey string `json:"appkey,omitempty" url:"-"`
}

type SubPackage struct {
	/*
	   The number of units defiled by `periodType`. This parameter, used with `periodType`, calculates the billing cycle duration.
	   Example: 1
	*/
	Period int `json:"period,omitempty" url:"-"`

	/*
	   The unit for the billing cycle. Valid values:
	   + `DAY`: Days
	   + `MONTH`: Months
	   + `YEAR`: Years
	   Example:
	*/
	PeriodType string `json:"periodType,omitempty" url:"-"`

	/*
	   Indicates whether the current subscription is a trial plan.
	   + `true`: Trial plan
	   + `false`: Standard plan
	   Example: false
	*/
	Trial bool `json:"trial,omitempty" url:"-"`

	/*
	   Indicates whether the store has enabled auto-renewal for this app.
	   + `true`: Auto-renewal enabled
	   + `false`: Auto-renewal disabled
	   Example: false
	*/
	AutoRenewStatus bool `json:"autoRenewStatus,omitempty" url:"-"`

	/*
	   The expiration time of the subscription, formatted as a 13-digit millisecond timestamp.
	   Example: 1.7572392e+12
	*/
	EndAt int64 `json:"endAt,omitempty" url:"-"`

	/*
	   Feature keys included in the plan. If not set during app configuration, it will return `null`.
	   Example: ["KeyName1":"demo1","KeyName2":"demo2","KeyName3":"demo3","KeyName4":"demo4"]
	*/
	FeatureKeyList []string `json:"featureKeyList,omitempty" url:"-"`

	/*
	   The number of units defined by `gracePeriodUnit`. This parameter, used with `gracePeriodUnit`, calculates the total effective grace period after a subscription expires.

	   :::warning{title="Caution"}
	   The grace period follows calendar time. For example, if a plan expires at 22:00:00, a 1-day grace period will cause the app to expire at 22:00:00 the next day.
	   :::
	   Example: 2
	*/
	GracePeriod int64 `json:"gracePeriod,omitempty" url:"-"`

	/*
	   Services included in the plan, with remaining quantities and validity periods.
	   Example: []
	*/
	ServiceKeyList []ServiceKeyList `json:"serviceKeyList,omitempty" url:"-"`

	/*
	   The unique identifier for the plan, defined when the plan is created.
	   Example: email
	*/
	SpuKey string `json:"spuKey,omitempty" url:"-"`

	/*
	   The effective time of the subscription, formatted as a 13-digit millisecond timestamp.
	   Example: 1.756977716e+12
	*/
	StartAt int64 `json:"startAt,omitempty" url:"-"`

	/*
	   Unit of the grace period. Used together with `gracePeriod` to indicate the duration of the grace period for the current subscription plan.
	   Valid values are:
	   - `SECOND`: Seconds. Used for app plans and value-added services.
	   - `DAY`: Days. Used for one-time purchase products.
	   Example:
	*/
	GracePeriodUnit string `json:"gracePeriodUnit,omitempty" url:"-"`

	/*
	   Indicates whether the current subscription is part of an Enterprise plan gift.
	   This field can be ignored if the app is not participating in the Enterprise plan gift program.

	   Valid values:
	   - `true`: The subscription is part of the Enterprise plan gift.
	   - `false`: The subscription is not part of the Enterprise plan gift.

	   Default value: `false`.
	   Example: false
	*/
	IsEnterpriseGift bool `json:"isEnterpriseGift,omitempty" url:"-"`
}

type ServiceKeyList struct {
	/*
	   The remaining available service quantity.
	   Example: 20
	*/
	AvailableQty int64 `json:"availableQty,omitempty" url:"-"`

	/*
	   Indicates whether the current plan is a perpetual service.
	   + `true`: Unlimited validity.
	   + `false`: Limited validity.
	   Example: false
	*/
	Indefinite bool `json:"indefinite,omitempty" url:"-"`

	/*
	   The unique identifier for the service capability.
	   Example: email_100
	*/
	ServiceKey string `json:"serviceKey,omitempty" url:"-"`

	/*
	   The total service quantity.
	   Example: 100
	*/
	TotalQty int64 `json:"totalQty,omitempty" url:"-"`
}
