// Package customer generated by SHOPLINE since v20260301
package customer

import (
	"errors"
	"fmt"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type SendActivationMailAPIReq struct {
	client.BaseAPIRequest
	/*
	   Customer ID
	   Example: 4201801159
	*/
	Id string `url:"-" json:"-"` // Required
}

func (req *SendActivationMailAPIReq) GetEndpoint() string {

	return fmt.Sprintf("customers/%s/send_invite.json", req.Id)

}

func (req *SendActivationMailAPIReq) GetMethod() string {
	return "POST"
}

// Verify the api request parameters
func (req *SendActivationMailAPIReq) Verify() error {

	if req.Id == "" {
		return errors.New("Id is required")
	}

	return nil
}

func (req *SendActivationMailAPIReq) NewAPIResp() *SendActivationMailAPIResp {
	return &SendActivationMailAPIResp{}
}

type SendActivationMailAPIResp struct {
	client.BaseAPIResponse
	/*
	   Activate invitation mail
	   Example: map[from:******@example.com to:******@example.com]
	*/
	CustomerInvite CustomerInvite `json:"customer_invite,omitempty" url:"-"`
}

type CustomerInvite struct {
	/*
	   Sender mailbox
	   Example: ******@example.com
	*/
	From string `json:"from,omitempty" url:"-"`

	/*
	   Consignee mailbox
	   Example: ******@example.com
	*/
	To string `json:"to,omitempty" url:"-"`
}
