// Package market generated by SHOPLINE since v20251201
package market

import (
	"errors"
	"fmt"

	"github.com/shoplineos/shopline-sdk-go/client"
)

type QueryTheMarketPriceRangesOfTheProductAPIReq struct {
	client.BaseAPIRequest
	/*
	   Product ID
	   Example: 16060895302856191591063144
	*/
	ProductId string `url:"-" json:"-"` // Required
	/*
	   Country code, up to 10, separated by ',' , reference : https://shopline.yuque.com/slpm/lrmo5q/kg7dqrgywgbfyzrx?singleDoc#uPeC
	   Example: CN,US
	*/
	CountryCodes string `url:"country_codes,omitempty" json:"-"` // Required
}

func (req *QueryTheMarketPriceRangesOfTheProductAPIReq) GetEndpoint() string {

	return fmt.Sprintf("markets/%s/price/range.json", req.ProductId)

}

func (req *QueryTheMarketPriceRangesOfTheProductAPIReq) GetMethod() string {
	return "GET"
}

func (req *QueryTheMarketPriceRangesOfTheProductAPIReq) GetQuery() interface{} {
	return req
}

// Verify the api request parameters
func (req *QueryTheMarketPriceRangesOfTheProductAPIReq) Verify() error {

	if req.ProductId == "" {
		return errors.New("ProductId is required")
	}

	if req.CountryCodes == "" {
		return errors.New("CountryCodes is required")
	}

	return nil
}

func (req *QueryTheMarketPriceRangesOfTheProductAPIReq) NewAPIResp() *QueryTheMarketPriceRangesOfTheProductAPIResp {
	return &QueryTheMarketPriceRangesOfTheProductAPIResp{}
}

type QueryTheMarketPriceRangesOfTheProductAPIResp struct {
	client.BaseAPIResponse
	/*
	   Market price range
	   Example: [map[country_code:CN max_market_price:map[amount:10 currency_code:CNY] min_market_price:map[amount:10 currency_code:CNY]]]
	*/
	MarketPrices []QueryTheMarketPriceRangesOfTheProductAPIRespMarketPrice `json:"market_prices,omitempty" url:"-"`
}

type QueryTheMarketPriceRangesOfTheProductAPIRespMarketPrice struct {
	/*
	   Max market price
	   Example: map[amount:10 currency_code:CNY]
	*/
	MaxMarketPrice MaxMarketPrice `json:"max_market_price,omitempty" url:"-"`

	/*
	   Minimum market price
	   Example: map[amount:10 currency_code:CNY]
	*/
	MinMarketPrice MinMarketPrice `json:"min_market_price,omitempty" url:"-"`

	/*
	   Country code
	   Example: CN
	*/
	CountryCode string `json:"country_code,omitempty" url:"-"`
}

type MaxMarketPrice struct {
	/*
	   Currency
	   Example: CNY
	*/
	CurrencyCode string `json:"currency_code,omitempty" url:"-"`

	/*
	   Amount
	   Example: 10
	*/
	Amount string `json:"amount,omitempty" url:"-"`
}

type MinMarketPrice struct {
	/*
	   Amount
	   Example: 10
	*/
	Amount string `json:"amount,omitempty" url:"-"`

	/*
	   Currency
	   Example: CNY
	*/
	CurrencyCode string `json:"currency_code,omitempty" url:"-"`
}
