// Package buildingstation generated by SHOPLINE since v20251201
package buildingstation

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *AddBlogsEvent) GetSupportedTopic() string {
	return "blogs/create"
}

type AddBlogsEvent struct {
	client.WebhookEvent
	/*
	   Blog collection title
	   Example: News
	*/
	Title string `json:"title,omitempty"`

	/*
	   Blog collection update time
	   Example: 2021-11-09 06:41:00
	*/
	UpdatedAt string `json:"updated_at,omitempty"`

	/*
	   Evaluation processing method
	   Example: yes
	*/
	Commentable string `json:"commentable,omitempty"`

	/*
	   Blog collection created time
	   Example: 2021-11-09 06:41:00
	*/
	CreatedAt string `json:"created_at,omitempty"`

	/*
	   Blog collection handle
	   Example: new
	*/
	Handle string `json:"handle,omitempty"`

	/*
	   Blog collection id
	   Example: 6183a5c83d13eb7215356705
	*/
	Id string `json:"id,omitempty"`

	/*
	   Blog collection tag s
	   Example: 1,2,3
	*/
	Tags string `json:"tags,omitempty"`

	/*
	   Blog collection template
	   Example:
	*/
	TemplateSuffix string `json:"template_suffix,omitempty"`
}
