// Package batchoperation generated by SHOPLINE since v20251201
package batchoperation

import (
	"github.com/shoplineos/shopline-sdk-go/client"
)

func (e *BulkTaskStatusUpdatedEvent) GetSupportedTopic() string {
	return "others/update"
}

type BulkTaskStatusUpdatedEvent struct {
	client.WebhookEvent
	/*
	   The status of the bulk task. Valid values are:

	   - `CANCELED`：Canceled
	   - `CANCELING`：Canceling
	   - `COMPLETED`：Completed
	   - `CREATED`：Created
	   - `EXPIRED`：Expired
	   - `FAILED`：Failed
	   - `RUNNING`：Running

	   Example:
	*/
	Status string `json:"status,omitempty"`

	/*
	   The type of the bulk task. Valid values are:
	   - `QUERY`: Query operation
	   - `MUTATION`: Mutation operation, which refers to mutation operations executed through the [Bulk operation mutation (to be Deprecated)](https://developer.shopline.com/docs/admin-rest-api/bulk-operations/create-a-change-type-bulk-task-to-be-deprecated) API.
	   - `MUTATION_GENERAL`: Mutation operation

	   Example:
	*/
	Type string `json:"type,omitempty"`

	/*
	   A URL to a file containing all task processing results with an expiration time. Format: [JSON Lines](https://jsonlines.org/).
	   Example: https://sl-private-oss.oss-accelerate.example.com/task-jsonline/prod/1/9b0c0f04-53cb-4ae3-94db-79af6ec193bd.jsonl?Expires=1754059510
	*/
	Url string `json:"url,omitempty"`

	/*
	   The date and time when the bulk task was completed. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).

	   Example: 2023-04-06T10:48:29+08:00
	*/
	CompletedAt string `json:"completedAt,omitempty"`

	/*
	   The count of the completed bulk operations.
	   Example: 0
	*/
	CompletedCount int `json:"completedCount,omitempty"`

	/*
	   The date and time when the bulk task was created. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).

	   Example: 2023-04-06T10:48:29+08:00
	*/
	CreatedAt string `json:"createdAt,omitempty"`

	/*
	   The expiration time of the bulk task. Files will become unavailable for download after this time. Format: [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).

	   Example: 2023-04-06T10:48:29+08:00
	*/
	ExpiredAt string `json:"expiredAt,omitempty"`

	/*
	   The ID of the bulk task.
	   Example: gid://shopline/BulkOperation/f97a8c3304b98bcee17c12a0ceb85573
	*/
	Id string `json:"id,omitempty"`
}
